INSERT INTO curriculum_contents (id, descricao, unidade_tematica) VALUES
(1, 'Danças Populares Brasileiras', NULL),
(2, 'Origens das Danças', NULL),
(3, 'Variação de Tempo', NULL),
(4, 'Expressão Corporal', NULL),
(5, 'Elementos da Dança', NULL),
(6, 'Movimentos do Frevo', NULL),
(7, 'Uso do Espaço', NULL),
(8, 'Fatores do Movimento', NULL),
(9, 'Jongo', NULL),
(10, 'Frevo', NULL),
(11, 'Siriri', NULL),
(12, 'Carimbó', NULL),
(13, 'Criações Coreográficas', NULL),
(14, 'Expressão na Dança', NULL),
(15, 'Processos Criativos', NULL),
(16, 'Música Brasileira', NULL),
(17, 'Produção, Repertório e Circulação Musical', NULL),
(18, 'Função Social da Música', NULL),
(19, 'Repertório Musical Indígena e Afro-Brasileiro', NULL),
(20, 'Paisagem Sonora', NULL),
(21, 'Registro Musical', NULL),
(22, 'Notação Não Convencional', NULL),
(23, 'Composição e Improvisação Musical', NULL),
(24, 'Percussão Corporal', NULL),
(25, 'Instrumentos e Notação Não Convencionais', NULL),
(26, 'Instrumentos e Timbres', NULL),
(27, 'Improvisação Musical', NULL),
(28, 'Composição, Colaboração e Improvisação Musical', NULL),
(29, 'Produção e Registro Musical', NULL),
(30, 'Introdução à Dança', NULL),
(31, 'Dança: Diversidade Cultural', NULL),
(32, 'História da Dança', NULL),
(33, 'Dança Clássica', NULL),
(34, 'Dança Moderna', NULL),
(35, 'Fatores de Movimento', NULL),
(36, 'Qualidades dos Movimentos', NULL),
(37, 'Sequências Coreográficas', NULL),
(38, 'Ações de Esforço', NULL),
(39, 'Improvisação na Dança', NULL),
(40, 'Música Clássica', NULL),
(41, 'Música Instrumental', NULL),
(42, 'Música Orquestral', NULL),
(43, 'Canto Coral', NULL),
(44, 'Estrutura do Coro', NULL),
(45, 'Produção Musical', NULL),
(46, 'Estrutura da Orquestra', NULL),
(47, 'Técnicas de Execução', NULL),
(48, 'Instrumentos Convencionais', NULL),
(49, 'Timbres e Características', NULL),
(50, 'Notação Convencional', NULL),
(51, 'Composição Musical', NULL),
(52, 'Técnicas de Execução Musical', NULL),
(53, 'Performance Musical', NULL),
(54, 'Instrumentos Musicais', NULL),
(55, 'Origens da Dança', NULL),
(56, 'Dança Coletiva', NULL),
(57, 'Improvisação em Dança', NULL),
(58, 'Ações Corporais Dançadas', NULL),
(59, 'Personagens na Dança Popular', NULL),
(60, 'Improvisação Coletiva', NULL),
(61, 'Gravidade e Peso', NULL),
(62, 'Análise do Movimento', NULL),
(63, 'Partitura Corporal', NULL),
(64, 'Composição Coreográfica', NULL),
(65, 'Apreciação Musical', NULL),
(66, 'História da Música', NULL),
(67, 'Música Tradicional Africana', NULL),
(68, 'Timbre', NULL),
(69, 'Música Indígena', NULL),
(70, 'Música Contemporânea', NULL),
(71, 'Música Afro-Brasileira', NULL),
(72, 'Elementos da Música', NULL),
(73, 'Jogos Rítmicos', NULL),
(74, 'Práticas de Criação', NULL),
(75, 'Movimento Cotidiano', NULL),
(76, 'Jogos e Brincadeiras', NULL),
(77, 'Kinesfera', NULL),
(78, 'Corpo-Híbrido e Corpo-Tela', NULL),
(79, 'Criação Coreográfica', NULL),
(80, 'Dança Contemporânea', NULL),
(81, 'Independência ou Coexistência Estética', NULL),
(82, 'Qualidades do Movimento', NULL),
(83, 'Musicalidade Corporal', NULL),
(84, 'Brincadeiras e Dança', NULL),
(85, 'Corpo Memético e Corpo Midiático', NULL),
(86, 'Corpo e Tecnologia', NULL),
(87, 'Música Popular Brasileira', NULL),
(88, 'Música Popular Estrangeira', NULL),
(89, 'Movimentos Musicais Históricos', NULL),
(90, 'Canção de Protesto', NULL),
(91, 'Expressão, Composição e Apreciação Musical', NULL),
(92, 'Música e Tecnologia', NULL),
(93, 'Elementos de Composição Musical', NULL),
(94, 'Função Social da Arte', NULL),
(95, 'Cultura Contemporânea', NULL),
(96, 'Processo Criativo', NULL),
(97, 'Arte e Mídia', NULL),
(98, 'Análise Crítica', NULL),
(99, 'Criação Artística', NULL),
(100, 'Intervenção Artística', NULL),
(101, 'Manifestação Artística', NULL),
(102, 'Linguagens Artísticas', NULL),
(103, 'Expressão Artística', NULL),
(104, 'Artes do Corpo', NULL),
(105, 'Estereótipos Sociais', NULL),
(106, 'Criação Musical', NULL),
(107, 'Danças Sociais', NULL),
(108, 'Expressão Identitária', NULL),
(109, 'Discurso Crítico', NULL),
(110, 'Crítica de Arte', NULL),
(111, 'Performatividade', NULL),
(112, 'Patrimônio Cultural', NULL),
(113, 'Pesquisa em Arte', NULL),
(114, 'Análise Histórica e Cultural', NULL),
(115, 'Manifesto Artístico', NULL),
(116, 'Estética Relacional', NULL),
(117, 'Processo Colaborativo', NULL),
(118, 'Impacto Cultural', NULL),
(119, 'Processos de Criação', NULL),
(120, 'Movimentos Artísticos', NULL),
(121, 'Compartilhamento de Práticas', NULL),
(122, 'Contexto Histórico e Cultural', NULL),
(123, 'Zeitgeist, “Espírito do Tempo”', NULL),
(124, 'Manifestos Coletivos', NULL),
(125, 'Coletivos Artísticos', NULL),
(126, 'Arte Colaborativa', NULL),
(127, 'Sistema de numeração decimal', NULL),
(128, 'Operações fundamentais com números naturais', NULL),
(129, 'Múltiplos e divisores', NULL),
(130, 'O conceito de fração', NULL),
(131, 'Operações fundamentais com números fracionários', NULL),
(132, 'Polígonos, triângulos e quadriláteros', NULL),
(133, 'Números inteiros', NULL),
(134, 'Operações fundamentais com frações', NULL),
(135, 'Operações com números racionais nas formas fracionária e decimal', NULL),
(136, 'Figuras geométricas planas no plano cartesiano', NULL),
(137, 'Área de figuras geométricas planas', NULL),
(138, 'Operações fundamentais com números racionais', NULL),
(139, 'Potenciação e propriedades da potenciação', NULL),
(140, 'Radiciação e relações entre radiciação e potenciação', NULL),
(141, 'Expressões algébricas e noções de Álgebra', NULL),
(142, 'Equações polinomiais do 1º grau', NULL),
(143, 'Sistemas de equações polinomiais do 1º grau', NULL),
(144, 'Números racionais: Comparação, operações fundamentais e potenciação', NULL),
(145, 'Características dos triângulos e semelhança de triângulos', NULL),
(146, 'Semelhança de triângulos e teorema de Pitágoras', NULL),
(147, 'Números irracionais e dízimas periódicas', NULL),
(148, 'Números reais', NULL),
(149, 'Números racionais', NULL),
(150, 'Teorema de Pitágoras', NULL),
(151, 'Conceito de função', NULL),
(152, 'Relação entre grandezas e equações polinomiais de 1º grau', NULL),
(153, 'Função Afim – Parte 1', NULL),
(154, 'Potenciação e notação científica', NULL),
(155, 'Equações polinomiais do 1º e 2º graus', NULL),
(156, 'Equações exponenciais', NULL),
(157, 'Funções exponenciais', NULL),
(158, 'Logaritmos', NULL),
(159, 'Funções logarítmicas', NULL),
(160, 'Equações polinomiais do 1° e 2° graus', NULL),
(161, 'Sistemas de equações lineares – Parte 1', NULL),
(162, '138 - 173 Sistemas de equações lineares – Parte 2', NULL),
(163, 'Análise combinatória', NULL),
(164, 'Probabilidade – Parte 1', NULL),
(165, 'Probabilidade – Parte 2', NULL),
(166, 'Leitura de post', NULL),
(167, 'Leitura de comentários', NULL),
(168, 'Leitura de notícia', NULL),
(169, 'Leitura de charge', NULL),
(170, 'Acento circunflexo', NULL),
(171, 'Leitura de carta do leitor', NULL),
(172, 'Pontuação: exclamação e reticências', NULL),
(173, 'Notícias: fato central × subtemas', NULL),
(174, 'Classe gramatical: substantivos', NULL),
(175, 'Classe gramatical: adjetivos', NULL),
(176, 'Ortografia: sílaba tônica e acento gráfico', NULL),
(177, 'Ortografia: X e CH', NULL),
(178, 'Pontuação', NULL),
(179, 'Ortografia: uso da cedilha', NULL),
(180, 'Terminação -gem', NULL),
(181, 'Palavras "mau" e "mal"', NULL),
(182, 'Acentuação em palavras oxítonas, proparoxítonas e paroxítonas', NULL),
(183, 'O sentido de sufixos', NULL),
(184, 'Leitura de poema', NULL),
(185, 'Leitura de conto', NULL),
(186, 'Leitura de lenda', NULL),
(187, 'Leitura de trecho de romance infantojuvenil', NULL),
(188, 'Leitura de crônica literária', NULL),
(189, 'Concordância nominal', NULL),
(190, 'Classe gramatical: verbos', NULL),
(191, 'Concordância verbal (sujeito simples)', NULL),
(192, 'Sinônimos e antônimos', NULL),
(193, 'O sentido de prefixos', NULL),
(194, 'Leitura de carta de reclamação', NULL),
(195, 'Modos verbais: subjuntivo. Tempos e modos verbais', NULL),
(196, 'Sons da letra S. Polissemia. Uso da vírgula em vocativo. Revisão: artigos definidos e indefinidos', NULL),
(197, 'Leitura e compreensão de poemas', NULL),
(198, 'Comparação de notícias', NULL),
(199, 'Fato × opinião em textos jornalísticos', NULL),
(200, 'Leitura de anúncio publicitário', NULL),
(201, 'Linguagem verbal e não verbal em anúncios publicitários', NULL),
(202, 'Leitura de anúncio publicitário em mídias digitais', NULL),
(203, 'Leitura de reportagem', NULL),
(204, 'Leitura de fotorreportagem', NULL),
(205, 'Características de fotorreportagens', NULL),
(206, 'Leitura de petição', NULL),
(207, 'Leitura de entrevista', NULL),
(208, 'Coesão', NULL),
(209, 'Ortografia: uso de Ç e SS', NULL),
(210, 'Leitura e interpretação de notícias', NULL),
(211, 'Pronome demonstrativo', NULL),
(212, 'Modalização discursiva', NULL),
(213, 'Acento diferencial', NULL),
(214, 'Leitura: diferentes escolhas editoriais sobre um mesmo fato', NULL),
(215, 'Fato e opinião', NULL),
(216, 'Leitura de textos multissemióticos', NULL),
(217, 'Leitura de anúncio publicitário. Palavras-valise', NULL),
(218, 'Recursos linguístico-discursivos em folhetos/flyers de anúncios publicitários', NULL),
(219, 'Leitura de artigo de divulgação científica. Elementos do artigo de divulgação científica', NULL),
(220, 'Paragrafação', NULL),
(221, 'Tese', NULL),
(222, 'Opinião', NULL),
(223, 'Estratégias argumentativas', NULL),
(224, 'Verbo de ação', NULL),
(225, 'Verbo de estado', NULL),
(226, 'Leitura de biografia e de autobiografia. Verbo: pretérito. Conjunção', NULL),
(227, 'Leitura de romance infantojuvenil. Leitura de conto popular', NULL),
(228, 'Leitura de conto de ficção científica. Estratégias de leitura. Fábula', NULL),
(229, 'Elemento da narrativa: narrador e personagens', NULL),
(230, 'Verbos de enunciação', NULL),
(231, 'Leitura de parábola', NULL),
(232, 'Diário ficcional. Progressão textual: causa e consequência', NULL),
(233, 'Leitura de poemas', NULL),
(234, 'Poemas de versos livres × forma fixa', NULL),
(235, 'Leitura de conto indígena', NULL),
(236, 'Estratégias de leitura', NULL),
(237, 'Mecanismos da narrativa', NULL),
(238, 'Elementos dos livros: quarta capa', NULL),
(239, 'Programa (de teatro, dança, exposições etc.)', NULL),
(240, 'Leitura de cartaz de campanha', NULL),
(241, 'Comparação entre peças publicitárias', NULL),
(242, 'Estratégias de persuasão com recursos linguístico-discursivos (jogos de palavras, metáforas, sentidos figurados etc.)', NULL),
(243, 'Intertextualidade em textos diversos', NULL),
(244, 'Valores culturais em textos literários', NULL),
(245, 'Contos populares', NULL),
(246, 'Estratégias de leitura de textos literários', NULL),
(247, 'Práticas de leitura de textos literários', NULL),
(248, 'Contos indígenas', NULL),
(249, 'Leitura de piadas e anedotas', NULL),
(250, 'Leitura de contos de humor', NULL),
(251, 'Leitura de paródia e sátira', NULL),
(252, 'Leitura de mito', NULL),
(253, 'Coesão e coerência em textos narrativos', NULL),
(254, 'Tessitura textual', NULL),
(255, 'Leitura de crônica', NULL),
(256, 'Relato de viagem', NULL),
(257, 'Adjuntos adverbiais', NULL),
(258, 'Leitura de notícia impressa e digital', NULL),
(259, 'Leitura e análise crítica de artigo de opinião', NULL),
(260, 'Leitura de trecho de romance', NULL),
(261, 'Características de texto de divulgação científica', NULL),
(262, 'Pontuação: parênteses e aspas', NULL),
(263, 'Leitura de memórias', NULL),
(264, 'Leitura de biografia', NULL),
(265, 'Leitura de autobiografia', NULL),
(266, 'Leitura de diário pessoal', NULL),
(267, 'Compreensão de efeitos de sentido', NULL),
(268, 'Verbos', NULL),
(269, 'Estudo de tempos verbais', NULL),
(270, 'Presente histórico', NULL),
(271, 'Pretérito imperfeito do indicativo', NULL),
(272, 'Pontuação: ponto-final', NULL),
(273, 'Oração: sujeito e predicado', NULL),
(274, 'Concordância verbal e nominal', NULL),
(275, 'Observar uso de hífen no texto e conhecer critérios de hifenização', NULL),
(276, 'Modos indicativo e subjuntivo', NULL),
(277, 'Ortografia: acentuação', NULL),
(278, 'Transitividade verbal', NULL),
(279, 'Tempos e modos verbais', NULL),
(280, 'Sentido real e figurado de palavras', NULL),
(281, 'Artigos definidos e indefinidos', NULL),
(282, 'Verbo "haver" como auxiliar', NULL),
(283, 'Pretérito perfeito e imperfeito do indicativo', NULL),
(284, 'Notícia: fato central', NULL),
(285, 'Reportagem: fato central', NULL),
(286, 'Entrevista: ideia central', NULL),
(287, 'Reportagem: relação entre parágrafos', NULL),
(288, 'Comparação entre editorial e artigo de opinião. Confiabilidade em textos jornalísticos', NULL),
(289, 'Argumentação', NULL),
(290, 'Acentuação: oxítonas, paroxítonas e proparoxítonas', NULL),
(291, 'Leitura de tirinha', NULL),
(292, 'Leitura de cartaz instrucional (primeiros socorros)', NULL),
(293, 'Cartaz sobre direitos e deveres do estudante', NULL),
(294, 'Leitura de cartaz de campanha de saúde', NULL),
(295, 'Estratégias de persuasão', NULL),
(296, 'Características de anúncios publicitários', NULL),
(297, 'Figura de linguagem: metáfora', NULL),
(298, 'Verbo: modo imperativo', NULL),
(299, 'Leitura de anúncio publicitário digital', NULL),
(300, 'Ortografia', NULL),
(301, 'Ficha catalográfica', NULL),
(302, 'Resumo', NULL),
(303, 'Leitura de esquema(s)', NULL),
(304, 'Leitura de relatório(s)', NULL),
(305, 'Leitura de petição online', NULL),
(306, 'Coesão sequencial', NULL),
(307, 'Modalizadores argumentativos', NULL),
(308, 'Leitura de carta aberta', NULL),
(309, 'Ler memes e gifs, analisando efeitos de sentido gerados pelo uso de linguagem verbal, não verbal e mista', NULL),
(310, 'Refletir e posicionar-se de forma crítica e ética sobre opiniões e visões de mundo expressas por esses gêneros da cultura digital', NULL),
(311, 'Posts e comentários', NULL),
(312, 'Adequação do registro escrito', NULL),
(313, 'A Idade Média em Portugal e a influência da cultura galego-portuguesa. Flexão verbal (tempos e modos verbais)', NULL),
(314, 'As origens do Trovadorismo no século XII. A primeira época medieval. Conjugações verbais regulares e irregulares', NULL),
(315, 'Cantigas: amor, amigo, escárnio e maldizer', NULL),
(316, 'A segunda época medieval: fragmento de O Auto da Barca do Inferno, de Gil Vicente', NULL),
(317, 'Contexto histórico do Classicismo. Fragmento da obra épica Os Lusíadas, de Camões. Vida e obra de Luís Vaz de Camões e sua influência', NULL),
(318, 'Leitura de poemas. Comparação entre características de obras clássicas e obras marginais. Conceito de literatura marginal. Contracultura', NULL),
(319, 'Leitura e compreensão de poema', NULL),
(320, 'Figuras de linguagem (comparação, metáfora, antítese e eufemismo)', NULL),
(321, 'Leitura e compreensão de biografia. Leitura e compreensão de poema', NULL),
(322, 'Leitura e compreensão de poemas. Figuras de linguagem (hipérbole, paradoxo e personificação). Sonoridade em textos poéticos (rima, aliteração, assonância e eufonia)', NULL),
(323, 'Verbos. Flexão verbal', NULL),
(324, 'Elementos mórficos na formação de palavras. Formação de palavras (radicais, prefixos, sufixos)', NULL),
(325, 'Tipos de sujeito (simples, composto, oculto, indeterminado)', NULL),
(326, 'Poema falado: slam. Linguagem informal e variedades linguísticas', NULL),
(327, 'A norma-padrão e a variação linguística. Ortografia e a contracultura na “geração mimeógrafo”. A poesia periférica e a construção ortográfica', NULL),
(328, 'Advérbios e locuções adverbiais', NULL),
(329, 'Regência verbal e nominal', NULL),
(330, 'Morfologia: estrutura das palavras (radical, desinência, vogal temática, tema e afixos)', NULL),
(331, 'Processos de formação de palavras: derivação', NULL),
(332, 'Concordância verbal com sujeito composto', NULL),
(333, 'Regência nominal e verbal', NULL),
(334, 'Período composto por coordenação e subordinação', NULL),
(335, 'Poema falado: slam', NULL),
(336, 'Versificação', NULL),
(337, 'Intertextualidade. Paráfrase e paródia', NULL),
(338, 'Denotação e conotação em textos literários. Efeitos de sentido', NULL),
(339, 'Linguagem verbal e não verbal: charges e cartuns', NULL),
(340, 'Neologismo. Estrangeirismo', NULL),
(341, 'Acentuação de palavras', NULL),
(342, 'Elementos coesivos', NULL),
(343, 'Compreensão de texto', NULL),
(344, 'Sensibilização para sentidos literais e não literais', NULL),
(345, 'Literatura periférica', NULL),
(346, 'Fatos e opiniões no texto jornalístico. Pronomes demonstrativos', NULL),
(347, 'Análise de manchetes de jornais. Presente histórico', NULL),
(348, 'Fotonotícias. Fotorreportagens. Fotodenúncias', NULL),
(349, 'Leitura e análise de infográficos', NULL),
(350, 'Leitura de artigo de opinião', NULL),
(351, 'Resenha crítica', NULL),
(352, 'Reflexão crítica sobre função social e intencionalidade de textos', NULL),
(353, 'Leitura de texto de opinião. Movimentos argumentativos (sustentação e negociação)', NULL),
(354, 'Leitura de textos publicitários. Análise de efeitos de sentido (verbais e não verbais). Função social e estrutura do gênero anúncio publicitário', NULL),
(355, 'Leitura de textos publicitários. Ortografia: palavras que geram dúvida', NULL),
(356, 'Gênero debate', NULL),
(357, 'Debate: Parte 1 – preparação para o evento', NULL),
(358, 'Debate: Parte 2 – apresentação do evento a partir da discussão de tópicos polêmicos', NULL),
(359, 'Debate: Parte 3 – avaliação dos grupos do debate (planejamento, produção, revisão dos textos e apresentação oral)', NULL),
(360, 'Período composto por coordenação', NULL),
(361, 'Texto literário e não literário (definição)', NULL),
(362, 'Contexto de produção e circulação de textos literários (Barroco, Arcadismo e Pré- Romantismo)', NULL),
(363, 'Intertextualidade e interdiscursividade', NULL),
(364, 'Construção de sentido a partir da relação entre textos', NULL),
(365, 'Introdução ao Romantismo', NULL),
(366, 'Romantismo em Portugal', NULL),
(367, 'Estrutura da oração (sujeito, predicado)', NULL),
(368, 'Estrutura da oração (sujeito, predicado, complementos verbais e nominais)', NULL),
(369, 'Emprego da conjunção adversativa “mas” e do advérbio de intensidade comparativa “mais”', NULL),
(370, 'Conectivos – conjunções e locuções conjuntivas', NULL),
(371, 'Uso de pronomes', NULL),
(372, 'Slogan. Pontuação', NULL),
(373, 'Morfossintaxe e estilo nos textos literários: ordem dos constituintes, coordenação, subordinação, concordância e regência. Efeitos de sentido gerados pelas escolhas linguísticas e estruturais. Contextualização das escolhas linguísticas conforme época, autor e situação comunicativa', NULL),
(374, 'Acentuação', NULL),
(375, 'Poema – marcas do gênero. Contexto de produção de texto literário', NULL),
(376, 'Gregório de Matos. Informações sobre o poeta e seu tempo. A poesia satírica. Análise de poema', NULL),
(377, 'Arcadismo: período e características, principais autores e obras', NULL),
(378, 'Barroco e Arcadismo: períodos e características, principais autores e obras', NULL),
(379, 'Barroco (retomada): período e características, principais autores e obras. Emprego do verbo "haver"', NULL),
(380, 'Neoclassicismo e Pré-Romantismo português', NULL),
(381, 'O abolicionismo na literatura romântica brasileira. Maria Firmina dos Reis e o Romantismo no Brasil. Construção frasal e recursos linguísticos', NULL),
(382, 'Mulheres na literatura romântica no Brasil. Narcisa Amália e o Romantismo no Brasil. O abolicionismo na literatura romântica brasileira', NULL),
(383, 'Textos multimodais diversos', NULL),
(384, 'Artigo de opinião', NULL),
(385, 'Leitura de cartaz', NULL),
(386, 'Leitura de texto de divulgação científica', NULL),
(387, 'Identificação e inferência de motivações e/ou finalidades do texto/autor', NULL),
(388, 'Textos de divulgação científica: estrutura e características', NULL),
(389, 'Progressão temática', NULL),
(390, 'Pesquisa científica', NULL),
(391, 'Curadoria de informações', NULL),
(392, 'Referências bibliográficas e normas de referência', NULL),
(393, 'Citação direta e indireta', NULL),
(394, 'Gênero resumo', NULL),
(395, 'Citação direta e paráfrase', NULL),
(396, 'Análise de resenha crítica de livro', NULL),
(397, 'Adjetivos e orações adjetivas', NULL),
(398, 'Escrita e compartilhamento de resenhas', NULL),
(399, 'O gênero sinopse', NULL),
(400, 'Leitura de verbete enciclopédico. Compreensão do tipo textual expositivo. Denotação e conotação', NULL),
(401, 'Modalizadores discursivos. Tipos de modalizadores. Análise de modalizadores em diferentes textos', NULL),
(402, 'Leitura e análise de conto. Classes de palavras (revisão)', NULL),
(403, 'Leitura de e análise de artigo de opinião. Conectores sequenciais e referenciais', NULL),
(404, 'Gênero charge: características', NULL),
(405, 'Leitura e interpretação', NULL),
(406, 'Linguagem verbal, não verbal e mista', NULL),
(407, 'Leitura e análise de resultados de pesquisa', NULL),
(408, 'Curadoria de textos de científicos', NULL),
(409, 'Artigo científico como fonte de pesquisa', NULL),
(410, 'Textos científicos e sua função social', NULL),
(411, 'Gênero anúncio publicitário', NULL),
(412, 'Elementos de persuasão', NULL),
(413, 'Modo imperativo do verbo', NULL),
(414, 'Gênero anúncio publicitário e slogan', NULL),
(415, 'Tipo textual injuntivo', NULL),
(416, 'Função apelativa ou conativa da linguagem', NULL),
(417, 'Linguagem verbal e não verbal', NULL),
(418, 'Gênero conto. Foco narrativo', NULL),
(419, 'Gênero literário conto. Elementos da narrativa', NULL),
(420, 'Leitura e análise de contos. Reconstrução das condições de produção, circulação e recepção de textos artístico-literários no Brasil. José de Alencar e sua relevância na literatura brasileira. Literatura indianista', NULL),
(421, 'Literatura comparada. Análise de texto indianista do século XIX e literatura indígena contemporânea', NULL),
(422, 'Planejamento de texto de divulgação científica', NULL),
(423, 'Banner de divulgação científica', NULL),
(424, 'Apresentação de texto de divulgação científica: exposição e discussão', NULL),
(425, 'Autoavaliação de apresentação', NULL),
(426, 'Tese, argumentos, refutação', NULL),
(427, 'Pré-Modernismo. Euclides da Cunha. Lima Barreto. Augusto dos Anjos', NULL),
(428, 'A poética de Oswald de Andrade. Revistas modernistas brasileiras. Ortografia', NULL),
(429, 'Leitura de poemas. Comparação de literaturas (portuguesa, africana, brasileira, indígena, latino-americana etc.). Contexto de produção de texto literário', NULL),
(430, 'Leitura do conto "Pai contra mãe", de Machado de Assis. Compreensão do conto. Análise do contexto de produção', NULL),
(431, 'Retomada de conto. Análise de contexto de produção. Figura de linguagem: personificação', NULL),
(432, 'Leitura de conto de Guimarães Rosa. Compreensão do conto. Análise de efeitos de sentido de trechos específicos', NULL),
(433, 'Efeitos de sentido do conto. Análise de contexto de produção. Variação linguística', NULL),
(434, 'Leitura de conto. Compreensão do conto. Análise de efeitos de sentido de trechos específicos', NULL),
(435, 'Leitura e compreensão do conto. Análise dos efeitos de sentido do conto. Análise de contexto de produção', NULL),
(436, 'Conceito de manifesto e antropofagia. Manifesto antropófago', NULL),
(437, 'Semana de Arte Moderna. Poética de Manuel Bandeira', NULL),
(438, 'Primeira geração modernista. Poética de Mário de Andrade', NULL),
(439, 'Primeira geração modernista. Poética de Oswald de Andrade', NULL),
(440, 'Segunda geração modernista e poesia dos anos 1930. Poética de Carlos Drummond de Andrade', NULL),
(441, 'Segunda geração modernista e poesia dos anos 1930. Poética de Murilo Mendes', NULL),
(442, 'A segunda geração modernista: prosa regionalista. Prosa de Rachel de Queiroz', NULL),
(443, 'A segunda geração modernista: prosa regionalista. Prosa de Graciliano Ramos', NULL),
(444, 'A segunda geração modernista: prosa regionalista. Prosa de Jorge Amado', NULL),
(445, 'Leitura e análise de crônica', NULL),
(446, 'Artigo de opinião: características', NULL),
(447, 'Leitura e compreensão de artigo de opinião', NULL),
(448, 'Comparação de dados e informações em textos de divulgação científica opinativos', NULL),
(449, 'Identificação de posicionamento crítico', NULL),
(450, 'Averiguação de fidedignidade de informações', NULL),
(451, 'Editorial. Reflexão crítica sobre função social e intencionalidade de textos', NULL),
(452, 'Formas contemporâneas de publicidade. Reflexão crítica sobre função social e intencionalidade de textos', NULL),
(453, 'Leitura de notícia. Visão de mundo no texto. Identificação e inferência de motivações e/ou finalidades do texto/autor', NULL),
(454, 'Leitura de reportagem. Vozes no texto. Identificação e inferência de motivações e/ou finalidades do texto/autor. Regência verbal e nominal', NULL),
(455, 'Leitura e análise de editorial', NULL),
(456, 'Orações subordinadas adjetivas; Modalização textual', NULL),
(457, 'Modalização textual; Orações subordinadas adverbiais', NULL),
(458, 'Orações coordenadas sindéticas aditivas, adversativas, alternativas, conclusivas, explicativas', NULL),
(459, 'Paralelismo sintático', NULL),
(460, 'Sistematização de diferenças marcantes entre romances românticos e realistas, com base em trechos de livros. Figuras de linguagem: metonímia e sinestesia', NULL),
(461, 'O gênero notícia: estrutura e características. Sinais de pontuação', NULL),
(462, 'Operadores lógico-discursivos', NULL),
(463, 'Ordem direta e inversões', NULL),
(464, 'Conjunções e outros elementos coesivos', NULL),
(465, 'Gênero textual romance. Romantismo. Obras abordadas: Iracema e Senhora, ambas de José de Alencar', NULL),
(466, 'Gênero textual romance. Realismo. Obra abordada: Dom Casmurro, de Machado de Assis', NULL),
(467, 'Sistematização de diferenças marcantes entre romances românticos e realistas, com base em trechos de livros', NULL),
(468, 'Definições e características das vanguardas europeias', NULL),
(469, 'Leitura e análise de crônica. Intertextualidade. Polissemia', NULL),
(470, 'Leitura e compreensão do Estatuto da Pessoa Idosa (texto normativo)', NULL),
(471, 'Entrevista oral', NULL),
(472, 'Marcas de oralidade', NULL),
(473, 'Variação linguística', NULL),
(474, 'Marcas de oralidade em textos transcritos', NULL),
(475, 'Tipos de transcrição', NULL),
(476, 'Definição de esporte de invasão. História do handebol. Regras do handebol. Movimentos/fundamentos. Posições e sistemas táticos', NULL),
(477, 'Jogo pré-desportivo do handebol: Queimada', NULL),
(478, 'Jogo pré-desportivo do handebol: Resgate', NULL),
(479, 'Fundamentos do handebol através de um circuito de estações; cada uma referente a um ou mais fundamentos do handebol: empunhadura, recepção, passe, finta, drible e arremesso', NULL),
(480, 'Exercícios em duplas, trios e grupos, se utilizando dos fundamentos do handebol', NULL),
(481, 'Jogo de handebol com equipes femininas e equipes masculinas', NULL),
(482, 'Jogo de handebol com equipes mistas', NULL),
(483, 'Esporte de marca. Atletismo. Provas do atletismo. Esportes e Jogos Paralímpicos. Atletismo paralímpico', NULL),
(484, 'Corrida de velocidade. Corrida de revezamento', NULL),
(485, 'Corrida com barreiras. Corrida com obstáculos', NULL),
(486, 'Salto vertical. Salto horizontal', NULL),
(487, 'Arremesso de peso. Lançamento de disco', NULL),
(488, 'Caminhada de olhos vendados', NULL),
(489, 'com guia', NULL),
(490, 'Corrida de olhos vendados', NULL),
(491, 'Danças: origem; elementos constitutivos; diferentes estilos e evolução em diferentes épocas', NULL),
(492, 'Danças urbanas: o movimento, a música e a dança Hip-hop', NULL),
(493, 'Diferentes sensações através da dança', NULL),
(494, 'Processo criativo: RAP', NULL),
(495, 'Movimentos do Break', NULL),
(496, 'Criação de coreografias de hip-hop em grupos', NULL),
(497, 'Ensaio das coreografias criadas', NULL),
(498, 'Apresentação das coreografias criadas', NULL),
(499, 'Definição de Ginástica de Condicionamento Físico:', NULL),
(500, 'Conceito de Capacidades Físicas', NULL),
(501, 'Conceito de exercícios aeróbios e exercícios anaeróbios', NULL),
(502, 'Benefícios da GCF e prática de alongamento (flexibilidade)', NULL),
(503, 'Circuito de capacidades físicas (flexibilidade, velocidade, agilidade, resistência e força)', NULL),
(504, 'Estafetas de capacidades físicas (velocidade e agilidade)', NULL),
(505, 'Exercícios aeróbios (caminhar, correr e pedalar)', NULL),
(506, 'Exercícios anaeróbios (membros superiores)', NULL),
(507, 'Exercícios anaeróbios (membros inferiores)', NULL),
(508, 'Lutas do Brasil', NULL),
(509, 'Conceitos', NULL),
(510, 'Capoeira Regional × Capoeira Angola', NULL),
(511, 'Golpes da capoeira', NULL),
(512, 'A música, os instrumentos e o ritmo da capoeira', NULL),
(513, 'A ginga como posição base da capoeira', NULL),
(514, 'Movimentos básicos a partir da ginga: Meia-lua de frente;Queixada; Armada', NULL),
(515, 'Outros movimentos da capoeira: Martelo, Bênção, Aú, Cocorinha etc', NULL),
(516, 'Atividades lúdicas se utilizando de movimentos da capoeira, em roda', NULL),
(517, 'Roda de capoeira com os golpes aprendidos', NULL),
(518, 'Definição de Esporte de precisão', NULL),
(519, 'O boliche como esporte de precisão', NULL),
(520, 'A bocha como esporte de precisão', NULL),
(521, 'A bocha paralímpica', NULL),
(522, 'Práticas alternativas de precisão', NULL),
(523, 'Confecção de materiais para jogar boliche e bocha nas aulas de Educação Física', NULL),
(524, 'Jogo de boliche com os materiais confeccionados', NULL),
(525, 'Jogo de bocha com os materiais confeccionados', NULL),
(526, 'Jogo de bocha no contexto paralímpico', NULL),
(527, 'Opção de brincadeiras e jogos pré-desportivos com materiais recicláveis/ adaptados/ alternativos', NULL),
(528, 'O movimento Hip Hop: Street Dance', NULL),
(529, 'Os quatro estilos do Street Dance: Breaking, Locking, Popping e Freestyle', NULL),
(530, 'Passos básicos do breaking', NULL),
(531, 'Passos básicos do locking', NULL),
(532, 'Passos básicos do popping', NULL),
(533, 'Passos básicos do freestyle', NULL),
(534, 'Criação e ensaio de coreografias de street dance, em grupos', NULL),
(535, 'Ginástica de condicionamento físico', NULL),
(536, 'Capacidades físicas em ação', NULL),
(537, 'Benefícios do exercício regular', NULL),
(538, 'Criação de exercícios em grupos, se utilizando da ginástica de condicionamento físico', NULL),
(539, 'Desafios que se utilizam de diferentes capacidades físicas', NULL),
(540, 'Exploração das capacidades físicas por meio de exercícios em formato de circuito', NULL),
(541, 'Benefícios físicos: melhora da força, resistência, postura e saúde cardiovascular./Benefícios mentais: bem', NULL),
(542, 'estar, redução do estresse, aumento da concentração./Benefícios sociais: cooperação, respeito às regras, convivência e trabalho em equipe', NULL),
(543, 'Criação, em grupos, de programas de exercícios físicos', NULL),
(544, 'Apresentação, em grupos, dos programas de exercícios físicos criados', NULL),
(545, 'Definição de esporte de rede/ parede', NULL),
(546, 'História e características do voleibol', NULL),
(547, 'Fundamentos e regras do voleibol', NULL),
(548, 'Posicionamento e Rodízio', NULL),
(549, 'Esporte Paralímpico; vôlei sentado', NULL),
(550, 'Jogo pré-desportivo do voleibol: Volençol', NULL),
(551, 'Jogo pré-desportivo do voleibol: Rede Humana', NULL),
(552, 'Jogo pré-desportivo do voleibol: Câmbio', NULL),
(553, 'Fundamentos do voleibol através de um circuito de estações; cada uma referente a um ou mais fundamentos do voleibol: saque por baixo, toque, machete etc', NULL),
(554, 'Exercícios em duplas, trios e grupos, se utilizando dos fundamentos do voleibol', NULL),
(555, 'Jogo de voleibol com 4 equipes praticando ao mesmo tempo (meia quadra)', NULL),
(556, 'Jogo de voleibol com rodízio 6x0', NULL),
(557, 'Prática e jogo de voleibol com regras, fundamentos e rodízio 6x0', NULL),
(558, 'Esporte Paralímpico: Vôlei sentado', NULL),
(559, 'Definição de esporte de campo e taco', NULL),
(560, 'Jogo de taco', NULL),
(561, 'Jogo base 4', NULL),
(562, 'Beisebol', NULL),
(563, 'Jogo pré-desportivo do Beisebol: Taco', NULL),
(564, 'Jogo pré-desportivo do Beisebol: Base 4', NULL),
(565, 'Jogo de Beisebol adaptado para o ambiente escolar', NULL),
(566, 'Conceito de lutas do mundo', NULL),
(567, 'Origem do Judô, Jiu-Jitsu e do Caratê', NULL),
(568, 'Características específicas do Judô, Jiu-Jitsu e Caratê', NULL),
(569, 'Saudações e Ukemis do Judô', NULL),
(570, 'Técnicas de perna, braço e quadril no Judô', NULL),
(571, 'Vivências do Judô', NULL),
(572, 'simulação de luta', NULL),
(573, 'Jogos de oposição no Jiu-Jitsu', NULL),
(574, 'Técnicas do Jiu-Jitsu', NULL),
(575, 'Saudações e bases no caratê', NULL),
(576, 'Chutes no caratê', NULL),
(577, 'Socos e defesas no caratê', NULL),
(578, 'Katas no caratê', NULL),
(579, 'Materiais Digitais -Origem e evolução do Judô para cegos', NULL),
(580, 'Mudanças e adequações às regras base do judô para sua versão paralímpica', NULL),
(581, 'Ukemis e movimentações', NULL),
(582, 'Técnicas de perna, braço e quadril no Judô para cegos', NULL),
(583, 'Vivências do Judô para cegos', NULL),
(584, 'Retomada da definição de esporte de invasão', NULL),
(585, 'História do futsal', NULL),
(586, 'Regras e fundamentos do futsal', NULL),
(587, 'Esporte Paralímpico: Futebol de cegos', NULL),
(588, 'Fundamentos do futsal através de estafetas; domínio, condução, drible, passe de chapa, chute ao gol etc', NULL),
(589, 'Exercícios em duplas, trios e grupos, se utilizando dos fundamentos do futsal', NULL),
(590, 'Jogo pré-desportivo do futsal: Futsal de duplas', NULL),
(591, 'Jogo de Futsal com regras e fundamentos', NULL),
(592, 'equipes mistas', NULL),
(593, 'Jogo de futsal com regras e fundamentos', NULL),
(594, 'equipes femininas e equipes masculinas', NULL),
(595, 'História do basquetebol', NULL),
(596, 'Regras e fundamentos do basquetebol', NULL),
(597, 'Esporte Paralímpico: basquete em cadeira de rodas', NULL),
(598, 'Fundamentos do basquete através de estafetas; drible, passe, arremesso, rebote, defesa, bloqueio etc', NULL),
(599, 'Exercícios em duplas, trios e grupos, se utilizando dos fundamentos do basquete', NULL),
(600, 'Jogo pré-desportivo do basquete: Torrebol', NULL),
(601, 'Jogo de Basquete com regras e fundamentos', NULL),
(602, 'Esporte Paralímpico: Basquete em cadeira de rodas', NULL),
(603, 'Lutas de percussão', NULL),
(604, 'Boxe', NULL),
(605, 'Muay Thai', NULL),
(606, 'Posturas. Movimentações. Esquivas do Boxe', NULL),
(607, 'Golpes', NULL),
(608, 'jab, direto, cruzado, gancho. A Sombra', NULL),
(609, 'Postura. Movimentações. Esquivas e Bloqueios do Muay Thai', NULL),
(610, 'Golpes de membros superiores', NULL),
(611, 'Golpes de membros inferiores', NULL),
(612, 'Origem e evolução do MMA', NULL),
(613, 'Origem e evolução da esgrima', NULL),
(614, 'Mudanças e adequações às regras e dinâmicas da esgrima em sua versão paralímpica', NULL),
(615, 'Jogos de oposição no MMA', NULL),
(616, 'Práticas de golpes percussivos de membros superiores; Análise sobre as relações com outras modalidades vivenciadas', NULL),
(617, 'Práticas de golpes percussivos de membros inferiores; Análise sobre as relações com outras modalidades vivenciadas', NULL),
(618, 'Confecção de materiais para vivenciar a esgrima e a esgrima em cadeira de rodas nas aulas de Educação Física', NULL),
(619, 'Vivência da Esgrima', NULL),
(620, 'Adaptação da Esgrima em cadeira de rodas', NULL),
(621, 'Disputa de esgrima e disputa de esgrima em cadeira de rodas. Análise sobre a esgrima e a esgrima em cadeira de rodas. Relações, diferenças e desafios', NULL),
(622, 'Diferentes possibilidades de se praticar o Futebol; Futebol como prática democrática; Futebol de campo; Futebol society; Futsal; Fútbol callejero', NULL),
(623, 'Futebol de campo adaptado para o espaço escolar', NULL),
(624, 'Prática do futebol de campo adaptado', NULL),
(625, 'Futebol society de maneira adaptada para o espaço escolar', NULL),
(626, 'Prática do futebol society', NULL),
(627, 'Jogos pré-desportivos do futsal', NULL),
(628, 'Exercícios coletivos: fundamentos do futsal', NULL),
(629, 'Prática do Futsal', NULL),
(630, 'Regras, objetivos e vivências do fútbol callejero', NULL),
(631, 'Prática do fútbol callejero', NULL),
(632, 'Vivência de um futebol elencado pela turma', NULL),
(633, 'Retomada sobre a história e a importância dos esportes e jogos paralímpicos; Modalidades paralímpicas', NULL),
(634, 'Apresentação do goalball; Papel social, cultural e esportivo do goalball na inclusão', NULL),
(635, 'Goalball de maneira adaptada para o espaço escolar', NULL),
(636, 'Prática do goalball', NULL),
(637, 'Surgimento e diferenças entre o Rugby e o Futebol americano; Fundamentos e regras do Rugby e do Futebol Americano', NULL),
(638, 'Regras e possíveis adaptações do Rugby', NULL),
(639, '"Exercícios para atender o desenvolvimento técnico', NULL),
(640, 'Exercícios de condicionamento físico', NULL),
(641, 'Prática do Rugby', NULL),
(642, 'Regras e possíveis adaptações do Futebol americano', NULL),
(643, 'Exercícios de preparação física e treinamento técnico', NULL),
(644, 'Prática do Futebol americano', NULL),
(645, 'Definição de samba de roda; Significado histórico e cultural do carnaval; História do Ballet clássico; Origem da dança contemporânea', NULL),
(646, 'Musicalidade, ritmo e expressão corporal', NULL),
(647, 'Passos básicos do samba de roda: ginga, miudinho e trança', NULL),
(648, 'Simulação de um desfile de escola de samba', NULL),
(649, 'Posições e movimentos básicos do Ballet', NULL),
(650, 'Exploração livre de movimentos e improvisação guiada', NULL),
(651, 'Criação coletiva para dança contemporânea', NULL),
(652, 'Apresentação dos esportes de rede/quadra dividida; Diferença entre o Tênis de mesa e o Tênis de campo; Fundamentos e regras do Tênis de mesa e do Tênis de campo', NULL),
(653, 'Fundamentos; postura, saque, recepção, golpes básicos e tipos de empunhadura', NULL),
(654, 'Regras; Arbitragem', NULL),
(655, 'Prática do Tênis de Mesa; Diferenças com o Ping-Pong', NULL),
(656, 'Jogo de tênis de maneira adaptada para o espaço escolar', NULL),
(657, 'História e origem da Dança Circular, do Dabke e do Fandango; A chegada dessas danças ao Brasil; Significado, função cultural e contexto social dessas danças do mundo', NULL),
(658, 'Ritmo e musicalidade; Diversidade cultural', NULL),
(659, 'Formação do círculo e passos básicos', NULL),
(660, 'Ritmo e musicalidade; Relevância cultural', NULL),
(661, 'Formação e passos na roda', NULL),
(662, 'Olhar cultural', NULL),
(663, 'Formação, passo de base, passo cruzado e giro', NULL),
(664, 'Esporte de rede/quadra dividida; Esporte de invasão/ territorial; Punhobol; Kin-Ball; Tchoukball; Ultimate Frisbee', NULL),
(665, 'Regras e possíveis adaptações do Punhobol e/ou do Kimball', NULL),
(666, 'Prática do Punhobol e/ou do Kimball', NULL),
(667, 'Regras e possíveis adaptações do Tchoukball', NULL),
(668, 'Prática do Tchoukball', NULL),
(669, 'Regras e possíveis adaptações do Ultimate Frisbee', NULL),
(670, 'Prática do Ultimate Frisbee', NULL),
(671, 'Materiais Digitais -Esportes praticados em quadra de areia/ praia; Origem e características do Vôlei de praia, do Futevôlei, do Beach tennis e do Frescobol', NULL),
(672, 'Regras, possíveis adaptações e prática do Vôlei de praia', NULL),
(673, 'Regras e possíveis adaptações do Futevôlei', NULL),
(674, 'Prática de Futevôlei', NULL),
(675, 'Regras, possíveis adaptações e prática do Beach tennis', NULL),
(676, 'Regras e possíveis adaptações do Frescobol', NULL),
(677, 'Prática de Frescobol', NULL),
(678, 'Continentes. Oceanos. Paisagens pelo mundo', NULL),
(679, 'O conceito de paisagem.', NULL),
(680, 'Tipos de paisagem.', NULL),
(681, 'Planos da paisagem', NULL),
(682, 'Paisagens transformadas pela ação da natureza.', NULL),
(683, 'Paisagens transformadas por diferentes grupos sociais', NULL),
(684, 'O conceito de lugar', NULL),
(685, 'Lugares do cotidiano', NULL),
(686, 'Relação entre os lugares', NULL),
(687, 'O conceito de espaço geográfico.', NULL),
(688, 'Produção do espaço geográfico.', NULL),
(689, 'Trabalho, técnica e as transformações no espaço geográfico.', NULL),
(690, 'Mapas mentais. Lugares de vivência. Transformações no espaço geográfico', NULL),
(691, 'Atividades econômicas.', NULL),
(692, 'Setores da economia.', NULL),
(693, 'Extrativismos minerais, animal e vegetal', NULL),
(694, 'Principais produtos extrativistas.', NULL),
(695, 'Distribuição no espaço geográfico.', NULL),
(696, 'Impactos ambientais', NULL),
(697, 'Tipos de agricultura.', NULL),
(698, 'Principais cultivos.', NULL),
(699, 'Sistemas de Produção pecuária.', NULL),
(700, 'Principais criações da pecuária', NULL),
(701, 'Principais produtos agropecuários.', NULL),
(702, 'Distribuição agropecuária no espaço geográfico.', NULL),
(703, 'Processo de industrialização. As fases da industrialização.', NULL),
(704, 'Distribuição industrial no espaço geográfico', NULL),
(705, 'Indústrias de base, de bens intermediários e de bens de consumo', NULL),
(706, 'Comércios locais, eletrônico e internacional', NULL),
(707, 'Serviços de saúde, de educação, financeiros, de turismo, de transporte e de comunicação', NULL),
(708, 'Interdependência das atividades econômicas. Setores produtivos.', NULL),
(709, 'Estágios de produção das mercadorias. As paisagens urbanas. O processo de urbanização', NULL),
(710, 'Principais problemas urbanos', NULL),
(711, 'As paisagens rurais. As transformações no campo', NULL),
(712, 'Principais problemas no campo', NULL),
(713, 'Principais movimentos do planeta Terra e suas consequências', NULL),
(714, 'Representações do planeta Terra.', NULL),
(715, 'Definição de cartografia.', NULL),
(716, 'Evolução das técnicas cartográficas', NULL),
(717, 'Elementos e convenções cartográficas.', NULL),
(718, 'Projeções planas, cônicas e cilíndricas', NULL),
(719, 'Formas de orientação espacial.', NULL),
(720, 'Orientação nos mapas', NULL),
(721, 'Instrumentos de orientação espacial.', NULL),
(722, 'Paralelos, Meridianos, Zonas térmicas', NULL),
(723, 'Fusos horários.', NULL),
(724, 'Latitude e longitude.', NULL),
(725, 'Escalas gráficas, numéricas, grandes e pequenas', NULL),
(726, 'Cálculo de escala cartográfica', NULL),
(727, 'Croqui, Mapa, Carta, Planta', NULL),
(728, 'Mapa temático', NULL),
(729, 'Perfil topográfico', NULL),
(730, 'Litosfera, Atmosfera, Hidrosfera e Biosfera.', NULL),
(731, 'Composição e camadas da atmosfera.', NULL),
(732, 'Tempo e clima.', NULL),
(733, 'Frentes de ar.', NULL),
(734, 'Previsão do tempo.', NULL),
(735, 'Latitude, Altitude, Maritimidade e Continentalidade.', NULL),
(736, 'Precipitação e Temperatura.', NULL),
(737, 'Climograma', NULL),
(738, 'Localização e limites do território brasileiro.', NULL),
(739, 'Conceito de região e de regionalização.', NULL),
(740, 'Divisão regional do IBGE.', NULL),
(741, 'Características da região Norte, da região Nordeste, da região Centro-Oeste, da região Sul e da região Sudeste.', NULL),
(742, 'Complexos regionais ou regiões geoeconômicas.', NULL),
(743, 'Complexo regional Amazônia.', NULL),
(744, 'Complexo regional Centro-Sul.', NULL),
(745, 'Complexo regional do Nordeste.', NULL),
(746, 'Regiões do Brasil', NULL),
(747, 'Conceito de território e sua dimensão política.', NULL),
(748, 'Ciclos econômicos.', NULL),
(749, 'Construção do território brasileiro.', NULL),
(750, 'Características do território brasileiro.', NULL),
(751, 'Tensões ligadas ao uso e posse do território.', NULL),
(752, 'Transformações territoriais em São Paulo.', NULL),
(753, 'Estereótipos e representações territoriais nos meios de comunicação', NULL),
(754, 'Diversidade étnico-racial e cultural da população brasileira.', NULL),
(755, 'Fluxos migratórios históricos e contemporâneos.', NULL),
(756, 'Fatores de atração e repulsão populacional, com foco nos complexos regionais.', NULL),
(757, 'Taxas de natalidade e mortalidade no Brasil.', NULL),
(758, 'Densidade demográfica e migrações internas.', NULL),
(759, 'Censo demográfico e dados populacionais.', NULL),
(760, 'Pirâmide etária e estrutura da população brasileira.', NULL),
(761, 'População economicamente ativa e setores da economia.', NULL),
(762, 'Formação da diversidade étnico-racial no Brasil.', NULL),
(763, 'Análise de dados demográficos por etnia no Brasil', NULL),
(764, 'Transporte e comunicação na integração do território brasileiro', NULL),
(765, 'O espaço das redes no Brasil', NULL),
(766, 'Redes de transporte no Brasil', NULL),
(767, 'Evolução dos transportes e de comunicação no Brasil', NULL),
(768, 'Industrialização brasileira, concentração e desconcentração industrial no Brasil', NULL),
(769, 'Parques científicos e tecnológicos no Brasil', NULL),
(770, 'Conexão entre lugares, Redes de transporte e comunicação e Distribuição das atividades econômicas', NULL),
(771, 'Redes de transporte e comunicação', NULL),
(772, 'Desconcentração industrial', NULL),
(773, 'Do mundo bipolar ao mundo multipolar', NULL),
(774, 'A ascensão dos Estados Unidos', NULL),
(775, 'O poderio militar e econômico dos Estados Unidos', NULL),
(776, 'O poder político dos Estados Unidos', NULL),
(777, 'Estratégias diplomáticas e econômicas', NULL),
(778, 'Desafios e oportunidades para os países latino', NULL),
(779, 'americanos no contexto da Nova Ordem Mundial', NULL),
(780, 'Brasil e Nova Ordem Mundial', NULL),
(781, 'África e Nova Ordem Mundial. 1º bim: 1, 2, 3, 4', NULL),
(782, 'Conceitos da Geopolítica', NULL),
(783, 'Relações internacionais', NULL),
(784, 'Principais organizações mundiais', NULL),
(785, 'Países-membros da ONU', NULL),
(786, 'Funções, objetivos e estrutura da ONU', NULL),
(787, 'Regionalização e aspectos físicos da África', NULL),
(788, 'Conflitos civis no continente africano', NULL),
(789, 'Crise humanitária na África', NULL),
(790, 'Conflitos africanos', NULL),
(791, 'Regionalização e aspectos físicos da América', NULL),
(792, 'Estados Unidos e México', NULL),
(793, 'Tensões e conflitos entre Chile e Bolívia', NULL),
(794, 'Tensões e conflitos entre Argentina e Chile', NULL),
(795, 'Tensões e conflitos entre Venezuela e Guiana', NULL),
(796, 'GATT e OMC. Indicadores econômicos dos Estados Unidos, da China e dos BRICS.', NULL),
(797, 'Principais produtos e serviços comercializados por Estados Unidos e China, e entre Estados Unidos e BRICS.', NULL),
(798, 'Países membros e parceiros dos BRICS. Características gerais dos BRICS.', NULL),
(799, 'Economia global e emergente.', NULL),
(800, 'Brasil, Rússia, Índia, China e África do Sul.', NULL),
(801, 'USMCA, CAN, ALADI e MERCOSUL', NULL),
(802, 'Setores da economia', NULL),
(803, 'Descentralização e Recentralização econômica', NULL),
(804, 'Investimentos dos Estados Unidos no mundo', NULL),
(805, 'Influência do capital estadunidense no Brasil', NULL),
(806, 'Tecnologias e os setores da economia', NULL),
(807, 'Profissões do futuro', NULL),
(808, 'Oportunidades e desafios', NULL),
(809, 'Grandes Navegações e expansão marítima', NULL),
(810, 'Início da globalização e hegemonia europeia no controle territorial', NULL),
(811, 'Evolução dos mapas e representações do espaço', NULL),
(812, 'Visões eurocêntricas, divisão simbólica do mundo e cartografia como instrumento de poder', NULL),
(813, 'Organização do sistema colonial e pacto colonial', NULL),
(814, 'Consequências atuais da colonização nas fronteiras, culturas e relações de poder', NULL),
(815, 'Participação de países e colônias na 1ª e 2ª Guerras Mundiais.', NULL),
(816, 'Mudanças de fronteiras e divisões territoriais após os conflitos.', NULL),
(817, 'Consequências sociais, políticas e culturais para colonizadores e colonizados.', NULL),
(818, 'Características gerais da Guerra Fria e disputas geopolíticas em diferentes áreas.', NULL),
(819, 'Corrida espacial e tecnológica e o Muro de Berlim como símbolos da divisão global.', NULL),
(820, 'Disputas ideológicas e tecnológicas durante a Guerra Fria.', NULL),
(821, 'Divisão do mundo em blocos e consequências nas relações globais e nas desigualdades sociopolíticas.', NULL),
(822, 'Conceito de globalização e suas relações com a Geografia.', NULL),
(823, 'Características da primeira fase da globalização (séculos XV a XVII).', NULL),
(824, 'Segunda fase da globalização e a Revolução Industrial.', NULL),
(825, 'Êxodo rural, urbanização e mudanças nos modos de vida, consumo e trabalho.', NULL),
(826, 'Terceira fase da globalização: marcos e avanços tecnológicos.', NULL),
(827, 'Expansão das comunicações e novas formas de consumo, trabalho e informação.', NULL),
(828, 'Quarta fase da globalização e tecnologias emergentes.', NULL),
(829, 'Desigualdades, tensões e novas dinâmicas no mundo atual.', NULL),
(830, 'Tipos de moeda, evolução e circulação no sistema econômico global.', NULL),
(831, 'Moedas sociais, criptomoedas e alternativas locais ao sistema monetário tradicional.', NULL),
(832, 'Localização e limites do Oriente Médio.', NULL),
(833, 'Climas, relevos e recursos naturais predominantes.', NULL),
(834, 'Diversidade cultural e religiosa no Oriente Médio.', NULL),
(835, 'Principais dinâmicas populacionais da região.', NULL),
(836, 'Conflitos, tensões e disputas na região.', NULL),
(837, 'Principais influências nos conflitos contemporâneos do Oriente Médio.', NULL),
(838, 'O fim da URSS: causas, processo e desdobramentos.', NULL),
(839, 'Tensões geopolíticas atuais: mudanças territoriais e conflitos contemporâneos.', NULL),
(840, 'A influência política e econômica da Rússia na Eurásia.', NULL),
(841, 'Os conflitos na Ucrânia e na Geórgia: causas e consequências.', NULL),
(842, 'Desenvolvimento econômico, industrial e tecnológico da China nas últimas décadas.', NULL),
(843, 'Relação com Taiwan e impactos políticos regionais e globais da China.', NULL),
(844, 'O conflito entre as Coreias e seus desdobramentos.', NULL),
(845, 'Relações políticas dos países vizinhos (Japão e China) com o conflito coreano.', NULL),
(846, 'Processo político, econômico e populacional da Índia atual.', NULL),
(847, 'A questão da Caxemira e suas implicações territoriais e políticas', NULL),
(848, 'Economia global e seu impacto no cotidiano local.', NULL),
(849, 'Influência das corporações, instituições internacionais, cultura e identidade na globalização.', NULL),
(850, 'Principais organizações econômicas e comerciais e sua atuação no cenário mundial.', NULL),
(851, 'Definição, origem e princípios básicos dos direitos humanos.', NULL),
(852, 'Destaque para o contexto histórico do pós-segunda Guerra Mundial.', NULL),
(853, 'Direitos humanos atualmente: desafios e exemplos.', NULL),
(854, 'Fundamentos no pós-guerra.', NULL),
(855, 'Tipos de deslocamentos humanos.', NULL),
(856, 'Diferença entre migrantes e refugiados.', NULL),
(857, 'Principais causas dos deslocamentos contemporâneos.', NULL),
(858, 'Refugiados no Brasil. Causas, rotas e desafios da migração forçada', NULL),
(859, 'Diferenças entre Climatologia e Meteorologia.', NULL),
(860, 'Conceitos de Tempo e Clima.', NULL),
(861, 'Divisão das camadas da atmosfera e suas principais características.', NULL),
(862, 'Circulação geral da atmosfera.', NULL),
(863, 'Elementos e controles climáticos.', NULL),
(864, 'Principais elementos de um climograma: temperatura e precipitação.', NULL),
(865, 'Biomas associados a determinados padrões de climogramas.', NULL),
(866, 'Climogramas de diferentes regiões do mundo.', NULL),
(867, 'Principais regiões geomorfológicas do Brasil.', NULL),
(868, 'Relevo e ocupação humana.', NULL),
(869, 'Processos que causam degradação do relevo.', NULL),
(870, 'Principais riscos e desastres relacionados ao relevo.', NULL),
(871, 'Prevenção e mitigação: técnicas de manejo e medidas estruturais para minimizar riscos.', NULL),
(872, 'Prevenção e mitigação de impactos dos processos de desastres relacionados ao relevo.', NULL),
(873, 'Sistema Nacional de Unidades de Conservação da natureza (SNUC).', NULL),
(874, 'Principais unidades de conservação no Brasil.', NULL),
(875, 'Indústria 4.0 e automação', NULL),
(876, 'Distribuição da água na Terra. Conceito de bacia hidrográfica', NULL),
(877, 'Políticas públicas e práticas de gestão sustentável dos recursos hídricos', NULL),
(878, 'Processos endógenos e exógeno de formação do relevo', NULL),
(879, 'Definição de Bioma. Principais Biomas da Terra', NULL),
(880, 'Biomas do estado de São Paulo. Diferenças entre os biomas.', NULL),
(881, 'Importância da cartografia para a geografia. Elementos dos mapas. Projeções cartográficas', NULL),
(882, 'Cartografia temática. Mapas qualitativos e quantitativos', NULL),
(883, 'Cartografia tátil', NULL),
(884, 'Criação de produtos cartográficos', NULL),
(885, 'Definição de sensoriamento remoto. Origens do sensoriamento remoto', NULL),
(886, 'Definição de Sistema de Informações Geográficas (SIG). Histórico e evolução do SIG', NULL),
(887, 'Produção de mapas temáticos', NULL),
(888, 'Conceito de globalização', NULL),
(889, 'Conceito de produção.', NULL),
(890, 'Cadeias produtivas', NULL),
(891, 'Regionalismos e blocos econômicos', NULL),
(892, 'Globalização cultural.', NULL),
(893, 'Homogeneização cultural.', NULL),
(894, 'Principais conceitos de demografia.', NULL),
(895, 'Transição demográfica', NULL),
(896, 'Dados de demografia do Brasil.', NULL),
(897, 'Distribuição e principais características da população brasileira', NULL),
(898, 'Demografia da comunidade escolar', NULL),
(899, 'Evolução da economia do Brasil com destaque para os séculos XVIII, XIX e XX', NULL),
(900, 'Principais dados da economia brasileira atual, com destaque para o PIB.', NULL),
(901, 'O papel da economia brasileira no cenário mundial', NULL),
(902, 'Indicadores socioeconômicos do Brasil', NULL),
(903, 'Desigualdade socioeconômica e distribuição de renda no Brasil', NULL),
(904, 'O mercado de trabalho no Brasil e as desigualdades sociais.', NULL),
(905, 'Principais direitos dos trabalhadores no Brasil. Reformas trabalhistas e flexibilizações legais', NULL),
(906, 'Conceitos de Estado, nação e território', NULL),
(907, 'Conceito de Estado moderno. Processos históricos de formação das nações', NULL),
(908, 'Povos sem Estado. Conflitos e reivindicações por autonomia ou reconhecimento', NULL),
(909, 'Conflitos territoriais atuais. O papel da ONU e dos organismos internacionais nesses conflitos', NULL),
(910, 'Territorialidade e identidade. Diásporas e povos sem Estado. Desafios contemporâneos das cidades', NULL),
(911, 'Territórios Indígenas: importância cultural, social e geográfica', NULL),
(912, 'Demarcações dos territórios indígenas.', NULL),
(913, 'Urbanização no Brasil', NULL),
(914, 'Impactos socioambientais do processo de urbanização', NULL),
(915, 'O Processo de Urbanização Mundial', NULL),
(916, 'Problemas Urbanos e Desigualdades Socioespaciais', NULL),
(917, 'O espaço agrário brasileiro', NULL),
(918, 'Os contrastes dos modelos agrícolas', NULL),
(919, 'Onu e o cenário agrário', NULL),
(920, 'O agronegócio e as novas fronteiras', NULL),
(921, 'Fatores bióticos e abióticos', NULL),
(922, 'Cadeias alimentares e teias alimentares', NULL),
(923, 'Nicho ecológico e comunidade biológica', NULL),
(924, 'Pirâmides ecológicas', NULL),
(925, 'Fluxo de matéria e energia', NULL),
(926, 'Sucessão ecológica', NULL),
(927, 'Biomas terrestres brasileiros', NULL),
(928, 'Fotossíntese', NULL),
(929, 'Metabolismo energético', NULL),
(930, 'Respiração celular', NULL),
(931, 'Relações ecológicas', NULL),
(932, 'Degradação ambiental', NULL),
(933, 'Reflorestamento', NULL),
(934, 'Educação ambiental', NULL),
(935, 'Agroecologia e sistemas agroflorestais', NULL),
(936, 'Descarte e tratamento de resíduos', NULL),
(937, 'Biocombustíveis e biomassa', NULL),
(938, 'ODS 7', NULL),
(939, 'Biosfera, população, comunidade, hábitat e nicho ecológico', NULL),
(940, 'Efeito estufa', NULL),
(941, 'Composição da atmosfera', NULL),
(942, 'Tempo e clima', NULL),
(943, 'Aquecimento global', NULL),
(944, 'Mudanças climáticas', NULL),
(945, 'Eventos climáticos extremos', NULL),
(946, 'Educação para Redução de Riscos e Desastres', NULL),
(947, 'Impactos antrópicos no ambiente', NULL),
(948, 'Vulnerabilidades relacionadas às mudanças climáticas', NULL),
(949, 'Matriz energética', NULL),
(950, 'Fontes renováveis', NULL),
(951, 'Fontes não renováveis', NULL),
(952, 'Impactos socioambientais da geração de energia', NULL),
(953, 'Tipos de poluição', NULL),
(954, 'Poluição do ar e da água', NULL),
(955, 'Saneamento básico', NULL),
(956, 'Sistema fisiológico: visão', NULL),
(957, 'Sistema fisiológico: audição', NULL),
(958, 'Sistema respiratório', NULL),
(959, 'Sistema cardiovascular', NULL),
(960, 'Aplicação da radiação no diagnóstico e tratamento de enfermidades', NULL),
(961, 'Cuidados com a exposição à radiação em exames', NULL),
(962, 'Radiação ultravioleta', NULL),
(963, 'Efeitos da radiação no DNA', NULL),
(964, 'Cuidados com a exposição à radiação solar', NULL),
(965, 'Mitose', NULL),
(966, 'Câncer', NULL),
(967, 'Meiose', NULL),
(968, 'Gametogênese humana', NULL),
(969, 'Desmatamento, queimadas e mudanças climáticas', NULL),
(970, 'Mineração', NULL),
(971, 'Monocultura', NULL),
(972, 'Rios voadores', NULL),
(973, 'Crises hídrica e elétrica', NULL),
(974, 'Zoonoses', NULL),
(975, 'Quebra de barreira', NULL),
(976, 'Medidas profiláticas', NULL),
(977, 'Áreas de Preservação Permanente', NULL),
(978, 'Bioma Cerrado', NULL),
(979, 'Serviços ecossistêmicos', NULL),
(980, 'Perda de hábitat e fragmentação', NULL),
(981, 'Corredores ecológicos', NULL),
(982, 'Coexistência humano-fauna', NULL),
(983, 'Áreas verdes urbanas', NULL),
(984, 'Preservação e conservação', NULL),
(985, 'Ciência cidadã', NULL),
(986, 'Unidades de Conservação', NULL),
(987, 'Alterações em teias e cadeias alimentares', NULL),
(988, 'Relação ambiente e doenças', NULL),
(989, 'Vírus: capsídeo e material genético', NULL),
(990, 'Bioacumulação', NULL),
(991, 'Bioconcentração', NULL),
(992, 'Biomagnificação', NULL),
(993, 'Níveis tróficos', NULL),
(994, 'Bioindicadores', NULL),
(995, 'Defensivos agrícolas', NULL),
(996, 'Descarte indevido de resíduos', NULL),
(997, 'Polinização', NULL),
(998, 'Controle biológico', NULL),
(999, 'Sistema reprodutor de plantas com flores', NULL),
(1000, 'Organismos Geneticamente Modificados', NULL),
(1001, 'Transgênicos', NULL),
(1002, 'Biossegurança', NULL),
(1003, 'Transgenes', NULL),
(1004, 'Melhoramento genético', NULL),
(1005, 'Bioética', NULL),
(1006, 'Diversidade genética', NULL),
(1007, 'Biodiversidade', NULL),
(1008, 'Manipulação genética', NULL),
(1009, 'Riscos da perda da biodiversidade', NULL),
(1010, 'Big Bang', NULL),
(1011, 'Método científico', NULL),
(1012, 'Sistema Solar', NULL),
(1013, 'Corpos celestes', NULL),
(1014, 'Terra primitiva', NULL),
(1015, 'Tempo geológico', NULL),
(1016, 'Camadas da Terra', NULL),
(1017, 'Atmosfera', NULL),
(1018, 'Tipos de águas e distribuição no planeta', NULL),
(1019, 'Estados e mudanças de estado da matéria', NULL),
(1020, 'Poluição da água', NULL),
(1021, 'Biosfera', NULL),
(1022, 'Gravidade', NULL),
(1023, 'Esfericidade da Terra', NULL),
(1024, 'Movimento de rotação', NULL),
(1025, 'Movimento de translação', NULL),
(1026, 'Movimento aparente do Sol', NULL),
(1027, 'Pontos cardeais', NULL),
(1028, 'Movimentos da Lua', NULL),
(1029, 'Eclipse lunar', NULL),
(1030, 'Eclipse solar', NULL),
(1031, 'Estações do ano', NULL),
(1032, 'Modelo Terra-Sol-Lua', NULL),
(1033, 'Crosta terrestre', NULL),
(1034, 'Rochas sedimentares', NULL),
(1035, 'Rochas metamórficas', NULL),
(1036, 'Rochas magmáticas', NULL),
(1037, 'Formação do solo', NULL),
(1038, 'Fósseis', NULL),
(1039, 'Ações antrópicas no meio ambiente', NULL),
(1040, 'Preservação do solo', NULL),
(1041, 'Substâncias puras, simples e compostas', NULL),
(1042, 'Misturas homogêneas e heterogêneas', NULL),
(1043, 'Transformações químicas e físicas', NULL),
(1044, 'Separação de misturas', NULL),
(1045, 'Estado de organização da matéria', NULL),
(1046, 'Placas tectônicas', NULL),
(1047, 'Deriva continental', NULL),
(1048, 'Eventos naturais', NULL),
(1049, 'Vulcanismo', NULL),
(1050, 'Terremotos e tsunamis', NULL),
(1051, 'Atmosfera da Terra', NULL),
(1052, 'Camada de ozônio', NULL),
(1053, 'Pressão atmosférica', NULL),
(1054, 'Altitude', NULL),
(1055, 'Qualidade do ar', NULL),
(1056, 'Doenças respiratórias', NULL),
(1057, 'Força', NULL),
(1058, 'Máquinas simples', NULL),
(1059, 'Calor e temperatura', NULL),
(1060, 'Sensação térmica', NULL),
(1061, 'Máquinas térmicas', NULL),
(1062, 'Máquinas elétricas', NULL),
(1063, 'Construção de soluções tecnológicas', NULL),
(1064, 'Sustentabilidade', NULL),
(1065, 'Objetivos do Desenvolvimento Sustentável', NULL),
(1066, 'Plano de intervenção sustentável', NULL),
(1067, 'Combustíveis fósseis', NULL),
(1068, 'Desmatamento', NULL),
(1069, 'Queimadas', NULL),
(1070, 'Conscientização ambiental', NULL),
(1071, 'Microrganismos', NULL),
(1072, 'Doenças causadas por microrganismos', NULL),
(1073, 'Invertebrados', NULL),
(1074, 'Vertebrados', NULL),
(1075, 'Plantas terrestres', NULL),
(1076, 'Biodiversidade local', NULL),
(1077, 'Adolescência', NULL),
(1078, 'Puberdade', NULL),
(1079, 'Sistema nervoso', NULL),
(1080, 'Sistema endócrino', NULL),
(1081, 'Sistema genital', NULL),
(1082, 'Reprodução assexuada', NULL),
(1083, 'Reprodução sexuada', NULL),
(1084, 'Variabilidade genética', NULL),
(1085, 'Cuidado parental', NULL),
(1086, 'Reprodução dos vegetais', NULL),
(1087, 'Gimnospermas', NULL),
(1088, 'Angiospermas', NULL),
(1089, 'Prevenção', NULL),
(1090, 'ISTs', NULL),
(1091, 'Gravidez precoce', NULL),
(1092, 'Vulnerabilidade', NULL),
(1093, 'Sexualidade humana', NULL),
(1094, 'Drogas', NULL),
(1095, 'Macronutrientes e micronutrientes', NULL),
(1096, 'Guia Alimentar para a População Brasileira', NULL),
(1097, 'Informação nutricional', NULL),
(1098, 'Sistema digestório', NULL),
(1099, 'Processo de digestão', NULL),
(1100, 'Alimentação balanceada', NULL),
(1101, 'Inspiração e expiração', NULL),
(1102, 'Saúde do sistema respiratório', NULL),
(1103, 'Modelo do sistema respiratório', NULL),
(1104, 'Coração', NULL),
(1105, 'Sangue', NULL),
(1106, 'Vasos sanguíneos', NULL),
(1107, 'Sistema imune', NULL),
(1108, 'Doenças crônicas não transmissíveis', NULL),
(1109, 'Pressão arterial', NULL),
(1110, 'Natureza da ciência', NULL),
(1111, 'Produção do conhecimento científico', NULL),
(1112, 'Divulgação científica', NULL),
(1113, 'Desinformação', NULL),
(1114, 'Átomo', NULL),
(1115, 'Modelos atômicos', NULL),
(1116, 'Classificação periódica', NULL),
(1117, 'Estados físicos da matéria', NULL),
(1118, 'Mudanças de estado físico', NULL),
(1119, 'Fusão e ebulição', NULL),
(1120, 'Substâncias simples e compostas', NULL),
(1121, 'Alotropia', NULL),
(1122, 'Reações químicas', NULL),
(1123, 'Lei de Lavoisier', NULL),
(1124, 'Lei de Proust', NULL),
(1125, 'Leis ponderais', NULL),
(1126, 'Natureza das ondas', NULL),
(1127, 'Amplitude, frequência, período e velocidade', NULL),
(1128, 'Espectro eletromagnético', NULL),
(1129, 'Radiações ionizantes e não ionizantes', NULL),
(1130, 'Aplicações da radiação na saúde', NULL),
(1131, 'Interação das ondas', NULL),
(1132, 'Reflexão', NULL),
(1133, 'Refração', NULL),
(1134, 'Difração', NULL),
(1135, 'Som e comunicação', NULL),
(1136, 'Hereditariedade', NULL),
(1137, 'Biotecnologia', NULL),
(1138, 'Material genético', NULL),
(1139, 'Leis de Mendel', NULL),
(1140, 'Gametas', NULL),
(1141, 'Segregação', NULL),
(1142, 'Fecundação', NULL),
(1143, 'Heredogramas', NULL),
(1144, 'Lamarckismo', NULL),
(1145, 'Darwinismo', NULL),
(1146, 'Evolução biológica', NULL),
(1147, 'Filosofia e formação para a cidadania', NULL),
(1148, 'Origens da Filosofia', NULL),
(1149, 'Atitude filosófica', NULL),
(1150, 'Diálogo', NULL),
(1151, 'Lógica', NULL),
(1152, 'Falácias formais e informais', NULL),
(1153, 'Narrativa mitológica e discurso filosófico', NULL),
(1154, 'Períodos da história da Filosofia', NULL),
(1155, 'Campos de investigação da Filosofia', NULL),
(1156, 'Platão e Aristóteles', NULL),
(1157, 'Escola de Atenas', NULL),
(1158, 'Arte como objeto de reflexão filosófica', NULL),
(1159, 'Estética', NULL),
(1160, 'Conceitos fundamentais da Estética', NULL),
(1161, 'Conceito de crítica', NULL),
(1162, 'Reflexão estética', NULL),
(1163, 'Produção de significados', NULL),
(1164, 'Análise crítica de obra de arte', NULL),
(1165, 'Estereótipos geracionais', NULL),
(1166, 'Etarismo', NULL),
(1167, 'Alteridade', NULL),
(1168, 'Empatia', NULL),
(1169, 'Convívio intergeracional', NULL),
(1170, 'Estatuto da Criança e do Adolescente', NULL),
(1171, 'Estatuto da Juventude', NULL),
(1172, 'Estatuto da Pessoa Idosa', NULL),
(1173, 'O olhar do outro em Sartre', NULL),
(1174, 'Protagonismo juvenil', NULL),
(1175, 'Violência e suas análises filosóficas', NULL),
(1176, 'Hannah Arendt', NULL),
(1177, 'Dignidade humana', NULL),
(1178, 'Pico della Mirandola', NULL),
(1179, 'Immanuel Kant', NULL),
(1180, 'Direitos Humanos', NULL),
(1181, 'Liberdade republicana', NULL),
(1182, 'Autoritarismo', NULL),
(1183, 'Desigualdade', NULL),
(1184, 'Emmanuel Lévinas', NULL),
(1185, 'Legitimidade do poder soberano', NULL),
(1186, 'Direito divino ao poder', NULL),
(1187, 'Thomas Hobbes', NULL),
(1188, 'John Locke', NULL),
(1189, 'Jean-Jacques Rousseau', NULL),
(1190, 'Contrato social', NULL),
(1191, 'Liberalismo', NULL),
(1192, 'Direitos individuais', NULL),
(1193, 'Vontade geral', NULL),
(1194, 'Soberania popular', NULL),
(1195, 'Conceitos iniciais do movimento', NULL),
(1196, 'Função horária do MRU', NULL),
(1197, 'Movimento Retilíneo Uniforme', NULL),
(1198, 'Movimento Retilíneo Uniformemente Variado', NULL),
(1199, 'Equação de Torricelli', NULL),
(1200, 'Queda livre', NULL),
(1201, 'Lançamento vertical', NULL),
(1202, 'Movimento horizontal e oblíquo', NULL),
(1203, 'Movimento Circular Uniforme', NULL),
(1204, 'Acoplamento de polias', NULL),
(1205, 'Grandezas escalares e vetoriais', NULL),
(1206, 'Representação e operações com vetores', NULL),
(1207, 'Primeira Lei de Newton', NULL),
(1208, 'Segunda Lei de Newton', NULL),
(1209, 'Terceira Lei de Newton', NULL),
(1210, 'Forças de contato e de campo', NULL),
(1211, 'Blocos em superfícies sem atrito', NULL),
(1212, 'Polias', NULL),
(1213, 'Atrito estático e dinâmico', NULL),
(1214, 'Força elástica', NULL),
(1215, 'Plano inclinado', NULL),
(1216, 'Trabalho mecânico', NULL),
(1217, 'Trabalho de forças inclinadas', NULL),
(1218, 'Energia cinética', NULL),
(1219, 'Conservação da energia mecânica', NULL),
(1220, 'Impulso e colisões', NULL),
(1221, 'Escalas termométricas', NULL),
(1222, 'Dilatação térmica', NULL),
(1223, 'Calor sensível', NULL),
(1224, 'Calor latente', NULL),
(1225, 'Propagação do calor', NULL),
(1226, 'Gases ideais', NULL),
(1227, 'Leis dos gases', NULL),
(1228, 'Lei Geral dos Gases', NULL),
(1229, 'Modelo do gás perfeito', NULL),
(1230, 'Energia interna', NULL),
(1231, 'Primeira Lei da Termodinâmica', NULL),
(1232, 'Transformações gasosas', NULL),
(1233, 'Ciclos termodinâmicos', NULL),
(1234, 'Calor específico do gás', NULL),
(1235, 'Segunda Lei da Termodinâmica', NULL),
(1236, 'Ciclo de Carnot', NULL),
(1237, 'Motor Stirling', NULL),
(1238, 'Refrigeradores', NULL),
(1239, 'Rendimento e eficiência', NULL),
(1240, 'Carga elétrica', NULL),
(1241, 'Condutores e isolantes', NULL),
(1242, 'Eletrização', NULL),
(1243, 'Conservação da carga', NULL),
(1244, 'Lei de Coulomb', NULL),
(1245, 'Campo elétrico', NULL),
(1246, 'Superposição de campos', NULL),
(1247, 'Potencial elétrico', NULL),
(1248, 'Energia potencial elétrica', NULL),
(1249, 'Corrente elétrica', NULL),
(1250, 'Sentido real e convencional', NULL),
(1251, 'Resistores ôhmicos e não ôhmicos', NULL),
(1252, 'Primeira Lei de Ohm', NULL),
(1253, 'Potência elétrica', NULL),
(1254, 'Consumo de energia', NULL),
(1255, 'Resistores em série', NULL),
(1256, 'Associação mista', NULL),
(1257, 'Segunda Lei de Ohm', NULL),
(1258, 'Resistividade e temperatura', NULL),
(1259, 'Matéria e constituição da matéria', NULL),
(1260, 'Teoria atômica de Dalton', NULL),
(1261, 'Evolução dos modelos atômicos', NULL),
(1262, 'Experimento de Rutherford', NULL),
(1263, 'Modelo de Bohr', NULL),
(1264, 'Modelo quântico', NULL),
(1265, 'Número atômico e número de massa', NULL),
(1266, 'Isótopos', NULL),
(1267, 'Níveis e subníveis de energia', NULL),
(1268, 'Distribuição eletrônica', NULL),
(1269, 'Princípios de Aufbau, Pauli e Hund', NULL),
(1270, 'Elementos e substâncias químicas', NULL),
(1271, 'Tabela periódica', NULL),
(1272, 'Radioisótopos', NULL),
(1273, 'Estrutura da matéria', NULL),
(1274, 'Propriedades periódicas', NULL),
(1275, 'Emissões alfa, beta e gama', NULL),
(1276, 'Formação de substâncias', NULL),
(1277, 'Ligações químicas', NULL),
(1278, 'Ligação iônica', NULL),
(1279, 'Ligação covalente', NULL),
(1280, 'Ligação metálica', NULL),
(1281, 'Teoria do octeto', NULL),
(1282, 'Camada de valência', NULL),
(1283, 'Fórmula de Lewis', NULL),
(1284, 'Soluções e misturas', NULL),
(1285, 'Solubilidade', NULL),
(1286, 'Eletronegatividade', NULL),
(1287, 'Geometria molecular', NULL),
(1288, 'Polaridade', NULL),
(1289, 'Pontos de fusão e ebulição', NULL),
(1290, 'Interações intermoleculares', NULL),
(1291, 'Aminoácidos e proteínas', NULL),
(1292, 'Transformações químicas', NULL),
(1293, 'Reações e equações químicas', NULL),
(1294, 'Reagentes e produtos', NULL),
(1295, 'Símbolos químicos', NULL),
(1296, 'Balanceamento', NULL),
(1297, 'Extração de matéria-prima', NULL),
(1298, 'Uso de recursos naturais', NULL),
(1299, 'Impactos socioambientais', NULL),
(1300, 'Reações endotérmicas e exotérmicas', NULL),
(1301, 'Reações de combustão', NULL),
(1302, 'Metais pesados', NULL),
(1303, 'Toxicidade das substâncias químicas', NULL),
(1304, 'Tempo de permanência dos poluentes', NULL),
(1305, 'Plásticos: definição, classificação e estrutura', NULL),
(1306, 'Embalagens plásticas', NULL),
(1307, 'Poluição de ambientes aquáticos e terrestres', NULL),
(1308, 'Gases poluentes na atmosfera', NULL),
(1309, 'Gases de efeito estufa', NULL),
(1310, 'Emissões de CO2', NULL),
(1311, 'Entalpia de combustão', NULL),
(1312, 'Eficiência energética', NULL),
(1313, 'Gasolina, diesel, biodiesel, biogás e etanol', NULL),
(1314, 'Materiais, combustíveis e energias alternativas', NULL),
(1315, 'Lei de Hess', NULL),
(1316, 'Poder calorífico', NULL),
(1317, 'Teoria da força vital', NULL),
(1318, 'Postulados de Kekulé', NULL),
(1319, 'Hibridização do carbono', NULL),
(1320, 'Cadeias carbônicas', NULL),
(1321, 'Hidrocarbonetos', NULL),
(1322, 'Funções oxigenadas', NULL),
(1323, 'Funções nitrogenadas', NULL),
(1324, 'Funções halogenadas', NULL),
(1325, 'ODS 3', NULL),
(1326, 'Estrutura e importância de vitaminas', NULL),
(1327, 'Proteínas', NULL),
(1328, 'Carboidratos', NULL),
(1329, 'Ácidos graxos', NULL),
(1330, 'Isomeria plana', NULL),
(1331, 'Agrotóxicos e fertilizantes', NULL),
(1332, 'Insegurança alimentar', NULL),
(1333, 'Polímeros naturais e sintéticos', NULL),
(1334, 'Polimerização', NULL),
(1335, 'Isomeria cis-trans', NULL),
(1336, 'Consequências ambientais do uso de plásticos', NULL),
(1337, 'Surgimento da Sociologia', NULL),
(1338, 'Auguste Comte', NULL),
(1339, 'Fatos sociais', NULL),
(1340, 'Consciência coletiva', NULL),
(1341, 'Instituições sociais', NULL),
(1342, 'Durkheim', NULL),
(1343, 'Ação social', NULL),
(1344, 'Weber', NULL),
(1345, 'Materialismo histórico', NULL),
(1346, 'Luta de classes', NULL),
(1347, 'Marx', NULL),
(1348, 'Ideologia', NULL),
(1349, 'Alienação', NULL),
(1350, 'Cultura', NULL),
(1351, 'Identidade cultural', NULL),
(1352, 'Socialização primária e secundária', NULL),
(1353, 'Sociabilidade', NULL),
(1354, 'Identidade social e pessoal', NULL),
(1355, 'Contatos culturais', NULL),
(1356, 'Aculturação', NULL),
(1357, 'Assimilação', NULL),
(1358, 'Integração', NULL),
(1359, 'Sincretismo', NULL),
(1360, 'Hibridismo', NULL),
(1361, 'Etnocentrismo', NULL),
(1362, 'Relativismo cultural', NULL),
(1363, 'Observação e interpretação da realidade', NULL),
(1364, 'Olhar sociológico', NULL),
(1365, 'Estranhamento', NULL),
(1366, 'Desnaturalização', NULL),
(1367, 'Senso comum', NULL),
(1368, 'Estudo de caso', NULL),
(1369, 'Produção social das diferenças', NULL),
(1370, 'Marcadores sociais das diferenças', NULL),
(1371, 'Preconceito', NULL),
(1372, 'Discriminação', NULL),
(1373, 'Intolerância', NULL),
(1374, 'Estratificação social', NULL),
(1375, 'Classe social', NULL),
(1376, 'Desigualdade estrutural', NULL),
(1377, 'Mobilidade social', NULL),
(1378, 'Violência como construção social', NULL),
(1379, 'Violência simbólica', NULL),
(1380, 'Estruturas sociais', NULL),
(1381, 'Ordem social', NULL),
(1382, 'Raça e etnia', NULL),
(1383, 'Relações étnico-raciais', NULL),
(1384, 'Racismo e racismo estrutural', NULL),
(1385, 'Violência étnico-racial', NULL),
(1386, 'Gênero', NULL),
(1387, 'Relações sociais de gênero', NULL),
(1388, 'Violência de gênero', NULL),
(1389, 'Combate ao racismo', NULL),
(1390, 'Combate ao machismo', NULL),
(1391, 'Dignidade da pessoa humana', NULL),
(1392, 'Igualdade', NULL),
(1393, 'Não violência', NULL),
(1394, 'Situação dos Direitos Humanos no Brasil e no mundo', NULL),
(1395, 'Avanços e entraves', NULL),
(1396, 'Desafios para a concretização dos Direitos Humanos', NULL);
