INSERT INTO curriculum_contents (id, descricao, unidade_tematica) VALUES
(1, 'DanÃ§as Populares Brasileiras', NULL),
(2, 'Origens das DanÃ§as', NULL),
(3, 'VariaÃ§Ã£o de Tempo', NULL),
(4, 'ExpressÃ£o Corporal', NULL),
(5, 'Elementos da DanÃ§a', NULL),
(6, 'Movimentos do Frevo', NULL),
(7, 'Uso do EspaÃ§o', NULL),
(8, 'Fatores do Movimento', NULL),
(9, 'Jongo', NULL),
(10, 'Frevo', NULL),
(11, 'Siriri', NULL),
(12, 'CarimbÃ³', NULL),
(13, 'CriaÃ§Ãµes CoreogrÃ¡ficas', NULL),
(14, 'ExpressÃ£o na DanÃ§a', NULL),
(15, 'Processos Criativos', NULL),
(16, 'MÃºsica Brasileira', NULL),
(17, 'ProduÃ§Ã£o, RepertÃ³rio e CirculaÃ§Ã£o Musical', NULL),
(18, 'FunÃ§Ã£o Social da MÃºsica', NULL),
(19, 'RepertÃ³rio Musical IndÃ­gena e Afro-Brasileiro', NULL),
(20, 'Paisagem Sonora', NULL),
(21, 'Registro Musical', NULL),
(22, 'NotaÃ§Ã£o NÃ£o Convencional', NULL),
(23, 'ComposiÃ§Ã£o e ImprovisaÃ§Ã£o Musical', NULL),
(24, 'PercussÃ£o Corporal', NULL),
(25, 'Instrumentos e NotaÃ§Ã£o NÃ£o Convencionais', NULL),
(26, 'Instrumentos e Timbres', NULL),
(27, 'ImprovisaÃ§Ã£o Musical', NULL),
(28, 'ComposiÃ§Ã£o, ColaboraÃ§Ã£o e ImprovisaÃ§Ã£o Musical', NULL),
(29, 'ProduÃ§Ã£o e Registro Musical', NULL),
(30, 'IntroduÃ§Ã£o Ã  DanÃ§a', NULL),
Diversidade Cultural', NULL),
(32, 'HistÃ³ria da DanÃ§a', NULL),
(33, 'DanÃ§a ClÃ¡ssica', NULL),
(34, 'DanÃ§a Moderna', NULL),
(35, 'Fatores de Movimento', NULL),
(36, 'Qualidades dos Movimentos', NULL),
(37, 'SequÃªncias CoreogrÃ¡ficas', NULL),
(38, 'AÃ§Ãµes de EsforÃ§o', NULL),
(39, 'ImprovisaÃ§Ã£o na DanÃ§a', NULL),
(40, 'MÃºsica ClÃ¡ssica', NULL),
(41, 'MÃºsica Instrumental', NULL),
(42, 'MÃºsica Orquestral', NULL),
(43, 'Canto Coral', NULL),
(44, 'Estrutura do Coro', NULL),
(45, 'ProduÃ§Ã£o Musical', NULL),
(46, 'Estrutura da Orquestra', NULL),
(47, 'TÃ©cnicas de ExecuÃ§Ã£o', NULL),
(48, 'Instrumentos Convencionais', NULL),
(49, 'Timbres e CaracterÃ­sticas', NULL),
(50, 'NotaÃ§Ã£o Convencional', NULL),
(51, 'ComposiÃ§Ã£o Musical', NULL),
(52, 'TÃ©cnicas de ExecuÃ§Ã£o Musical', NULL),
(53, 'Performance Musical', NULL),
(54, 'Instrumentos Musicais', NULL),
(55, 'Origens da DanÃ§a', NULL),
(56, 'DanÃ§a Coletiva', NULL),
(57, 'ImprovisaÃ§Ã£o em DanÃ§a', NULL),
(58, 'AÃ§Ãµes Corporais DanÃ§adas', NULL),
(59, 'Personagens na DanÃ§a Popular', NULL),
(60, 'ImprovisaÃ§Ã£o Coletiva', NULL),
(61, 'Gravidade e Peso', NULL),
(62, 'AnÃ¡lise do Movimento', NULL),
(63, 'Partitura Corporal', NULL),
(64, 'ComposiÃ§Ã£o CoreogrÃ¡fica', NULL),
(65, 'ApreciaÃ§Ã£o Musical', NULL),
(66, 'HistÃ³ria da MÃºsica', NULL),
(67, 'MÃºsica Tradicional Africana', NULL),
(68, 'Timbre', NULL),
(69, 'MÃºsica IndÃ­gena', NULL),
(70, 'MÃºsica ContemporÃ¢nea', NULL),
(71, 'MÃºsica Afro-Brasileira', NULL),
(72, 'Elementos da MÃºsica', NULL),
(73, 'Jogos RÃ­tmicos', NULL),
(74, 'PrÃ¡ticas de CriaÃ§Ã£o', NULL),
(75, 'Movimento Cotidiano', NULL),
(76, 'Jogos e Brincadeiras', NULL),
(77, 'Kinesfera', NULL),
(78, 'Corpo-HÃ­brido e Corpo-Tela', NULL),
(79, 'CriaÃ§Ã£o CoreogrÃ¡fica', NULL),
(80, 'DanÃ§a ContemporÃ¢nea', NULL),
(81, 'IndependÃªncia ou CoexistÃªncia EstÃ©tica', NULL),
(82, 'Qualidades do Movimento', NULL),
(83, 'Musicalidade Corporal', NULL),
(84, 'Brincadeiras e DanÃ§a', NULL),
(85, 'Corpo MemÃ©tico e Corpo MidiÃ¡tico', NULL),
(86, 'Corpo e Tecnologia', NULL),
(87, 'MÃºsica Popular Brasileira', NULL),
(88, 'MÃºsica Popular Estrangeira', NULL),
(89, 'Movimentos Musicais HistÃ³ricos', NULL),
(90, 'CanÃ§Ã£o de Protesto', NULL),
(91, 'ExpressÃ£o, ComposiÃ§Ã£o e ApreciaÃ§Ã£o Musical', NULL),
(92, 'MÃºsica e Tecnologia', NULL),
(93, 'Elementos de ComposiÃ§Ã£o Musical', NULL),
(94, 'FunÃ§Ã£o Social da Arte', NULL),
(95, 'Cultura ContemporÃ¢nea', NULL),
(96, 'Processo Criativo', NULL),
(97, 'Arte e MÃ­dia', NULL),
(98, 'AnÃ¡lise CrÃ­tica', NULL),
(99, 'CriaÃ§Ã£o ArtÃ­stica', NULL),
(100, 'IntervenÃ§Ã£o ArtÃ­stica', NULL),
(101, 'ManifestaÃ§Ã£o ArtÃ­stica', NULL),
(102, 'Linguagens ArtÃ­sticas', NULL),
(103, 'ExpressÃ£o ArtÃ­stica', NULL),
(104, 'Artes do Corpo', NULL),
(105, 'EstereÃ³tipos Sociais', NULL),
(106, 'CriaÃ§Ã£o Musical', NULL),
(107, 'DanÃ§as Sociais', NULL),
(108, 'ExpressÃ£o IdentitÃ¡ria', NULL),
(109, 'Discurso CrÃ­tico', NULL),
(110, 'CrÃ­tica de Arte', NULL),
(111, 'Performatividade', NULL),
(112, 'PatrimÃ´nio Cultural', NULL),
(113, 'Pesquisa em Arte', NULL),
(114, 'AnÃ¡lise HistÃ³rica e Cultural', NULL),
(115, 'Manifesto ArtÃ­stico', NULL),
(116, 'EstÃ©tica Relacional', NULL),
(117, 'Processo Colaborativo', NULL),
(118, 'Impacto Cultural', NULL),
(119, 'Processos de CriaÃ§Ã£o', NULL),
(120, 'Movimentos ArtÃ­sticos', NULL),
(121, 'Compartilhamento de PrÃ¡ticas', NULL),
(122, 'Contexto HistÃ³rico e Cultural', NULL),
(123, 'Zeitgeist, âEspÃ­rito do Tempoâ', NULL),
(124, 'Manifestos Coletivos', NULL),
(125, 'Coletivos ArtÃ­sticos', NULL),
(126, 'Arte Colaborativa', NULL),
(127, 'Sistema de numeraÃ§Ã£o decimal', NULL),
(128, 'OperaÃ§Ãµes fundamentais com nÃºmeros naturais', NULL),
(129, 'MÃºltiplos e divisores', NULL),
(130, 'O conceito de fraÃ§Ã£o', NULL),
(131, 'OperaÃ§Ãµes fundamentais com nÃºmeros fracionÃ¡rios', NULL),
(132, 'PolÃ­gonos, triÃ¢ngulos e quadrilÃ¡teros', NULL),
(133, 'NÃºmeros inteiros', NULL),
(134, 'OperaÃ§Ãµes fundamentais com fraÃ§Ãµes', NULL),
(135, 'OperaÃ§Ãµes com nÃºmeros racionais nas formas fracionÃ¡ria e decimal', NULL),
(136, 'Figuras geomÃ©tricas planas no plano cartesiano', NULL),
(137, 'Ãrea de figuras geomÃ©tricas planas', NULL),
(138, 'OperaÃ§Ãµes fundamentais com nÃºmeros racionais', NULL),
(139, 'PotenciaÃ§Ã£o e propriedades da potenciaÃ§Ã£o', NULL),
(140, 'RadiciaÃ§Ã£o e relaÃ§Ãµes entre radiciaÃ§Ã£o e potenciaÃ§Ã£o', NULL),
(141, 'ExpressÃµes algÃ©bricas e noÃ§Ãµes de Ãlgebra', NULL),
(142, 'EquaÃ§Ãµes polinomiais do 1Âº grau', NULL),
(143, 'Sistemas de equaÃ§Ãµes polinomiais do 1Âº grau', NULL),
ComparaÃ§Ã£o, operaÃ§Ãµes fundamentais e potenciaÃ§Ã£o', NULL),
(145, 'CaracterÃ­sticas dos triÃ¢ngulos e semelhanÃ§a de triÃ¢ngulos', NULL),
(146, 'SemelhanÃ§a de triÃ¢ngulos e teorema de PitÃ¡goras', NULL),
(147, 'NÃºmeros irracionais e dÃ­zimas periÃ³dicas', NULL),
(148, 'NÃºmeros reais', NULL),
(149, 'NÃºmeros racionais', NULL),
(150, 'Teorema de PitÃ¡goras', NULL),
(151, 'Conceito de funÃ§Ã£o', NULL),
(152, 'RelaÃ§Ã£o entre grandezas e equaÃ§Ãµes polinomiais de 1Âº grau', NULL),
(153, 'FunÃ§Ã£o Afim â Parte 1', NULL),
(154, 'PotenciaÃ§Ã£o e notaÃ§Ã£o cientÃ­fica', NULL),
(155, 'EquaÃ§Ãµes polinomiais do 1Âº e 2Âº graus', NULL),
(156, 'EquaÃ§Ãµes exponenciais', NULL),
(157, 'FunÃ§Ãµes exponenciais', NULL),
(158, 'Logaritmos', NULL),
(159, 'FunÃ§Ãµes logarÃ­tmicas', NULL),
(160, 'EquaÃ§Ãµes polinomiais do 1Â° e 2Â° graus', NULL),
(161, 'Sistemas de equaÃ§Ãµes lineares â Parte 1', NULL),
(162, '138 - 173 Sistemas de equaÃ§Ãµes lineares â Parte 2', NULL),
(163, 'AnÃ¡lise combinatÃ³ria', NULL),
(164, 'Probabilidade â Parte 1', NULL),
(165, 'Probabilidade â Parte 2', NULL),
(166, 'Leitura de post', NULL),
(167, 'Leitura de comentÃ¡rios', NULL),
(168, 'Leitura de notÃ­cia', NULL),
(169, 'Leitura de charge', NULL),
(170, 'Acento circunflexo', NULL),
(171, 'Leitura de carta do leitor', NULL),
exclamaÃ§Ã£o e reticÃªncias', NULL),
fato central Ã subtemas', NULL),
substantivos', NULL),
adjetivos', NULL),
sÃ­laba tÃ´nica e acento grÃ¡fico', NULL),
X e CH', NULL),
(178, 'PontuaÃ§Ã£o', NULL),
uso da cedilha', NULL),
(180, 'TerminaÃ§Ã£o -gem', NULL),
(181, 'Palavras "mau" e "mal"', NULL),
(182, 'AcentuaÃ§Ã£o em palavras oxÃ­tonas, proparoxÃ­tonas e paroxÃ­tonas', NULL),
(183, 'O sentido de sufixos', NULL),
(184, 'Leitura de poema', NULL),
(185, 'Leitura de conto', NULL),
(186, 'Leitura de lenda', NULL),
(187, 'Leitura de trecho de romance infantojuvenil', NULL),
(188, 'Leitura de crÃ´nica literÃ¡ria', NULL),
(189, 'ConcordÃ¢ncia nominal', NULL),
verbos', NULL),
(191, 'ConcordÃ¢ncia verbal (sujeito simples)', NULL),
(192, 'SinÃ´nimos e antÃ´nimos', NULL),
(193, 'O sentido de prefixos', NULL),
(194, 'Leitura de carta de reclamaÃ§Ã£o', NULL),
subjuntivo. Tempos e modos verbais', NULL),
artigos definidos e indefinidos', NULL),
(197, 'Leitura e compreensÃ£o de poemas', NULL),
(198, 'ComparaÃ§Ã£o de notÃ­cias', NULL),
(199, 'Fato Ã opiniÃ£o em textos jornalÃ­sticos', NULL),
(200, 'Leitura de anÃºncio publicitÃ¡rio', NULL),
(201, 'Linguagem verbal e nÃ£o verbal em anÃºncios publicitÃ¡rios', NULL),
(202, 'Leitura de anÃºncio publicitÃ¡rio em mÃ­dias digitais', NULL),
(203, 'Leitura de reportagem', NULL),
(204, 'Leitura de fotorreportagem', NULL),
(205, 'CaracterÃ­sticas de fotorreportagens', NULL),
(206, 'Leitura de petiÃ§Ã£o', NULL),
(207, 'Leitura de entrevista', NULL),
(208, 'CoesÃ£o', NULL),
uso de Ã e SS', NULL),
(210, 'Leitura e interpretaÃ§Ã£o de notÃ­cias', NULL),
(211, 'Pronome demonstrativo', NULL),
(212, 'ModalizaÃ§Ã£o discursiva', NULL),
(213, 'Acento diferencial', NULL),
diferentes escolhas editoriais sobre um mesmo fato', NULL),
(215, 'Fato e opiniÃ£o', NULL),
(216, 'Leitura de textos multissemiÃ³ticos', NULL),
(217, 'Leitura de anÃºncio publicitÃ¡rio. Palavras-valise', NULL),
(218, 'Recursos linguÃ­stico-discursivos em folhetos/flyers de anÃºncios publicitÃ¡rios', NULL),
(219, 'Leitura de artigo de divulgaÃ§Ã£o cientÃ­fica. Elementos do artigo de divulgaÃ§Ã£o cientÃ­fica', NULL),
(220, 'ParagrafaÃ§Ã£o', NULL),
(221, 'Tese', NULL),
(222, 'OpiniÃ£o', NULL),
(223, 'EstratÃ©gias argumentativas', NULL),
(224, 'Verbo de aÃ§Ã£o', NULL),
(225, 'Verbo de estado', NULL),
pretÃ©rito. ConjunÃ§Ã£o', NULL),
(227, 'Leitura de romance infantojuvenil. Leitura de conto popular', NULL),
(228, 'Leitura de conto de ficÃ§Ã£o cientÃ­fica. EstratÃ©gias de leitura. FÃ¡bula', NULL),
narrador e personagens', NULL),
(230, 'Verbos de enunciaÃ§Ã£o', NULL),
(231, 'Leitura de parÃ¡bola', NULL),
causa e consequÃªncia', NULL),
(233, 'Leitura de poemas', NULL),
(234, 'Poemas de versos livres Ã forma fixa', NULL),
(235, 'Leitura de conto indÃ­gena', NULL),
(236, 'EstratÃ©gias de leitura', NULL),
(237, 'Mecanismos da narrativa', NULL),
quarta capa', NULL),
(239, 'Programa (de teatro, danÃ§a, exposiÃ§Ãµes etc.)', NULL),
(240, 'Leitura de cartaz de campanha', NULL),
(241, 'ComparaÃ§Ã£o entre peÃ§as publicitÃ¡rias', NULL),
(242, 'EstratÃ©gias de persuasÃ£o com recursos linguÃ­stico-discursivos (jogos de palavras, metÃ¡foras, sentidos figurados etc.)', NULL),
(243, 'Intertextualidade em textos diversos', NULL),
(244, 'Valores culturais em textos literÃ¡rios', NULL),
(245, 'Contos populares', NULL),
(246, 'EstratÃ©gias de leitura de textos literÃ¡rios', NULL),
(247, 'PrÃ¡ticas de leitura de textos literÃ¡rios', NULL),
(248, 'Contos indÃ­genas', NULL),
(249, 'Leitura de piadas e anedotas', NULL),
(250, 'Leitura de contos de humor', NULL),
(251, 'Leitura de parÃ³dia e sÃ¡tira', NULL),
(252, 'Leitura de mito', NULL),
(253, 'CoesÃ£o e coerÃªncia em textos narrativos', NULL),
(254, 'Tessitura textual', NULL),
(255, 'Leitura de crÃ´nica', NULL),
(256, 'Relato de viagem', NULL),
(257, 'Adjuntos adverbiais', NULL),
(258, 'Leitura de notÃ­cia impressa e digital', NULL),
(259, 'Leitura e anÃ¡lise crÃ­tica de artigo de opiniÃ£o', NULL),
(260, 'Leitura de trecho de romance', NULL),
(261, 'CaracterÃ­sticas de texto de divulgaÃ§Ã£o cientÃ­fica', NULL),
parÃªnteses e aspas', NULL),
(263, 'Leitura de memÃ³rias', NULL),
(264, 'Leitura de biografia', NULL),
(265, 'Leitura de autobiografia', NULL),
(266, 'Leitura de diÃ¡rio pessoal', NULL),
(267, 'CompreensÃ£o de efeitos de sentido', NULL),
(268, 'Verbos', NULL),
(269, 'Estudo de tempos verbais', NULL),
(270, 'Presente histÃ³rico', NULL),
(271, 'PretÃ©rito imperfeito do indicativo', NULL),
ponto-final', NULL),
sujeito e predicado', NULL),
(274, 'ConcordÃ¢ncia verbal e nominal', NULL),
(275, 'Observar uso de hÃ­fen no texto e conhecer critÃ©rios de hifenizaÃ§Ã£o', NULL),
(276, 'Modos indicativo e subjuntivo', NULL),
acentuaÃ§Ã£o', NULL),
(278, 'Transitividade verbal', NULL),
(279, 'Tempos e modos verbais', NULL),
(280, 'Sentido real e figurado de palavras', NULL),
(281, 'Artigos definidos e indefinidos', NULL),
(282, 'Verbo "haver" como auxiliar', NULL),
(283, 'PretÃ©rito perfeito e imperfeito do indicativo', NULL),
fato central', NULL),
fato central', NULL),
ideia central', NULL),
relaÃ§Ã£o entre parÃ¡grafos', NULL),
(288, 'ComparaÃ§Ã£o entre editorial e artigo de opiniÃ£o. Confiabilidade em textos jornalÃ­sticos', NULL),
(289, 'ArgumentaÃ§Ã£o', NULL),
oxÃ­tonas, paroxÃ­tonas e proparoxÃ­tonas', NULL),
(291, 'Leitura de tirinha', NULL),
(292, 'Leitura de cartaz instrucional (primeiros socorros)', NULL),
(293, 'Cartaz sobre direitos e deveres do estudante', NULL),
(294, 'Leitura de cartaz de campanha de saÃºde', NULL),
(295, 'EstratÃ©gias de persuasÃ£o', NULL),
(296, 'CaracterÃ­sticas de anÃºncios publicitÃ¡rios', NULL),
metÃ¡fora', NULL),
modo imperativo', NULL),
(299, 'Leitura de anÃºncio publicitÃ¡rio digital', NULL),
(300, 'Ortografia', NULL),
(301, 'Ficha catalogrÃ¡fica', NULL),
(302, 'Resumo', NULL),
(303, 'Leitura de esquema(s)', NULL),
(304, 'Leitura de relatÃ³rio(s)', NULL),
(305, 'Leitura de petiÃ§Ã£o online', NULL),
(306, 'CoesÃ£o sequencial', NULL),
(307, 'Modalizadores argumentativos', NULL),
(308, 'Leitura de carta aberta', NULL),
(309, 'Ler memes e gifs, analisando efeitos de sentido gerados pelo uso de linguagem verbal, nÃ£o verbal e mista', NULL),
(310, 'Refletir e posicionar-se de forma crÃ­tica e Ã©tica sobre opiniÃµes e visÃµes de mundo expressas por esses gÃªneros da cultura digital', NULL),
(311, 'Posts e comentÃ¡rios', NULL),
(312, 'AdequaÃ§Ã£o do registro escrito', NULL),
(313, 'A Idade MÃ©dia em Portugal e a influÃªncia da cultura galego-portuguesa. FlexÃ£o verbal (tempos e modos verbais)', NULL),
(314, 'As origens do Trovadorismo no sÃ©culo XII. A primeira Ã©poca medieval. ConjugaÃ§Ãµes verbais regulares e irregulares', NULL),
amor, amigo, escÃ¡rnio e maldizer', NULL),
fragmento de O Auto da Barca do Inferno, de Gil Vicente', NULL),
(317, 'Contexto histÃ³rico do Classicismo. Fragmento da obra Ã©pica Os LusÃ­adas, de CamÃµes. Vida e obra de LuÃ­s Vaz de CamÃµes e sua influÃªncia', NULL),
(318, 'Leitura de poemas. ComparaÃ§Ã£o entre caracterÃ­sticas de obras clÃ¡ssicas e obras marginais. Conceito de literatura marginal. Contracultura', NULL),
(319, 'Leitura e compreensÃ£o de poema', NULL),
(320, 'Figuras de linguagem (comparaÃ§Ã£o, metÃ¡fora, antÃ­tese e eufemismo)', NULL),
(321, 'Leitura e compreensÃ£o de biografia. Leitura e compreensÃ£o de poema', NULL),
(322, 'Leitura e compreensÃ£o de poemas. Figuras de linguagem (hipÃ©rbole, paradoxo e personificaÃ§Ã£o). Sonoridade em textos poÃ©ticos (rima, aliteraÃ§Ã£o, assonÃ¢ncia e eufonia)', NULL),
(323, 'Verbos. FlexÃ£o verbal', NULL),
(324, 'Elementos mÃ³rficos na formaÃ§Ã£o de palavras. FormaÃ§Ã£o de palavras (radicais, prefixos, sufixos)', NULL),
(325, 'Tipos de sujeito (simples, composto, oculto, indeterminado)', NULL),
slam. Linguagem informal e variedades linguÃ­sticas', NULL),
(327, 'A norma-padrÃ£o e a variaÃ§Ã£o linguÃ­stica. Ortografia e a contracultura na âgeraÃ§Ã£o mimeÃ³grafoâ. A poesia perifÃ©rica e a construÃ§Ã£o ortogrÃ¡fica', NULL),
(328, 'AdvÃ©rbios e locuÃ§Ãµes adverbiais', NULL),
(329, 'RegÃªncia verbal e nominal', NULL),
estrutura das palavras (radical, desinÃªncia, vogal temÃ¡tica, tema e afixos)', NULL),
derivaÃ§Ã£o', NULL),
(332, 'ConcordÃ¢ncia verbal com sujeito composto', NULL),
(333, 'RegÃªncia nominal e verbal', NULL),
(334, 'PerÃ­odo composto por coordenaÃ§Ã£o e subordinaÃ§Ã£o', NULL),
slam', NULL),
(336, 'VersificaÃ§Ã£o', NULL),
(337, 'Intertextualidade. ParÃ¡frase e parÃ³dia', NULL),
(338, 'DenotaÃ§Ã£o e conotaÃ§Ã£o em textos literÃ¡rios. Efeitos de sentido', NULL),
charges e cartuns', NULL),
(340, 'Neologismo. Estrangeirismo', NULL),
(341, 'AcentuaÃ§Ã£o de palavras', NULL),
(342, 'Elementos coesivos', NULL),
(343, 'CompreensÃ£o de texto', NULL),
(344, 'SensibilizaÃ§Ã£o para sentidos literais e nÃ£o literais', NULL),
(345, 'Literatura perifÃ©rica', NULL),
(346, 'Fatos e opiniÃµes no texto jornalÃ­stico. Pronomes demonstrativos', NULL),
(347, 'AnÃ¡lise de manchetes de jornais. Presente histÃ³rico', NULL),
(348, 'FotonotÃ­cias. Fotorreportagens. FotodenÃºncias', NULL),
(349, 'Leitura e anÃ¡lise de infogrÃ¡ficos', NULL),
(350, 'Leitura de artigo de opiniÃ£o', NULL),
(351, 'Resenha crÃ­tica', NULL),
(352, 'ReflexÃ£o crÃ­tica sobre funÃ§Ã£o social e intencionalidade de textos', NULL),
(353, 'Leitura de texto de opiniÃ£o. Movimentos argumentativos (sustentaÃ§Ã£o e negociaÃ§Ã£o)', NULL),
(354, 'Leitura de textos publicitÃ¡rios. AnÃ¡lise de efeitos de sentido (verbais e nÃ£o verbais). FunÃ§Ã£o social e estrutura do gÃªnero anÃºncio publicitÃ¡rio', NULL),
palavras que geram dÃºvida', NULL),
(356, 'GÃªnero debate', NULL),
Parte 1 â preparaÃ§Ã£o para o evento', NULL),
Parte 2 â apresentaÃ§Ã£o do evento a partir da discussÃ£o de tÃ³picos polÃªmicos', NULL),
Parte 3 â avaliaÃ§Ã£o dos grupos do debate (planejamento, produÃ§Ã£o, revisÃ£o dos textos e apresentaÃ§Ã£o oral)', NULL),
(360, 'PerÃ­odo composto por coordenaÃ§Ã£o', NULL),
(361, 'Texto literÃ¡rio e nÃ£o literÃ¡rio (definiÃ§Ã£o)', NULL),
(362, 'Contexto de produÃ§Ã£o e circulaÃ§Ã£o de textos literÃ¡rios (Barroco, Arcadismo e PrÃ©- Romantismo)', NULL),
(363, 'Intertextualidade e interdiscursividade', NULL),
(364, 'ConstruÃ§Ã£o de sentido a partir da relaÃ§Ã£o entre textos', NULL),
(365, 'IntroduÃ§Ã£o ao Romantismo', NULL),
(366, 'Romantismo em Portugal', NULL),
(367, 'Estrutura da oraÃ§Ã£o (sujeito, predicado)', NULL),
(368, 'Estrutura da oraÃ§Ã£o (sujeito, predicado, complementos verbais e nominais)', NULL),
(369, 'Emprego da conjunÃ§Ã£o adversativa âmasâ e do advÃ©rbio de intensidade comparativa âmaisâ', NULL),
(370, 'Conectivos â conjunÃ§Ãµes e locuÃ§Ãµes conjuntivas', NULL),
(371, 'Uso de pronomes', NULL),
(372, 'Slogan. PontuaÃ§Ã£o', NULL),
ordem dos constituintes, coordenaÃ§Ã£o, subordinaÃ§Ã£o, concordÃ¢ncia e regÃªncia. Efeitos de sentido gerados pelas escolhas linguÃ­sticas e estruturais. ContextualizaÃ§Ã£o das escolhas linguÃ­sticas conforme Ã©poca, autor e situaÃ§Ã£o comunicativa', NULL),
(374, 'AcentuaÃ§Ã£o', NULL),
(375, 'Poema â marcas do gÃªnero. Contexto de produÃ§Ã£o de texto literÃ¡rio', NULL),
(376, 'GregÃ³rio de Matos. InformaÃ§Ãµes sobre o poeta e seu tempo. A poesia satÃ­rica. AnÃ¡lise de poema', NULL),
perÃ­odo e caracterÃ­sticas, principais autores e obras', NULL),
perÃ­odos e caracterÃ­sticas, principais autores e obras', NULL),
perÃ­odo e caracterÃ­sticas, principais autores e obras. Emprego do verbo "haver"', NULL),
(380, 'Neoclassicismo e PrÃ©-Romantismo portuguÃªs', NULL),
(381, 'O abolicionismo na literatura romÃ¢ntica brasileira. Maria Firmina dos Reis e o Romantismo no Brasil. ConstruÃ§Ã£o frasal e recursos linguÃ­sticos', NULL),
(382, 'Mulheres na literatura romÃ¢ntica no Brasil. Narcisa AmÃ¡lia e o Romantismo no Brasil. O abolicionismo na literatura romÃ¢ntica brasileira', NULL),
(383, 'Textos multimodais diversos', NULL),
(384, 'Artigo de opiniÃ£o', NULL),
(385, 'Leitura de cartaz', NULL),
(386, 'Leitura de texto de divulgaÃ§Ã£o cientÃ­fica', NULL),
(387, 'IdentificaÃ§Ã£o e inferÃªncia de motivaÃ§Ãµes e/ou finalidades do texto/autor', NULL),
estrutura e caracterÃ­sticas', NULL),
(389, 'ProgressÃ£o temÃ¡tica', NULL),
(390, 'Pesquisa cientÃ­fica', NULL),
(391, 'Curadoria de informaÃ§Ãµes', NULL),
(392, 'ReferÃªncias bibliogrÃ¡ficas e normas de referÃªncia', NULL),
(393, 'CitaÃ§Ã£o direta e indireta', NULL),
(394, 'GÃªnero resumo', NULL),
(395, 'CitaÃ§Ã£o direta e parÃ¡frase', NULL),
(396, 'AnÃ¡lise de resenha crÃ­tica de livro', NULL),
(397, 'Adjetivos e oraÃ§Ãµes adjetivas', NULL),
(398, 'Escrita e compartilhamento de resenhas', NULL),
(399, 'O gÃªnero sinopse', NULL),
(400, 'Leitura de verbete enciclopÃ©dico. CompreensÃ£o do tipo textual expositivo. DenotaÃ§Ã£o e conotaÃ§Ã£o', NULL),
(401, 'Modalizadores discursivos. Tipos de modalizadores. AnÃ¡lise de modalizadores em diferentes textos', NULL),
(402, 'Leitura e anÃ¡lise de conto. Classes de palavras (revisÃ£o)', NULL),
(403, 'Leitura de e anÃ¡lise de artigo de opiniÃ£o. Conectores sequenciais e referenciais', NULL),
caracterÃ­sticas', NULL),
(405, 'Leitura e interpretaÃ§Ã£o', NULL),
(406, 'Linguagem verbal, nÃ£o verbal e mista', NULL),
(407, 'Leitura e anÃ¡lise de resultados de pesquisa', NULL),
(408, 'Curadoria de textos de cientÃ­ficos', NULL),
(409, 'Artigo cientÃ­fico como fonte de pesquisa', NULL),
(410, 'Textos cientÃ­ficos e sua funÃ§Ã£o social', NULL),
(411, 'GÃªnero anÃºncio publicitÃ¡rio', NULL),
(412, 'Elementos de persuasÃ£o', NULL),
(413, 'Modo imperativo do verbo', NULL),
(414, 'GÃªnero anÃºncio publicitÃ¡rio e slogan', NULL),
(415, 'Tipo textual injuntivo', NULL),
(416, 'FunÃ§Ã£o apelativa ou conativa da linguagem', NULL),
(417, 'Linguagem verbal e nÃ£o verbal', NULL),
(418, 'GÃªnero conto. Foco narrativo', NULL),
(419, 'GÃªnero literÃ¡rio conto. Elementos da narrativa', NULL),
(420, 'Leitura e anÃ¡lise de contos. ReconstruÃ§Ã£o das condiÃ§Ãµes de produÃ§Ã£o, circulaÃ§Ã£o e recepÃ§Ã£o de textos artÃ­stico-literÃ¡rios no Brasil. JosÃ© de Alencar e sua relevÃ¢ncia na literatura brasileira. Literatura indianista', NULL),
(421, 'Literatura comparada. AnÃ¡lise de texto indianista do sÃ©culo XIX e literatura indÃ­gena contemporÃ¢nea', NULL),
(422, 'Planejamento de texto de divulgaÃ§Ã£o cientÃ­fica', NULL),
(423, 'Banner de divulgaÃ§Ã£o cientÃ­fica', NULL),
exposiÃ§Ã£o e discussÃ£o', NULL),
(425, 'AutoavaliaÃ§Ã£o de apresentaÃ§Ã£o', NULL),
(426, 'Tese, argumentos, refutaÃ§Ã£o', NULL),
(427, 'PrÃ©-Modernismo. Euclides da Cunha. Lima Barreto. Augusto dos Anjos', NULL),
(428, 'A poÃ©tica de Oswald de Andrade. Revistas modernistas brasileiras. Ortografia', NULL),
(429, 'Leitura de poemas. ComparaÃ§Ã£o de literaturas (portuguesa, africana, brasileira, indÃ­gena, latino-americana etc.). Contexto de produÃ§Ã£o de texto literÃ¡rio', NULL),
(430, 'Leitura do conto "Pai contra mÃ£e", de Machado de Assis. CompreensÃ£o do conto. AnÃ¡lise do contexto de produÃ§Ã£o', NULL),
personificaÃ§Ã£o', NULL),
(432, 'Leitura de conto de GuimarÃ£es Rosa. CompreensÃ£o do conto. AnÃ¡lise de efeitos de sentido de trechos especÃ­ficos', NULL),
(433, 'Efeitos de sentido do conto. AnÃ¡lise de contexto de produÃ§Ã£o. VariaÃ§Ã£o linguÃ­stica', NULL),
(434, 'Leitura de conto. CompreensÃ£o do conto. AnÃ¡lise de efeitos de sentido de trechos especÃ­ficos', NULL),
(435, 'Leitura e compreensÃ£o do conto. AnÃ¡lise dos efeitos de sentido do conto. AnÃ¡lise de contexto de produÃ§Ã£o', NULL),
(436, 'Conceito de manifesto e antropofagia. Manifesto antropÃ³fago', NULL),
(437, 'Semana de Arte Moderna. PoÃ©tica de Manuel Bandeira', NULL),
(438, 'Primeira geraÃ§Ã£o modernista. PoÃ©tica de MÃ¡rio de Andrade', NULL),
(439, 'Primeira geraÃ§Ã£o modernista. PoÃ©tica de Oswald de Andrade', NULL),
(440, 'Segunda geraÃ§Ã£o modernista e poesia dos anos 1930. PoÃ©tica de Carlos Drummond de Andrade', NULL),
(441, 'Segunda geraÃ§Ã£o modernista e poesia dos anos 1930. PoÃ©tica de Murilo Mendes', NULL),
prosa regionalista. Prosa de Rachel de Queiroz', NULL),
prosa regionalista. Prosa de Graciliano Ramos', NULL),
prosa regionalista. Prosa de Jorge Amado', NULL),
(445, 'Leitura e anÃ¡lise de crÃ´nica', NULL),
caracterÃ­sticas', NULL),
(447, 'Leitura e compreensÃ£o de artigo de opiniÃ£o', NULL),
(448, 'ComparaÃ§Ã£o de dados e informaÃ§Ãµes em textos de divulgaÃ§Ã£o cientÃ­fica opinativos', NULL),
(449, 'IdentificaÃ§Ã£o de posicionamento crÃ­tico', NULL),
(450, 'AveriguaÃ§Ã£o de fidedignidade de informaÃ§Ãµes', NULL),
(451, 'Editorial. ReflexÃ£o crÃ­tica sobre funÃ§Ã£o social e intencionalidade de textos', NULL),
(452, 'Formas contemporÃ¢neas de publicidade. ReflexÃ£o crÃ­tica sobre funÃ§Ã£o social e intencionalidade de textos', NULL),
(453, 'Leitura de notÃ­cia. VisÃ£o de mundo no texto. IdentificaÃ§Ã£o e inferÃªncia de motivaÃ§Ãµes e/ou finalidades do texto/autor', NULL),
(454, 'Leitura de reportagem. Vozes no texto. IdentificaÃ§Ã£o e inferÃªncia de motivaÃ§Ãµes e/ou finalidades do texto/autor. RegÃªncia verbal e nominal', NULL),
(455, 'Leitura e anÃ¡lise de editorial', NULL),
(456, 'OraÃ§Ãµes subordinadas adjetivas; ModalizaÃ§Ã£o textual', NULL),
(457, 'ModalizaÃ§Ã£o textual; OraÃ§Ãµes subordinadas adverbiais', NULL),
(458, 'OraÃ§Ãµes coordenadas sindÃ©ticas aditivas, adversativas, alternativas, conclusivas, explicativas', NULL),
(459, 'Paralelismo sintÃ¡tico', NULL),
metonÃ­mia e sinestesia', NULL),
estrutura e caracterÃ­sticas. Sinais de pontuaÃ§Ã£o', NULL),
(462, 'Operadores lÃ³gico-discursivos', NULL),
(463, 'Ordem direta e inversÃµes', NULL),
(464, 'ConjunÃ§Ãµes e outros elementos coesivos', NULL),
Iracema e Senhora, ambas de JosÃ© de Alencar', NULL),
Dom Casmurro, de Machado de Assis', NULL),
(467, 'SistematizaÃ§Ã£o de diferenÃ§as marcantes entre romances romÃ¢nticos e realistas, com base em trechos de livros', NULL),
(468, 'DefiniÃ§Ãµes e caracterÃ­sticas das vanguardas europeias', NULL),
(469, 'Leitura e anÃ¡lise de crÃ´nica. Intertextualidade. Polissemia', NULL),
(470, 'Leitura e compreensÃ£o do Estatuto da Pessoa Idosa (texto normativo)', NULL),
(471, 'Entrevista oral', NULL),
(472, 'Marcas de oralidade', NULL),
(473, 'VariaÃ§Ã£o linguÃ­stica', NULL),
(474, 'Marcas de oralidade em textos transcritos', NULL),
(475, 'Tipos de transcriÃ§Ã£o', NULL),
(476, 'DefiniÃ§Ã£o de esporte de invasÃ£o. HistÃ³ria do handebol. Regras do handebol. Movimentos/fundamentos. PosiÃ§Ãµes e sistemas tÃ¡ticos', NULL),
Queimada', NULL),
Resgate', NULL),
empunhadura, recepÃ§Ã£o, passe, finta, drible e arremesso', NULL),
(480, 'ExercÃ­cios em duplas, trios e grupos, se utilizando dos fundamentos do handebol', NULL),
(481, 'Jogo de handebol com equipes femininas e equipes masculinas', NULL),
(482, 'Jogo de handebol com equipes mistas', NULL),
(483, 'Esporte de marca. Atletismo. Provas do atletismo. Esportes e Jogos ParalÃ­mpicos. Atletismo paralÃ­mpico', NULL),
(484, 'Corrida de velocidade. Corrida de revezamento', NULL),
(485, 'Corrida com barreiras. Corrida com obstÃ¡culos', NULL),
(486, 'Salto vertical. Salto horizontal', NULL),
(487, 'Arremesso de peso. LanÃ§amento de disco', NULL),
(488, 'Caminhada de olhos vendados', NULL),
(489, 'com guia', NULL),
(490, 'Corrida de olhos vendados', NULL),
origem; elementos constitutivos; diferentes estilos e evoluÃ§Ã£o em diferentes Ã©pocas', NULL),
o movimento, a mÃºsica e a danÃ§a Hip-hop', NULL),
(493, 'Diferentes sensaÃ§Ãµes atravÃ©s da danÃ§a', NULL),
RAP', NULL),
(495, 'Movimentos do Break', NULL),
(496, 'CriaÃ§Ã£o de coreografias de hip-hop em grupos', NULL),
(497, 'Ensaio das coreografias criadas', NULL),
(498, 'ApresentaÃ§Ã£o das coreografias criadas', NULL),
(499, 'DefiniÃ§Ã£o de GinÃ¡stica de Condicionamento FÃ­sico:', NULL),
(500, 'Conceito de Capacidades FÃ­sicas', NULL),
(501, 'Conceito de exercÃ­cios aerÃ³bios e exercÃ­cios anaerÃ³bios', NULL),
(502, 'BenefÃ­cios da GCF e prÃ¡tica de alongamento (flexibilidade)', NULL),
(503, 'Circuito de capacidades fÃ­sicas (flexibilidade, velocidade, agilidade, resistÃªncia e forÃ§a)', NULL),
(504, 'Estafetas de capacidades fÃ­sicas (velocidade e agilidade)', NULL),
(505, 'ExercÃ­cios aerÃ³bios (caminhar, correr e pedalar)', NULL),
(506, 'ExercÃ­cios anaerÃ³bios (membros superiores)', NULL),
(507, 'ExercÃ­cios anaerÃ³bios (membros inferiores)', NULL),
(508, 'Lutas do Brasil', NULL),
(509, 'Conceitos', NULL),
(510, 'Capoeira Regional Ã Capoeira Angola', NULL),
(511, 'Golpes da capoeira', NULL),
(512, 'A mÃºsica, os instrumentos e o ritmo da capoeira', NULL),
(513, 'A ginga como posiÃ§Ã£o base da capoeira', NULL),
Meia-lua de frente;Queixada; Armada', NULL),
Martelo, BÃªnÃ§Ã£o, AÃº, Cocorinha etc', NULL),
(516, 'Atividades lÃºdicas se utilizando de movimentos da capoeira, em roda', NULL),
(517, 'Roda de capoeira com os golpes aprendidos', NULL),
(518, 'DefiniÃ§Ã£o de Esporte de precisÃ£o', NULL),
(519, 'O boliche como esporte de precisÃ£o', NULL),
(520, 'A bocha como esporte de precisÃ£o', NULL),
(521, 'A bocha paralÃ­mpica', NULL),
(522, 'PrÃ¡ticas alternativas de precisÃ£o', NULL),
(523, 'ConfecÃ§Ã£o de materiais para jogar boliche e bocha nas aulas de EducaÃ§Ã£o FÃ­sica', NULL),
(524, 'Jogo de boliche com os materiais confeccionados', NULL),
(525, 'Jogo de bocha com os materiais confeccionados', NULL),
(526, 'Jogo de bocha no contexto paralÃ­mpico', NULL),
(527, 'OpÃ§Ã£o de brincadeiras e jogos prÃ©-desportivos com materiais reciclÃ¡veis/ adaptados/ alternativos', NULL),
Street Dance', NULL),
Breaking, Locking, Popping e Freestyle', NULL),
(530, 'Passos bÃ¡sicos do breaking', NULL),
(531, 'Passos bÃ¡sicos do locking', NULL),
(532, 'Passos bÃ¡sicos do popping', NULL),
(533, 'Passos bÃ¡sicos do freestyle', NULL),
(534, 'CriaÃ§Ã£o e ensaio de coreografias de street dance, em grupos', NULL),
(535, 'GinÃ¡stica de condicionamento fÃ­sico', NULL),
(536, 'Capacidades fÃ­sicas em aÃ§Ã£o', NULL),
(537, 'BenefÃ­cios do exercÃ­cio regular', NULL),
(538, 'CriaÃ§Ã£o de exercÃ­cios em grupos, se utilizando da ginÃ¡stica de condicionamento fÃ­sico', NULL),
(539, 'Desafios que se utilizam de diferentes capacidades fÃ­sicas', NULL),
(540, 'ExploraÃ§Ã£o das capacidades fÃ­sicas por meio de exercÃ­cios em formato de circuito', NULL),
melhora da forÃ§a, resistÃªncia, postura e saÃºde cardiovascular./BenefÃ­cios mentais: bem', NULL),
cooperaÃ§Ã£o, respeito Ã s regras, convivÃªncia e trabalho em equipe', NULL),
(543, 'CriaÃ§Ã£o, em grupos, de programas de exercÃ­cios fÃ­sicos', NULL),
(544, 'ApresentaÃ§Ã£o, em grupos, dos programas de exercÃ­cios fÃ­sicos criados', NULL),
(545, 'DefiniÃ§Ã£o de esporte de rede/ parede', NULL),
(546, 'HistÃ³ria e caracterÃ­sticas do voleibol', NULL),
(547, 'Fundamentos e regras do voleibol', NULL),
(548, 'Posicionamento e RodÃ­zio', NULL),
(549, 'Esporte ParalÃ­mpico; vÃ´lei sentado', NULL),
VolenÃ§ol', NULL),
Rede Humana', NULL),
CÃ¢mbio', NULL),
saque por baixo, toque, machete etc', NULL),
(554, 'ExercÃ­cios em duplas, trios e grupos, se utilizando dos fundamentos do voleibol', NULL),
(555, 'Jogo de voleibol com 4 equipes praticando ao mesmo tempo (meia quadra)', NULL),
(556, 'Jogo de voleibol com rodÃ­zio 6x0', NULL),
(557, 'PrÃ¡tica e jogo de voleibol com regras, fundamentos e rodÃ­zio 6x0', NULL),
VÃ´lei sentado', NULL),
(559, 'DefiniÃ§Ã£o de esporte de campo e taco', NULL),
(560, 'Jogo de taco', NULL),
(561, 'Jogo base 4', NULL),
(562, 'Beisebol', NULL),
Taco', NULL),
Base 4', NULL),
(565, 'Jogo de Beisebol adaptado para o ambiente escolar', NULL),
(566, 'Conceito de lutas do mundo', NULL),
(567, 'Origem do JudÃ´, Jiu-Jitsu e do CaratÃª', NULL),
(568, 'CaracterÃ­sticas especÃ­ficas do JudÃ´, Jiu-Jitsu e CaratÃª', NULL),
(569, 'SaudaÃ§Ãµes e Ukemis do JudÃ´', NULL),
(570, 'TÃ©cnicas de perna, braÃ§o e quadril no JudÃ´', NULL),
(571, 'VivÃªncias do JudÃ´', NULL),
(572, 'simulaÃ§Ã£o de luta', NULL),
(573, 'Jogos de oposiÃ§Ã£o no Jiu-Jitsu', NULL),
(574, 'TÃ©cnicas do Jiu-Jitsu', NULL),
(575, 'SaudaÃ§Ãµes e bases no caratÃª', NULL),
(576, 'Chutes no caratÃª', NULL),
(577, 'Socos e defesas no caratÃª', NULL),
(578, 'Katas no caratÃª', NULL),
(579, 'Materiais Digitais -Origem e evoluÃ§Ã£o do JudÃ´ para cegos', NULL),
(580, 'MudanÃ§as e adequaÃ§Ãµes Ã s regras base do judÃ´ para sua versÃ£o paralÃ­mpica', NULL),
(581, 'Ukemis e movimentaÃ§Ãµes', NULL),
(582, 'TÃ©cnicas de perna, braÃ§o e quadril no JudÃ´ para cegos', NULL),
(583, 'VivÃªncias do JudÃ´ para cegos', NULL),
(584, 'Retomada da definiÃ§Ã£o de esporte de invasÃ£o', NULL),
(585, 'HistÃ³ria do futsal', NULL),
(586, 'Regras e fundamentos do futsal', NULL),
Futebol de cegos', NULL),
(588, 'Fundamentos do futsal atravÃ©s de estafetas; domÃ­nio, conduÃ§Ã£o, drible, passe de chapa, chute ao gol etc', NULL),
(589, 'ExercÃ­cios em duplas, trios e grupos, se utilizando dos fundamentos do futsal', NULL),
Futsal de duplas', NULL),
(591, 'Jogo de Futsal com regras e fundamentos', NULL),
(592, 'equipes mistas', NULL),
(593, 'Jogo de futsal com regras e fundamentos', NULL),
(594, 'equipes femininas e equipes masculinas', NULL),
(595, 'HistÃ³ria do basquetebol', NULL),
(596, 'Regras e fundamentos do basquetebol', NULL),
basquete em cadeira de rodas', NULL),
(598, 'Fundamentos do basquete atravÃ©s de estafetas; drible, passe, arremesso, rebote, defesa, bloqueio etc', NULL),
(599, 'ExercÃ­cios em duplas, trios e grupos, se utilizando dos fundamentos do basquete', NULL),
Torrebol', NULL),
(601, 'Jogo de Basquete com regras e fundamentos', NULL),
Basquete em cadeira de rodas', NULL),
(603, 'Lutas de percussÃ£o', NULL),
(604, 'Boxe', NULL),
(605, 'Muay Thai', NULL),
(606, 'Posturas. MovimentaÃ§Ãµes. Esquivas do Boxe', NULL),
(607, 'Golpes', NULL),
(608, 'jab, direto, cruzado, gancho. A Sombra', NULL),
(609, 'Postura. MovimentaÃ§Ãµes. Esquivas e Bloqueios do Muay Thai', NULL),
(610, 'Golpes de membros superiores', NULL),
(611, 'Golpes de membros inferiores', NULL),
(612, 'Origem e evoluÃ§Ã£o do MMA', NULL),
(613, 'Origem e evoluÃ§Ã£o da esgrima', NULL),
(614, 'MudanÃ§as e adequaÃ§Ãµes Ã s regras e dinÃ¢micas da esgrima em sua versÃ£o paralÃ­mpica', NULL),
(615, 'Jogos de oposiÃ§Ã£o no MMA', NULL),
(616, 'PrÃ¡ticas de golpes percussivos de membros superiores; AnÃ¡lise sobre as relaÃ§Ãµes com outras modalidades vivenciadas', NULL),
(617, 'PrÃ¡ticas de golpes percussivos de membros inferiores; AnÃ¡lise sobre as relaÃ§Ãµes com outras modalidades vivenciadas', NULL),
(618, 'ConfecÃ§Ã£o de materiais para vivenciar a esgrima e a esgrima em cadeira de rodas nas aulas de EducaÃ§Ã£o FÃ­sica', NULL),
(619, 'VivÃªncia da Esgrima', NULL),
(620, 'AdaptaÃ§Ã£o da Esgrima em cadeira de rodas', NULL),
(621, 'Disputa de esgrima e disputa de esgrima em cadeira de rodas. AnÃ¡lise sobre a esgrima e a esgrima em cadeira de rodas. RelaÃ§Ãµes, diferenÃ§as e desafios', NULL),
(622, 'Diferentes possibilidades de se praticar o Futebol; Futebol como prÃ¡tica democrÃ¡tica; Futebol de campo; Futebol society; Futsal; FÃºtbol callejero', NULL),
(623, 'Futebol de campo adaptado para o espaÃ§o escolar', NULL),
(624, 'PrÃ¡tica do futebol de campo adaptado', NULL),
(625, 'Futebol society de maneira adaptada para o espaÃ§o escolar', NULL),
(626, 'PrÃ¡tica do futebol society', NULL),
(627, 'Jogos prÃ©-desportivos do futsal', NULL),
fundamentos do futsal', NULL),
(629, 'PrÃ¡tica do Futsal', NULL),
(630, 'Regras, objetivos e vivÃªncias do fÃºtbol callejero', NULL),
(631, 'PrÃ¡tica do fÃºtbol callejero', NULL),
(632, 'VivÃªncia de um futebol elencado pela turma', NULL),
(633, 'Retomada sobre a histÃ³ria e a importÃ¢ncia dos esportes e jogos paralÃ­mpicos; Modalidades paralÃ­mpicas', NULL),
(634, 'ApresentaÃ§Ã£o do goalball; Papel social, cultural e esportivo do goalball na inclusÃ£o', NULL),
(635, 'Goalball de maneira adaptada para o espaÃ§o escolar', NULL),
(636, 'PrÃ¡tica do goalball', NULL),
(637, 'Surgimento e diferenÃ§as entre o Rugby e o Futebol americano; Fundamentos e regras do Rugby e do Futebol Americano', NULL),
(638, 'Regras e possÃ­veis adaptaÃ§Ãµes do Rugby', NULL),
(639, '"ExercÃ­cios para atender o desenvolvimento tÃ©cnico', NULL),
(640, 'ExercÃ­cios de condicionamento fÃ­sico', NULL),
(641, 'PrÃ¡tica do Rugby', NULL),
(642, 'Regras e possÃ­veis adaptaÃ§Ãµes do Futebol americano', NULL),
(643, 'ExercÃ­cios de preparaÃ§Ã£o fÃ­sica e treinamento tÃ©cnico', NULL),
(644, 'PrÃ¡tica do Futebol americano', NULL),
(645, 'DefiniÃ§Ã£o de samba de roda; Significado histÃ³rico e cultural do carnaval; HistÃ³ria do Ballet clÃ¡ssico; Origem da danÃ§a contemporÃ¢nea', NULL),
(646, 'Musicalidade, ritmo e expressÃ£o corporal', NULL),
ginga, miudinho e tranÃ§a', NULL),
(648, 'SimulaÃ§Ã£o de um desfile de escola de samba', NULL),
(649, 'PosiÃ§Ãµes e movimentos bÃ¡sicos do Ballet', NULL),
(650, 'ExploraÃ§Ã£o livre de movimentos e improvisaÃ§Ã£o guiada', NULL),
(651, 'CriaÃ§Ã£o coletiva para danÃ§a contemporÃ¢nea', NULL),
(652, 'ApresentaÃ§Ã£o dos esportes de rede/quadra dividida; DiferenÃ§a entre o TÃªnis de mesa e o TÃªnis de campo; Fundamentos e regras do TÃªnis de mesa e do TÃªnis de campo', NULL),
(653, 'Fundamentos; postura, saque, recepÃ§Ã£o, golpes bÃ¡sicos e tipos de empunhadura', NULL),
(654, 'Regras; Arbitragem', NULL),
(655, 'PrÃ¡tica do TÃªnis de Mesa; DiferenÃ§as com o Ping-Pong', NULL),
(656, 'Jogo de tÃªnis de maneira adaptada para o espaÃ§o escolar', NULL),
(657, 'HistÃ³ria e origem da DanÃ§a Circular, do Dabke e do Fandango; A chegada dessas danÃ§as ao Brasil; Significado, funÃ§Ã£o cultural e contexto social dessas danÃ§as do mundo', NULL),
(658, 'Ritmo e musicalidade; Diversidade cultural', NULL),
(659, 'FormaÃ§Ã£o do cÃ­rculo e passos bÃ¡sicos', NULL),
(660, 'Ritmo e musicalidade; RelevÃ¢ncia cultural', NULL),
(661, 'FormaÃ§Ã£o e passos na roda', NULL),
(662, 'Olhar cultural', NULL),
(663, 'FormaÃ§Ã£o, passo de base, passo cruzado e giro', NULL),
(664, 'Esporte de rede/quadra dividida; Esporte de invasÃ£o/ territorial; Punhobol; Kin-Ball; Tchoukball; Ultimate Frisbee', NULL),
(665, 'Regras e possÃ­veis adaptaÃ§Ãµes do Punhobol e/ou do Kimball', NULL),
(666, 'PrÃ¡tica do Punhobol e/ou do Kimball', NULL),
(667, 'Regras e possÃ­veis adaptaÃ§Ãµes do Tchoukball', NULL),
(668, 'PrÃ¡tica do Tchoukball', NULL),
(669, 'Regras e possÃ­veis adaptaÃ§Ãµes do Ultimate Frisbee', NULL),
(670, 'PrÃ¡tica do Ultimate Frisbee', NULL),
(671, 'Materiais Digitais -Esportes praticados em quadra de areia/ praia; Origem e caracterÃ­sticas do VÃ´lei de praia, do FutevÃ´lei, do Beach tennis e do Frescobol', NULL),
(672, 'Regras, possÃ­veis adaptaÃ§Ãµes e prÃ¡tica do VÃ´lei de praia', NULL),
(673, 'Regras e possÃ­veis adaptaÃ§Ãµes do FutevÃ´lei', NULL),
(674, 'PrÃ¡tica de FutevÃ´lei', NULL),
(675, 'Regras, possÃ­veis adaptaÃ§Ãµes e prÃ¡tica do Beach tennis', NULL),
(676, 'Regras e possÃ­veis adaptaÃ§Ãµes do Frescobol', NULL),
(677, 'PrÃ¡tica de Frescobol', NULL),
(678, 'Continentes. Oceanos. Paisagens pelo mundo', NULL),
(679, 'O conceito de paisagem.', NULL),
(680, 'Tipos de paisagem.', NULL),
(681, 'Planos da paisagem', NULL),
(682, 'Paisagens transformadas pela aÃ§Ã£o da natureza.', NULL),
(683, 'Paisagens transformadas por diferentes grupos sociais', NULL),
(684, 'O conceito de lugar', NULL),
(685, 'Lugares do cotidiano', NULL),
(686, 'RelaÃ§Ã£o entre os lugares', NULL),
(687, 'O conceito de espaÃ§o geogrÃ¡fico.', NULL),
(688, 'ProduÃ§Ã£o do espaÃ§o geogrÃ¡fico.', NULL),
(689, 'Trabalho, tÃ©cnica e as transformaÃ§Ãµes no espaÃ§o geogrÃ¡fico.', NULL),
(690, 'Mapas mentais. Lugares de vivÃªncia. TransformaÃ§Ãµes no espaÃ§o geogrÃ¡fico', NULL),
(691, 'Atividades econÃ´micas.', NULL),
(692, 'Setores da economia.', NULL),
(693, 'Extrativismos minerais, animal e vegetal', NULL),
(694, 'Principais produtos extrativistas.', NULL),
(695, 'DistribuiÃ§Ã£o no espaÃ§o geogrÃ¡fico.', NULL),
(696, 'Impactos ambientais', NULL),
(697, 'Tipos de agricultura.', NULL),
(698, 'Principais cultivos.', NULL),
(699, 'Sistemas de ProduÃ§Ã£o pecuÃ¡ria.', NULL),
(700, 'Principais criaÃ§Ãµes da pecuÃ¡ria', NULL),
(701, 'Principais produtos agropecuÃ¡rios.', NULL),
(702, 'DistribuiÃ§Ã£o agropecuÃ¡ria no espaÃ§o geogrÃ¡fico.', NULL),
(703, 'Processo de industrializaÃ§Ã£o. As fases da industrializaÃ§Ã£o.', NULL),
(704, 'DistribuiÃ§Ã£o industrial no espaÃ§o geogrÃ¡fico', NULL),
(705, 'IndÃºstrias de base, de bens intermediÃ¡rios e de bens de consumo', NULL),
(706, 'ComÃ©rcios locais, eletrÃ´nico e internacional', NULL),
(707, 'ServiÃ§os de saÃºde, de educaÃ§Ã£o, financeiros, de turismo, de transporte e de comunicaÃ§Ã£o', NULL),
(708, 'InterdependÃªncia das atividades econÃ´micas. Setores produtivos.', NULL),
(709, 'EstÃ¡gios de produÃ§Ã£o das mercadorias. As paisagens urbanas. O processo de urbanizaÃ§Ã£o', NULL),
(710, 'Principais problemas urbanos', NULL),
(711, 'As paisagens rurais. As transformaÃ§Ãµes no campo', NULL),
(712, 'Principais problemas no campo', NULL),
(713, 'Principais movimentos do planeta Terra e suas consequÃªncias', NULL),
(714, 'RepresentaÃ§Ãµes do planeta Terra.', NULL),
(715, 'DefiniÃ§Ã£o de cartografia.', NULL),
(716, 'EvoluÃ§Ã£o das tÃ©cnicas cartogrÃ¡ficas', NULL),
(717, 'Elementos e convenÃ§Ãµes cartogrÃ¡ficas.', NULL),
(718, 'ProjeÃ§Ãµes planas, cÃ´nicas e cilÃ­ndricas', NULL),
(719, 'Formas de orientaÃ§Ã£o espacial.', NULL),
(720, 'OrientaÃ§Ã£o nos mapas', NULL),
(721, 'Instrumentos de orientaÃ§Ã£o espacial.', NULL),
(722, 'Paralelos, Meridianos, Zonas tÃ©rmicas', NULL),
(723, 'Fusos horÃ¡rios.', NULL),
(724, 'Latitude e longitude.', NULL),
(725, 'Escalas grÃ¡ficas, numÃ©ricas, grandes e pequenas', NULL),
(726, 'CÃ¡lculo de escala cartogrÃ¡fica', NULL),
(727, 'Croqui, Mapa, Carta, Planta', NULL),
(728, 'Mapa temÃ¡tico', NULL),
(729, 'Perfil topogrÃ¡fico', NULL),
(730, 'Litosfera, Atmosfera, Hidrosfera e Biosfera.', NULL),
(731, 'ComposiÃ§Ã£o e camadas da atmosfera.', NULL),
(732, 'Tempo e clima.', NULL),
(733, 'Frentes de ar.', NULL),
(734, 'PrevisÃ£o do tempo.', NULL),
(735, 'Latitude, Altitude, Maritimidade e Continentalidade.', NULL),
(736, 'PrecipitaÃ§Ã£o e Temperatura.', NULL),
(737, 'Climograma', NULL),
(738, 'LocalizaÃ§Ã£o e limites do territÃ³rio brasileiro.', NULL),
(739, 'Conceito de regiÃ£o e de regionalizaÃ§Ã£o.', NULL),
(740, 'DivisÃ£o regional do IBGE.', NULL),
(741, 'CaracterÃ­sticas da regiÃ£o Norte, da regiÃ£o Nordeste, da regiÃ£o Centro-Oeste, da regiÃ£o Sul e da regiÃ£o Sudeste.', NULL),
(742, 'Complexos regionais ou regiÃµes geoeconÃ´micas.', NULL),
(743, 'Complexo regional AmazÃ´nia.', NULL),
(744, 'Complexo regional Centro-Sul.', NULL),
(745, 'Complexo regional do Nordeste.', NULL),
(746, 'RegiÃµes do Brasil', NULL),
(747, 'Conceito de territÃ³rio e sua dimensÃ£o polÃ­tica.', NULL),
(748, 'Ciclos econÃ´micos.', NULL),
(749, 'ConstruÃ§Ã£o do territÃ³rio brasileiro.', NULL),
(750, 'CaracterÃ­sticas do territÃ³rio brasileiro.', NULL),
(751, 'TensÃµes ligadas ao uso e posse do territÃ³rio.', NULL),
(752, 'TransformaÃ§Ãµes territoriais em SÃ£o Paulo.', NULL),
(753, 'EstereÃ³tipos e representaÃ§Ãµes territoriais nos meios de comunicaÃ§Ã£o', NULL),
(754, 'Diversidade Ã©tnico-racial e cultural da populaÃ§Ã£o brasileira.', NULL),
(755, 'Fluxos migratÃ³rios histÃ³ricos e contemporÃ¢neos.', NULL),
(756, 'Fatores de atraÃ§Ã£o e repulsÃ£o populacional, com foco nos complexos regionais.', NULL),
(757, 'Taxas de natalidade e mortalidade no Brasil.', NULL),
(758, 'Densidade demogrÃ¡fica e migraÃ§Ãµes internas.', NULL),
(759, 'Censo demogrÃ¡fico e dados populacionais.', NULL),
(760, 'PirÃ¢mide etÃ¡ria e estrutura da populaÃ§Ã£o brasileira.', NULL),
(761, 'PopulaÃ§Ã£o economicamente ativa e setores da economia.', NULL),
(762, 'FormaÃ§Ã£o da diversidade Ã©tnico-racial no Brasil.', NULL),
(763, 'AnÃ¡lise de dados demogrÃ¡ficos por etnia no Brasil', NULL),
(764, 'Transporte e comunicaÃ§Ã£o na integraÃ§Ã£o do territÃ³rio brasileiro', NULL),
(765, 'O espaÃ§o das redes no Brasil', NULL),
(766, 'Redes de transporte no Brasil', NULL),
(767, 'EvoluÃ§Ã£o dos transportes e de comunicaÃ§Ã£o no Brasil', NULL),
(768, 'IndustrializaÃ§Ã£o brasileira, concentraÃ§Ã£o e desconcentraÃ§Ã£o industrial no Brasil', NULL),
(769, 'Parques cientÃ­ficos e tecnolÃ³gicos no Brasil', NULL),
(770, 'ConexÃ£o entre lugares, Redes de transporte e comunicaÃ§Ã£o e DistribuiÃ§Ã£o das atividades econÃ´micas', NULL),
(771, 'Redes de transporte e comunicaÃ§Ã£o', NULL),
(772, 'DesconcentraÃ§Ã£o industrial', NULL),
(773, 'Do mundo bipolar ao mundo multipolar', NULL),
(774, 'A ascensÃ£o dos Estados Unidos', NULL),
(775, 'O poderio militar e econÃ´mico dos Estados Unidos', NULL),
(776, 'O poder polÃ­tico dos Estados Unidos', NULL),
(777, 'EstratÃ©gias diplomÃ¡ticas e econÃ´micas', NULL),
(778, 'Desafios e oportunidades para os paÃ­ses latino', NULL),
(779, 'americanos no contexto da Nova Ordem Mundial', NULL),
(780, 'Brasil e Nova Ordem Mundial', NULL),
1, 2, 3, 4', NULL),
(782, 'Conceitos da GeopolÃ­tica', NULL),
(783, 'RelaÃ§Ãµes internacionais', NULL),
(784, 'Principais organizaÃ§Ãµes mundiais', NULL),
(785, 'PaÃ­ses-membros da ONU', NULL),
(786, 'FunÃ§Ãµes, objetivos e estrutura da ONU', NULL),
(787, 'RegionalizaÃ§Ã£o e aspectos fÃ­sicos da Ãfrica', NULL),
(788, 'Conflitos civis no continente africano', NULL),
(789, 'Crise humanitÃ¡ria na Ãfrica', NULL),
(790, 'Conflitos africanos', NULL),
(791, 'RegionalizaÃ§Ã£o e aspectos fÃ­sicos da AmÃ©rica', NULL),
(792, 'Estados Unidos e MÃ©xico', NULL),
(793, 'TensÃµes e conflitos entre Chile e BolÃ­via', NULL),
(794, 'TensÃµes e conflitos entre Argentina e Chile', NULL),
(795, 'TensÃµes e conflitos entre Venezuela e Guiana', NULL),
(796, 'GATT e OMC. Indicadores econÃ´micos dos Estados Unidos, da China e dos BRICS.', NULL),
(797, 'Principais produtos e serviÃ§os comercializados por Estados Unidos e China, e entre Estados Unidos e BRICS.', NULL),
(798, 'PaÃ­ses membros e parceiros dos BRICS. CaracterÃ­sticas gerais dos BRICS.', NULL),
(799, 'Economia global e emergente.', NULL),
(800, 'Brasil, RÃºssia, Ãndia, China e Ãfrica do Sul.', NULL),
(801, 'USMCA, CAN, ALADI e MERCOSUL', NULL),
(802, 'Setores da economia', NULL),
(803, 'DescentralizaÃ§Ã£o e RecentralizaÃ§Ã£o econÃ´mica', NULL),
(804, 'Investimentos dos Estados Unidos no mundo', NULL),
(805, 'InfluÃªncia do capital estadunidense no Brasil', NULL),
(806, 'Tecnologias e os setores da economia', NULL),
(807, 'ProfissÃµes do futuro', NULL),
(808, 'Oportunidades e desafios', NULL),
(809, 'Grandes NavegaÃ§Ãµes e expansÃ£o marÃ­tima', NULL),
(810, 'InÃ­cio da globalizaÃ§Ã£o e hegemonia europeia no controle territorial', NULL),
(811, 'EvoluÃ§Ã£o dos mapas e representaÃ§Ãµes do espaÃ§o', NULL),
(812, 'VisÃµes eurocÃªntricas, divisÃ£o simbÃ³lica do mundo e cartografia como instrumento de poder', NULL),
(813, 'OrganizaÃ§Ã£o do sistema colonial e pacto colonial', NULL),
(814, 'ConsequÃªncias atuais da colonizaÃ§Ã£o nas fronteiras, culturas e relaÃ§Ãµes de poder', NULL),
(815, 'ParticipaÃ§Ã£o de paÃ­ses e colÃ´nias na 1Âª e 2Âª Guerras Mundiais.', NULL),
(816, 'MudanÃ§as de fronteiras e divisÃµes territoriais apÃ³s os conflitos.', NULL),
(817, 'ConsequÃªncias sociais, polÃ­ticas e culturais para colonizadores e colonizados.', NULL),
(818, 'CaracterÃ­sticas gerais da Guerra Fria e disputas geopolÃ­ticas em diferentes Ã¡reas.', NULL),
(819, 'Corrida espacial e tecnolÃ³gica e o Muro de Berlim como sÃ­mbolos da divisÃ£o global.', NULL),
(820, 'Disputas ideolÃ³gicas e tecnolÃ³gicas durante a Guerra Fria.', NULL),
(821, 'DivisÃ£o do mundo em blocos e consequÃªncias nas relaÃ§Ãµes globais e nas desigualdades sociopolÃ­ticas.', NULL),
(822, 'Conceito de globalizaÃ§Ã£o e suas relaÃ§Ãµes com a Geografia.', NULL),
(823, 'CaracterÃ­sticas da primeira fase da globalizaÃ§Ã£o (sÃ©culos XV a XVII).', NULL),
(824, 'Segunda fase da globalizaÃ§Ã£o e a RevoluÃ§Ã£o Industrial.', NULL),
(825, 'Ãxodo rural, urbanizaÃ§Ã£o e mudanÃ§as nos modos de vida, consumo e trabalho.', NULL),
marcos e avanÃ§os tecnolÃ³gicos.', NULL),
(827, 'ExpansÃ£o das comunicaÃ§Ãµes e novas formas de consumo, trabalho e informaÃ§Ã£o.', NULL),
(828, 'Quarta fase da globalizaÃ§Ã£o e tecnologias emergentes.', NULL),
(829, 'Desigualdades, tensÃµes e novas dinÃ¢micas no mundo atual.', NULL),
(830, 'Tipos de moeda, evoluÃ§Ã£o e circulaÃ§Ã£o no sistema econÃ´mico global.', NULL),
(831, 'Moedas sociais, criptomoedas e alternativas locais ao sistema monetÃ¡rio tradicional.', NULL),
(832, 'LocalizaÃ§Ã£o e limites do Oriente MÃ©dio.', NULL),
(833, 'Climas, relevos e recursos naturais predominantes.', NULL),
(834, 'Diversidade cultural e religiosa no Oriente MÃ©dio.', NULL),
(835, 'Principais dinÃ¢micas populacionais da regiÃ£o.', NULL),
(836, 'Conflitos, tensÃµes e disputas na regiÃ£o.', NULL),
(837, 'Principais influÃªncias nos conflitos contemporÃ¢neos do Oriente MÃ©dio.', NULL),
causas, processo e desdobramentos.', NULL),
mudanÃ§as territoriais e conflitos contemporÃ¢neos.', NULL),
(840, 'A influÃªncia polÃ­tica e econÃ´mica da RÃºssia na EurÃ¡sia.', NULL),
causas e consequÃªncias.', NULL),
(842, 'Desenvolvimento econÃ´mico, industrial e tecnolÃ³gico da China nas Ãºltimas dÃ©cadas.', NULL),
(843, 'RelaÃ§Ã£o com Taiwan e impactos polÃ­ticos regionais e globais da China.', NULL),
(844, 'O conflito entre as Coreias e seus desdobramentos.', NULL),
(845, 'RelaÃ§Ãµes polÃ­ticas dos paÃ­ses vizinhos (JapÃ£o e China) com o conflito coreano.', NULL),
(846, 'Processo polÃ­tico, econÃ´mico e populacional da Ãndia atual.', NULL),
(847, 'A questÃ£o da Caxemira e suas implicaÃ§Ãµes territoriais e polÃ­ticas', NULL),
(848, 'Economia global e seu impacto no cotidiano local.', NULL),
(849, 'InfluÃªncia das corporaÃ§Ãµes, instituiÃ§Ãµes internacionais, cultura e identidade na globalizaÃ§Ã£o.', NULL),
(850, 'Principais organizaÃ§Ãµes econÃ´micas e comerciais e sua atuaÃ§Ã£o no cenÃ¡rio mundial.', NULL),
(851, 'DefiniÃ§Ã£o, origem e princÃ­pios bÃ¡sicos dos direitos humanos.', NULL),
(852, 'Destaque para o contexto histÃ³rico do pÃ³s-segunda Guerra Mundial.', NULL),
desafios e exemplos.', NULL),
(854, 'Fundamentos no pÃ³s-guerra.', NULL),
(855, 'Tipos de deslocamentos humanos.', NULL),
(856, 'DiferenÃ§a entre migrantes e refugiados.', NULL),
(857, 'Principais causas dos deslocamentos contemporÃ¢neos.', NULL),
(858, 'Refugiados no Brasil. Causas, rotas e desafios da migraÃ§Ã£o forÃ§ada', NULL),
(859, 'DiferenÃ§as entre Climatologia e Meteorologia.', NULL),
(860, 'Conceitos de Tempo e Clima.', NULL),
(861, 'DivisÃ£o das camadas da atmosfera e suas principais caracterÃ­sticas.', NULL),
(862, 'CirculaÃ§Ã£o geral da atmosfera.', NULL),
(863, 'Elementos e controles climÃ¡ticos.', NULL),
temperatura e precipitaÃ§Ã£o.', NULL),
(865, 'Biomas associados a determinados padrÃµes de climogramas.', NULL),
(866, 'Climogramas de diferentes regiÃµes do mundo.', NULL),
(867, 'Principais regiÃµes geomorfolÃ³gicas do Brasil.', NULL),
(868, 'Relevo e ocupaÃ§Ã£o humana.', NULL),
(869, 'Processos que causam degradaÃ§Ã£o do relevo.', NULL),
(870, 'Principais riscos e desastres relacionados ao relevo.', NULL),
tÃ©cnicas de manejo e medidas estruturais para minimizar riscos.', NULL),
(872, 'PrevenÃ§Ã£o e mitigaÃ§Ã£o de impactos dos processos de desastres relacionados ao relevo.', NULL),
(873, 'Sistema Nacional de Unidades de ConservaÃ§Ã£o da natureza (SNUC).', NULL),
(874, 'Principais unidades de conservaÃ§Ã£o no Brasil.', NULL),
(875, 'IndÃºstria 4.0 e automaÃ§Ã£o', NULL),
(876, 'DistribuiÃ§Ã£o da Ã¡gua na Terra. Conceito de bacia hidrogrÃ¡fica', NULL),
(877, 'PolÃ­ticas pÃºblicas e prÃ¡ticas de gestÃ£o sustentÃ¡vel dos recursos hÃ­dricos', NULL),
(878, 'Processos endÃ³genos e exÃ³geno de formaÃ§Ã£o do relevo', NULL),
(879, 'DefiniÃ§Ã£o de Bioma. Principais Biomas da Terra', NULL),
(880, 'Biomas do estado de SÃ£o Paulo. DiferenÃ§as entre os biomas.', NULL),
(881, 'ImportÃ¢ncia da cartografia para a geografia. Elementos dos mapas. ProjeÃ§Ãµes cartogrÃ¡ficas', NULL),
(882, 'Cartografia temÃ¡tica. Mapas qualitativos e quantitativos', NULL),
(883, 'Cartografia tÃ¡til', NULL),
(884, 'CriaÃ§Ã£o de produtos cartogrÃ¡ficos', NULL),
(885, 'DefiniÃ§Ã£o de sensoriamento remoto. Origens do sensoriamento remoto', NULL),
(886, 'DefiniÃ§Ã£o de Sistema de InformaÃ§Ãµes GeogrÃ¡ficas (SIG). HistÃ³rico e evoluÃ§Ã£o do SIG', NULL),
(887, 'ProduÃ§Ã£o de mapas temÃ¡ticos', NULL),
(888, 'Conceito de globalizaÃ§Ã£o', NULL),
(889, 'Conceito de produÃ§Ã£o.', NULL),
(890, 'Cadeias produtivas', NULL),
(891, 'Regionalismos e blocos econÃ´micos', NULL),
(892, 'GlobalizaÃ§Ã£o cultural.', NULL),
(893, 'HomogeneizaÃ§Ã£o cultural.', NULL),
(894, 'Principais conceitos de demografia.', NULL),
(895, 'TransiÃ§Ã£o demogrÃ¡fica', NULL),
(896, 'Dados de demografia do Brasil.', NULL),
(897, 'DistribuiÃ§Ã£o e principais caracterÃ­sticas da populaÃ§Ã£o brasileira', NULL),
(898, 'Demografia da comunidade escolar', NULL),
(899, 'EvoluÃ§Ã£o da economia do Brasil com destaque para os sÃ©culos XVIII, XIX e XX', NULL),
(900, 'Principais dados da economia brasileira atual, com destaque para o PIB.', NULL),
(901, 'O papel da economia brasileira no cenÃ¡rio mundial', NULL),
(902, 'Indicadores socioeconÃ´micos do Brasil', NULL),
(903, 'Desigualdade socioeconÃ´mica e distribuiÃ§Ã£o de renda no Brasil', NULL),
(904, 'O mercado de trabalho no Brasil e as desigualdades sociais.', NULL),
(905, 'Principais direitos dos trabalhadores no Brasil. Reformas trabalhistas e flexibilizaÃ§Ãµes legais', NULL),
(906, 'Conceitos de Estado, naÃ§Ã£o e territÃ³rio', NULL),
(907, 'Conceito de Estado moderno. Processos histÃ³ricos de formaÃ§Ã£o das naÃ§Ãµes', NULL),
(908, 'Povos sem Estado. Conflitos e reivindicaÃ§Ãµes por autonomia ou reconhecimento', NULL),
(909, 'Conflitos territoriais atuais. O papel da ONU e dos organismos internacionais nesses conflitos', NULL),
(910, 'Territorialidade e identidade. DiÃ¡sporas e povos sem Estado. Desafios contemporÃ¢neos das cidades', NULL),
importÃ¢ncia cultural, social e geogrÃ¡fica', NULL),
(912, 'DemarcaÃ§Ãµes dos territÃ³rios indÃ­genas.', NULL),
(913, 'UrbanizaÃ§Ã£o no Brasil', NULL),
(914, 'Impactos socioambientais do processo de urbanizaÃ§Ã£o', NULL),
(915, 'O Processo de UrbanizaÃ§Ã£o Mundial', NULL),
(916, 'Problemas Urbanos e Desigualdades Socioespaciais', NULL),
(917, 'O espaÃ§o agrÃ¡rio brasileiro', NULL),
(918, 'Os contrastes dos modelos agrÃ­colas', NULL),
(919, 'Onu e o cenÃ¡rio agrÃ¡rio', NULL),
(920, 'O agronegÃ³cio e as novas fronteiras', NULL),
(921, 'Fatores biÃ³ticos e abiÃ³ticos', NULL),
(922, 'Cadeias alimentares e teias alimentares', NULL),
(923, 'Nicho ecolÃ³gico e comunidade biolÃ³gica', NULL),
(924, 'PirÃ¢mides ecolÃ³gicas', NULL),
(925, 'Fluxo de matÃ©ria e energia', NULL),
(926, 'SucessÃ£o ecolÃ³gica', NULL),
(927, 'Biomas terrestres brasileiros', NULL),
(928, 'FotossÃ­ntese', NULL),
(929, 'Metabolismo energÃ©tico', NULL),
(930, 'RespiraÃ§Ã£o celular', NULL),
(931, 'RelaÃ§Ãµes ecolÃ³gicas', NULL),
(932, 'DegradaÃ§Ã£o ambiental', NULL),
(933, 'Reflorestamento', NULL),
(934, 'EducaÃ§Ã£o ambiental', NULL),
(935, 'Agroecologia e sistemas agroflorestais', NULL),
(936, 'Descarte e tratamento de resÃ­duos', NULL),
(937, 'BiocombustÃ­veis e biomassa', NULL),
(938, 'ODS 7', NULL),
(939, 'Biosfera, populaÃ§Ã£o, comunidade, hÃ¡bitat e nicho ecolÃ³gico', NULL),
(940, 'Efeito estufa', NULL),
(941, 'ComposiÃ§Ã£o da atmosfera', NULL),
(942, 'Tempo e clima', NULL),
(943, 'Aquecimento global', NULL),
(944, 'MudanÃ§as climÃ¡ticas', NULL),
(945, 'Eventos climÃ¡ticos extremos', NULL),
(946, 'EducaÃ§Ã£o para ReduÃ§Ã£o de Riscos e Desastres', NULL),
(947, 'Impactos antrÃ³picos no ambiente', NULL),
(948, 'Vulnerabilidades relacionadas Ã s mudanÃ§as climÃ¡ticas', NULL),
(949, 'Matriz energÃ©tica', NULL),
(950, 'Fontes renovÃ¡veis', NULL),
(951, 'Fontes nÃ£o renovÃ¡veis', NULL),
(952, 'Impactos socioambientais da geraÃ§Ã£o de energia', NULL),
(953, 'Tipos de poluiÃ§Ã£o', NULL),
(954, 'PoluiÃ§Ã£o do ar e da Ã¡gua', NULL),
(955, 'Saneamento bÃ¡sico', NULL),
visÃ£o', NULL),
audiÃ§Ã£o', NULL),
(958, 'Sistema respiratÃ³rio', NULL),
(959, 'Sistema cardiovascular', NULL),
(960, 'AplicaÃ§Ã£o da radiaÃ§Ã£o no diagnÃ³stico e tratamento de enfermidades', NULL),
(961, 'Cuidados com a exposiÃ§Ã£o Ã  radiaÃ§Ã£o em exames', NULL),
(962, 'RadiaÃ§Ã£o ultravioleta', NULL),
(963, 'Efeitos da radiaÃ§Ã£o no DNA', NULL),
(964, 'Cuidados com a exposiÃ§Ã£o Ã  radiaÃ§Ã£o solar', NULL),
(965, 'Mitose', NULL),
(966, 'CÃ¢ncer', NULL),
(967, 'Meiose', NULL),
(968, 'GametogÃªnese humana', NULL),
(969, 'Desmatamento, queimadas e mudanÃ§as climÃ¡ticas', NULL),
(970, 'MineraÃ§Ã£o', NULL),
(971, 'Monocultura', NULL),
(972, 'Rios voadores', NULL),
(973, 'Crises hÃ­drica e elÃ©trica', NULL),
(974, 'Zoonoses', NULL),
(975, 'Quebra de barreira', NULL),
(976, 'Medidas profilÃ¡ticas', NULL),
(977, 'Ãreas de PreservaÃ§Ã£o Permanente', NULL),
(978, 'Bioma Cerrado', NULL),
(979, 'ServiÃ§os ecossistÃªmicos', NULL),
(980, 'Perda de hÃ¡bitat e fragmentaÃ§Ã£o', NULL),
(981, 'Corredores ecolÃ³gicos', NULL),
(982, 'CoexistÃªncia humano-fauna', NULL),
(983, 'Ãreas verdes urbanas', NULL),
(984, 'PreservaÃ§Ã£o e conservaÃ§Ã£o', NULL),
(985, 'CiÃªncia cidadÃ£', NULL),
(986, 'Unidades de ConservaÃ§Ã£o', NULL),
(987, 'AlteraÃ§Ãµes em teias e cadeias alimentares', NULL),
(988, 'RelaÃ§Ã£o ambiente e doenÃ§as', NULL),
capsÃ­deo e material genÃ©tico', NULL),
(990, 'BioacumulaÃ§Ã£o', NULL),
(991, 'BioconcentraÃ§Ã£o', NULL),
(992, 'BiomagnificaÃ§Ã£o', NULL),
(993, 'NÃ­veis trÃ³ficos', NULL),
(994, 'Bioindicadores', NULL),
(995, 'Defensivos agrÃ­colas', NULL),
(996, 'Descarte indevido de resÃ­duos', NULL),
(997, 'PolinizaÃ§Ã£o', NULL),
(998, 'Controle biolÃ³gico', NULL),
(999, 'Sistema reprodutor de plantas com flores', NULL),
(1000, 'Organismos Geneticamente Modificados', NULL),
(1001, 'TransgÃªnicos', NULL),
(1002, 'BiosseguranÃ§a', NULL),
(1003, 'Transgenes', NULL),
(1004, 'Melhoramento genÃ©tico', NULL),
(1005, 'BioÃ©tica', NULL),
(1006, 'Diversidade genÃ©tica', NULL),
(1007, 'Biodiversidade', NULL),
(1008, 'ManipulaÃ§Ã£o genÃ©tica', NULL),
(1009, 'Riscos da perda da biodiversidade', NULL),
(1010, 'Big Bang', NULL),
(1011, 'MÃ©todo cientÃ­fico', NULL),
(1012, 'Sistema Solar', NULL),
(1013, 'Corpos celestes', NULL),
(1014, 'Terra primitiva', NULL),
(1015, 'Tempo geolÃ³gico', NULL),
(1016, 'Camadas da Terra', NULL),
(1017, 'Atmosfera', NULL),
(1018, 'Tipos de Ã¡guas e distribuiÃ§Ã£o no planeta', NULL),
(1019, 'Estados e mudanÃ§as de estado da matÃ©ria', NULL),
(1020, 'PoluiÃ§Ã£o da Ã¡gua', NULL),
(1021, 'Biosfera', NULL),
(1022, 'Gravidade', NULL),
(1023, 'Esfericidade da Terra', NULL),
(1024, 'Movimento de rotaÃ§Ã£o', NULL),
(1025, 'Movimento de translaÃ§Ã£o', NULL),
(1026, 'Movimento aparente do Sol', NULL),
(1027, 'Pontos cardeais', NULL),
(1028, 'Movimentos da Lua', NULL),
(1029, 'Eclipse lunar', NULL),
(1030, 'Eclipse solar', NULL),
(1031, 'EstaÃ§Ãµes do ano', NULL),
(1032, 'Modelo Terra-Sol-Lua', NULL),
(1033, 'Crosta terrestre', NULL),
(1034, 'Rochas sedimentares', NULL),
(1035, 'Rochas metamÃ³rficas', NULL),
(1036, 'Rochas magmÃ¡ticas', NULL),
(1037, 'FormaÃ§Ã£o do solo', NULL),
(1038, 'FÃ³sseis', NULL),
(1039, 'AÃ§Ãµes antrÃ³picas no meio ambiente', NULL),
(1040, 'PreservaÃ§Ã£o do solo', NULL),
(1041, 'SubstÃ¢ncias puras, simples e compostas', NULL),
(1042, 'Misturas homogÃªneas e heterogÃªneas', NULL),
(1043, 'TransformaÃ§Ãµes quÃ­micas e fÃ­sicas', NULL),
(1044, 'SeparaÃ§Ã£o de misturas', NULL),
(1045, 'Estado de organizaÃ§Ã£o da matÃ©ria', NULL),
(1046, 'Placas tectÃ´nicas', NULL),
(1047, 'Deriva continental', NULL),
(1048, 'Eventos naturais', NULL),
(1049, 'Vulcanismo', NULL),
(1050, 'Terremotos e tsunamis', NULL),
(1051, 'Atmosfera da Terra', NULL),
(1052, 'Camada de ozÃ´nio', NULL),
(1053, 'PressÃ£o atmosfÃ©rica', NULL),
(1054, 'Altitude', NULL),
(1055, 'Qualidade do ar', NULL),
(1056, 'DoenÃ§as respiratÃ³rias', NULL),
(1057, 'ForÃ§a', NULL),
(1058, 'MÃ¡quinas simples', NULL),
(1059, 'Calor e temperatura', NULL),
(1060, 'SensaÃ§Ã£o tÃ©rmica', NULL),
(1061, 'MÃ¡quinas tÃ©rmicas', NULL),
(1062, 'MÃ¡quinas elÃ©tricas', NULL),
(1063, 'ConstruÃ§Ã£o de soluÃ§Ãµes tecnolÃ³gicas', NULL),
(1064, 'Sustentabilidade', NULL),
(1065, 'Objetivos do Desenvolvimento SustentÃ¡vel', NULL),
(1066, 'Plano de intervenÃ§Ã£o sustentÃ¡vel', NULL),
(1067, 'CombustÃ­veis fÃ³sseis', NULL),
(1068, 'Desmatamento', NULL),
(1069, 'Queimadas', NULL),
(1070, 'ConscientizaÃ§Ã£o ambiental', NULL),
(1071, 'Microrganismos', NULL),
(1072, 'DoenÃ§as causadas por microrganismos', NULL),
(1073, 'Invertebrados', NULL),
(1074, 'Vertebrados', NULL),
(1075, 'Plantas terrestres', NULL),
(1076, 'Biodiversidade local', NULL),
(1077, 'AdolescÃªncia', NULL),
(1078, 'Puberdade', NULL),
(1079, 'Sistema nervoso', NULL),
(1080, 'Sistema endÃ³crino', NULL),
(1081, 'Sistema genital', NULL),
(1082, 'ReproduÃ§Ã£o assexuada', NULL),
(1083, 'ReproduÃ§Ã£o sexuada', NULL),
(1084, 'Variabilidade genÃ©tica', NULL),
(1085, 'Cuidado parental', NULL),
(1086, 'ReproduÃ§Ã£o dos vegetais', NULL),
(1087, 'Gimnospermas', NULL),
(1088, 'Angiospermas', NULL),
(1089, 'PrevenÃ§Ã£o', NULL),
(1090, 'ISTs', NULL),
(1091, 'Gravidez precoce', NULL),
(1092, 'Vulnerabilidade', NULL),
(1093, 'Sexualidade humana', NULL),
(1094, 'Drogas', NULL),
(1095, 'Macronutrientes e micronutrientes', NULL),
(1096, 'Guia Alimentar para a PopulaÃ§Ã£o Brasileira', NULL),
(1097, 'InformaÃ§Ã£o nutricional', NULL),
(1098, 'Sistema digestÃ³rio', NULL),
(1099, 'Processo de digestÃ£o', NULL),
(1100, 'AlimentaÃ§Ã£o balanceada', NULL),
(1101, 'InspiraÃ§Ã£o e expiraÃ§Ã£o', NULL),
(1102, 'SaÃºde do sistema respiratÃ³rio', NULL),
(1103, 'Modelo do sistema respiratÃ³rio', NULL),
(1104, 'CoraÃ§Ã£o', NULL),
(1105, 'Sangue', NULL),
(1106, 'Vasos sanguÃ­neos', NULL),
(1107, 'Sistema imune', NULL),
(1108, 'DoenÃ§as crÃ´nicas nÃ£o transmissÃ­veis', NULL),
(1109, 'PressÃ£o arterial', NULL),
(1110, 'Natureza da ciÃªncia', NULL),
(1111, 'ProduÃ§Ã£o do conhecimento cientÃ­fico', NULL),
(1112, 'DivulgaÃ§Ã£o cientÃ­fica', NULL),
(1113, 'DesinformaÃ§Ã£o', NULL),
(1114, 'Ãtomo', NULL),
(1115, 'Modelos atÃ´micos', NULL),
(1116, 'ClassificaÃ§Ã£o periÃ³dica', NULL),
(1117, 'Estados fÃ­sicos da matÃ©ria', NULL),
(1118, 'MudanÃ§as de estado fÃ­sico', NULL),
(1119, 'FusÃ£o e ebuliÃ§Ã£o', NULL),
(1120, 'SubstÃ¢ncias simples e compostas', NULL),
(1121, 'Alotropia', NULL),
(1122, 'ReaÃ§Ãµes quÃ­micas', NULL),
(1123, 'Lei de Lavoisier', NULL),
(1124, 'Lei de Proust', NULL),
(1125, 'Leis ponderais', NULL),
(1126, 'Natureza das ondas', NULL),
(1127, 'Amplitude, frequÃªncia, perÃ­odo e velocidade', NULL),
(1128, 'Espectro eletromagnÃ©tico', NULL),
(1129, 'RadiaÃ§Ãµes ionizantes e nÃ£o ionizantes', NULL),
(1130, 'AplicaÃ§Ãµes da radiaÃ§Ã£o na saÃºde', NULL),
(1131, 'InteraÃ§Ã£o das ondas', NULL),
(1132, 'ReflexÃ£o', NULL),
(1133, 'RefraÃ§Ã£o', NULL),
(1134, 'DifraÃ§Ã£o', NULL),
(1135, 'Som e comunicaÃ§Ã£o', NULL),
(1136, 'Hereditariedade', NULL),
(1137, 'Biotecnologia', NULL),
(1138, 'Material genÃ©tico', NULL),
(1139, 'Leis de Mendel', NULL),
(1140, 'Gametas', NULL),
(1141, 'SegregaÃ§Ã£o', NULL),
(1142, 'FecundaÃ§Ã£o', NULL),
(1143, 'Heredogramas', NULL),
(1144, 'Lamarckismo', NULL),
(1145, 'Darwinismo', NULL),
(1146, 'EvoluÃ§Ã£o biolÃ³gica', NULL),
(1147, 'Filosofia e formaÃ§Ã£o para a cidadania', NULL),
(1148, 'Origens da Filosofia', NULL),
(1149, 'Atitude filosÃ³fica', NULL),
(1150, 'DiÃ¡logo', NULL),
(1151, 'LÃ³gica', NULL),
(1152, 'FalÃ¡cias formais e informais', NULL),
(1153, 'Narrativa mitolÃ³gica e discurso filosÃ³fico', NULL),
(1154, 'PerÃ­odos da histÃ³ria da Filosofia', NULL),
(1155, 'Campos de investigaÃ§Ã£o da Filosofia', NULL),
(1156, 'PlatÃ£o e AristÃ³teles', NULL),
(1157, 'Escola de Atenas', NULL),
(1158, 'Arte como objeto de reflexÃ£o filosÃ³fica', NULL),
(1159, 'EstÃ©tica', NULL),
(1160, 'Conceitos fundamentais da EstÃ©tica', NULL),
(1161, 'Conceito de crÃ­tica', NULL),
(1162, 'ReflexÃ£o estÃ©tica', NULL),
(1163, 'ProduÃ§Ã£o de significados', NULL),
(1164, 'AnÃ¡lise crÃ­tica de obra de arte', NULL),
(1165, 'EstereÃ³tipos geracionais', NULL),
(1166, 'Etarismo', NULL),
(1167, 'Alteridade', NULL),
(1168, 'Empatia', NULL),
(1169, 'ConvÃ­vio intergeracional', NULL),
(1170, 'Estatuto da CrianÃ§a e do Adolescente', NULL),
(1171, 'Estatuto da Juventude', NULL),
(1172, 'Estatuto da Pessoa Idosa', NULL),
(1173, 'O olhar do outro em Sartre', NULL),
(1174, 'Protagonismo juvenil', NULL),
(1175, 'ViolÃªncia e suas anÃ¡lises filosÃ³ficas', NULL),
(1176, 'Hannah Arendt', NULL),
(1177, 'Dignidade humana', NULL),
(1178, 'Pico della Mirandola', NULL),
(1179, 'Immanuel Kant', NULL),
(1180, 'Direitos Humanos', NULL),
(1181, 'Liberdade republicana', NULL),
(1182, 'Autoritarismo', NULL),
(1183, 'Desigualdade', NULL),
(1184, 'Emmanuel LÃ©vinas', NULL),
(1185, 'Legitimidade do poder soberano', NULL),
(1186, 'Direito divino ao poder', NULL),
(1187, 'Thomas Hobbes', NULL),
(1188, 'John Locke', NULL),
(1189, 'Jean-Jacques Rousseau', NULL),
(1190, 'Contrato social', NULL),
(1191, 'Liberalismo', NULL),
(1192, 'Direitos individuais', NULL),
(1193, 'Vontade geral', NULL),
(1194, 'Soberania popular', NULL),
(1195, 'Conceitos iniciais do movimento', NULL),
(1196, 'FunÃ§Ã£o horÃ¡ria do MRU', NULL),
(1197, 'Movimento RetilÃ­neo Uniforme', NULL),
(1198, 'Movimento RetilÃ­neo Uniformemente Variado', NULL),
(1199, 'EquaÃ§Ã£o de Torricelli', NULL),
(1200, 'Queda livre', NULL),
(1201, 'LanÃ§amento vertical', NULL),
(1202, 'Movimento horizontal e oblÃ­quo', NULL),
(1203, 'Movimento Circular Uniforme', NULL),
(1204, 'Acoplamento de polias', NULL),
(1205, 'Grandezas escalares e vetoriais', NULL),
(1206, 'RepresentaÃ§Ã£o e operaÃ§Ãµes com vetores', NULL),
(1207, 'Primeira Lei de Newton', NULL),
(1208, 'Segunda Lei de Newton', NULL),
(1209, 'Terceira Lei de Newton', NULL),
(1210, 'ForÃ§as de contato e de campo', NULL),
(1211, 'Blocos em superfÃ­cies sem atrito', NULL),
(1212, 'Polias', NULL),
(1213, 'Atrito estÃ¡tico e dinÃ¢mico', NULL),
(1214, 'ForÃ§a elÃ¡stica', NULL),
(1215, 'Plano inclinado', NULL),
(1216, 'Trabalho mecÃ¢nico', NULL),
(1217, 'Trabalho de forÃ§as inclinadas', NULL),
(1218, 'Energia cinÃ©tica', NULL),
(1219, 'ConservaÃ§Ã£o da energia mecÃ¢nica', NULL),
(1220, 'Impulso e colisÃµes', NULL),
(1221, 'Escalas termomÃ©tricas', NULL),
(1222, 'DilataÃ§Ã£o tÃ©rmica', NULL),
(1223, 'Calor sensÃ­vel', NULL),
(1224, 'Calor latente', NULL),
(1225, 'PropagaÃ§Ã£o do calor', NULL),
(1226, 'Gases ideais', NULL),
(1227, 'Leis dos gases', NULL),
(1228, 'Lei Geral dos Gases', NULL),
(1229, 'Modelo do gÃ¡s perfeito', NULL),
(1230, 'Energia interna', NULL),
(1231, 'Primeira Lei da TermodinÃ¢mica', NULL),
(1232, 'TransformaÃ§Ãµes gasosas', NULL),
(1233, 'Ciclos termodinÃ¢micos', NULL),
(1234, 'Calor especÃ­fico do gÃ¡s', NULL),
(1235, 'Segunda Lei da TermodinÃ¢mica', NULL),
(1236, 'Ciclo de Carnot', NULL),
(1237, 'Motor Stirling', NULL),
(1238, 'Refrigeradores', NULL),
(1239, 'Rendimento e eficiÃªncia', NULL),
(1240, 'Carga elÃ©trica', NULL),
(1241, 'Condutores e isolantes', NULL),
(1242, 'EletrizaÃ§Ã£o', NULL),
(1243, 'ConservaÃ§Ã£o da carga', NULL),
(1244, 'Lei de Coulomb', NULL),
(1245, 'Campo elÃ©trico', NULL),
(1246, 'SuperposiÃ§Ã£o de campos', NULL),
(1247, 'Potencial elÃ©trico', NULL),
(1248, 'Energia potencial elÃ©trica', NULL),
(1249, 'Corrente elÃ©trica', NULL),
(1250, 'Sentido real e convencional', NULL),
(1251, 'Resistores Ã´hmicos e nÃ£o Ã´hmicos', NULL),
(1252, 'Primeira Lei de Ohm', NULL),
(1253, 'PotÃªncia elÃ©trica', NULL),
(1254, 'Consumo de energia', NULL),
(1255, 'Resistores em sÃ©rie', NULL),
(1256, 'AssociaÃ§Ã£o mista', NULL),
(1257, 'Segunda Lei de Ohm', NULL),
(1258, 'Resistividade e temperatura', NULL),
(1259, 'MatÃ©ria e constituiÃ§Ã£o da matÃ©ria', NULL),
(1260, 'Teoria atÃ´mica de Dalton', NULL),
(1261, 'EvoluÃ§Ã£o dos modelos atÃ´micos', NULL),
(1262, 'Experimento de Rutherford', NULL),
(1263, 'Modelo de Bohr', NULL),
(1264, 'Modelo quÃ¢ntico', NULL),
(1265, 'NÃºmero atÃ´mico e nÃºmero de massa', NULL),
(1266, 'IsÃ³topos', NULL),
(1267, 'NÃ­veis e subnÃ­veis de energia', NULL),
(1268, 'DistribuiÃ§Ã£o eletrÃ´nica', NULL),
(1269, 'PrincÃ­pios de Aufbau, Pauli e Hund', NULL),
(1270, 'Elementos e substÃ¢ncias quÃ­micas', NULL),
(1271, 'Tabela periÃ³dica', NULL),
(1272, 'RadioisÃ³topos', NULL),
(1273, 'Estrutura da matÃ©ria', NULL),
(1274, 'Propriedades periÃ³dicas', NULL),
(1275, 'EmissÃµes alfa, beta e gama', NULL),
(1276, 'FormaÃ§Ã£o de substÃ¢ncias', NULL),
(1277, 'LigaÃ§Ãµes quÃ­micas', NULL),
(1278, 'LigaÃ§Ã£o iÃ´nica', NULL),
(1279, 'LigaÃ§Ã£o covalente', NULL),
(1280, 'LigaÃ§Ã£o metÃ¡lica', NULL),
(1281, 'Teoria do octeto', NULL),
(1282, 'Camada de valÃªncia', NULL),
(1283, 'FÃ³rmula de Lewis', NULL),
(1284, 'SoluÃ§Ãµes e misturas', NULL),
(1285, 'Solubilidade', NULL),
(1286, 'Eletronegatividade', NULL),
(1287, 'Geometria molecular', NULL),
(1288, 'Polaridade', NULL),
(1289, 'Pontos de fusÃ£o e ebuliÃ§Ã£o', NULL),
(1290, 'InteraÃ§Ãµes intermoleculares', NULL),
(1291, 'AminoÃ¡cidos e proteÃ­nas', NULL),
(1292, 'TransformaÃ§Ãµes quÃ­micas', NULL),
(1293, 'ReaÃ§Ãµes e equaÃ§Ãµes quÃ­micas', NULL),
(1294, 'Reagentes e produtos', NULL),
(1295, 'SÃ­mbolos quÃ­micos', NULL),
(1296, 'Balanceamento', NULL),
(1297, 'ExtraÃ§Ã£o de matÃ©ria-prima', NULL),
(1298, 'Uso de recursos naturais', NULL),
(1299, 'Impactos socioambientais', NULL),
(1300, 'ReaÃ§Ãµes endotÃ©rmicas e exotÃ©rmicas', NULL),
(1301, 'ReaÃ§Ãµes de combustÃ£o', NULL),
(1302, 'Metais pesados', NULL),
(1303, 'Toxicidade das substÃ¢ncias quÃ­micas', NULL),
(1304, 'Tempo de permanÃªncia dos poluentes', NULL),
definiÃ§Ã£o, classificaÃ§Ã£o e estrutura', NULL),
(1306, 'Embalagens plÃ¡sticas', NULL),
(1307, 'PoluiÃ§Ã£o de ambientes aquÃ¡ticos e terrestres', NULL),
(1308, 'Gases poluentes na atmosfera', NULL),
(1309, 'Gases de efeito estufa', NULL),
(1310, 'EmissÃµes de CO2', NULL),
(1311, 'Entalpia de combustÃ£o', NULL),
(1312, 'EficiÃªncia energÃ©tica', NULL),
(1313, 'Gasolina, diesel, biodiesel, biogÃ¡s e etanol', NULL),
(1314, 'Materiais, combustÃ­veis e energias alternativas', NULL),
(1315, 'Lei de Hess', NULL),
(1316, 'Poder calorÃ­fico', NULL),
(1317, 'Teoria da forÃ§a vital', NULL),
(1318, 'Postulados de KekulÃ©', NULL),
(1319, 'HibridizaÃ§Ã£o do carbono', NULL),
(1320, 'Cadeias carbÃ´nicas', NULL),
(1321, 'Hidrocarbonetos', NULL),
(1322, 'FunÃ§Ãµes oxigenadas', NULL),
(1323, 'FunÃ§Ãµes nitrogenadas', NULL),
(1324, 'FunÃ§Ãµes halogenadas', NULL),
(1325, 'ODS 3', NULL),
(1326, 'Estrutura e importÃ¢ncia de vitaminas', NULL),
(1327, 'ProteÃ­nas', NULL),
(1328, 'Carboidratos', NULL),
(1329, 'Ãcidos graxos', NULL),
(1330, 'Isomeria plana', NULL),
(1331, 'AgrotÃ³xicos e fertilizantes', NULL),
(1332, 'InseguranÃ§a alimentar', NULL),
(1333, 'PolÃ­meros naturais e sintÃ©ticos', NULL),
(1334, 'PolimerizaÃ§Ã£o', NULL),
(1335, 'Isomeria cis-trans', NULL),
(1336, 'ConsequÃªncias ambientais do uso de plÃ¡sticos', NULL),
(1337, 'Surgimento da Sociologia', NULL),
(1338, 'Auguste Comte', NULL),
(1339, 'Fatos sociais', NULL),
(1340, 'ConsciÃªncia coletiva', NULL),
(1341, 'InstituiÃ§Ãµes sociais', NULL),
(1342, 'Durkheim', NULL),
(1343, 'AÃ§Ã£o social', NULL),
(1344, 'Weber', NULL),
(1345, 'Materialismo histÃ³rico', NULL),
(1346, 'Luta de classes', NULL),
(1347, 'Marx', NULL),
(1348, 'Ideologia', NULL),
(1349, 'AlienaÃ§Ã£o', NULL),
(1350, 'Cultura', NULL),
(1351, 'Identidade cultural', NULL),
(1352, 'SocializaÃ§Ã£o primÃ¡ria e secundÃ¡ria', NULL),
(1353, 'Sociabilidade', NULL),
(1354, 'Identidade social e pessoal', NULL),
(1355, 'Contatos culturais', NULL),
(1356, 'AculturaÃ§Ã£o', NULL),
(1357, 'AssimilaÃ§Ã£o', NULL),
(1358, 'IntegraÃ§Ã£o', NULL),
(1359, 'Sincretismo', NULL),
(1360, 'Hibridismo', NULL),
(1361, 'Etnocentrismo', NULL),
(1362, 'Relativismo cultural', NULL),
(1363, 'ObservaÃ§Ã£o e interpretaÃ§Ã£o da realidade', NULL),
(1364, 'Olhar sociolÃ³gico', NULL),
(1365, 'Estranhamento', NULL),
(1366, 'DesnaturalizaÃ§Ã£o', NULL),
(1367, 'Senso comum', NULL),
(1368, 'Estudo de caso', NULL),
(1369, 'ProduÃ§Ã£o social das diferenÃ§as', NULL),
(1370, 'Marcadores sociais das diferenÃ§as', NULL),
(1371, 'Preconceito', NULL),
(1372, 'DiscriminaÃ§Ã£o', NULL),
(1373, 'IntolerÃ¢ncia', NULL),
(1374, 'EstratificaÃ§Ã£o social', NULL),
(1375, 'Classe social', NULL),
(1376, 'Desigualdade estrutural', NULL),
(1377, 'Mobilidade social', NULL),
(1378, 'ViolÃªncia como construÃ§Ã£o social', NULL),
(1379, 'ViolÃªncia simbÃ³lica', NULL),
(1380, 'Estruturas sociais', NULL),
(1381, 'Ordem social', NULL),
(1382, 'RaÃ§a e etnia', NULL),
(1383, 'RelaÃ§Ãµes Ã©tnico-raciais', NULL),
(1384, 'Racismo e racismo estrutural', NULL),
(1385, 'ViolÃªncia Ã©tnico-racial', NULL),
(1386, 'GÃªnero', NULL),
(1387, 'RelaÃ§Ãµes sociais de gÃªnero', NULL),
(1388, 'ViolÃªncia de gÃªnero', NULL),
(1389, 'Combate ao racismo', NULL),
(1390, 'Combate ao machismo', NULL),
(1391, 'Dignidade da pessoa humana', NULL),
(1392, 'Igualdade', NULL),
(1393, 'NÃ£o violÃªncia', NULL),
(1394, 'SituaÃ§Ã£o dos Direitos Humanos no Brasil e no mundo', NULL),
(1395, 'AvanÃ§os e entraves', NULL),
(1396, 'Desafios para a concretizaÃ§Ã£o dos Direitos Humanos', NULL);
