INSERT INTO curriculum_contents (id, descricao, unidade_tematica) VALUES
(601, 'Jogo de Basquete com regras e fundamentos', NULL),
(602, 'Esporte Paralímpico: Basquete em cadeira de rodas', NULL),
(603, 'Lutas de percussão', NULL),
(604, 'Boxe', NULL),
(605, 'Muay Thai', NULL),
(606, 'Posturas. Movimentações. Esquivas do Boxe', NULL),
(607, 'Golpes', NULL),
(608, 'jab, direto, cruzado, gancho. A Sombra', NULL),
(609, 'Postura. Movimentações. Esquivas e Bloqueios do Muay Thai', NULL),
(610, 'Golpes de membros superiores', NULL),
(611, 'Golpes de membros inferiores', NULL),
(612, 'Origem e evolução do MMA', NULL),
(613, 'Origem e evolução da esgrima', NULL),
(614, 'Mudanças e adequações às regras e dinâmicas da esgrima em sua versão paralímpica', NULL),
(615, 'Jogos de oposição no MMA', NULL),
(616, 'Práticas de golpes percussivos de membros superiores; Análise sobre as relações com outras modalidades vivenciadas', NULL),
(617, 'Práticas de golpes percussivos de membros inferiores; Análise sobre as relações com outras modalidades vivenciadas', NULL),
(618, 'Confecção de materiais para vivenciar a esgrima e a esgrima em cadeira de rodas nas aulas de Educação Física', NULL),
(619, 'Vivência da Esgrima', NULL),
(620, 'Adaptação da Esgrima em cadeira de rodas', NULL),
(621, 'Disputa de esgrima e disputa de esgrima em cadeira de rodas. Análise sobre a esgrima e a esgrima em cadeira de rodas. Relações, diferenças e desafios', NULL),
(622, 'Diferentes possibilidades de se praticar o Futebol; Futebol como prática democrática; Futebol de campo; Futebol society; Futsal; Fútbol callejero', NULL),
(623, 'Futebol de campo adaptado para o espaço escolar', NULL),
(624, 'Prática do futebol de campo adaptado', NULL),
(625, 'Futebol society de maneira adaptada para o espaço escolar', NULL),
(626, 'Prática do futebol society', NULL),
(627, 'Jogos pré-desportivos do futsal', NULL),
(628, 'Exercícios coletivos: fundamentos do futsal', NULL),
(629, 'Prática do Futsal', NULL),
(630, 'Regras, objetivos e vivências do fútbol callejero', NULL),
(631, 'Prática do fútbol callejero', NULL),
(632, 'Vivência de um futebol elencado pela turma', NULL),
(633, 'Retomada sobre a história e a importância dos esportes e jogos paralímpicos; Modalidades paralímpicas', NULL),
(634, 'Apresentação do goalball; Papel social, cultural e esportivo do goalball na inclusão', NULL),
(635, 'Goalball de maneira adaptada para o espaço escolar', NULL),
(636, 'Prática do goalball', NULL),
(637, 'Surgimento e diferenças entre o Rugby e o Futebol americano; Fundamentos e regras do Rugby e do Futebol Americano', NULL),
(638, 'Regras e possíveis adaptações do Rugby', NULL),
(639, '"Exercícios para atender o desenvolvimento técnico', NULL),
(640, 'Exercícios de condicionamento físico', NULL),
(641, 'Prática do Rugby', NULL),
(642, 'Regras e possíveis adaptações do Futebol americano', NULL),
(643, 'Exercícios de preparação física e treinamento técnico', NULL),
(644, 'Prática do Futebol americano', NULL),
(645, 'Definição de samba de roda; Significado histórico e cultural do carnaval; História do Ballet clássico; Origem da dança contemporânea', NULL),
(646, 'Musicalidade, ritmo e expressão corporal', NULL),
(647, 'Passos básicos do samba de roda: ginga, miudinho e trança', NULL),
(648, 'Simulação de um desfile de escola de samba', NULL),
(649, 'Posições e movimentos básicos do Ballet', NULL),
(650, 'Exploração livre de movimentos e improvisação guiada', NULL),
(651, 'Criação coletiva para dança contemporânea', NULL),
(652, 'Apresentação dos esportes de rede/quadra dividida; Diferença entre o Tênis de mesa e o Tênis de campo; Fundamentos e regras do Tênis de mesa e do Tênis de campo', NULL),
(653, 'Fundamentos; postura, saque, recepção, golpes básicos e tipos de empunhadura', NULL),
(654, 'Regras; Arbitragem', NULL),
(655, 'Prática do Tênis de Mesa; Diferenças com o Ping-Pong', NULL),
(656, 'Jogo de tênis de maneira adaptada para o espaço escolar', NULL),
(657, 'História e origem da Dança Circular, do Dabke e do Fandango; A chegada dessas danças ao Brasil; Significado, função cultural e contexto social dessas danças do mundo', NULL),
(658, 'Ritmo e musicalidade; Diversidade cultural', NULL),
(659, 'Formação do círculo e passos básicos', NULL),
(660, 'Ritmo e musicalidade; Relevância cultural', NULL),
(661, 'Formação e passos na roda', NULL),
(662, 'Olhar cultural', NULL),
(663, 'Formação, passo de base, passo cruzado e giro', NULL),
(664, 'Esporte de rede/quadra dividida; Esporte de invasão/ territorial; Punhobol; Kin-Ball; Tchoukball; Ultimate Frisbee', NULL),
(665, 'Regras e possíveis adaptações do Punhobol e/ou do Kimball', NULL),
(666, 'Prática do Punhobol e/ou do Kimball', NULL),
(667, 'Regras e possíveis adaptações do Tchoukball', NULL),
(668, 'Prática do Tchoukball', NULL),
(669, 'Regras e possíveis adaptações do Ultimate Frisbee', NULL),
(670, 'Prática do Ultimate Frisbee', NULL),
(671, 'Materiais Digitais -Esportes praticados em quadra de areia/ praia; Origem e características do Vôlei de praia, do Futevôlei, do Beach tennis e do Frescobol', NULL),
(672, 'Regras, possíveis adaptações e prática do Vôlei de praia', NULL),
(673, 'Regras e possíveis adaptações do Futevôlei', NULL),
(674, 'Prática de Futevôlei', NULL),
(675, 'Regras, possíveis adaptações e prática do Beach tennis', NULL),
(676, 'Regras e possíveis adaptações do Frescobol', NULL),
(677, 'Prática de Frescobol', NULL),
(678, 'Continentes. Oceanos. Paisagens pelo mundo', NULL),
(679, 'O conceito de paisagem.', NULL),
(680, 'Tipos de paisagem.', NULL),
(681, 'Planos da paisagem', NULL),
(682, 'Paisagens transformadas pela ação da natureza.', NULL),
(683, 'Paisagens transformadas por diferentes grupos sociais', NULL),
(684, 'O conceito de lugar', NULL),
(685, 'Lugares do cotidiano', NULL),
(686, 'Relação entre os lugares', NULL),
(687, 'O conceito de espaço geográfico.', NULL),
(688, 'Produção do espaço geográfico.', NULL),
(689, 'Trabalho, técnica e as transformações no espaço geográfico.', NULL),
(690, 'Mapas mentais. Lugares de vivência. Transformações no espaço geográfico', NULL),
(691, 'Atividades econômicas.', NULL),
(692, 'Setores da economia.', NULL),
(693, 'Extrativismos minerais, animal e vegetal', NULL),
(694, 'Principais produtos extrativistas.', NULL),
(695, 'Distribuição no espaço geográfico.', NULL),
(696, 'Impactos ambientais', NULL),
(697, 'Tipos de agricultura.', NULL),
(698, 'Principais cultivos.', NULL),
(699, 'Sistemas de Produção pecuária.', NULL),
(700, 'Principais criações da pecuária', NULL),
(701, 'Principais produtos agropecuários.', NULL),
(702, 'Distribuição agropecuária no espaço geográfico.', NULL),
(703, 'Processo de industrialização. As fases da industrialização.', NULL),
(704, 'Distribuição industrial no espaço geográfico', NULL),
(705, 'Indústrias de base, de bens intermediários e de bens de consumo', NULL),
(706, 'Comércios locais, eletrônico e internacional', NULL),
(707, 'Serviços de saúde, de educação, financeiros, de turismo, de transporte e de comunicação', NULL),
(708, 'Interdependência das atividades econômicas. Setores produtivos.', NULL),
(709, 'Estágios de produção das mercadorias. As paisagens urbanas. O processo de urbanização', NULL),
(710, 'Principais problemas urbanos', NULL),
(711, 'As paisagens rurais. As transformações no campo', NULL),
(712, 'Principais problemas no campo', NULL),
(713, 'Principais movimentos do planeta Terra e suas consequências', NULL),
(714, 'Representações do planeta Terra.', NULL),
(715, 'Definição de cartografia.', NULL),
(716, 'Evolução das técnicas cartográficas', NULL),
(717, 'Elementos e convenções cartográficas.', NULL),
(718, 'Projeções planas, cônicas e cilíndricas', NULL),
(719, 'Formas de orientação espacial.', NULL),
(720, 'Orientação nos mapas', NULL),
(721, 'Instrumentos de orientação espacial.', NULL),
(722, 'Paralelos, Meridianos, Zonas térmicas', NULL),
(723, 'Fusos horários.', NULL),
(724, 'Latitude e longitude.', NULL),
(725, 'Escalas gráficas, numéricas, grandes e pequenas', NULL),
(726, 'Cálculo de escala cartográfica', NULL),
(727, 'Croqui, Mapa, Carta, Planta', NULL),
(728, 'Mapa temático', NULL),
(729, 'Perfil topográfico', NULL),
(730, 'Litosfera, Atmosfera, Hidrosfera e Biosfera.', NULL),
(731, 'Composição e camadas da atmosfera.', NULL),
(732, 'Tempo e clima.', NULL),
(733, 'Frentes de ar.', NULL),
(734, 'Previsão do tempo.', NULL),
(735, 'Latitude, Altitude, Maritimidade e Continentalidade.', NULL),
(736, 'Precipitação e Temperatura.', NULL),
(737, 'Climograma', NULL),
(738, 'Localização e limites do território brasileiro.', NULL),
(739, 'Conceito de região e de regionalização.', NULL),
(740, 'Divisão regional do IBGE.', NULL),
(741, 'Características da região Norte, da região Nordeste, da região Centro-Oeste, da região Sul e da região Sudeste.', NULL),
(742, 'Complexos regionais ou regiões geoeconômicas.', NULL),
(743, 'Complexo regional Amazônia.', NULL),
(744, 'Complexo regional Centro-Sul.', NULL),
(745, 'Complexo regional do Nordeste.', NULL),
(746, 'Regiões do Brasil', NULL),
(747, 'Conceito de território e sua dimensão política.', NULL),
(748, 'Ciclos econômicos.', NULL),
(749, 'Construção do território brasileiro.', NULL),
(750, 'Características do território brasileiro.', NULL),
(751, 'Tensões ligadas ao uso e posse do território.', NULL),
(752, 'Transformações territoriais em São Paulo.', NULL),
(753, 'Estereótipos e representações territoriais nos meios de comunicação', NULL),
(754, 'Diversidade étnico-racial e cultural da população brasileira.', NULL),
(755, 'Fluxos migratórios históricos e contemporâneos.', NULL),
(756, 'Fatores de atração e repulsão populacional, com foco nos complexos regionais.', NULL),
(757, 'Taxas de natalidade e mortalidade no Brasil.', NULL),
(758, 'Densidade demográfica e migrações internas.', NULL),
(759, 'Censo demográfico e dados populacionais.', NULL),
(760, 'Pirâmide etária e estrutura da população brasileira.', NULL),
(761, 'População economicamente ativa e setores da economia.', NULL),
(762, 'Formação da diversidade étnico-racial no Brasil.', NULL),
(763, 'Análise de dados demográficos por etnia no Brasil', NULL),
(764, 'Transporte e comunicação na integração do território brasileiro', NULL),
(765, 'O espaço das redes no Brasil', NULL),
(766, 'Redes de transporte no Brasil', NULL),
(767, 'Evolução dos transportes e de comunicação no Brasil', NULL),
(768, 'Industrialização brasileira, concentração e desconcentração industrial no Brasil', NULL),
(769, 'Parques científicos e tecnológicos no Brasil', NULL),
(770, 'Conexão entre lugares, Redes de transporte e comunicação e Distribuição das atividades econômicas', NULL),
(771, 'Redes de transporte e comunicação', NULL),
(772, 'Desconcentração industrial', NULL),
(773, 'Do mundo bipolar ao mundo multipolar', NULL),
(774, 'A ascensão dos Estados Unidos', NULL),
(775, 'O poderio militar e econômico dos Estados Unidos', NULL),
(776, 'O poder político dos Estados Unidos', NULL),
(777, 'Estratégias diplomáticas e econômicas', NULL),
(778, 'Desafios e oportunidades para os países latino', NULL),
(779, 'americanos no contexto da Nova Ordem Mundial', NULL),
(780, 'Brasil e Nova Ordem Mundial', NULL),
(781, 'África e Nova Ordem Mundial. 1º bim: 1, 2, 3, 4', NULL),
(782, 'Conceitos da Geopolítica', NULL),
(783, 'Relações internacionais', NULL),
(784, 'Principais organizações mundiais', NULL),
(785, 'Países-membros da ONU', NULL),
(786, 'Funções, objetivos e estrutura da ONU', NULL),
(787, 'Regionalização e aspectos físicos da África', NULL),
(788, 'Conflitos civis no continente africano', NULL),
(789, 'Crise humanitária na África', NULL),
(790, 'Conflitos africanos', NULL),
(791, 'Regionalização e aspectos físicos da América', NULL),
(792, 'Estados Unidos e México', NULL),
(793, 'Tensões e conflitos entre Chile e Bolívia', NULL),
(794, 'Tensões e conflitos entre Argentina e Chile', NULL),
(795, 'Tensões e conflitos entre Venezuela e Guiana', NULL),
(796, 'GATT e OMC. Indicadores econômicos dos Estados Unidos, da China e dos BRICS.', NULL),
(797, 'Principais produtos e serviços comercializados por Estados Unidos e China, e entre Estados Unidos e BRICS.', NULL),
(798, 'Países membros e parceiros dos BRICS. Características gerais dos BRICS.', NULL),
(799, 'Economia global e emergente.', NULL),
(800, 'Brasil, Rússia, Índia, China e África do Sul.', NULL);
