ï»¿INSERT INTO curriculum_contents (id, descricao, unidade_tematica) VALUES
(1, 'DanÃÂ§as Populares Brasileiras', NULL),
(2, 'Origens das DanÃÂ§as', NULL),
(3, 'VariaÃÂ§ÃÂ£o de Tempo', NULL),
(4, 'ExpressÃÂ£o Corporal', NULL),
(5, 'Elementos da DanÃÂ§a', NULL),
(6, 'Movimentos do Frevo', NULL),
(7, 'Uso do EspaÃÂ§o', NULL),
(8, 'Fatores do Movimento', NULL),
(9, 'Jongo', NULL),
(10, 'Frevo', NULL),
(11, 'Siriri', NULL),
(12, 'CarimbÃÂ³', NULL),
(13, 'CriaÃÂ§ÃÂµes CoreogrÃÂ¡ficas', NULL),
(14, 'ExpressÃÂ£o na DanÃÂ§a', NULL),
(15, 'Processos Criativos', NULL),
(16, 'MÃÂºsica Brasileira', NULL),
(17, 'ProduÃÂ§ÃÂ£o, RepertÃÂ³rio e CirculaÃÂ§ÃÂ£o Musical', NULL),
(18, 'FunÃÂ§ÃÂ£o Social da MÃÂºsica', NULL),
(19, 'RepertÃÂ³rio Musical IndÃÂ­gena e Afro-Brasileiro', NULL),
(20, 'Paisagem Sonora', NULL),
(21, 'Registro Musical', NULL),
(22, 'NotaÃÂ§ÃÂ£o NÃÂ£o Convencional', NULL),
(23, 'ComposiÃÂ§ÃÂ£o e ImprovisaÃÂ§ÃÂ£o Musical', NULL),
(24, 'PercussÃÂ£o Corporal', NULL),
(25, 'Instrumentos e NotaÃÂ§ÃÂ£o NÃÂ£o Convencionais', NULL),
(26, 'Instrumentos e Timbres', NULL),
(27, 'ImprovisaÃÂ§ÃÂ£o Musical', NULL),
(28, 'ComposiÃÂ§ÃÂ£o, ColaboraÃÂ§ÃÂ£o e ImprovisaÃÂ§ÃÂ£o Musical', NULL),
(29, 'ProduÃÂ§ÃÂ£o e Registro Musical', NULL),
(30, 'IntroduÃÂ§ÃÂ£o ÃÂ  DanÃÂ§a', NULL),
Diversidade Cultural', NULL),
(32, 'HistÃÂ³ria da DanÃÂ§a', NULL),
(33, 'DanÃÂ§a ClÃÂ¡ssica', NULL),
(34, 'DanÃÂ§a Moderna', NULL),
(35, 'Fatores de Movimento', NULL),
(36, 'Qualidades dos Movimentos', NULL),
(37, 'SequÃÂªncias CoreogrÃÂ¡ficas', NULL),
(38, 'AÃÂ§ÃÂµes de EsforÃÂ§o', NULL),
(39, 'ImprovisaÃÂ§ÃÂ£o na DanÃÂ§a', NULL),
(40, 'MÃÂºsica ClÃÂ¡ssica', NULL),
(41, 'MÃÂºsica Instrumental', NULL),
(42, 'MÃÂºsica Orquestral', NULL),
(43, 'Canto Coral', NULL),
(44, 'Estrutura do Coro', NULL),
(45, 'ProduÃÂ§ÃÂ£o Musical', NULL),
(46, 'Estrutura da Orquestra', NULL),
(47, 'TÃÂ©cnicas de ExecuÃÂ§ÃÂ£o', NULL),
(48, 'Instrumentos Convencionais', NULL),
(49, 'Timbres e CaracterÃÂ­sticas', NULL),
(50, 'NotaÃÂ§ÃÂ£o Convencional', NULL),
(51, 'ComposiÃÂ§ÃÂ£o Musical', NULL),
(52, 'TÃÂ©cnicas de ExecuÃÂ§ÃÂ£o Musical', NULL),
(53, 'Performance Musical', NULL),
(54, 'Instrumentos Musicais', NULL),
(55, 'Origens da DanÃÂ§a', NULL),
(56, 'DanÃÂ§a Coletiva', NULL),
(57, 'ImprovisaÃÂ§ÃÂ£o em DanÃÂ§a', NULL),
(58, 'AÃÂ§ÃÂµes Corporais DanÃÂ§adas', NULL),
(59, 'Personagens na DanÃÂ§a Popular', NULL),
(60, 'ImprovisaÃÂ§ÃÂ£o Coletiva', NULL),
(61, 'Gravidade e Peso', NULL),
(62, 'AnÃÂ¡lise do Movimento', NULL),
(63, 'Partitura Corporal', NULL),
(64, 'ComposiÃÂ§ÃÂ£o CoreogrÃÂ¡fica', NULL),
(65, 'ApreciaÃÂ§ÃÂ£o Musical', NULL),
(66, 'HistÃÂ³ria da MÃÂºsica', NULL),
(67, 'MÃÂºsica Tradicional Africana', NULL),
(68, 'Timbre', NULL),
(69, 'MÃÂºsica IndÃÂ­gena', NULL),
(70, 'MÃÂºsica ContemporÃÂ¢nea', NULL),
(71, 'MÃÂºsica Afro-Brasileira', NULL),
(72, 'Elementos da MÃÂºsica', NULL),
(73, 'Jogos RÃÂ­tmicos', NULL),
(74, 'PrÃÂ¡ticas de CriaÃÂ§ÃÂ£o', NULL),
(75, 'Movimento Cotidiano', NULL),
(76, 'Jogos e Brincadeiras', NULL),
(77, 'Kinesfera', NULL),
(78, 'Corpo-HÃÂ­brido e Corpo-Tela', NULL),
(79, 'CriaÃÂ§ÃÂ£o CoreogrÃÂ¡fica', NULL),
(80, 'DanÃÂ§a ContemporÃÂ¢nea', NULL),
(81, 'IndependÃÂªncia ou CoexistÃÂªncia EstÃÂ©tica', NULL),
(82, 'Qualidades do Movimento', NULL),
(83, 'Musicalidade Corporal', NULL),
(84, 'Brincadeiras e DanÃÂ§a', NULL),
(85, 'Corpo MemÃÂ©tico e Corpo MidiÃÂ¡tico', NULL),
(86, 'Corpo e Tecnologia', NULL),
(87, 'MÃÂºsica Popular Brasileira', NULL),
(88, 'MÃÂºsica Popular Estrangeira', NULL),
(89, 'Movimentos Musicais HistÃÂ³ricos', NULL),
(90, 'CanÃÂ§ÃÂ£o de Protesto', NULL),
(91, 'ExpressÃÂ£o, ComposiÃÂ§ÃÂ£o e ApreciaÃÂ§ÃÂ£o Musical', NULL),
(92, 'MÃÂºsica e Tecnologia', NULL),
(93, 'Elementos de ComposiÃÂ§ÃÂ£o Musical', NULL),
(94, 'FunÃÂ§ÃÂ£o Social da Arte', NULL),
(95, 'Cultura ContemporÃÂ¢nea', NULL),
(96, 'Processo Criativo', NULL),
(97, 'Arte e MÃÂ­dia', NULL),
(98, 'AnÃÂ¡lise CrÃÂ­tica', NULL),
(99, 'CriaÃÂ§ÃÂ£o ArtÃÂ­stica', NULL),
(100, 'IntervenÃÂ§ÃÂ£o ArtÃÂ­stica', NULL),
(101, 'ManifestaÃÂ§ÃÂ£o ArtÃÂ­stica', NULL),
(102, 'Linguagens ArtÃÂ­sticas', NULL),
(103, 'ExpressÃÂ£o ArtÃÂ­stica', NULL),
(104, 'Artes do Corpo', NULL),
(105, 'EstereÃÂ³tipos Sociais', NULL),
(106, 'CriaÃÂ§ÃÂ£o Musical', NULL),
(107, 'DanÃÂ§as Sociais', NULL),
(108, 'ExpressÃÂ£o IdentitÃÂ¡ria', NULL),
(109, 'Discurso CrÃÂ­tico', NULL),
(110, 'CrÃÂ­tica de Arte', NULL),
(111, 'Performatividade', NULL),
(112, 'PatrimÃÂ´nio Cultural', NULL),
(113, 'Pesquisa em Arte', NULL),
(114, 'AnÃÂ¡lise HistÃÂ³rica e Cultural', NULL),
(115, 'Manifesto ArtÃÂ­stico', NULL),
(116, 'EstÃÂ©tica Relacional', NULL),
(117, 'Processo Colaborativo', NULL),
(118, 'Impacto Cultural', NULL),
(119, 'Processos de CriaÃÂ§ÃÂ£o', NULL),
(120, 'Movimentos ArtÃÂ­sticos', NULL),
(121, 'Compartilhamento de PrÃÂ¡ticas', NULL),
(122, 'Contexto HistÃÂ³rico e Cultural', NULL),
(123, 'Zeitgeist, Ã¢â¬ÅEspÃÂ­rito do TempoÃ¢â¬Â', NULL),
(124, 'Manifestos Coletivos', NULL),
(125, 'Coletivos ArtÃÂ­sticos', NULL),
(126, 'Arte Colaborativa', NULL),
(127, 'Sistema de numeraÃÂ§ÃÂ£o decimal', NULL),
(128, 'OperaÃÂ§ÃÂµes fundamentais com nÃÂºmeros naturais', NULL),
(129, 'MÃÂºltiplos e divisores', NULL),
(130, 'O conceito de fraÃÂ§ÃÂ£o', NULL),
(131, 'OperaÃÂ§ÃÂµes fundamentais com nÃÂºmeros fracionÃÂ¡rios', NULL),
(132, 'PolÃÂ­gonos, triÃÂ¢ngulos e quadrilÃÂ¡teros', NULL),
(133, 'NÃÂºmeros inteiros', NULL),
(134, 'OperaÃÂ§ÃÂµes fundamentais com fraÃÂ§ÃÂµes', NULL),
(135, 'OperaÃÂ§ÃÂµes com nÃÂºmeros racionais nas formas fracionÃÂ¡ria e decimal', NULL),
(136, 'Figuras geomÃÂ©tricas planas no plano cartesiano', NULL),
(137, 'ÃÂrea de figuras geomÃÂ©tricas planas', NULL),
(138, 'OperaÃÂ§ÃÂµes fundamentais com nÃÂºmeros racionais', NULL),
(139, 'PotenciaÃÂ§ÃÂ£o e propriedades da potenciaÃÂ§ÃÂ£o', NULL),
(140, 'RadiciaÃÂ§ÃÂ£o e relaÃÂ§ÃÂµes entre radiciaÃÂ§ÃÂ£o e potenciaÃÂ§ÃÂ£o', NULL),
(141, 'ExpressÃÂµes algÃÂ©bricas e noÃÂ§ÃÂµes de ÃÂlgebra', NULL),
(142, 'EquaÃÂ§ÃÂµes polinomiais do 1ÃÂº grau', NULL),
(143, 'Sistemas de equaÃÂ§ÃÂµes polinomiais do 1ÃÂº grau', NULL),
ComparaÃÂ§ÃÂ£o, operaÃÂ§ÃÂµes fundamentais e potenciaÃÂ§ÃÂ£o', NULL),
(145, 'CaracterÃÂ­sticas dos triÃÂ¢ngulos e semelhanÃÂ§a de triÃÂ¢ngulos', NULL),
(146, 'SemelhanÃÂ§a de triÃÂ¢ngulos e teorema de PitÃÂ¡goras', NULL),
(147, 'NÃÂºmeros irracionais e dÃÂ­zimas periÃÂ³dicas', NULL),
(148, 'NÃÂºmeros reais', NULL),
(149, 'NÃÂºmeros racionais', NULL),
(150, 'Teorema de PitÃÂ¡goras', NULL),
(151, 'Conceito de funÃÂ§ÃÂ£o', NULL),
(152, 'RelaÃÂ§ÃÂ£o entre grandezas e equaÃÂ§ÃÂµes polinomiais de 1ÃÂº grau', NULL),
(153, 'FunÃÂ§ÃÂ£o Afim Ã¢â¬â Parte 1', NULL),
(154, 'PotenciaÃÂ§ÃÂ£o e notaÃÂ§ÃÂ£o cientÃÂ­fica', NULL),
(155, 'EquaÃÂ§ÃÂµes polinomiais do 1ÃÂº e 2ÃÂº graus', NULL),
(156, 'EquaÃÂ§ÃÂµes exponenciais', NULL),
(157, 'FunÃÂ§ÃÂµes exponenciais', NULL),
(158, 'Logaritmos', NULL),
(159, 'FunÃÂ§ÃÂµes logarÃÂ­tmicas', NULL),
(160, 'EquaÃÂ§ÃÂµes polinomiais do 1ÃÂ° e 2ÃÂ° graus', NULL),
(161, 'Sistemas de equaÃÂ§ÃÂµes lineares Ã¢â¬â Parte 1', NULL),
(162, '138 - 173 Sistemas de equaÃÂ§ÃÂµes lineares Ã¢â¬â Parte 2', NULL),
(163, 'AnÃÂ¡lise combinatÃÂ³ria', NULL),
(164, 'Probabilidade Ã¢â¬â Parte 1', NULL),
(165, 'Probabilidade Ã¢â¬â Parte 2', NULL),
(166, 'Leitura de post', NULL),
(167, 'Leitura de comentÃÂ¡rios', NULL),
(168, 'Leitura de notÃÂ­cia', NULL),
(169, 'Leitura de charge', NULL),
(170, 'Acento circunflexo', NULL),
(171, 'Leitura de carta do leitor', NULL),
exclamaÃÂ§ÃÂ£o e reticÃÂªncias', NULL),
fato central Ãâ subtemas', NULL),
substantivos', NULL),
adjetivos', NULL),
sÃÂ­laba tÃÂ´nica e acento grÃÂ¡fico', NULL),
X e CH', NULL),
(178, 'PontuaÃÂ§ÃÂ£o', NULL),
uso da cedilha', NULL),
(180, 'TerminaÃÂ§ÃÂ£o -gem', NULL),
(181, 'Palavras "mau" e "mal"', NULL),
(182, 'AcentuaÃÂ§ÃÂ£o em palavras oxÃÂ­tonas, proparoxÃÂ­tonas e paroxÃÂ­tonas', NULL),
(183, 'O sentido de sufixos', NULL),
(184, 'Leitura de poema', NULL),
(185, 'Leitura de conto', NULL),
(186, 'Leitura de lenda', NULL),
(187, 'Leitura de trecho de romance infantojuvenil', NULL),
(188, 'Leitura de crÃÂ´nica literÃÂ¡ria', NULL),
(189, 'ConcordÃÂ¢ncia nominal', NULL),
verbos', NULL),
(191, 'ConcordÃÂ¢ncia verbal (sujeito simples)', NULL),
(192, 'SinÃÂ´nimos e antÃÂ´nimos', NULL),
(193, 'O sentido de prefixos', NULL),
(194, 'Leitura de carta de reclamaÃÂ§ÃÂ£o', NULL),
subjuntivo. Tempos e modos verbais', NULL),
artigos definidos e indefinidos', NULL),
(197, 'Leitura e compreensÃÂ£o de poemas', NULL),
(198, 'ComparaÃÂ§ÃÂ£o de notÃÂ­cias', NULL),
(199, 'Fato Ãâ opiniÃÂ£o em textos jornalÃÂ­sticos', NULL),
(200, 'Leitura de anÃÂºncio publicitÃÂ¡rio', NULL);
