ï»¿INSERT INTO curriculum_contents (id, descricao, unidade_tematica) VALUES
(1, 'DanâÂºas Populares Brasileiras', NULL),
(2, 'Origens das DanâÂºas', NULL),
(3, 'VariaâÂºâÃºo de Tempo', NULL),
(4, 'ExpressâÃºo Corporal', NULL),
(5, 'Elementos da DanâÂºa', NULL),
(6, 'Movimentos do Frevo', NULL),
(7, 'Uso do EspaâÂºo', NULL),
(8, 'Fatores do Movimento', NULL),
(9, 'Jongo', NULL),
(10, 'Frevo', NULL),
(11, 'Siriri', NULL),
(12, 'Carimbââ', NULL),
(13, 'CriaâÂºââ¡es CoreogrâÃ­ficas', NULL),
(14, 'ExpressâÃºo na DanâÂºa', NULL),
(15, 'Processos Criativos', NULL),
(16, 'Mââsica Brasileira', NULL),
(17, 'ProduâÂºâÃºo, Repertâârio e CirculaâÂºâÃºo Musical', NULL),
(18, 'FunâÂºâÃºo Social da Mââsica', NULL),
(19, 'Repertâârio Musical IndâÂ¡gena e Afro-Brasileiro', NULL),
(20, 'Paisagem Sonora', NULL),
(21, 'Registro Musical', NULL),
(22, 'NotaâÂºâÃºo NâÃºo Convencional', NULL),
(23, 'ComposiâÂºâÃºo e ImprovisaâÂºâÃºo Musical', NULL),
(24, 'PercussâÃºo Corporal', NULL),
(25, 'Instrumentos e NotaâÂºâÃºo NâÃºo Convencionais', NULL),
(26, 'Instrumentos e Timbres', NULL),
(27, 'ImprovisaâÂºâÃºo Musical', NULL),
(28, 'ComposiâÂºâÃºo, ColaboraâÂºâÃºo e ImprovisaâÂºâÃºo Musical', NULL),
(29, 'ProduâÂºâÃºo e Registro Musical', NULL),
(30, 'IntroduâÂºâÃºo âÃ¡ DanâÂºa', NULL),
Diversidade Cultural', NULL),
(32, 'Histââria da DanâÂºa', NULL),
(33, 'DanâÂºa ClâÃ­ssica', NULL),
(34, 'DanâÂºa Moderna', NULL),
(35, 'Fatores de Movimento', NULL),
(36, 'Qualidades dos Movimentos', NULL),
(37, 'SequâÂ¬ncias CoreogrâÃ­ficas', NULL),
(38, 'AâÂºââ¡es de EsforâÂºo', NULL),
(39, 'ImprovisaâÂºâÃºo na DanâÂºa', NULL),
(40, 'Mââsica ClâÃ­ssica', NULL),
(41, 'Mââsica Instrumental', NULL),
(42, 'Mââsica Orquestral', NULL),
(43, 'Canto Coral', NULL),
(44, 'Estrutura do Coro', NULL),
(45, 'ProduâÂºâÃºo Musical', NULL),
(46, 'Estrutura da Orquestra', NULL),
(47, 'Tââcnicas de ExecuâÂºâÃºo', NULL),
(48, 'Instrumentos Convencionais', NULL),
(49, 'Timbres e CaracterâÂ¡sticas', NULL),
(50, 'NotaâÂºâÃºo Convencional', NULL),
(51, 'ComposiâÂºâÃºo Musical', NULL),
(52, 'Tââcnicas de ExecuâÂºâÃºo Musical', NULL),
(53, 'Performance Musical', NULL),
(54, 'Instrumentos Musicais', NULL),
(55, 'Origens da DanâÂºa', NULL),
(56, 'DanâÂºa Coletiva', NULL),
(57, 'ImprovisaâÂºâÃºo em DanâÂºa', NULL),
(58, 'AâÂºââ¡es Corporais DanâÂºadas', NULL),
(59, 'Personagens na DanâÂºa Popular', NULL),
(60, 'ImprovisaâÂºâÃºo Coletiva', NULL),
(61, 'Gravidade e Peso', NULL),
(62, 'AnâÃ­lise do Movimento', NULL),
(63, 'Partitura Corporal', NULL),
(64, 'ComposiâÂºâÃºo CoreogrâÃ­fica', NULL),
(65, 'ApreciaâÂºâÃºo Musical', NULL),
(66, 'Histââria da Mââsica', NULL),
(67, 'Mââsica Tradicional Africana', NULL),
(68, 'Timbre', NULL),
(69, 'Mââsica IndâÂ¡gena', NULL),
(70, 'Mââsica ContemporâÃ³nea', NULL),
(71, 'Mââsica Afro-Brasileira', NULL),
(72, 'Elementos da Mââsica', NULL),
(73, 'Jogos RâÂ¡tmicos', NULL),
(74, 'PrâÃ­ticas de CriaâÂºâÃºo', NULL),
(75, 'Movimento Cotidiano', NULL),
(76, 'Jogos e Brincadeiras', NULL),
(77, 'Kinesfera', NULL),
(78, 'Corpo-HâÂ¡brido e Corpo-Tela', NULL),
(79, 'CriaâÂºâÃºo CoreogrâÃ­fica', NULL),
(80, 'DanâÂºa ContemporâÃ³nea', NULL),
(81, 'IndependâÂ¬ncia ou CoexistâÂ¬ncia Estââtica', NULL),
(82, 'Qualidades do Movimento', NULL),
(83, 'Musicalidade Corporal', NULL),
(84, 'Brincadeiras e DanâÂºa', NULL),
(85, 'Corpo Memââtico e Corpo MidiâÃ­tico', NULL),
(86, 'Corpo e Tecnologia', NULL),
(87, 'Mââsica Popular Brasileira', NULL),
(88, 'Mââsica Popular Estrangeira', NULL),
(89, 'Movimentos Musicais Histââricos', NULL),
(90, 'CanâÂºâÃºo de Protesto', NULL),
(91, 'ExpressâÃºo, ComposiâÂºâÃºo e ApreciaâÂºâÃºo Musical', NULL),
(92, 'Mââsica e Tecnologia', NULL),
(93, 'Elementos de ComposiâÂºâÃºo Musical', NULL),
(94, 'FunâÂºâÃºo Social da Arte', NULL),
(95, 'Cultura ContemporâÃ³nea', NULL),
(96, 'Processo Criativo', NULL),
(97, 'Arte e MâÂ¡dia', NULL),
(98, 'AnâÃ­lise CrâÂ¡tica', NULL),
(99, 'CriaâÂºâÃºo ArtâÂ¡stica', NULL),
(100, 'IntervenâÂºâÃºo ArtâÂ¡stica', NULL),
(101, 'ManifestaâÂºâÃºo ArtâÂ¡stica', NULL),
(102, 'Linguagens ArtâÂ¡sticas', NULL),
(103, 'ExpressâÃºo ArtâÂ¡stica', NULL),
(104, 'Artes do Corpo', NULL),
(105, 'Estereââtipos Sociais', NULL),
(106, 'CriaâÂºâÃºo Musical', NULL),
(107, 'DanâÂºas Sociais', NULL),
(108, 'ExpressâÃºo IdentitâÃ­ria', NULL),
(109, 'Discurso CrâÂ¡tico', NULL),
(110, 'CrâÂ¡tica de Arte', NULL),
(111, 'Performatividade', NULL),
(112, 'Patrimââ¤nio Cultural', NULL),
(113, 'Pesquisa em Arte', NULL),
(114, 'AnâÃ­lise Histâârica e Cultural', NULL),
(115, 'Manifesto ArtâÂ¡stico', NULL),
(116, 'Estââtica Relacional', NULL),
(117, 'Processo Colaborativo', NULL),
(118, 'Impacto Cultural', NULL),
(119, 'Processos de CriaâÂºâÃºo', NULL),
(120, 'Movimentos ArtâÂ¡sticos', NULL),
(121, 'Compartilhamento de PrâÃ­ticas', NULL),
(122, 'Contexto Histâârico e Cultural', NULL),
(123, 'Zeitgeist, ÎÃÂ£EspâÂ¡rito do TempoÎÃÂ¥', NULL),
(124, 'Manifestos Coletivos', NULL),
(125, 'Coletivos ArtâÂ¡sticos', NULL),
(126, 'Arte Colaborativa', NULL),
(127, 'Sistema de numeraâÂºâÃºo decimal', NULL),
(128, 'OperaâÂºââ¡es fundamentais com nââmeros naturais', NULL),
(129, 'Mââltiplos e divisores', NULL),
(130, 'O conceito de fraâÂºâÃºo', NULL),
(131, 'OperaâÂºââ¡es fundamentais com nââmeros fracionâÃ­rios', NULL),
(132, 'PolâÂ¡gonos, triâÃ³ngulos e quadrilâÃ­teros', NULL),
(133, 'Nââmeros inteiros', NULL),
(134, 'OperaâÂºââ¡es fundamentais com fraâÂºââ¡es', NULL),
(135, 'OperaâÂºââ¡es com nââmeros racionais nas formas fracionâÃ­ria e decimal', NULL),
(136, 'Figuras geomââtricas planas no plano cartesiano', NULL),
(137, 'âÃ¼rea de figuras geomââtricas planas', NULL),
(138, 'OperaâÂºââ¡es fundamentais com nââmeros racionais', NULL),
(139, 'PotenciaâÂºâÃºo e propriedades da potenciaâÂºâÃºo', NULL),
(140, 'RadiciaâÂºâÃºo e relaâÂºââ¡es entre radiciaâÂºâÃºo e potenciaâÂºâÃºo', NULL),
(141, 'Expressââ¡es algââbricas e noâÂºââ¡es de âÃ¼lgebra', NULL),
(142, 'EquaâÂºââ¡es polinomiais do 1â¬â grau', NULL),
(143, 'Sistemas de equaâÂºââ¡es polinomiais do 1â¬â grau', NULL),
ComparaâÂºâÃºo, operaâÂºââ¡es fundamentais e potenciaâÂºâÃºo', NULL),
(145, 'CaracterâÂ¡sticas dos triâÃ³ngulos e semelhanâÂºa de triâÃ³ngulos', NULL),
(146, 'SemelhanâÂºa de triâÃ³ngulos e teorema de PitâÃ­goras', NULL),
(147, 'Nââmeros irracionais e dâÂ¡zimas periââdicas', NULL),
(148, 'Nââmeros reais', NULL),
(149, 'Nââmeros racionais', NULL),
(150, 'Teorema de PitâÃ­goras', NULL),
(151, 'Conceito de funâÂºâÃºo', NULL),
(152, 'RelaâÂºâÃºo entre grandezas e equaâÂºââ¡es polinomiais de 1â¬â grau', NULL),
(153, 'FunâÂºâÃºo Afim ÎÃÃ´ Parte 1', NULL),
(154, 'PotenciaâÂºâÃºo e notaâÂºâÃºo cientâÂ¡fica', NULL),
(155, 'EquaâÂºââ¡es polinomiais do 1â¬â e 2â¬â graus', NULL),
(156, 'EquaâÂºââ¡es exponenciais', NULL),
(157, 'FunâÂºââ¡es exponenciais', NULL),
(158, 'Logaritmos', NULL),
(159, 'FunâÂºââ¡es logarâÂ¡tmicas', NULL),
(160, 'EquaâÂºââ¡es polinomiais do 1â¬â e 2â¬â graus', NULL),
(161, 'Sistemas de equaâÂºââ¡es lineares ÎÃÃ´ Parte 1', NULL),
(162, '138 - 173 Sistemas de equaâÂºââ¡es lineares ÎÃÃ´ Parte 2', NULL),
(163, 'AnâÃ­lise combinatââria', NULL),
(164, 'Probabilidade ÎÃÃ´ Parte 1', NULL),
(165, 'Probabilidade ÎÃÃ´ Parte 2', NULL),
(166, 'Leitura de post', NULL),
(167, 'Leitura de comentâÃ­rios', NULL),
(168, 'Leitura de notâÂ¡cia', NULL),
(169, 'Leitura de charge', NULL),
(170, 'Acento circunflexo', NULL),
(171, 'Leitura de carta do leitor', NULL),
exclamaâÂºâÃºo e reticâÂ¬ncias', NULL),
fato central âÃ¹ subtemas', NULL),
substantivos', NULL),
adjetivos', NULL),
sâÂ¡laba tââ¤nica e acento grâÃ­fico', NULL),
X e CH', NULL),
(178, 'PontuaâÂºâÃºo', NULL),
uso da cedilha', NULL),
(180, 'TerminaâÂºâÃºo -gem', NULL),
(181, 'Palavras "mau" e "mal"', NULL),
(182, 'AcentuaâÂºâÃºo em palavras oxâÂ¡tonas, proparoxâÂ¡tonas e paroxâÂ¡tonas', NULL),
(183, 'O sentido de sufixos', NULL),
(184, 'Leitura de poema', NULL),
(185, 'Leitura de conto', NULL),
(186, 'Leitura de lenda', NULL),
(187, 'Leitura de trecho de romance infantojuvenil', NULL),
(188, 'Leitura de crââ¤nica literâÃ­ria', NULL),
(189, 'ConcordâÃ³ncia nominal', NULL),
verbos', NULL),
(191, 'ConcordâÃ³ncia verbal (sujeito simples)', NULL),
(192, 'Sinââ¤nimos e antââ¤nimos', NULL),
(193, 'O sentido de prefixos', NULL),
(194, 'Leitura de carta de reclamaâÂºâÃºo', NULL),
subjuntivo. Tempos e modos verbais', NULL),
artigos definidos e indefinidos', NULL),
(197, 'Leitura e compreensâÃºo de poemas', NULL),
(198, 'ComparaâÂºâÃºo de notâÂ¡cias', NULL),
(199, 'Fato âÃ¹ opiniâÃºo em textos jornalâÂ¡sticos', NULL),
(200, 'Leitura de anââncio publicitâÃ­rio', NULL);
