INSERT INTO curriculum_contents (id, descricao, unidade_tematica) VALUES
(1, 'DanÃ§as Populares Brasileiras', NULL),
(2, 'Origens das DanÃ§as', NULL),
(3, 'VariaÃ§Ã£o de Tempo', NULL),
(4, 'ExpressÃ£o Corporal', NULL),
(5, 'Elementos da DanÃ§a', NULL),
(6, 'Movimentos do Frevo', NULL),
(7, 'Uso do EspaÃ§o', NULL),
(8, 'Fatores do Movimento', NULL),
(9, 'Jongo', NULL),
(10, 'Frevo', NULL),
(11, 'Siriri', NULL),
(12, 'CarimbÃ³', NULL),
(13, 'CriaÃ§Ãµes CoreogrÃ¡ficas', NULL),
(14, 'ExpressÃ£o na DanÃ§a', NULL),
(15, 'Processos Criativos', NULL),
(16, 'MÃºsica Brasileira', NULL),
(17, 'ProduÃ§Ã£o, RepertÃ³rio e CirculaÃ§Ã£o Musical', NULL),
(18, 'FunÃ§Ã£o Social da MÃºsica', NULL),
(19, 'RepertÃ³rio Musical IndÃ­gena e Afro-Brasileiro', NULL),
(20, 'Paisagem Sonora', NULL),
(21, 'Registro Musical', NULL),
(22, 'NotaÃ§Ã£o NÃ£o Convencional', NULL),
(23, 'ComposiÃ§Ã£o e ImprovisaÃ§Ã£o Musical', NULL),
(24, 'PercussÃ£o Corporal', NULL),
(25, 'Instrumentos e NotaÃ§Ã£o NÃ£o Convencionais', NULL),
(26, 'Instrumentos e Timbres', NULL),
(27, 'ImprovisaÃ§Ã£o Musical', NULL),
(28, 'ComposiÃ§Ã£o, ColaboraÃ§Ã£o e ImprovisaÃ§Ã£o Musical', NULL),
(29, 'ProduÃ§Ã£o e Registro Musical', NULL),
(30, 'IntroduÃ§Ã£o Ã  DanÃ§a', NULL),
(31, 'DanÃ§a: Diversidade Cultural', NULL),
(32, 'HistÃ³ria da DanÃ§a', NULL),
(33, 'DanÃ§a ClÃ¡ssica', NULL),
(34, 'DanÃ§a Moderna', NULL),
(35, 'Fatores de Movimento', NULL),
(36, 'Qualidades dos Movimentos', NULL),
(37, 'SequÃªncias CoreogrÃ¡ficas', NULL),
(38, 'AÃ§Ãµes de EsforÃ§o', NULL),
(39, 'ImprovisaÃ§Ã£o na DanÃ§a', NULL),
(40, 'MÃºsica ClÃ¡ssica', NULL),
(41, 'MÃºsica Instrumental', NULL),
(42, 'MÃºsica Orquestral', NULL),
(43, 'Canto Coral', NULL),
(44, 'Estrutura do Coro', NULL),
(45, 'ProduÃ§Ã£o Musical', NULL),
(46, 'Estrutura da Orquestra', NULL),
(47, 'TÃ©cnicas de ExecuÃ§Ã£o', NULL),
(48, 'Instrumentos Convencionais', NULL),
(49, 'Timbres e CaracterÃ­sticas', NULL),
(50, 'NotaÃ§Ã£o Convencional', NULL),
(51, 'ComposiÃ§Ã£o Musical', NULL),
(52, 'TÃ©cnicas de ExecuÃ§Ã£o Musical', NULL),
(53, 'Performance Musical', NULL),
(54, 'Instrumentos Musicais', NULL),
(55, 'Origens da DanÃ§a', NULL),
(56, 'DanÃ§a Coletiva', NULL),
(57, 'ImprovisaÃ§Ã£o em DanÃ§a', NULL),
(58, 'AÃ§Ãµes Corporais DanÃ§adas', NULL),
(59, 'Personagens na DanÃ§a Popular', NULL),
(60, 'ImprovisaÃ§Ã£o Coletiva', NULL),
(61, 'Gravidade e Peso', NULL),
(62, 'AnÃ¡lise do Movimento', NULL),
(63, 'Partitura Corporal', NULL),
(64, 'ComposiÃ§Ã£o CoreogrÃ¡fica', NULL),
(65, 'ApreciaÃ§Ã£o Musical', NULL),
(66, 'HistÃ³ria da MÃºsica', NULL),
(67, 'MÃºsica Tradicional Africana', NULL),
(68, 'Timbre', NULL),
(69, 'MÃºsica IndÃ­gena', NULL),
(70, 'MÃºsica ContemporÃ¢nea', NULL),
(71, 'MÃºsica Afro-Brasileira', NULL),
(72, 'Elementos da MÃºsica', NULL),
(73, 'Jogos RÃ­tmicos', NULL),
(74, 'PrÃ¡ticas de CriaÃ§Ã£o', NULL),
(75, 'Movimento Cotidiano', NULL),
(76, 'Jogos e Brincadeiras', NULL),
(77, 'Kinesfera', NULL),
(78, 'Corpo-HÃ­brido e Corpo-Tela', NULL),
(79, 'CriaÃ§Ã£o CoreogrÃ¡fica', NULL),
(80, 'DanÃ§a ContemporÃ¢nea', NULL),
(81, 'IndependÃªncia ou CoexistÃªncia EstÃ©tica', NULL),
(82, 'Qualidades do Movimento', NULL),
(83, 'Musicalidade Corporal', NULL),
(84, 'Brincadeiras e DanÃ§a', NULL),
(85, 'Corpo MemÃ©tico e Corpo MidiÃ¡tico', NULL),
(86, 'Corpo e Tecnologia', NULL),
(87, 'MÃºsica Popular Brasileira', NULL),
(88, 'MÃºsica Popular Estrangeira', NULL),
(89, 'Movimentos Musicais HistÃ³ricos', NULL),
(90, 'CanÃ§Ã£o de Protesto', NULL),
(91, 'ExpressÃ£o, ComposiÃ§Ã£o e ApreciaÃ§Ã£o Musical', NULL),
(92, 'MÃºsica e Tecnologia', NULL),
(93, 'Elementos de ComposiÃ§Ã£o Musical', NULL),
(94, 'FunÃ§Ã£o Social da Arte', NULL),
(95, 'Cultura ContemporÃ¢nea', NULL),
(96, 'Processo Criativo', NULL),
(97, 'Arte e MÃ­dia', NULL),
(98, 'AnÃ¡lise CrÃ­tica', NULL),
(99, 'CriaÃ§Ã£o ArtÃ­stica', NULL),
(100, 'IntervenÃ§Ã£o ArtÃ­stica', NULL),
(101, 'ManifestaÃ§Ã£o ArtÃ­stica', NULL),
(102, 'Linguagens ArtÃ­sticas', NULL),
(103, 'ExpressÃ£o ArtÃ­stica', NULL),
(104, 'Artes do Corpo', NULL),
(105, 'EstereÃ³tipos Sociais', NULL),
(106, 'CriaÃ§Ã£o Musical', NULL),
(107, 'DanÃ§as Sociais', NULL),
(108, 'ExpressÃ£o IdentitÃ¡ria', NULL),
(109, 'Discurso CrÃ­tico', NULL),
(110, 'CrÃ­tica de Arte', NULL),
(111, 'Performatividade', NULL),
(112, 'PatrimÃ´nio Cultural', NULL),
(113, 'Pesquisa em Arte', NULL),
(114, 'AnÃ¡lise HistÃ³rica e Cultural', NULL),
(115, 'Manifesto ArtÃ­stico', NULL),
(116, 'EstÃ©tica Relacional', NULL),
(117, 'Processo Colaborativo', NULL),
(118, 'Impacto Cultural', NULL),
(119, 'Processos de CriaÃ§Ã£o', NULL),
(120, 'Movimentos ArtÃ­sticos', NULL),
(121, 'Compartilhamento de PrÃ¡ticas', NULL),
(122, 'Contexto HistÃ³rico e Cultural', NULL),
(123, 'Zeitgeist, â€œEspÃ­rito do Tempoâ€', NULL),
(124, 'Manifestos Coletivos', NULL),
(125, 'Coletivos ArtÃ­sticos', NULL),
(126, 'Arte Colaborativa', NULL),
(127, 'Sistema de numeraÃ§Ã£o decimal', NULL),
(128, 'OperaÃ§Ãµes fundamentais com nÃºmeros naturais', NULL),
(129, 'MÃºltiplos e divisores', NULL),
(130, 'O conceito de fraÃ§Ã£o', NULL),
(131, 'OperaÃ§Ãµes fundamentais com nÃºmeros fracionÃ¡rios', NULL),
(132, 'PolÃ­gonos, triÃ¢ngulos e quadrilÃ¡teros', NULL),
(133, 'NÃºmeros inteiros', NULL),
(134, 'OperaÃ§Ãµes fundamentais com fraÃ§Ãµes', NULL),
(135, 'OperaÃ§Ãµes com nÃºmeros racionais nas formas fracionÃ¡ria e decimal', NULL),
(136, 'Figuras geomÃ©tricas planas no plano cartesiano', NULL),
(137, 'Ãrea de figuras geomÃ©tricas planas', NULL),
(138, 'OperaÃ§Ãµes fundamentais com nÃºmeros racionais', NULL),
(139, 'PotenciaÃ§Ã£o e propriedades da potenciaÃ§Ã£o', NULL),
(140, 'RadiciaÃ§Ã£o e relaÃ§Ãµes entre radiciaÃ§Ã£o e potenciaÃ§Ã£o', NULL),
(141, 'ExpressÃµes algÃ©bricas e noÃ§Ãµes de Ãlgebra', NULL),
(142, 'EquaÃ§Ãµes polinomiais do 1Âº grau', NULL),
(143, 'Sistemas de equaÃ§Ãµes polinomiais do 1Âº grau', NULL),
(144, 'NÃºmeros racionais: ComparaÃ§Ã£o, operaÃ§Ãµes fundamentais e potenciaÃ§Ã£o', NULL),
(145, 'CaracterÃ­sticas dos triÃ¢ngulos e semelhanÃ§a de triÃ¢ngulos', NULL),
(146, 'SemelhanÃ§a de triÃ¢ngulos e teorema de PitÃ¡goras', NULL),
(147, 'NÃºmeros irracionais e dÃ­zimas periÃ³dicas', NULL),
(148, 'NÃºmeros reais', NULL),
(149, 'NÃºmeros racionais', NULL),
(150, 'Teorema de PitÃ¡goras', NULL),
(151, 'Conceito de funÃ§Ã£o', NULL),
(152, 'RelaÃ§Ã£o entre grandezas e equaÃ§Ãµes polinomiais de 1Âº grau', NULL),
(153, 'FunÃ§Ã£o Afim â€“ Parte 1', NULL),
(154, 'PotenciaÃ§Ã£o e notaÃ§Ã£o cientÃ­fica', NULL),
(155, 'EquaÃ§Ãµes polinomiais do 1Âº e 2Âº graus', NULL),
(156, 'EquaÃ§Ãµes exponenciais', NULL),
(157, 'FunÃ§Ãµes exponenciais', NULL),
(158, 'Logaritmos', NULL),
(159, 'FunÃ§Ãµes logarÃ­tmicas', NULL),
(160, 'EquaÃ§Ãµes polinomiais do 1Â° e 2Â° graus', NULL),
(161, 'Sistemas de equaÃ§Ãµes lineares â€“ Parte 1', NULL),
(162, '138 - 173 Sistemas de equaÃ§Ãµes lineares â€“ Parte 2', NULL),
(163, 'AnÃ¡lise combinatÃ³ria', NULL),
(164, 'Probabilidade â€“ Parte 1', NULL),
(165, 'Probabilidade â€“ Parte 2', NULL),
(166, 'Leitura de post', NULL),
(167, 'Leitura de comentÃ¡rios', NULL),
(168, 'Leitura de notÃ­cia', NULL),
(169, 'Leitura de charge', NULL),
(170, 'Acento circunflexo', NULL),
(171, 'Leitura de carta do leitor', NULL),
(172, 'PontuaÃ§Ã£o: exclamaÃ§Ã£o e reticÃªncias', NULL),
(173, 'NotÃ­cias: fato central Ã— subtemas', NULL),
(174, 'Classe gramatical: substantivos', NULL),
(175, 'Classe gramatical: adjetivos', NULL),
(176, 'Ortografia: sÃ­laba tÃ´nica e acento grÃ¡fico', NULL),
(177, 'Ortografia: X e CH', NULL),
(178, 'PontuaÃ§Ã£o', NULL),
(179, 'Ortografia: uso da cedilha', NULL),
(180, 'TerminaÃ§Ã£o -gem', NULL),
(181, 'Palavras "mau" e "mal"', NULL),
(182, 'AcentuaÃ§Ã£o em palavras oxÃ­tonas, proparoxÃ­tonas e paroxÃ­tonas', NULL),
(183, 'O sentido de sufixos', NULL),
(184, 'Leitura de poema', NULL),
(185, 'Leitura de conto', NULL),
(186, 'Leitura de lenda', NULL),
(187, 'Leitura de trecho de romance infantojuvenil', NULL),
(188, 'Leitura de crÃ´nica literÃ¡ria', NULL),
(189, 'ConcordÃ¢ncia nominal', NULL),
(190, 'Classe gramatical: verbos', NULL),
(191, 'ConcordÃ¢ncia verbal (sujeito simples)', NULL),
(192, 'SinÃ´nimos e antÃ´nimos', NULL),
(193, 'O sentido de prefixos', NULL),
(194, 'Leitura de carta de reclamaÃ§Ã£o', NULL),
(195, 'Modos verbais: subjuntivo. Tempos e modos verbais', NULL),
(196, 'Sons da letra S. Polissemia. Uso da vÃ­rgula em vocativo. RevisÃ£o: artigos definidos e indefinidos', NULL),
(197, 'Leitura e compreensÃ£o de poemas', NULL),
(198, 'ComparaÃ§Ã£o de notÃ­cias', NULL),
(199, 'Fato Ã— opiniÃ£o em textos jornalÃ­sticos', NULL),
(200, 'Leitura de anÃºncio publicitÃ¡rio', NULL);
