INSERT INTO curriculum_contents (id, descricao, unidade_tematica) VALUES
(401, 'Modalizadores discursivos. Tipos de modalizadores. Análise de modalizadores em diferentes textos', NULL),
(402, 'Leitura e análise de conto. Classes de palavras (revisão)', NULL),
(403, 'Leitura de e análise de artigo de opinião. Conectores sequenciais e referenciais', NULL),
(404, 'Gênero charge: características', NULL),
(405, 'Leitura e interpretação', NULL),
(406, 'Linguagem verbal, não verbal e mista', NULL),
(407, 'Leitura e análise de resultados de pesquisa', NULL),
(408, 'Curadoria de textos de científicos', NULL),
(409, 'Artigo científico como fonte de pesquisa', NULL),
(410, 'Textos científicos e sua função social', NULL),
(411, 'Gênero anúncio publicitário', NULL),
(412, 'Elementos de persuasão', NULL),
(413, 'Modo imperativo do verbo', NULL),
(414, 'Gênero anúncio publicitário e slogan', NULL),
(415, 'Tipo textual injuntivo', NULL),
(416, 'Função apelativa ou conativa da linguagem', NULL),
(417, 'Linguagem verbal e não verbal', NULL),
(418, 'Gênero conto. Foco narrativo', NULL),
(419, 'Gênero literário conto. Elementos da narrativa', NULL),
(420, 'Leitura e análise de contos. Reconstrução das condições de produção, circulação e recepção de textos artístico-literários no Brasil. José de Alencar e sua relevância na literatura brasileira. Literatura indianista', NULL),
(421, 'Literatura comparada. Análise de texto indianista do século XIX e literatura indígena contemporânea', NULL),
(422, 'Planejamento de texto de divulgação científica', NULL),
(423, 'Banner de divulgação científica', NULL),
(424, 'Apresentação de texto de divulgação científica: exposição e discussão', NULL),
(425, 'Autoavaliação de apresentação', NULL),
(426, 'Tese, argumentos, refutação', NULL),
(427, 'Pré-Modernismo. Euclides da Cunha. Lima Barreto. Augusto dos Anjos', NULL),
(428, 'A poética de Oswald de Andrade. Revistas modernistas brasileiras. Ortografia', NULL),
(429, 'Leitura de poemas. Comparação de literaturas (portuguesa, africana, brasileira, indígena, latino-americana etc.). Contexto de produção de texto literário', NULL),
(430, 'Leitura do conto "Pai contra mãe", de Machado de Assis. Compreensão do conto. Análise do contexto de produção', NULL),
(431, 'Retomada de conto. Análise de contexto de produção. Figura de linguagem: personificação', NULL),
(432, 'Leitura de conto de Guimarães Rosa. Compreensão do conto. Análise de efeitos de sentido de trechos específicos', NULL),
(433, 'Efeitos de sentido do conto. Análise de contexto de produção. Variação linguística', NULL),
(434, 'Leitura de conto. Compreensão do conto. Análise de efeitos de sentido de trechos específicos', NULL),
(435, 'Leitura e compreensão do conto. Análise dos efeitos de sentido do conto. Análise de contexto de produção', NULL),
(436, 'Conceito de manifesto e antropofagia. Manifesto antropófago', NULL),
(437, 'Semana de Arte Moderna. Poética de Manuel Bandeira', NULL),
(438, 'Primeira geração modernista. Poética de Mário de Andrade', NULL),
(439, 'Primeira geração modernista. Poética de Oswald de Andrade', NULL),
(440, 'Segunda geração modernista e poesia dos anos 1930. Poética de Carlos Drummond de Andrade', NULL),
(441, 'Segunda geração modernista e poesia dos anos 1930. Poética de Murilo Mendes', NULL),
(442, 'A segunda geração modernista: prosa regionalista. Prosa de Rachel de Queiroz', NULL),
(443, 'A segunda geração modernista: prosa regionalista. Prosa de Graciliano Ramos', NULL),
(444, 'A segunda geração modernista: prosa regionalista. Prosa de Jorge Amado', NULL),
(445, 'Leitura e análise de crônica', NULL),
(446, 'Artigo de opinião: características', NULL),
(447, 'Leitura e compreensão de artigo de opinião', NULL),
(448, 'Comparação de dados e informações em textos de divulgação científica opinativos', NULL),
(449, 'Identificação de posicionamento crítico', NULL),
(450, 'Averiguação de fidedignidade de informações', NULL),
(451, 'Editorial. Reflexão crítica sobre função social e intencionalidade de textos', NULL),
(452, 'Formas contemporâneas de publicidade. Reflexão crítica sobre função social e intencionalidade de textos', NULL),
(453, 'Leitura de notícia. Visão de mundo no texto. Identificação e inferência de motivações e/ou finalidades do texto/autor', NULL),
(454, 'Leitura de reportagem. Vozes no texto. Identificação e inferência de motivações e/ou finalidades do texto/autor. Regência verbal e nominal', NULL),
(455, 'Leitura e análise de editorial', NULL),
(456, 'Orações subordinadas adjetivas; Modalização textual', NULL),
(457, 'Modalização textual; Orações subordinadas adverbiais', NULL),
(458, 'Orações coordenadas sindéticas aditivas, adversativas, alternativas, conclusivas, explicativas', NULL),
(459, 'Paralelismo sintático', NULL),
(460, 'Sistematização de diferenças marcantes entre romances românticos e realistas, com base em trechos de livros. Figuras de linguagem: metonímia e sinestesia', NULL),
(461, 'O gênero notícia: estrutura e características. Sinais de pontuação', NULL),
(462, 'Operadores lógico-discursivos', NULL),
(463, 'Ordem direta e inversões', NULL),
(464, 'Conjunções e outros elementos coesivos', NULL),
(465, 'Gênero textual romance. Romantismo. Obras abordadas: Iracema e Senhora, ambas de José de Alencar', NULL),
(466, 'Gênero textual romance. Realismo. Obra abordada: Dom Casmurro, de Machado de Assis', NULL),
(467, 'Sistematização de diferenças marcantes entre romances românticos e realistas, com base em trechos de livros', NULL),
(468, 'Definições e características das vanguardas europeias', NULL),
(469, 'Leitura e análise de crônica. Intertextualidade. Polissemia', NULL),
(470, 'Leitura e compreensão do Estatuto da Pessoa Idosa (texto normativo)', NULL),
(471, 'Entrevista oral', NULL),
(472, 'Marcas de oralidade', NULL),
(473, 'Variação linguística', NULL),
(474, 'Marcas de oralidade em textos transcritos', NULL),
(475, 'Tipos de transcrição', NULL),
(476, 'Definição de esporte de invasão. História do handebol. Regras do handebol. Movimentos/fundamentos. Posições e sistemas táticos', NULL),
(477, 'Jogo pré-desportivo do handebol: Queimada', NULL),
(478, 'Jogo pré-desportivo do handebol: Resgate', NULL),
(479, 'Fundamentos do handebol através de um circuito de estações; cada uma referente a um ou mais fundamentos do handebol: empunhadura, recepção, passe, finta, drible e arremesso', NULL),
(480, 'Exercícios em duplas, trios e grupos, se utilizando dos fundamentos do handebol', NULL),
(481, 'Jogo de handebol com equipes femininas e equipes masculinas', NULL),
(482, 'Jogo de handebol com equipes mistas', NULL),
(483, 'Esporte de marca. Atletismo. Provas do atletismo. Esportes e Jogos Paralímpicos. Atletismo paralímpico', NULL),
(484, 'Corrida de velocidade. Corrida de revezamento', NULL),
(485, 'Corrida com barreiras. Corrida com obstáculos', NULL),
(486, 'Salto vertical. Salto horizontal', NULL),
(487, 'Arremesso de peso. Lançamento de disco', NULL),
(488, 'Caminhada de olhos vendados', NULL),
(489, 'com guia', NULL),
(490, 'Corrida de olhos vendados', NULL),
(491, 'Danças: origem; elementos constitutivos; diferentes estilos e evolução em diferentes épocas', NULL),
(492, 'Danças urbanas: o movimento, a música e a dança Hip-hop', NULL),
(493, 'Diferentes sensações através da dança', NULL),
(494, 'Processo criativo: RAP', NULL),
(495, 'Movimentos do Break', NULL),
(496, 'Criação de coreografias de hip-hop em grupos', NULL),
(497, 'Ensaio das coreografias criadas', NULL),
(498, 'Apresentação das coreografias criadas', NULL),
(499, 'Definição de Ginástica de Condicionamento Físico:', NULL),
(500, 'Conceito de Capacidades Físicas', NULL),
(501, 'Conceito de exercícios aeróbios e exercícios anaeróbios', NULL),
(502, 'Benefícios da GCF e prática de alongamento (flexibilidade)', NULL),
(503, 'Circuito de capacidades físicas (flexibilidade, velocidade, agilidade, resistência e força)', NULL),
(504, 'Estafetas de capacidades físicas (velocidade e agilidade)', NULL),
(505, 'Exercícios aeróbios (caminhar, correr e pedalar)', NULL),
(506, 'Exercícios anaeróbios (membros superiores)', NULL),
(507, 'Exercícios anaeróbios (membros inferiores)', NULL),
(508, 'Lutas do Brasil', NULL),
(509, 'Conceitos', NULL),
(510, 'Capoeira Regional × Capoeira Angola', NULL),
(511, 'Golpes da capoeira', NULL),
(512, 'A música, os instrumentos e o ritmo da capoeira', NULL),
(513, 'A ginga como posição base da capoeira', NULL),
(514, 'Movimentos básicos a partir da ginga: Meia-lua de frente;Queixada; Armada', NULL),
(515, 'Outros movimentos da capoeira: Martelo, Bênção, Aú, Cocorinha etc', NULL),
(516, 'Atividades lúdicas se utilizando de movimentos da capoeira, em roda', NULL),
(517, 'Roda de capoeira com os golpes aprendidos', NULL),
(518, 'Definição de Esporte de precisão', NULL),
(519, 'O boliche como esporte de precisão', NULL),
(520, 'A bocha como esporte de precisão', NULL),
(521, 'A bocha paralímpica', NULL),
(522, 'Práticas alternativas de precisão', NULL),
(523, 'Confecção de materiais para jogar boliche e bocha nas aulas de Educação Física', NULL),
(524, 'Jogo de boliche com os materiais confeccionados', NULL),
(525, 'Jogo de bocha com os materiais confeccionados', NULL),
(526, 'Jogo de bocha no contexto paralímpico', NULL),
(527, 'Opção de brincadeiras e jogos pré-desportivos com materiais recicláveis/ adaptados/ alternativos', NULL),
(528, 'O movimento Hip Hop: Street Dance', NULL),
(529, 'Os quatro estilos do Street Dance: Breaking, Locking, Popping e Freestyle', NULL),
(530, 'Passos básicos do breaking', NULL),
(531, 'Passos básicos do locking', NULL),
(532, 'Passos básicos do popping', NULL),
(533, 'Passos básicos do freestyle', NULL),
(534, 'Criação e ensaio de coreografias de street dance, em grupos', NULL),
(535, 'Ginástica de condicionamento físico', NULL),
(536, 'Capacidades físicas em ação', NULL),
(537, 'Benefícios do exercício regular', NULL),
(538, 'Criação de exercícios em grupos, se utilizando da ginástica de condicionamento físico', NULL),
(539, 'Desafios que se utilizam de diferentes capacidades físicas', NULL),
(540, 'Exploração das capacidades físicas por meio de exercícios em formato de circuito', NULL),
(541, 'Benefícios físicos: melhora da força, resistência, postura e saúde cardiovascular./Benefícios mentais: bem', NULL),
(542, 'estar, redução do estresse, aumento da concentração./Benefícios sociais: cooperação, respeito às regras, convivência e trabalho em equipe', NULL),
(543, 'Criação, em grupos, de programas de exercícios físicos', NULL),
(544, 'Apresentação, em grupos, dos programas de exercícios físicos criados', NULL),
(545, 'Definição de esporte de rede/ parede', NULL),
(546, 'História e características do voleibol', NULL),
(547, 'Fundamentos e regras do voleibol', NULL),
(548, 'Posicionamento e Rodízio', NULL),
(549, 'Esporte Paralímpico; vôlei sentado', NULL),
(550, 'Jogo pré-desportivo do voleibol: Volençol', NULL),
(551, 'Jogo pré-desportivo do voleibol: Rede Humana', NULL),
(552, 'Jogo pré-desportivo do voleibol: Câmbio', NULL),
(553, 'Fundamentos do voleibol através de um circuito de estações; cada uma referente a um ou mais fundamentos do voleibol: saque por baixo, toque, machete etc', NULL),
(554, 'Exercícios em duplas, trios e grupos, se utilizando dos fundamentos do voleibol', NULL),
(555, 'Jogo de voleibol com 4 equipes praticando ao mesmo tempo (meia quadra)', NULL),
(556, 'Jogo de voleibol com rodízio 6x0', NULL),
(557, 'Prática e jogo de voleibol com regras, fundamentos e rodízio 6x0', NULL),
(558, 'Esporte Paralímpico: Vôlei sentado', NULL),
(559, 'Definição de esporte de campo e taco', NULL),
(560, 'Jogo de taco', NULL),
(561, 'Jogo base 4', NULL),
(562, 'Beisebol', NULL),
(563, 'Jogo pré-desportivo do Beisebol: Taco', NULL),
(564, 'Jogo pré-desportivo do Beisebol: Base 4', NULL),
(565, 'Jogo de Beisebol adaptado para o ambiente escolar', NULL),
(566, 'Conceito de lutas do mundo', NULL),
(567, 'Origem do Judô, Jiu-Jitsu e do Caratê', NULL),
(568, 'Características específicas do Judô, Jiu-Jitsu e Caratê', NULL),
(569, 'Saudações e Ukemis do Judô', NULL),
(570, 'Técnicas de perna, braço e quadril no Judô', NULL),
(571, 'Vivências do Judô', NULL),
(572, 'simulação de luta', NULL),
(573, 'Jogos de oposição no Jiu-Jitsu', NULL),
(574, 'Técnicas do Jiu-Jitsu', NULL),
(575, 'Saudações e bases no caratê', NULL),
(576, 'Chutes no caratê', NULL),
(577, 'Socos e defesas no caratê', NULL),
(578, 'Katas no caratê', NULL),
(579, 'Materiais Digitais -Origem e evolução do Judô para cegos', NULL),
(580, 'Mudanças e adequações às regras base do judô para sua versão paralímpica', NULL),
(581, 'Ukemis e movimentações', NULL),
(582, 'Técnicas de perna, braço e quadril no Judô para cegos', NULL),
(583, 'Vivências do Judô para cegos', NULL),
(584, 'Retomada da definição de esporte de invasão', NULL),
(585, 'História do futsal', NULL),
(586, 'Regras e fundamentos do futsal', NULL),
(587, 'Esporte Paralímpico: Futebol de cegos', NULL),
(588, 'Fundamentos do futsal através de estafetas; domínio, condução, drible, passe de chapa, chute ao gol etc', NULL),
(589, 'Exercícios em duplas, trios e grupos, se utilizando dos fundamentos do futsal', NULL),
(590, 'Jogo pré-desportivo do futsal: Futsal de duplas', NULL),
(591, 'Jogo de Futsal com regras e fundamentos', NULL),
(592, 'equipes mistas', NULL),
(593, 'Jogo de futsal com regras e fundamentos', NULL),
(594, 'equipes femininas e equipes masculinas', NULL),
(595, 'História do basquetebol', NULL),
(596, 'Regras e fundamentos do basquetebol', NULL),
(597, 'Esporte Paralímpico: basquete em cadeira de rodas', NULL),
(598, 'Fundamentos do basquete através de estafetas; drible, passe, arremesso, rebote, defesa, bloqueio etc', NULL),
(599, 'Exercícios em duplas, trios e grupos, se utilizando dos fundamentos do basquete', NULL),
(600, 'Jogo pré-desportivo do basquete: Torrebol', NULL);
