INSERT INTO curriculum_contents (id, descricao, unidade_tematica) VALUES
(1, 'Danças Populares Brasileiras', NULL),
(2, 'Origens das Danças', NULL),
(3, 'Variação de Tempo', NULL),
(4, 'Expressão Corporal', NULL),
(5, 'Elementos da Dança', NULL),
(6, 'Movimentos do Frevo', NULL),
(7, 'Uso do Espaço', NULL),
(8, 'Fatores do Movimento', NULL),
(9, 'Jongo', NULL),
(10, 'Frevo', NULL),
(11, 'Siriri', NULL),
(12, 'Carimbó', NULL),
(13, 'Criações Coreográficas', NULL),
(14, 'Expressão na Dança', NULL),
(15, 'Processos Criativos', NULL),
(16, 'Música Brasileira', NULL),
(17, 'Produção, Repertório e Circulação Musical', NULL),
(18, 'Função Social da Música', NULL),
(19, 'Repertório Musical Indígena e Afro-Brasileiro', NULL),
(20, 'Paisagem Sonora', NULL),
(21, 'Registro Musical', NULL),
(22, 'Notação Não Convencional', NULL),
(23, 'Composição e Improvisação Musical', NULL),
(24, 'Percussão Corporal', NULL),
(25, 'Instrumentos e Notação Não Convencionais', NULL),
(26, 'Instrumentos e Timbres', NULL),
(27, 'Improvisação Musical', NULL),
(28, 'Composição, Colaboração e Improvisação Musical', NULL),
(29, 'Produção e Registro Musical', NULL),
(30, 'Introdução à Dança', NULL),
(31, 'Dança: Diversidade Cultural', NULL),
(32, 'História da Dança', NULL),
(33, 'Dança Clássica', NULL),
(34, 'Dança Moderna', NULL),
(35, 'Fatores de Movimento', NULL),
(36, 'Qualidades dos Movimentos', NULL),
(37, 'Sequências Coreográficas', NULL),
(38, 'Ações de Esforço', NULL),
(39, 'Improvisação na Dança', NULL),
(40, 'Música Clássica', NULL),
(41, 'Música Instrumental', NULL),
(42, 'Música Orquestral', NULL),
(43, 'Canto Coral', NULL),
(44, 'Estrutura do Coro', NULL),
(45, 'Produção Musical', NULL),
(46, 'Estrutura da Orquestra', NULL),
(47, 'Técnicas de Execução', NULL),
(48, 'Instrumentos Convencionais', NULL),
(49, 'Timbres e Características', NULL),
(50, 'Notação Convencional', NULL),
(51, 'Composição Musical', NULL),
(52, 'Técnicas de Execução Musical', NULL),
(53, 'Performance Musical', NULL),
(54, 'Instrumentos Musicais', NULL),
(55, 'Origens da Dança', NULL),
(56, 'Dança Coletiva', NULL),
(57, 'Improvisação em Dança', NULL),
(58, 'Ações Corporais Dançadas', NULL),
(59, 'Personagens na Dança Popular', NULL),
(60, 'Improvisação Coletiva', NULL),
(61, 'Gravidade e Peso', NULL),
(62, 'Análise do Movimento', NULL),
(63, 'Partitura Corporal', NULL),
(64, 'Composição Coreográfica', NULL),
(65, 'Apreciação Musical', NULL),
(66, 'História da Música', NULL),
(67, 'Música Tradicional Africana', NULL),
(68, 'Timbre', NULL),
(69, 'Música Indígena', NULL),
(70, 'Música Contemporânea', NULL),
(71, 'Música Afro-Brasileira', NULL),
(72, 'Elementos da Música', NULL),
(73, 'Jogos Rítmicos', NULL),
(74, 'Práticas de Criação', NULL),
(75, 'Movimento Cotidiano', NULL),
(76, 'Jogos e Brincadeiras', NULL),
(77, 'Kinesfera', NULL),
(78, 'Corpo-Híbrido e Corpo-Tela', NULL),
(79, 'Criação Coreográfica', NULL),
(80, 'Dança Contemporânea', NULL),
(81, 'Independência ou Coexistência Estética', NULL),
(82, 'Qualidades do Movimento', NULL),
(83, 'Musicalidade Corporal', NULL),
(84, 'Brincadeiras e Dança', NULL),
(85, 'Corpo Memético e Corpo Midiático', NULL),
(86, 'Corpo e Tecnologia', NULL),
(87, 'Música Popular Brasileira', NULL),
(88, 'Música Popular Estrangeira', NULL),
(89, 'Movimentos Musicais Históricos', NULL),
(90, 'Canção de Protesto', NULL),
(91, 'Expressão, Composição e Apreciação Musical', NULL),
(92, 'Música e Tecnologia', NULL),
(93, 'Elementos de Composição Musical', NULL),
(94, 'Função Social da Arte', NULL),
(95, 'Cultura Contemporânea', NULL),
(96, 'Processo Criativo', NULL),
(97, 'Arte e Mídia', NULL),
(98, 'Análise Crítica', NULL),
(99, 'Criação Artística', NULL),
(100, 'Intervenção Artística', NULL),
(101, 'Manifestação Artística', NULL),
(102, 'Linguagens Artísticas', NULL),
(103, 'Expressão Artística', NULL),
(104, 'Artes do Corpo', NULL),
(105, 'Estereótipos Sociais', NULL),
(106, 'Criação Musical', NULL),
(107, 'Danças Sociais', NULL),
(108, 'Expressão Identitária', NULL),
(109, 'Discurso Crítico', NULL),
(110, 'Crítica de Arte', NULL),
(111, 'Performatividade', NULL),
(112, 'Patrimônio Cultural', NULL),
(113, 'Pesquisa em Arte', NULL),
(114, 'Análise Histórica e Cultural', NULL),
(115, 'Manifesto Artístico', NULL),
(116, 'Estética Relacional', NULL),
(117, 'Processo Colaborativo', NULL),
(118, 'Impacto Cultural', NULL),
(119, 'Processos de Criação', NULL),
(120, 'Movimentos Artísticos', NULL),
(121, 'Compartilhamento de Práticas', NULL),
(122, 'Contexto Histórico e Cultural', NULL),
(123, 'Zeitgeist, “Espírito do Tempo”', NULL),
(124, 'Manifestos Coletivos', NULL),
(125, 'Coletivos Artísticos', NULL),
(126, 'Arte Colaborativa', NULL),
(127, 'Sistema de numeração decimal', NULL),
(128, 'Operações fundamentais com números naturais', NULL),
(129, 'Múltiplos e divisores', NULL),
(130, 'O conceito de fração', NULL),
(131, 'Operações fundamentais com números fracionários', NULL),
(132, 'Polígonos, triângulos e quadriláteros', NULL),
(133, 'Números inteiros', NULL),
(134, 'Operações fundamentais com frações', NULL),
(135, 'Operações com números racionais nas formas fracionária e decimal', NULL),
(136, 'Figuras geométricas planas no plano cartesiano', NULL),
(137, 'Área de figuras geométricas planas', NULL),
(138, 'Operações fundamentais com números racionais', NULL),
(139, 'Potenciação e propriedades da potenciação', NULL),
(140, 'Radiciação e relações entre radiciação e potenciação', NULL),
(141, 'Expressões algébricas e noções de Álgebra', NULL),
(142, 'Equações polinomiais do 1º grau', NULL),
(143, 'Sistemas de equações polinomiais do 1º grau', NULL),
(144, 'Números racionais: Comparação, operações fundamentais e potenciação', NULL),
(145, 'Características dos triângulos e semelhança de triângulos', NULL),
(146, 'Semelhança de triângulos e teorema de Pitágoras', NULL),
(147, 'Números irracionais e dízimas periódicas', NULL),
(148, 'Números reais', NULL),
(149, 'Números racionais', NULL),
(150, 'Teorema de Pitágoras', NULL),
(151, 'Conceito de função', NULL),
(152, 'Relação entre grandezas e equações polinomiais de 1º grau', NULL),
(153, 'Função Afim – Parte 1', NULL),
(154, 'Potenciação e notação científica', NULL),
(155, 'Equações polinomiais do 1º e 2º graus', NULL),
(156, 'Equações exponenciais', NULL),
(157, 'Funções exponenciais', NULL),
(158, 'Logaritmos', NULL),
(159, 'Funções logarítmicas', NULL),
(160, 'Equações polinomiais do 1° e 2° graus', NULL),
(161, 'Sistemas de equações lineares – Parte 1', NULL),
(162, '138 - 173 Sistemas de equações lineares – Parte 2', NULL),
(163, 'Análise combinatória', NULL),
(164, 'Probabilidade – Parte 1', NULL),
(165, 'Probabilidade – Parte 2', NULL),
(166, 'Leitura de post', NULL),
(167, 'Leitura de comentários', NULL),
(168, 'Leitura de notícia', NULL),
(169, 'Leitura de charge', NULL),
(170, 'Acento circunflexo', NULL),
(171, 'Leitura de carta do leitor', NULL),
(172, 'Pontuação: exclamação e reticências', NULL),
(173, 'Notícias: fato central × subtemas', NULL),
(174, 'Classe gramatical: substantivos', NULL),
(175, 'Classe gramatical: adjetivos', NULL),
(176, 'Ortografia: sílaba tônica e acento gráfico', NULL),
(177, 'Ortografia: X e CH', NULL),
(178, 'Pontuação', NULL),
(179, 'Ortografia: uso da cedilha', NULL),
(180, 'Terminação -gem', NULL),
(181, 'Palavras "mau" e "mal"', NULL),
(182, 'Acentuação em palavras oxítonas, proparoxítonas e paroxítonas', NULL),
(183, 'O sentido de sufixos', NULL),
(184, 'Leitura de poema', NULL),
(185, 'Leitura de conto', NULL),
(186, 'Leitura de lenda', NULL),
(187, 'Leitura de trecho de romance infantojuvenil', NULL),
(188, 'Leitura de crônica literária', NULL),
(189, 'Concordância nominal', NULL),
(190, 'Classe gramatical: verbos', NULL),
(191, 'Concordância verbal (sujeito simples)', NULL),
(192, 'Sinônimos e antônimos', NULL),
(193, 'O sentido de prefixos', NULL),
(194, 'Leitura de carta de reclamação', NULL),
(195, 'Modos verbais: subjuntivo. Tempos e modos verbais', NULL),
(196, 'Sons da letra S. Polissemia. Uso da vírgula em vocativo. Revisão: artigos definidos e indefinidos', NULL),
(197, 'Leitura e compreensão de poemas', NULL),
(198, 'Comparação de notícias', NULL),
(199, 'Fato × opinião em textos jornalísticos', NULL),
(200, 'Leitura de anúncio publicitário', NULL);
