INSERT INTO curriculum_contents (id, descricao, unidade_tematica) VALUES
(201, 'Linguagem verbal e nÃ£o verbal em anÃºncios publicitÃ¡rios', NULL),
(202, 'Leitura de anÃºncio publicitÃ¡rio em mÃ­dias digitais', NULL),
(203, 'Leitura de reportagem', NULL),
(204, 'Leitura de fotorreportagem', NULL),
(205, 'CaracterÃ­sticas de fotorreportagens', NULL),
(206, 'Leitura de petiÃ§Ã£o', NULL),
(207, 'Leitura de entrevista', NULL),
(208, 'CoesÃ£o', NULL),
uso de Ã e SS', NULL),
(210, 'Leitura e interpretaÃ§Ã£o de notÃ­cias', NULL),
(211, 'Pronome demonstrativo', NULL),
(212, 'ModalizaÃ§Ã£o discursiva', NULL),
(213, 'Acento diferencial', NULL),
diferentes escolhas editoriais sobre um mesmo fato', NULL),
(215, 'Fato e opiniÃ£o', NULL),
(216, 'Leitura de textos multissemiÃ³ticos', NULL),
(217, 'Leitura de anÃºncio publicitÃ¡rio. Palavras-valise', NULL),
(218, 'Recursos linguÃ­stico-discursivos em folhetos/flyers de anÃºncios publicitÃ¡rios', NULL),
(219, 'Leitura de artigo de divulgaÃ§Ã£o cientÃ­fica. Elementos do artigo de divulgaÃ§Ã£o cientÃ­fica', NULL),
(220, 'ParagrafaÃ§Ã£o', NULL),
(221, 'Tese', NULL),
(222, 'OpiniÃ£o', NULL),
(223, 'EstratÃ©gias argumentativas', NULL),
(224, 'Verbo de aÃ§Ã£o', NULL),
(225, 'Verbo de estado', NULL),
pretÃ©rito. ConjunÃ§Ã£o', NULL),
(227, 'Leitura de romance infantojuvenil. Leitura de conto popular', NULL),
(228, 'Leitura de conto de ficÃ§Ã£o cientÃ­fica. EstratÃ©gias de leitura. FÃ¡bula', NULL),
narrador e personagens', NULL),
(230, 'Verbos de enunciaÃ§Ã£o', NULL),
(231, 'Leitura de parÃ¡bola', NULL),
causa e consequÃªncia', NULL),
(233, 'Leitura de poemas', NULL),
(234, 'Poemas de versos livres Ã forma fixa', NULL),
(235, 'Leitura de conto indÃ­gena', NULL),
(236, 'EstratÃ©gias de leitura', NULL),
(237, 'Mecanismos da narrativa', NULL),
quarta capa', NULL),
(239, 'Programa (de teatro, danÃ§a, exposiÃ§Ãµes etc.)', NULL),
(240, 'Leitura de cartaz de campanha', NULL),
(241, 'ComparaÃ§Ã£o entre peÃ§as publicitÃ¡rias', NULL),
(242, 'EstratÃ©gias de persuasÃ£o com recursos linguÃ­stico-discursivos (jogos de palavras, metÃ¡foras, sentidos figurados etc.)', NULL),
(243, 'Intertextualidade em textos diversos', NULL),
(244, 'Valores culturais em textos literÃ¡rios', NULL),
(245, 'Contos populares', NULL),
(246, 'EstratÃ©gias de leitura de textos literÃ¡rios', NULL),
(247, 'PrÃ¡ticas de leitura de textos literÃ¡rios', NULL),
(248, 'Contos indÃ­genas', NULL),
(249, 'Leitura de piadas e anedotas', NULL),
(250, 'Leitura de contos de humor', NULL),
(251, 'Leitura de parÃ³dia e sÃ¡tira', NULL),
(252, 'Leitura de mito', NULL),
(253, 'CoesÃ£o e coerÃªncia em textos narrativos', NULL),
(254, 'Tessitura textual', NULL),
(255, 'Leitura de crÃ´nica', NULL),
(256, 'Relato de viagem', NULL),
(257, 'Adjuntos adverbiais', NULL),
(258, 'Leitura de notÃ­cia impressa e digital', NULL),
(259, 'Leitura e anÃ¡lise crÃ­tica de artigo de opiniÃ£o', NULL),
(260, 'Leitura de trecho de romance', NULL),
(261, 'CaracterÃ­sticas de texto de divulgaÃ§Ã£o cientÃ­fica', NULL),
parÃªnteses e aspas', NULL),
(263, 'Leitura de memÃ³rias', NULL),
(264, 'Leitura de biografia', NULL),
(265, 'Leitura de autobiografia', NULL),
(266, 'Leitura de diÃ¡rio pessoal', NULL),
(267, 'CompreensÃ£o de efeitos de sentido', NULL),
(268, 'Verbos', NULL),
(269, 'Estudo de tempos verbais', NULL),
(270, 'Presente histÃ³rico', NULL),
(271, 'PretÃ©rito imperfeito do indicativo', NULL),
ponto-final', NULL),
sujeito e predicado', NULL),
(274, 'ConcordÃ¢ncia verbal e nominal', NULL),
(275, 'Observar uso de hÃ­fen no texto e conhecer critÃ©rios de hifenizaÃ§Ã£o', NULL),
(276, 'Modos indicativo e subjuntivo', NULL),
acentuaÃ§Ã£o', NULL),
(278, 'Transitividade verbal', NULL),
(279, 'Tempos e modos verbais', NULL),
(280, 'Sentido real e figurado de palavras', NULL),
(281, 'Artigos definidos e indefinidos', NULL),
(282, 'Verbo "haver" como auxiliar', NULL),
(283, 'PretÃ©rito perfeito e imperfeito do indicativo', NULL),
fato central', NULL),
fato central', NULL),
ideia central', NULL),
relaÃ§Ã£o entre parÃ¡grafos', NULL),
(288, 'ComparaÃ§Ã£o entre editorial e artigo de opiniÃ£o. Confiabilidade em textos jornalÃ­sticos', NULL),
(289, 'ArgumentaÃ§Ã£o', NULL),
oxÃ­tonas, paroxÃ­tonas e proparoxÃ­tonas', NULL),
(291, 'Leitura de tirinha', NULL),
(292, 'Leitura de cartaz instrucional (primeiros socorros)', NULL),
(293, 'Cartaz sobre direitos e deveres do estudante', NULL),
(294, 'Leitura de cartaz de campanha de saÃºde', NULL),
(295, 'EstratÃ©gias de persuasÃ£o', NULL),
(296, 'CaracterÃ­sticas de anÃºncios publicitÃ¡rios', NULL),
metÃ¡fora', NULL),
modo imperativo', NULL),
(299, 'Leitura de anÃºncio publicitÃ¡rio digital', NULL),
(300, 'Ortografia', NULL),
(301, 'Ficha catalogrÃ¡fica', NULL),
(302, 'Resumo', NULL),
(303, 'Leitura de esquema(s)', NULL),
(304, 'Leitura de relatÃ³rio(s)', NULL),
(305, 'Leitura de petiÃ§Ã£o online', NULL),
(306, 'CoesÃ£o sequencial', NULL),
(307, 'Modalizadores argumentativos', NULL),
(308, 'Leitura de carta aberta', NULL),
(309, 'Ler memes e gifs, analisando efeitos de sentido gerados pelo uso de linguagem verbal, nÃ£o verbal e mista', NULL),
(310, 'Refletir e posicionar-se de forma crÃ­tica e Ã©tica sobre opiniÃµes e visÃµes de mundo expressas por esses gÃªneros da cultura digital', NULL),
(311, 'Posts e comentÃ¡rios', NULL),
(312, 'AdequaÃ§Ã£o do registro escrito', NULL),
(313, 'A Idade MÃ©dia em Portugal e a influÃªncia da cultura galego-portuguesa. FlexÃ£o verbal (tempos e modos verbais)', NULL),
(314, 'As origens do Trovadorismo no sÃ©culo XII. A primeira Ã©poca medieval. ConjugaÃ§Ãµes verbais regulares e irregulares', NULL),
amor, amigo, escÃ¡rnio e maldizer', NULL),
fragmento de O Auto da Barca do Inferno, de Gil Vicente', NULL),
(317, 'Contexto histÃ³rico do Classicismo. Fragmento da obra Ã©pica Os LusÃ­adas, de CamÃµes. Vida e obra de LuÃ­s Vaz de CamÃµes e sua influÃªncia', NULL),
(318, 'Leitura de poemas. ComparaÃ§Ã£o entre caracterÃ­sticas de obras clÃ¡ssicas e obras marginais. Conceito de literatura marginal. Contracultura', NULL),
(319, 'Leitura e compreensÃ£o de poema', NULL),
(320, 'Figuras de linguagem (comparaÃ§Ã£o, metÃ¡fora, antÃ­tese e eufemismo)', NULL),
(321, 'Leitura e compreensÃ£o de biografia. Leitura e compreensÃ£o de poema', NULL),
(322, 'Leitura e compreensÃ£o de poemas. Figuras de linguagem (hipÃ©rbole, paradoxo e personificaÃ§Ã£o). Sonoridade em textos poÃ©ticos (rima, aliteraÃ§Ã£o, assonÃ¢ncia e eufonia)', NULL),
(323, 'Verbos. FlexÃ£o verbal', NULL),
(324, 'Elementos mÃ³rficos na formaÃ§Ã£o de palavras. FormaÃ§Ã£o de palavras (radicais, prefixos, sufixos)', NULL),
(325, 'Tipos de sujeito (simples, composto, oculto, indeterminado)', NULL),
slam. Linguagem informal e variedades linguÃ­sticas', NULL),
(327, 'A norma-padrÃ£o e a variaÃ§Ã£o linguÃ­stica. Ortografia e a contracultura na âgeraÃ§Ã£o mimeÃ³grafoâ. A poesia perifÃ©rica e a construÃ§Ã£o ortogrÃ¡fica', NULL),
(328, 'AdvÃ©rbios e locuÃ§Ãµes adverbiais', NULL),
(329, 'RegÃªncia verbal e nominal', NULL),
estrutura das palavras (radical, desinÃªncia, vogal temÃ¡tica, tema e afixos)', NULL),
derivaÃ§Ã£o', NULL),
(332, 'ConcordÃ¢ncia verbal com sujeito composto', NULL),
(333, 'RegÃªncia nominal e verbal', NULL),
(334, 'PerÃ­odo composto por coordenaÃ§Ã£o e subordinaÃ§Ã£o', NULL),
slam', NULL),
(336, 'VersificaÃ§Ã£o', NULL),
(337, 'Intertextualidade. ParÃ¡frase e parÃ³dia', NULL),
(338, 'DenotaÃ§Ã£o e conotaÃ§Ã£o em textos literÃ¡rios. Efeitos de sentido', NULL),
charges e cartuns', NULL),
(340, 'Neologismo. Estrangeirismo', NULL),
(341, 'AcentuaÃ§Ã£o de palavras', NULL),
(342, 'Elementos coesivos', NULL),
(343, 'CompreensÃ£o de texto', NULL),
(344, 'SensibilizaÃ§Ã£o para sentidos literais e nÃ£o literais', NULL),
(345, 'Literatura perifÃ©rica', NULL),
(346, 'Fatos e opiniÃµes no texto jornalÃ­stico. Pronomes demonstrativos', NULL),
(347, 'AnÃ¡lise de manchetes de jornais. Presente histÃ³rico', NULL),
(348, 'FotonotÃ­cias. Fotorreportagens. FotodenÃºncias', NULL),
(349, 'Leitura e anÃ¡lise de infogrÃ¡ficos', NULL),
(350, 'Leitura de artigo de opiniÃ£o', NULL),
(351, 'Resenha crÃ­tica', NULL),
(352, 'ReflexÃ£o crÃ­tica sobre funÃ§Ã£o social e intencionalidade de textos', NULL),
(353, 'Leitura de texto de opiniÃ£o. Movimentos argumentativos (sustentaÃ§Ã£o e negociaÃ§Ã£o)', NULL),
(354, 'Leitura de textos publicitÃ¡rios. AnÃ¡lise de efeitos de sentido (verbais e nÃ£o verbais). FunÃ§Ã£o social e estrutura do gÃªnero anÃºncio publicitÃ¡rio', NULL),
palavras que geram dÃºvida', NULL),
(356, 'GÃªnero debate', NULL),
Parte 1 â preparaÃ§Ã£o para o evento', NULL),
Parte 2 â apresentaÃ§Ã£o do evento a partir da discussÃ£o de tÃ³picos polÃªmicos', NULL),
Parte 3 â avaliaÃ§Ã£o dos grupos do debate (planejamento, produÃ§Ã£o, revisÃ£o dos textos e apresentaÃ§Ã£o oral)', NULL),
(360, 'PerÃ­odo composto por coordenaÃ§Ã£o', NULL),
(361, 'Texto literÃ¡rio e nÃ£o literÃ¡rio (definiÃ§Ã£o)', NULL),
(362, 'Contexto de produÃ§Ã£o e circulaÃ§Ã£o de textos literÃ¡rios (Barroco, Arcadismo e PrÃ©- Romantismo)', NULL),
(363, 'Intertextualidade e interdiscursividade', NULL),
(364, 'ConstruÃ§Ã£o de sentido a partir da relaÃ§Ã£o entre textos', NULL),
(365, 'IntroduÃ§Ã£o ao Romantismo', NULL),
(366, 'Romantismo em Portugal', NULL),
(367, 'Estrutura da oraÃ§Ã£o (sujeito, predicado)', NULL),
(368, 'Estrutura da oraÃ§Ã£o (sujeito, predicado, complementos verbais e nominais)', NULL),
(369, 'Emprego da conjunÃ§Ã£o adversativa âmasâ e do advÃ©rbio de intensidade comparativa âmaisâ', NULL),
(370, 'Conectivos â conjunÃ§Ãµes e locuÃ§Ãµes conjuntivas', NULL),
(371, 'Uso de pronomes', NULL),
(372, 'Slogan. PontuaÃ§Ã£o', NULL),
ordem dos constituintes, coordenaÃ§Ã£o, subordinaÃ§Ã£o, concordÃ¢ncia e regÃªncia. Efeitos de sentido gerados pelas escolhas linguÃ­sticas e estruturais. ContextualizaÃ§Ã£o das escolhas linguÃ­sticas conforme Ã©poca, autor e situaÃ§Ã£o comunicativa', NULL),
(374, 'AcentuaÃ§Ã£o', NULL),
(375, 'Poema â marcas do gÃªnero. Contexto de produÃ§Ã£o de texto literÃ¡rio', NULL),
(376, 'GregÃ³rio de Matos. InformaÃ§Ãµes sobre o poeta e seu tempo. A poesia satÃ­rica. AnÃ¡lise de poema', NULL),
perÃ­odo e caracterÃ­sticas, principais autores e obras', NULL),
perÃ­odos e caracterÃ­sticas, principais autores e obras', NULL),
perÃ­odo e caracterÃ­sticas, principais autores e obras. Emprego do verbo "haver"', NULL),
(380, 'Neoclassicismo e PrÃ©-Romantismo portuguÃªs', NULL),
(381, 'O abolicionismo na literatura romÃ¢ntica brasileira. Maria Firmina dos Reis e o Romantismo no Brasil. ConstruÃ§Ã£o frasal e recursos linguÃ­sticos', NULL),
(382, 'Mulheres na literatura romÃ¢ntica no Brasil. Narcisa AmÃ¡lia e o Romantismo no Brasil. O abolicionismo na literatura romÃ¢ntica brasileira', NULL),
(383, 'Textos multimodais diversos', NULL),
(384, 'Artigo de opiniÃ£o', NULL),
(385, 'Leitura de cartaz', NULL),
(386, 'Leitura de texto de divulgaÃ§Ã£o cientÃ­fica', NULL),
(387, 'IdentificaÃ§Ã£o e inferÃªncia de motivaÃ§Ãµes e/ou finalidades do texto/autor', NULL),
estrutura e caracterÃ­sticas', NULL),
(389, 'ProgressÃ£o temÃ¡tica', NULL),
(390, 'Pesquisa cientÃ­fica', NULL),
(391, 'Curadoria de informaÃ§Ãµes', NULL),
(392, 'ReferÃªncias bibliogrÃ¡ficas e normas de referÃªncia', NULL),
(393, 'CitaÃ§Ã£o direta e indireta', NULL),
(394, 'GÃªnero resumo', NULL),
(395, 'CitaÃ§Ã£o direta e parÃ¡frase', NULL),
(396, 'AnÃ¡lise de resenha crÃ­tica de livro', NULL),
(397, 'Adjetivos e oraÃ§Ãµes adjetivas', NULL),
(398, 'Escrita e compartilhamento de resenhas', NULL),
(399, 'O gÃªnero sinopse', NULL),
(400, 'Leitura de verbete enciclopÃ©dico. CompreensÃ£o do tipo textual expositivo. DenotaÃ§Ã£o e conotaÃ§Ã£o', NULL);
