INSERT INTO curriculum_contents (id, descricao, unidade_tematica) VALUES
(801, 'USMCA, CAN, ALADI e MERCOSUL', NULL),
(802, 'Setores da economia', NULL),
(803, 'DescentralizaÃ§Ã£o e RecentralizaÃ§Ã£o econÃ´mica', NULL),
(804, 'Investimentos dos Estados Unidos no mundo', NULL),
(805, 'InfluÃªncia do capital estadunidense no Brasil', NULL),
(806, 'Tecnologias e os setores da economia', NULL),
(807, 'ProfissÃµes do futuro', NULL),
(808, 'Oportunidades e desafios', NULL),
(809, 'Grandes NavegaÃ§Ãµes e expansÃ£o marÃ­tima', NULL),
(810, 'InÃ­cio da globalizaÃ§Ã£o e hegemonia europeia no controle territorial', NULL),
(811, 'EvoluÃ§Ã£o dos mapas e representaÃ§Ãµes do espaÃ§o', NULL),
(812, 'VisÃµes eurocÃªntricas, divisÃ£o simbÃ³lica do mundo e cartografia como instrumento de poder', NULL),
(813, 'OrganizaÃ§Ã£o do sistema colonial e pacto colonial', NULL),
(814, 'ConsequÃªncias atuais da colonizaÃ§Ã£o nas fronteiras, culturas e relaÃ§Ãµes de poder', NULL),
(815, 'ParticipaÃ§Ã£o de paÃ­ses e colÃ´nias na 1Âª e 2Âª Guerras Mundiais.', NULL),
(816, 'MudanÃ§as de fronteiras e divisÃµes territoriais apÃ³s os conflitos.', NULL),
(817, 'ConsequÃªncias sociais, polÃ­ticas e culturais para colonizadores e colonizados.', NULL),
(818, 'CaracterÃ­sticas gerais da Guerra Fria e disputas geopolÃ­ticas em diferentes Ã¡reas.', NULL),
(819, 'Corrida espacial e tecnolÃ³gica e o Muro de Berlim como sÃ­mbolos da divisÃ£o global.', NULL),
(820, 'Disputas ideolÃ³gicas e tecnolÃ³gicas durante a Guerra Fria.', NULL),
(821, 'DivisÃ£o do mundo em blocos e consequÃªncias nas relaÃ§Ãµes globais e nas desigualdades sociopolÃ­ticas.', NULL),
(822, 'Conceito de globalizaÃ§Ã£o e suas relaÃ§Ãµes com a Geografia.', NULL),
(823, 'CaracterÃ­sticas da primeira fase da globalizaÃ§Ã£o (sÃ©culos XV a XVII).', NULL),
(824, 'Segunda fase da globalizaÃ§Ã£o e a RevoluÃ§Ã£o Industrial.', NULL),
(825, 'Ãxodo rural, urbanizaÃ§Ã£o e mudanÃ§as nos modos de vida, consumo e trabalho.', NULL),
marcos e avanÃ§os tecnolÃ³gicos.', NULL),
(827, 'ExpansÃ£o das comunicaÃ§Ãµes e novas formas de consumo, trabalho e informaÃ§Ã£o.', NULL),
(828, 'Quarta fase da globalizaÃ§Ã£o e tecnologias emergentes.', NULL),
(829, 'Desigualdades, tensÃµes e novas dinÃ¢micas no mundo atual.', NULL),
(830, 'Tipos de moeda, evoluÃ§Ã£o e circulaÃ§Ã£o no sistema econÃ´mico global.', NULL),
(831, 'Moedas sociais, criptomoedas e alternativas locais ao sistema monetÃ¡rio tradicional.', NULL),
(832, 'LocalizaÃ§Ã£o e limites do Oriente MÃ©dio.', NULL),
(833, 'Climas, relevos e recursos naturais predominantes.', NULL),
(834, 'Diversidade cultural e religiosa no Oriente MÃ©dio.', NULL),
(835, 'Principais dinÃ¢micas populacionais da regiÃ£o.', NULL),
(836, 'Conflitos, tensÃµes e disputas na regiÃ£o.', NULL),
(837, 'Principais influÃªncias nos conflitos contemporÃ¢neos do Oriente MÃ©dio.', NULL),
causas, processo e desdobramentos.', NULL),
mudanÃ§as territoriais e conflitos contemporÃ¢neos.', NULL),
(840, 'A influÃªncia polÃ­tica e econÃ´mica da RÃºssia na EurÃ¡sia.', NULL),
causas e consequÃªncias.', NULL),
(842, 'Desenvolvimento econÃ´mico, industrial e tecnolÃ³gico da China nas Ãºltimas dÃ©cadas.', NULL),
(843, 'RelaÃ§Ã£o com Taiwan e impactos polÃ­ticos regionais e globais da China.', NULL),
(844, 'O conflito entre as Coreias e seus desdobramentos.', NULL),
(845, 'RelaÃ§Ãµes polÃ­ticas dos paÃ­ses vizinhos (JapÃ£o e China) com o conflito coreano.', NULL),
(846, 'Processo polÃ­tico, econÃ´mico e populacional da Ãndia atual.', NULL),
(847, 'A questÃ£o da Caxemira e suas implicaÃ§Ãµes territoriais e polÃ­ticas', NULL),
(848, 'Economia global e seu impacto no cotidiano local.', NULL),
(849, 'InfluÃªncia das corporaÃ§Ãµes, instituiÃ§Ãµes internacionais, cultura e identidade na globalizaÃ§Ã£o.', NULL),
(850, 'Principais organizaÃ§Ãµes econÃ´micas e comerciais e sua atuaÃ§Ã£o no cenÃ¡rio mundial.', NULL),
(851, 'DefiniÃ§Ã£o, origem e princÃ­pios bÃ¡sicos dos direitos humanos.', NULL),
(852, 'Destaque para o contexto histÃ³rico do pÃ³s-segunda Guerra Mundial.', NULL),
desafios e exemplos.', NULL),
(854, 'Fundamentos no pÃ³s-guerra.', NULL),
(855, 'Tipos de deslocamentos humanos.', NULL),
(856, 'DiferenÃ§a entre migrantes e refugiados.', NULL),
(857, 'Principais causas dos deslocamentos contemporÃ¢neos.', NULL),
(858, 'Refugiados no Brasil. Causas, rotas e desafios da migraÃ§Ã£o forÃ§ada', NULL),
(859, 'DiferenÃ§as entre Climatologia e Meteorologia.', NULL),
(860, 'Conceitos de Tempo e Clima.', NULL),
(861, 'DivisÃ£o das camadas da atmosfera e suas principais caracterÃ­sticas.', NULL),
(862, 'CirculaÃ§Ã£o geral da atmosfera.', NULL),
(863, 'Elementos e controles climÃ¡ticos.', NULL),
temperatura e precipitaÃ§Ã£o.', NULL),
(865, 'Biomas associados a determinados padrÃµes de climogramas.', NULL),
(866, 'Climogramas de diferentes regiÃµes do mundo.', NULL),
(867, 'Principais regiÃµes geomorfolÃ³gicas do Brasil.', NULL),
(868, 'Relevo e ocupaÃ§Ã£o humana.', NULL),
(869, 'Processos que causam degradaÃ§Ã£o do relevo.', NULL),
(870, 'Principais riscos e desastres relacionados ao relevo.', NULL),
tÃ©cnicas de manejo e medidas estruturais para minimizar riscos.', NULL),
(872, 'PrevenÃ§Ã£o e mitigaÃ§Ã£o de impactos dos processos de desastres relacionados ao relevo.', NULL),
(873, 'Sistema Nacional de Unidades de ConservaÃ§Ã£o da natureza (SNUC).', NULL),
(874, 'Principais unidades de conservaÃ§Ã£o no Brasil.', NULL),
(875, 'IndÃºstria 4.0 e automaÃ§Ã£o', NULL),
(876, 'DistribuiÃ§Ã£o da Ã¡gua na Terra. Conceito de bacia hidrogrÃ¡fica', NULL),
(877, 'PolÃ­ticas pÃºblicas e prÃ¡ticas de gestÃ£o sustentÃ¡vel dos recursos hÃ­dricos', NULL),
(878, 'Processos endÃ³genos e exÃ³geno de formaÃ§Ã£o do relevo', NULL),
(879, 'DefiniÃ§Ã£o de Bioma. Principais Biomas da Terra', NULL),
(880, 'Biomas do estado de SÃ£o Paulo. DiferenÃ§as entre os biomas.', NULL),
(881, 'ImportÃ¢ncia da cartografia para a geografia. Elementos dos mapas. ProjeÃ§Ãµes cartogrÃ¡ficas', NULL),
(882, 'Cartografia temÃ¡tica. Mapas qualitativos e quantitativos', NULL),
(883, 'Cartografia tÃ¡til', NULL),
(884, 'CriaÃ§Ã£o de produtos cartogrÃ¡ficos', NULL),
(885, 'DefiniÃ§Ã£o de sensoriamento remoto. Origens do sensoriamento remoto', NULL),
(886, 'DefiniÃ§Ã£o de Sistema de InformaÃ§Ãµes GeogrÃ¡ficas (SIG). HistÃ³rico e evoluÃ§Ã£o do SIG', NULL),
(887, 'ProduÃ§Ã£o de mapas temÃ¡ticos', NULL),
(888, 'Conceito de globalizaÃ§Ã£o', NULL),
(889, 'Conceito de produÃ§Ã£o.', NULL),
(890, 'Cadeias produtivas', NULL),
(891, 'Regionalismos e blocos econÃ´micos', NULL),
(892, 'GlobalizaÃ§Ã£o cultural.', NULL),
(893, 'HomogeneizaÃ§Ã£o cultural.', NULL),
(894, 'Principais conceitos de demografia.', NULL),
(895, 'TransiÃ§Ã£o demogrÃ¡fica', NULL),
(896, 'Dados de demografia do Brasil.', NULL),
(897, 'DistribuiÃ§Ã£o e principais caracterÃ­sticas da populaÃ§Ã£o brasileira', NULL),
(898, 'Demografia da comunidade escolar', NULL),
(899, 'EvoluÃ§Ã£o da economia do Brasil com destaque para os sÃ©culos XVIII, XIX e XX', NULL),
(900, 'Principais dados da economia brasileira atual, com destaque para o PIB.', NULL),
(901, 'O papel da economia brasileira no cenÃ¡rio mundial', NULL),
(902, 'Indicadores socioeconÃ´micos do Brasil', NULL),
(903, 'Desigualdade socioeconÃ´mica e distribuiÃ§Ã£o de renda no Brasil', NULL),
(904, 'O mercado de trabalho no Brasil e as desigualdades sociais.', NULL),
(905, 'Principais direitos dos trabalhadores no Brasil. Reformas trabalhistas e flexibilizaÃ§Ãµes legais', NULL),
(906, 'Conceitos de Estado, naÃ§Ã£o e territÃ³rio', NULL),
(907, 'Conceito de Estado moderno. Processos histÃ³ricos de formaÃ§Ã£o das naÃ§Ãµes', NULL),
(908, 'Povos sem Estado. Conflitos e reivindicaÃ§Ãµes por autonomia ou reconhecimento', NULL),
(909, 'Conflitos territoriais atuais. O papel da ONU e dos organismos internacionais nesses conflitos', NULL),
(910, 'Territorialidade e identidade. DiÃ¡sporas e povos sem Estado. Desafios contemporÃ¢neos das cidades', NULL),
importÃ¢ncia cultural, social e geogrÃ¡fica', NULL),
(912, 'DemarcaÃ§Ãµes dos territÃ³rios indÃ­genas.', NULL),
(913, 'UrbanizaÃ§Ã£o no Brasil', NULL),
(914, 'Impactos socioambientais do processo de urbanizaÃ§Ã£o', NULL),
(915, 'O Processo de UrbanizaÃ§Ã£o Mundial', NULL),
(916, 'Problemas Urbanos e Desigualdades Socioespaciais', NULL),
(917, 'O espaÃ§o agrÃ¡rio brasileiro', NULL),
(918, 'Os contrastes dos modelos agrÃ­colas', NULL),
(919, 'Onu e o cenÃ¡rio agrÃ¡rio', NULL),
(920, 'O agronegÃ³cio e as novas fronteiras', NULL),
(921, 'Fatores biÃ³ticos e abiÃ³ticos', NULL),
(922, 'Cadeias alimentares e teias alimentares', NULL),
(923, 'Nicho ecolÃ³gico e comunidade biolÃ³gica', NULL),
(924, 'PirÃ¢mides ecolÃ³gicas', NULL),
(925, 'Fluxo de matÃ©ria e energia', NULL),
(926, 'SucessÃ£o ecolÃ³gica', NULL),
(927, 'Biomas terrestres brasileiros', NULL),
(928, 'FotossÃ­ntese', NULL),
(929, 'Metabolismo energÃ©tico', NULL),
(930, 'RespiraÃ§Ã£o celular', NULL),
(931, 'RelaÃ§Ãµes ecolÃ³gicas', NULL),
(932, 'DegradaÃ§Ã£o ambiental', NULL),
(933, 'Reflorestamento', NULL),
(934, 'EducaÃ§Ã£o ambiental', NULL),
(935, 'Agroecologia e sistemas agroflorestais', NULL),
(936, 'Descarte e tratamento de resÃ­duos', NULL),
(937, 'BiocombustÃ­veis e biomassa', NULL),
(938, 'ODS 7', NULL),
(939, 'Biosfera, populaÃ§Ã£o, comunidade, hÃ¡bitat e nicho ecolÃ³gico', NULL),
(940, 'Efeito estufa', NULL),
(941, 'ComposiÃ§Ã£o da atmosfera', NULL),
(942, 'Tempo e clima', NULL),
(943, 'Aquecimento global', NULL),
(944, 'MudanÃ§as climÃ¡ticas', NULL),
(945, 'Eventos climÃ¡ticos extremos', NULL),
(946, 'EducaÃ§Ã£o para ReduÃ§Ã£o de Riscos e Desastres', NULL),
(947, 'Impactos antrÃ³picos no ambiente', NULL),
(948, 'Vulnerabilidades relacionadas Ã s mudanÃ§as climÃ¡ticas', NULL),
(949, 'Matriz energÃ©tica', NULL),
(950, 'Fontes renovÃ¡veis', NULL),
(951, 'Fontes nÃ£o renovÃ¡veis', NULL),
(952, 'Impactos socioambientais da geraÃ§Ã£o de energia', NULL),
(953, 'Tipos de poluiÃ§Ã£o', NULL),
(954, 'PoluiÃ§Ã£o do ar e da Ã¡gua', NULL),
(955, 'Saneamento bÃ¡sico', NULL),
visÃ£o', NULL),
audiÃ§Ã£o', NULL),
(958, 'Sistema respiratÃ³rio', NULL),
(959, 'Sistema cardiovascular', NULL),
(960, 'AplicaÃ§Ã£o da radiaÃ§Ã£o no diagnÃ³stico e tratamento de enfermidades', NULL),
(961, 'Cuidados com a exposiÃ§Ã£o Ã  radiaÃ§Ã£o em exames', NULL),
(962, 'RadiaÃ§Ã£o ultravioleta', NULL),
(963, 'Efeitos da radiaÃ§Ã£o no DNA', NULL),
(964, 'Cuidados com a exposiÃ§Ã£o Ã  radiaÃ§Ã£o solar', NULL),
(965, 'Mitose', NULL),
(966, 'CÃ¢ncer', NULL),
(967, 'Meiose', NULL),
(968, 'GametogÃªnese humana', NULL),
(969, 'Desmatamento, queimadas e mudanÃ§as climÃ¡ticas', NULL),
(970, 'MineraÃ§Ã£o', NULL),
(971, 'Monocultura', NULL),
(972, 'Rios voadores', NULL),
(973, 'Crises hÃ­drica e elÃ©trica', NULL),
(974, 'Zoonoses', NULL),
(975, 'Quebra de barreira', NULL),
(976, 'Medidas profilÃ¡ticas', NULL),
(977, 'Ãreas de PreservaÃ§Ã£o Permanente', NULL),
(978, 'Bioma Cerrado', NULL),
(979, 'ServiÃ§os ecossistÃªmicos', NULL),
(980, 'Perda de hÃ¡bitat e fragmentaÃ§Ã£o', NULL),
(981, 'Corredores ecolÃ³gicos', NULL),
(982, 'CoexistÃªncia humano-fauna', NULL),
(983, 'Ãreas verdes urbanas', NULL),
(984, 'PreservaÃ§Ã£o e conservaÃ§Ã£o', NULL),
(985, 'CiÃªncia cidadÃ£', NULL),
(986, 'Unidades de ConservaÃ§Ã£o', NULL),
(987, 'AlteraÃ§Ãµes em teias e cadeias alimentares', NULL),
(988, 'RelaÃ§Ã£o ambiente e doenÃ§as', NULL),
capsÃ­deo e material genÃ©tico', NULL),
(990, 'BioacumulaÃ§Ã£o', NULL),
(991, 'BioconcentraÃ§Ã£o', NULL),
(992, 'BiomagnificaÃ§Ã£o', NULL),
(993, 'NÃ­veis trÃ³ficos', NULL),
(994, 'Bioindicadores', NULL),
(995, 'Defensivos agrÃ­colas', NULL),
(996, 'Descarte indevido de resÃ­duos', NULL),
(997, 'PolinizaÃ§Ã£o', NULL),
(998, 'Controle biolÃ³gico', NULL),
(999, 'Sistema reprodutor de plantas com flores', NULL),
(1000, 'Organismos Geneticamente Modificados', NULL);
