INSERT INTO curriculum_contents (id, descricao, unidade_tematica) VALUES
(801, 'USMCA, CAN, ALADI e MERCOSUL', NULL),
(802, 'Setores da economia', NULL),
(803, 'Descentralização e Recentralização econômica', NULL),
(804, 'Investimentos dos Estados Unidos no mundo', NULL),
(805, 'Influência do capital estadunidense no Brasil', NULL),
(806, 'Tecnologias e os setores da economia', NULL),
(807, 'Profissões do futuro', NULL),
(808, 'Oportunidades e desafios', NULL),
(809, 'Grandes Navegações e expansão marítima', NULL),
(810, 'Início da globalização e hegemonia europeia no controle territorial', NULL),
(811, 'Evolução dos mapas e representações do espaço', NULL),
(812, 'Visões eurocêntricas, divisão simbólica do mundo e cartografia como instrumento de poder', NULL),
(813, 'Organização do sistema colonial e pacto colonial', NULL),
(814, 'Consequências atuais da colonização nas fronteiras, culturas e relações de poder', NULL),
(815, 'Participação de países e colônias na 1ª e 2ª Guerras Mundiais.', NULL),
(816, 'Mudanças de fronteiras e divisões territoriais após os conflitos.', NULL),
(817, 'Consequências sociais, políticas e culturais para colonizadores e colonizados.', NULL),
(818, 'Características gerais da Guerra Fria e disputas geopolíticas em diferentes áreas.', NULL),
(819, 'Corrida espacial e tecnológica e o Muro de Berlim como símbolos da divisão global.', NULL),
(820, 'Disputas ideológicas e tecnológicas durante a Guerra Fria.', NULL),
(821, 'Divisão do mundo em blocos e consequências nas relações globais e nas desigualdades sociopolíticas.', NULL),
(822, 'Conceito de globalização e suas relações com a Geografia.', NULL),
(823, 'Características da primeira fase da globalização (séculos XV a XVII).', NULL),
(824, 'Segunda fase da globalização e a Revolução Industrial.', NULL),
(825, 'Êxodo rural, urbanização e mudanças nos modos de vida, consumo e trabalho.', NULL),
(826, 'Terceira fase da globalização: marcos e avanços tecnológicos.', NULL),
(827, 'Expansão das comunicações e novas formas de consumo, trabalho e informação.', NULL),
(828, 'Quarta fase da globalização e tecnologias emergentes.', NULL),
(829, 'Desigualdades, tensões e novas dinâmicas no mundo atual.', NULL),
(830, 'Tipos de moeda, evolução e circulação no sistema econômico global.', NULL),
(831, 'Moedas sociais, criptomoedas e alternativas locais ao sistema monetário tradicional.', NULL),
(832, 'Localização e limites do Oriente Médio.', NULL),
(833, 'Climas, relevos e recursos naturais predominantes.', NULL),
(834, 'Diversidade cultural e religiosa no Oriente Médio.', NULL),
(835, 'Principais dinâmicas populacionais da região.', NULL),
(836, 'Conflitos, tensões e disputas na região.', NULL),
(837, 'Principais influências nos conflitos contemporâneos do Oriente Médio.', NULL),
(838, 'O fim da URSS: causas, processo e desdobramentos.', NULL),
(839, 'Tensões geopolíticas atuais: mudanças territoriais e conflitos contemporâneos.', NULL),
(840, 'A influência política e econômica da Rússia na Eurásia.', NULL),
(841, 'Os conflitos na Ucrânia e na Geórgia: causas e consequências.', NULL),
(842, 'Desenvolvimento econômico, industrial e tecnológico da China nas últimas décadas.', NULL),
(843, 'Relação com Taiwan e impactos políticos regionais e globais da China.', NULL),
(844, 'O conflito entre as Coreias e seus desdobramentos.', NULL),
(845, 'Relações políticas dos países vizinhos (Japão e China) com o conflito coreano.', NULL),
(846, 'Processo político, econômico e populacional da Índia atual.', NULL),
(847, 'A questão da Caxemira e suas implicações territoriais e políticas', NULL),
(848, 'Economia global e seu impacto no cotidiano local.', NULL),
(849, 'Influência das corporações, instituições internacionais, cultura e identidade na globalização.', NULL),
(850, 'Principais organizações econômicas e comerciais e sua atuação no cenário mundial.', NULL),
(851, 'Definição, origem e princípios básicos dos direitos humanos.', NULL),
(852, 'Destaque para o contexto histórico do pós-segunda Guerra Mundial.', NULL),
(853, 'Direitos humanos atualmente: desafios e exemplos.', NULL),
(854, 'Fundamentos no pós-guerra.', NULL),
(855, 'Tipos de deslocamentos humanos.', NULL),
(856, 'Diferença entre migrantes e refugiados.', NULL),
(857, 'Principais causas dos deslocamentos contemporâneos.', NULL),
(858, 'Refugiados no Brasil. Causas, rotas e desafios da migração forçada', NULL),
(859, 'Diferenças entre Climatologia e Meteorologia.', NULL),
(860, 'Conceitos de Tempo e Clima.', NULL),
(861, 'Divisão das camadas da atmosfera e suas principais características.', NULL),
(862, 'Circulação geral da atmosfera.', NULL),
(863, 'Elementos e controles climáticos.', NULL),
(864, 'Principais elementos de um climograma: temperatura e precipitação.', NULL),
(865, 'Biomas associados a determinados padrões de climogramas.', NULL),
(866, 'Climogramas de diferentes regiões do mundo.', NULL),
(867, 'Principais regiões geomorfológicas do Brasil.', NULL),
(868, 'Relevo e ocupação humana.', NULL),
(869, 'Processos que causam degradação do relevo.', NULL),
(870, 'Principais riscos e desastres relacionados ao relevo.', NULL),
(871, 'Prevenção e mitigação: técnicas de manejo e medidas estruturais para minimizar riscos.', NULL),
(872, 'Prevenção e mitigação de impactos dos processos de desastres relacionados ao relevo.', NULL),
(873, 'Sistema Nacional de Unidades de Conservação da natureza (SNUC).', NULL),
(874, 'Principais unidades de conservação no Brasil.', NULL),
(875, 'Indústria 4.0 e automação', NULL),
(876, 'Distribuição da água na Terra. Conceito de bacia hidrográfica', NULL),
(877, 'Políticas públicas e práticas de gestão sustentável dos recursos hídricos', NULL),
(878, 'Processos endógenos e exógeno de formação do relevo', NULL),
(879, 'Definição de Bioma. Principais Biomas da Terra', NULL),
(880, 'Biomas do estado de São Paulo. Diferenças entre os biomas.', NULL),
(881, 'Importância da cartografia para a geografia. Elementos dos mapas. Projeções cartográficas', NULL),
(882, 'Cartografia temática. Mapas qualitativos e quantitativos', NULL),
(883, 'Cartografia tátil', NULL),
(884, 'Criação de produtos cartográficos', NULL),
(885, 'Definição de sensoriamento remoto. Origens do sensoriamento remoto', NULL),
(886, 'Definição de Sistema de Informações Geográficas (SIG). Histórico e evolução do SIG', NULL),
(887, 'Produção de mapas temáticos', NULL),
(888, 'Conceito de globalização', NULL),
(889, 'Conceito de produção.', NULL),
(890, 'Cadeias produtivas', NULL),
(891, 'Regionalismos e blocos econômicos', NULL),
(892, 'Globalização cultural.', NULL),
(893, 'Homogeneização cultural.', NULL),
(894, 'Principais conceitos de demografia.', NULL),
(895, 'Transição demográfica', NULL),
(896, 'Dados de demografia do Brasil.', NULL),
(897, 'Distribuição e principais características da população brasileira', NULL),
(898, 'Demografia da comunidade escolar', NULL),
(899, 'Evolução da economia do Brasil com destaque para os séculos XVIII, XIX e XX', NULL),
(900, 'Principais dados da economia brasileira atual, com destaque para o PIB.', NULL),
(901, 'O papel da economia brasileira no cenário mundial', NULL),
(902, 'Indicadores socioeconômicos do Brasil', NULL),
(903, 'Desigualdade socioeconômica e distribuição de renda no Brasil', NULL),
(904, 'O mercado de trabalho no Brasil e as desigualdades sociais.', NULL),
(905, 'Principais direitos dos trabalhadores no Brasil. Reformas trabalhistas e flexibilizações legais', NULL),
(906, 'Conceitos de Estado, nação e território', NULL),
(907, 'Conceito de Estado moderno. Processos históricos de formação das nações', NULL),
(908, 'Povos sem Estado. Conflitos e reivindicações por autonomia ou reconhecimento', NULL),
(909, 'Conflitos territoriais atuais. O papel da ONU e dos organismos internacionais nesses conflitos', NULL),
(910, 'Territorialidade e identidade. Diásporas e povos sem Estado. Desafios contemporâneos das cidades', NULL),
(911, 'Territórios Indígenas: importância cultural, social e geográfica', NULL),
(912, 'Demarcações dos territórios indígenas.', NULL),
(913, 'Urbanização no Brasil', NULL),
(914, 'Impactos socioambientais do processo de urbanização', NULL),
(915, 'O Processo de Urbanização Mundial', NULL),
(916, 'Problemas Urbanos e Desigualdades Socioespaciais', NULL),
(917, 'O espaço agrário brasileiro', NULL),
(918, 'Os contrastes dos modelos agrícolas', NULL),
(919, 'Onu e o cenário agrário', NULL),
(920, 'O agronegócio e as novas fronteiras', NULL),
(921, 'Fatores bióticos e abióticos', NULL),
(922, 'Cadeias alimentares e teias alimentares', NULL),
(923, 'Nicho ecológico e comunidade biológica', NULL),
(924, 'Pirâmides ecológicas', NULL),
(925, 'Fluxo de matéria e energia', NULL),
(926, 'Sucessão ecológica', NULL),
(927, 'Biomas terrestres brasileiros', NULL),
(928, 'Fotossíntese', NULL),
(929, 'Metabolismo energético', NULL),
(930, 'Respiração celular', NULL),
(931, 'Relações ecológicas', NULL),
(932, 'Degradação ambiental', NULL),
(933, 'Reflorestamento', NULL),
(934, 'Educação ambiental', NULL),
(935, 'Agroecologia e sistemas agroflorestais', NULL),
(936, 'Descarte e tratamento de resíduos', NULL),
(937, 'Biocombustíveis e biomassa', NULL),
(938, 'ODS 7', NULL),
(939, 'Biosfera, população, comunidade, hábitat e nicho ecológico', NULL),
(940, 'Efeito estufa', NULL),
(941, 'Composição da atmosfera', NULL),
(942, 'Tempo e clima', NULL),
(943, 'Aquecimento global', NULL),
(944, 'Mudanças climáticas', NULL),
(945, 'Eventos climáticos extremos', NULL),
(946, 'Educação para Redução de Riscos e Desastres', NULL),
(947, 'Impactos antrópicos no ambiente', NULL),
(948, 'Vulnerabilidades relacionadas às mudanças climáticas', NULL),
(949, 'Matriz energética', NULL),
(950, 'Fontes renováveis', NULL),
(951, 'Fontes não renováveis', NULL),
(952, 'Impactos socioambientais da geração de energia', NULL),
(953, 'Tipos de poluição', NULL),
(954, 'Poluição do ar e da água', NULL),
(955, 'Saneamento básico', NULL),
(956, 'Sistema fisiológico: visão', NULL),
(957, 'Sistema fisiológico: audição', NULL),
(958, 'Sistema respiratório', NULL),
(959, 'Sistema cardiovascular', NULL),
(960, 'Aplicação da radiação no diagnóstico e tratamento de enfermidades', NULL),
(961, 'Cuidados com a exposição à radiação em exames', NULL),
(962, 'Radiação ultravioleta', NULL),
(963, 'Efeitos da radiação no DNA', NULL),
(964, 'Cuidados com a exposição à radiação solar', NULL),
(965, 'Mitose', NULL),
(966, 'Câncer', NULL),
(967, 'Meiose', NULL),
(968, 'Gametogênese humana', NULL),
(969, 'Desmatamento, queimadas e mudanças climáticas', NULL),
(970, 'Mineração', NULL),
(971, 'Monocultura', NULL),
(972, 'Rios voadores', NULL),
(973, 'Crises hídrica e elétrica', NULL),
(974, 'Zoonoses', NULL),
(975, 'Quebra de barreira', NULL),
(976, 'Medidas profiláticas', NULL),
(977, 'Áreas de Preservação Permanente', NULL),
(978, 'Bioma Cerrado', NULL),
(979, 'Serviços ecossistêmicos', NULL),
(980, 'Perda de hábitat e fragmentação', NULL),
(981, 'Corredores ecológicos', NULL),
(982, 'Coexistência humano-fauna', NULL),
(983, 'Áreas verdes urbanas', NULL),
(984, 'Preservação e conservação', NULL),
(985, 'Ciência cidadã', NULL),
(986, 'Unidades de Conservação', NULL),
(987, 'Alterações em teias e cadeias alimentares', NULL),
(988, 'Relação ambiente e doenças', NULL),
(989, 'Vírus: capsídeo e material genético', NULL),
(990, 'Bioacumulação', NULL),
(991, 'Bioconcentração', NULL),
(992, 'Biomagnificação', NULL),
(993, 'Níveis tróficos', NULL),
(994, 'Bioindicadores', NULL),
(995, 'Defensivos agrícolas', NULL),
(996, 'Descarte indevido de resíduos', NULL),
(997, 'Polinização', NULL),
(998, 'Controle biológico', NULL),
(999, 'Sistema reprodutor de plantas com flores', NULL),
(1000, 'Organismos Geneticamente Modificados', NULL);
