INSERT INTO curriculum_contents (id, descricao, unidade_tematica) VALUES
(601, 'Jogo de Basquete com regras e fundamentos', NULL),
Basquete em cadeira de rodas', NULL),
(603, 'Lutas de percussÃ£o', NULL),
(604, 'Boxe', NULL),
(605, 'Muay Thai', NULL),
(606, 'Posturas. MovimentaÃ§Ãµes. Esquivas do Boxe', NULL),
(607, 'Golpes', NULL),
(608, 'jab, direto, cruzado, gancho. A Sombra', NULL),
(609, 'Postura. MovimentaÃ§Ãµes. Esquivas e Bloqueios do Muay Thai', NULL),
(610, 'Golpes de membros superiores', NULL),
(611, 'Golpes de membros inferiores', NULL),
(612, 'Origem e evoluÃ§Ã£o do MMA', NULL),
(613, 'Origem e evoluÃ§Ã£o da esgrima', NULL),
(614, 'MudanÃ§as e adequaÃ§Ãµes Ã s regras e dinÃ¢micas da esgrima em sua versÃ£o paralÃ­mpica', NULL),
(615, 'Jogos de oposiÃ§Ã£o no MMA', NULL),
(616, 'PrÃ¡ticas de golpes percussivos de membros superiores; AnÃ¡lise sobre as relaÃ§Ãµes com outras modalidades vivenciadas', NULL),
(617, 'PrÃ¡ticas de golpes percussivos de membros inferiores; AnÃ¡lise sobre as relaÃ§Ãµes com outras modalidades vivenciadas', NULL),
(618, 'ConfecÃ§Ã£o de materiais para vivenciar a esgrima e a esgrima em cadeira de rodas nas aulas de EducaÃ§Ã£o FÃ­sica', NULL),
(619, 'VivÃªncia da Esgrima', NULL),
(620, 'AdaptaÃ§Ã£o da Esgrima em cadeira de rodas', NULL),
(621, 'Disputa de esgrima e disputa de esgrima em cadeira de rodas. AnÃ¡lise sobre a esgrima e a esgrima em cadeira de rodas. RelaÃ§Ãµes, diferenÃ§as e desafios', NULL),
(622, 'Diferentes possibilidades de se praticar o Futebol; Futebol como prÃ¡tica democrÃ¡tica; Futebol de campo; Futebol society; Futsal; FÃºtbol callejero', NULL),
(623, 'Futebol de campo adaptado para o espaÃ§o escolar', NULL),
(624, 'PrÃ¡tica do futebol de campo adaptado', NULL),
(625, 'Futebol society de maneira adaptada para o espaÃ§o escolar', NULL),
(626, 'PrÃ¡tica do futebol society', NULL),
(627, 'Jogos prÃ©-desportivos do futsal', NULL),
fundamentos do futsal', NULL),
(629, 'PrÃ¡tica do Futsal', NULL),
(630, 'Regras, objetivos e vivÃªncias do fÃºtbol callejero', NULL),
(631, 'PrÃ¡tica do fÃºtbol callejero', NULL),
(632, 'VivÃªncia de um futebol elencado pela turma', NULL),
(633, 'Retomada sobre a histÃ³ria e a importÃ¢ncia dos esportes e jogos paralÃ­mpicos; Modalidades paralÃ­mpicas', NULL),
(634, 'ApresentaÃ§Ã£o do goalball; Papel social, cultural e esportivo do goalball na inclusÃ£o', NULL),
(635, 'Goalball de maneira adaptada para o espaÃ§o escolar', NULL),
(636, 'PrÃ¡tica do goalball', NULL),
(637, 'Surgimento e diferenÃ§as entre o Rugby e o Futebol americano; Fundamentos e regras do Rugby e do Futebol Americano', NULL),
(638, 'Regras e possÃ­veis adaptaÃ§Ãµes do Rugby', NULL),
(639, '"ExercÃ­cios para atender o desenvolvimento tÃ©cnico', NULL),
(640, 'ExercÃ­cios de condicionamento fÃ­sico', NULL),
(641, 'PrÃ¡tica do Rugby', NULL),
(642, 'Regras e possÃ­veis adaptaÃ§Ãµes do Futebol americano', NULL),
(643, 'ExercÃ­cios de preparaÃ§Ã£o fÃ­sica e treinamento tÃ©cnico', NULL),
(644, 'PrÃ¡tica do Futebol americano', NULL),
(645, 'DefiniÃ§Ã£o de samba de roda; Significado histÃ³rico e cultural do carnaval; HistÃ³ria do Ballet clÃ¡ssico; Origem da danÃ§a contemporÃ¢nea', NULL),
(646, 'Musicalidade, ritmo e expressÃ£o corporal', NULL),
ginga, miudinho e tranÃ§a', NULL),
(648, 'SimulaÃ§Ã£o de um desfile de escola de samba', NULL),
(649, 'PosiÃ§Ãµes e movimentos bÃ¡sicos do Ballet', NULL),
(650, 'ExploraÃ§Ã£o livre de movimentos e improvisaÃ§Ã£o guiada', NULL),
(651, 'CriaÃ§Ã£o coletiva para danÃ§a contemporÃ¢nea', NULL),
(652, 'ApresentaÃ§Ã£o dos esportes de rede/quadra dividida; DiferenÃ§a entre o TÃªnis de mesa e o TÃªnis de campo; Fundamentos e regras do TÃªnis de mesa e do TÃªnis de campo', NULL),
(653, 'Fundamentos; postura, saque, recepÃ§Ã£o, golpes bÃ¡sicos e tipos de empunhadura', NULL),
(654, 'Regras; Arbitragem', NULL),
(655, 'PrÃ¡tica do TÃªnis de Mesa; DiferenÃ§as com o Ping-Pong', NULL),
(656, 'Jogo de tÃªnis de maneira adaptada para o espaÃ§o escolar', NULL),
(657, 'HistÃ³ria e origem da DanÃ§a Circular, do Dabke e do Fandango; A chegada dessas danÃ§as ao Brasil; Significado, funÃ§Ã£o cultural e contexto social dessas danÃ§as do mundo', NULL),
(658, 'Ritmo e musicalidade; Diversidade cultural', NULL),
(659, 'FormaÃ§Ã£o do cÃ­rculo e passos bÃ¡sicos', NULL),
(660, 'Ritmo e musicalidade; RelevÃ¢ncia cultural', NULL),
(661, 'FormaÃ§Ã£o e passos na roda', NULL),
(662, 'Olhar cultural', NULL),
(663, 'FormaÃ§Ã£o, passo de base, passo cruzado e giro', NULL),
(664, 'Esporte de rede/quadra dividida; Esporte de invasÃ£o/ territorial; Punhobol; Kin-Ball; Tchoukball; Ultimate Frisbee', NULL),
(665, 'Regras e possÃ­veis adaptaÃ§Ãµes do Punhobol e/ou do Kimball', NULL),
(666, 'PrÃ¡tica do Punhobol e/ou do Kimball', NULL),
(667, 'Regras e possÃ­veis adaptaÃ§Ãµes do Tchoukball', NULL),
(668, 'PrÃ¡tica do Tchoukball', NULL),
(669, 'Regras e possÃ­veis adaptaÃ§Ãµes do Ultimate Frisbee', NULL),
(670, 'PrÃ¡tica do Ultimate Frisbee', NULL),
(671, 'Materiais Digitais -Esportes praticados em quadra de areia/ praia; Origem e caracterÃ­sticas do VÃ´lei de praia, do FutevÃ´lei, do Beach tennis e do Frescobol', NULL),
(672, 'Regras, possÃ­veis adaptaÃ§Ãµes e prÃ¡tica do VÃ´lei de praia', NULL),
(673, 'Regras e possÃ­veis adaptaÃ§Ãµes do FutevÃ´lei', NULL),
(674, 'PrÃ¡tica de FutevÃ´lei', NULL),
(675, 'Regras, possÃ­veis adaptaÃ§Ãµes e prÃ¡tica do Beach tennis', NULL),
(676, 'Regras e possÃ­veis adaptaÃ§Ãµes do Frescobol', NULL),
(677, 'PrÃ¡tica de Frescobol', NULL),
(678, 'Continentes. Oceanos. Paisagens pelo mundo', NULL),
(679, 'O conceito de paisagem.', NULL),
(680, 'Tipos de paisagem.', NULL),
(681, 'Planos da paisagem', NULL),
(682, 'Paisagens transformadas pela aÃ§Ã£o da natureza.', NULL),
(683, 'Paisagens transformadas por diferentes grupos sociais', NULL),
(684, 'O conceito de lugar', NULL),
(685, 'Lugares do cotidiano', NULL),
(686, 'RelaÃ§Ã£o entre os lugares', NULL),
(687, 'O conceito de espaÃ§o geogrÃ¡fico.', NULL),
(688, 'ProduÃ§Ã£o do espaÃ§o geogrÃ¡fico.', NULL),
(689, 'Trabalho, tÃ©cnica e as transformaÃ§Ãµes no espaÃ§o geogrÃ¡fico.', NULL),
(690, 'Mapas mentais. Lugares de vivÃªncia. TransformaÃ§Ãµes no espaÃ§o geogrÃ¡fico', NULL),
(691, 'Atividades econÃ´micas.', NULL),
(692, 'Setores da economia.', NULL),
(693, 'Extrativismos minerais, animal e vegetal', NULL),
(694, 'Principais produtos extrativistas.', NULL),
(695, 'DistribuiÃ§Ã£o no espaÃ§o geogrÃ¡fico.', NULL),
(696, 'Impactos ambientais', NULL),
(697, 'Tipos de agricultura.', NULL),
(698, 'Principais cultivos.', NULL),
(699, 'Sistemas de ProduÃ§Ã£o pecuÃ¡ria.', NULL),
(700, 'Principais criaÃ§Ãµes da pecuÃ¡ria', NULL),
(701, 'Principais produtos agropecuÃ¡rios.', NULL),
(702, 'DistribuiÃ§Ã£o agropecuÃ¡ria no espaÃ§o geogrÃ¡fico.', NULL),
(703, 'Processo de industrializaÃ§Ã£o. As fases da industrializaÃ§Ã£o.', NULL),
(704, 'DistribuiÃ§Ã£o industrial no espaÃ§o geogrÃ¡fico', NULL),
(705, 'IndÃºstrias de base, de bens intermediÃ¡rios e de bens de consumo', NULL),
(706, 'ComÃ©rcios locais, eletrÃ´nico e internacional', NULL),
(707, 'ServiÃ§os de saÃºde, de educaÃ§Ã£o, financeiros, de turismo, de transporte e de comunicaÃ§Ã£o', NULL),
(708, 'InterdependÃªncia das atividades econÃ´micas. Setores produtivos.', NULL),
(709, 'EstÃ¡gios de produÃ§Ã£o das mercadorias. As paisagens urbanas. O processo de urbanizaÃ§Ã£o', NULL),
(710, 'Principais problemas urbanos', NULL),
(711, 'As paisagens rurais. As transformaÃ§Ãµes no campo', NULL),
(712, 'Principais problemas no campo', NULL),
(713, 'Principais movimentos do planeta Terra e suas consequÃªncias', NULL),
(714, 'RepresentaÃ§Ãµes do planeta Terra.', NULL),
(715, 'DefiniÃ§Ã£o de cartografia.', NULL),
(716, 'EvoluÃ§Ã£o das tÃ©cnicas cartogrÃ¡ficas', NULL),
(717, 'Elementos e convenÃ§Ãµes cartogrÃ¡ficas.', NULL),
(718, 'ProjeÃ§Ãµes planas, cÃ´nicas e cilÃ­ndricas', NULL),
(719, 'Formas de orientaÃ§Ã£o espacial.', NULL),
(720, 'OrientaÃ§Ã£o nos mapas', NULL),
(721, 'Instrumentos de orientaÃ§Ã£o espacial.', NULL),
(722, 'Paralelos, Meridianos, Zonas tÃ©rmicas', NULL),
(723, 'Fusos horÃ¡rios.', NULL),
(724, 'Latitude e longitude.', NULL),
(725, 'Escalas grÃ¡ficas, numÃ©ricas, grandes e pequenas', NULL),
(726, 'CÃ¡lculo de escala cartogrÃ¡fica', NULL),
(727, 'Croqui, Mapa, Carta, Planta', NULL),
(728, 'Mapa temÃ¡tico', NULL),
(729, 'Perfil topogrÃ¡fico', NULL),
(730, 'Litosfera, Atmosfera, Hidrosfera e Biosfera.', NULL),
(731, 'ComposiÃ§Ã£o e camadas da atmosfera.', NULL),
(732, 'Tempo e clima.', NULL),
(733, 'Frentes de ar.', NULL),
(734, 'PrevisÃ£o do tempo.', NULL),
(735, 'Latitude, Altitude, Maritimidade e Continentalidade.', NULL),
(736, 'PrecipitaÃ§Ã£o e Temperatura.', NULL),
(737, 'Climograma', NULL),
(738, 'LocalizaÃ§Ã£o e limites do territÃ³rio brasileiro.', NULL),
(739, 'Conceito de regiÃ£o e de regionalizaÃ§Ã£o.', NULL),
(740, 'DivisÃ£o regional do IBGE.', NULL),
(741, 'CaracterÃ­sticas da regiÃ£o Norte, da regiÃ£o Nordeste, da regiÃ£o Centro-Oeste, da regiÃ£o Sul e da regiÃ£o Sudeste.', NULL),
(742, 'Complexos regionais ou regiÃµes geoeconÃ´micas.', NULL),
(743, 'Complexo regional AmazÃ´nia.', NULL),
(744, 'Complexo regional Centro-Sul.', NULL),
(745, 'Complexo regional do Nordeste.', NULL),
(746, 'RegiÃµes do Brasil', NULL),
(747, 'Conceito de territÃ³rio e sua dimensÃ£o polÃ­tica.', NULL),
(748, 'Ciclos econÃ´micos.', NULL),
(749, 'ConstruÃ§Ã£o do territÃ³rio brasileiro.', NULL),
(750, 'CaracterÃ­sticas do territÃ³rio brasileiro.', NULL),
(751, 'TensÃµes ligadas ao uso e posse do territÃ³rio.', NULL),
(752, 'TransformaÃ§Ãµes territoriais em SÃ£o Paulo.', NULL),
(753, 'EstereÃ³tipos e representaÃ§Ãµes territoriais nos meios de comunicaÃ§Ã£o', NULL),
(754, 'Diversidade Ã©tnico-racial e cultural da populaÃ§Ã£o brasileira.', NULL),
(755, 'Fluxos migratÃ³rios histÃ³ricos e contemporÃ¢neos.', NULL),
(756, 'Fatores de atraÃ§Ã£o e repulsÃ£o populacional, com foco nos complexos regionais.', NULL),
(757, 'Taxas de natalidade e mortalidade no Brasil.', NULL),
(758, 'Densidade demogrÃ¡fica e migraÃ§Ãµes internas.', NULL),
(759, 'Censo demogrÃ¡fico e dados populacionais.', NULL),
(760, 'PirÃ¢mide etÃ¡ria e estrutura da populaÃ§Ã£o brasileira.', NULL),
(761, 'PopulaÃ§Ã£o economicamente ativa e setores da economia.', NULL),
(762, 'FormaÃ§Ã£o da diversidade Ã©tnico-racial no Brasil.', NULL),
(763, 'AnÃ¡lise de dados demogrÃ¡ficos por etnia no Brasil', NULL),
(764, 'Transporte e comunicaÃ§Ã£o na integraÃ§Ã£o do territÃ³rio brasileiro', NULL),
(765, 'O espaÃ§o das redes no Brasil', NULL),
(766, 'Redes de transporte no Brasil', NULL),
(767, 'EvoluÃ§Ã£o dos transportes e de comunicaÃ§Ã£o no Brasil', NULL),
(768, 'IndustrializaÃ§Ã£o brasileira, concentraÃ§Ã£o e desconcentraÃ§Ã£o industrial no Brasil', NULL),
(769, 'Parques cientÃ­ficos e tecnolÃ³gicos no Brasil', NULL),
(770, 'ConexÃ£o entre lugares, Redes de transporte e comunicaÃ§Ã£o e DistribuiÃ§Ã£o das atividades econÃ´micas', NULL),
(771, 'Redes de transporte e comunicaÃ§Ã£o', NULL),
(772, 'DesconcentraÃ§Ã£o industrial', NULL),
(773, 'Do mundo bipolar ao mundo multipolar', NULL),
(774, 'A ascensÃ£o dos Estados Unidos', NULL),
(775, 'O poderio militar e econÃ´mico dos Estados Unidos', NULL),
(776, 'O poder polÃ­tico dos Estados Unidos', NULL),
(777, 'EstratÃ©gias diplomÃ¡ticas e econÃ´micas', NULL),
(778, 'Desafios e oportunidades para os paÃ­ses latino', NULL),
(779, 'americanos no contexto da Nova Ordem Mundial', NULL),
(780, 'Brasil e Nova Ordem Mundial', NULL),
1, 2, 3, 4', NULL),
(782, 'Conceitos da GeopolÃ­tica', NULL),
(783, 'RelaÃ§Ãµes internacionais', NULL),
(784, 'Principais organizaÃ§Ãµes mundiais', NULL),
(785, 'PaÃ­ses-membros da ONU', NULL),
(786, 'FunÃ§Ãµes, objetivos e estrutura da ONU', NULL),
(787, 'RegionalizaÃ§Ã£o e aspectos fÃ­sicos da Ãfrica', NULL),
(788, 'Conflitos civis no continente africano', NULL),
(789, 'Crise humanitÃ¡ria na Ãfrica', NULL),
(790, 'Conflitos africanos', NULL),
(791, 'RegionalizaÃ§Ã£o e aspectos fÃ­sicos da AmÃ©rica', NULL),
(792, 'Estados Unidos e MÃ©xico', NULL),
(793, 'TensÃµes e conflitos entre Chile e BolÃ­via', NULL),
(794, 'TensÃµes e conflitos entre Argentina e Chile', NULL),
(795, 'TensÃµes e conflitos entre Venezuela e Guiana', NULL),
(796, 'GATT e OMC. Indicadores econÃ´micos dos Estados Unidos, da China e dos BRICS.', NULL),
(797, 'Principais produtos e serviÃ§os comercializados por Estados Unidos e China, e entre Estados Unidos e BRICS.', NULL),
(798, 'PaÃ­ses membros e parceiros dos BRICS. CaracterÃ­sticas gerais dos BRICS.', NULL),
(799, 'Economia global e emergente.', NULL),
(800, 'Brasil, RÃºssia, Ãndia, China e Ãfrica do Sul.', NULL);
