INSERT INTO curriculum_contents (id, descricao, unidade_tematica) VALUES
(1, 'Dan├ºas Populares Brasileiras', NULL),
(2, 'Origens das Dan├ºas', NULL),
(3, 'Varia├º├úo de Tempo', NULL),
(4, 'Express├úo Corporal', NULL),
(5, 'Elementos da Dan├ºa', NULL),
(6, 'Movimentos do Frevo', NULL),
(7, 'Uso do Espa├ºo', NULL),
(8, 'Fatores do Movimento', NULL),
(9, 'Jongo', NULL),
(10, 'Frevo', NULL),
(11, 'Siriri', NULL),
(12, 'Carimb├│', NULL),
(13, 'Cria├º├╡es Coreogr├íficas', NULL),
(14, 'Express├úo na Dan├ºa', NULL),
(15, 'Processos Criativos', NULL),
(16, 'M├║sica Brasileira', NULL),
(17, 'Produ├º├úo, Repert├│rio e Circula├º├úo Musical', NULL),
(18, 'Fun├º├úo Social da M├║sica', NULL),
(19, 'Repert├│rio Musical Ind├¡gena e Afro-Brasileiro', NULL),
(20, 'Paisagem Sonora', NULL),
(21, 'Registro Musical', NULL),
(22, 'Nota├º├úo N├úo Convencional', NULL),
(23, 'Composi├º├úo e Improvisa├º├úo Musical', NULL),
(24, 'Percuss├úo Corporal', NULL),
(25, 'Instrumentos e Nota├º├úo N├úo Convencionais', NULL),
(26, 'Instrumentos e Timbres', NULL),
(27, 'Improvisa├º├úo Musical', NULL),
(28, 'Composi├º├úo, Colabora├º├úo e Improvisa├º├úo Musical', NULL),
(29, 'Produ├º├úo e Registro Musical', NULL),
(30, 'Introdu├º├úo ├á Dan├ºa', NULL),
Diversidade Cultural', NULL),
(32, 'Hist├│ria da Dan├ºa', NULL),
(33, 'Dan├ºa Cl├íssica', NULL),
(34, 'Dan├ºa Moderna', NULL),
(35, 'Fatores de Movimento', NULL),
(36, 'Qualidades dos Movimentos', NULL),
(37, 'Sequ├¬ncias Coreogr├íficas', NULL),
(38, 'A├º├╡es de Esfor├ºo', NULL),
(39, 'Improvisa├º├úo na Dan├ºa', NULL),
(40, 'M├║sica Cl├íssica', NULL),
(41, 'M├║sica Instrumental', NULL),
(42, 'M├║sica Orquestral', NULL),
(43, 'Canto Coral', NULL),
(44, 'Estrutura do Coro', NULL),
(45, 'Produ├º├úo Musical', NULL),
(46, 'Estrutura da Orquestra', NULL),
(47, 'T├⌐cnicas de Execu├º├úo', NULL),
(48, 'Instrumentos Convencionais', NULL),
(49, 'Timbres e Caracter├¡sticas', NULL),
(50, 'Nota├º├úo Convencional', NULL),
(51, 'Composi├º├úo Musical', NULL),
(52, 'T├⌐cnicas de Execu├º├úo Musical', NULL),
(53, 'Performance Musical', NULL),
(54, 'Instrumentos Musicais', NULL),
(55, 'Origens da Dan├ºa', NULL),
(56, 'Dan├ºa Coletiva', NULL),
(57, 'Improvisa├º├úo em Dan├ºa', NULL),
(58, 'A├º├╡es Corporais Dan├ºadas', NULL),
(59, 'Personagens na Dan├ºa Popular', NULL),
(60, 'Improvisa├º├úo Coletiva', NULL),
(61, 'Gravidade e Peso', NULL),
(62, 'An├ílise do Movimento', NULL),
(63, 'Partitura Corporal', NULL),
(64, 'Composi├º├úo Coreogr├ífica', NULL),
(65, 'Aprecia├º├úo Musical', NULL),
(66, 'Hist├│ria da M├║sica', NULL),
(67, 'M├║sica Tradicional Africana', NULL),
(68, 'Timbre', NULL),
(69, 'M├║sica Ind├¡gena', NULL),
(70, 'M├║sica Contempor├ónea', NULL),
(71, 'M├║sica Afro-Brasileira', NULL),
(72, 'Elementos da M├║sica', NULL),
(73, 'Jogos R├¡tmicos', NULL),
(74, 'Pr├íticas de Cria├º├úo', NULL),
(75, 'Movimento Cotidiano', NULL),
(76, 'Jogos e Brincadeiras', NULL),
(77, 'Kinesfera', NULL),
(78, 'Corpo-H├¡brido e Corpo-Tela', NULL),
(79, 'Cria├º├úo Coreogr├ífica', NULL),
(80, 'Dan├ºa Contempor├ónea', NULL),
(81, 'Independ├¬ncia ou Coexist├¬ncia Est├⌐tica', NULL),
(82, 'Qualidades do Movimento', NULL),
(83, 'Musicalidade Corporal', NULL),
(84, 'Brincadeiras e Dan├ºa', NULL),
(85, 'Corpo Mem├⌐tico e Corpo Midi├ítico', NULL),
(86, 'Corpo e Tecnologia', NULL),
(87, 'M├║sica Popular Brasileira', NULL),
(88, 'M├║sica Popular Estrangeira', NULL),
(89, 'Movimentos Musicais Hist├│ricos', NULL),
(90, 'Can├º├úo de Protesto', NULL),
(91, 'Express├úo, Composi├º├úo e Aprecia├º├úo Musical', NULL),
(92, 'M├║sica e Tecnologia', NULL),
(93, 'Elementos de Composi├º├úo Musical', NULL),
(94, 'Fun├º├úo Social da Arte', NULL),
(95, 'Cultura Contempor├ónea', NULL),
(96, 'Processo Criativo', NULL),
(97, 'Arte e M├¡dia', NULL),
(98, 'An├ílise Cr├¡tica', NULL),
(99, 'Cria├º├úo Art├¡stica', NULL),
(100, 'Interven├º├úo Art├¡stica', NULL),
(101, 'Manifesta├º├úo Art├¡stica', NULL),
(102, 'Linguagens Art├¡sticas', NULL),
(103, 'Express├úo Art├¡stica', NULL),
(104, 'Artes do Corpo', NULL),
(105, 'Estere├│tipos Sociais', NULL),
(106, 'Cria├º├úo Musical', NULL),
(107, 'Dan├ºas Sociais', NULL),
(108, 'Express├úo Identit├íria', NULL),
(109, 'Discurso Cr├¡tico', NULL),
(110, 'Cr├¡tica de Arte', NULL),
(111, 'Performatividade', NULL),
(112, 'Patrim├┤nio Cultural', NULL),
(113, 'Pesquisa em Arte', NULL),
(114, 'An├ílise Hist├│rica e Cultural', NULL),
(115, 'Manifesto Art├¡stico', NULL),
(116, 'Est├⌐tica Relacional', NULL),
(117, 'Processo Colaborativo', NULL),
(118, 'Impacto Cultural', NULL),
(119, 'Processos de Cria├º├úo', NULL),
(120, 'Movimentos Art├¡sticos', NULL),
(121, 'Compartilhamento de Pr├íticas', NULL),
(122, 'Contexto Hist├│rico e Cultural', NULL),
(123, 'Zeitgeist, ΓÇ£Esp├¡rito do TempoΓÇ¥', NULL),
(124, 'Manifestos Coletivos', NULL),
(125, 'Coletivos Art├¡sticos', NULL),
(126, 'Arte Colaborativa', NULL),
(127, 'Sistema de numera├º├úo decimal', NULL),
(128, 'Opera├º├╡es fundamentais com n├║meros naturais', NULL),
(129, 'M├║ltiplos e divisores', NULL),
(130, 'O conceito de fra├º├úo', NULL),
(131, 'Opera├º├╡es fundamentais com n├║meros fracion├írios', NULL),
(132, 'Pol├¡gonos, tri├óngulos e quadril├íteros', NULL),
(133, 'N├║meros inteiros', NULL),
(134, 'Opera├º├╡es fundamentais com fra├º├╡es', NULL),
(135, 'Opera├º├╡es com n├║meros racionais nas formas fracion├íria e decimal', NULL),
(136, 'Figuras geom├⌐tricas planas no plano cartesiano', NULL),
(137, '├ürea de figuras geom├⌐tricas planas', NULL),
(138, 'Opera├º├╡es fundamentais com n├║meros racionais', NULL),
(139, 'Potencia├º├úo e propriedades da potencia├º├úo', NULL),
(140, 'Radicia├º├úo e rela├º├╡es entre radicia├º├úo e potencia├º├úo', NULL),
(141, 'Express├╡es alg├⌐bricas e no├º├╡es de ├ülgebra', NULL),
(142, 'Equa├º├╡es polinomiais do 1┬║ grau', NULL),
(143, 'Sistemas de equa├º├╡es polinomiais do 1┬║ grau', NULL),
Compara├º├úo, opera├º├╡es fundamentais e potencia├º├úo', NULL),
(145, 'Caracter├¡sticas dos tri├óngulos e semelhan├ºa de tri├óngulos', NULL),
(146, 'Semelhan├ºa de tri├óngulos e teorema de Pit├ígoras', NULL),
(147, 'N├║meros irracionais e d├¡zimas peri├│dicas', NULL),
(148, 'N├║meros reais', NULL),
(149, 'N├║meros racionais', NULL),
(150, 'Teorema de Pit├ígoras', NULL),
(151, 'Conceito de fun├º├úo', NULL),
(152, 'Rela├º├úo entre grandezas e equa├º├╡es polinomiais de 1┬║ grau', NULL),
(153, 'Fun├º├úo Afim ΓÇô Parte 1', NULL),
(154, 'Potencia├º├úo e nota├º├úo cient├¡fica', NULL),
(155, 'Equa├º├╡es polinomiais do 1┬║ e 2┬║ graus', NULL),
(156, 'Equa├º├╡es exponenciais', NULL),
(157, 'Fun├º├╡es exponenciais', NULL),
(158, 'Logaritmos', NULL),
(159, 'Fun├º├╡es logar├¡tmicas', NULL),
(160, 'Equa├º├╡es polinomiais do 1┬░ e 2┬░ graus', NULL),
(161, 'Sistemas de equa├º├╡es lineares ΓÇô Parte 1', NULL),
(162, '138 - 173 Sistemas de equa├º├╡es lineares ΓÇô Parte 2', NULL),
(163, 'An├ílise combinat├│ria', NULL),
(164, 'Probabilidade ΓÇô Parte 1', NULL),
(165, 'Probabilidade ΓÇô Parte 2', NULL),
(166, 'Leitura de post', NULL),
(167, 'Leitura de coment├írios', NULL),
(168, 'Leitura de not├¡cia', NULL),
(169, 'Leitura de charge', NULL),
(170, 'Acento circunflexo', NULL),
(171, 'Leitura de carta do leitor', NULL),
exclama├º├úo e retic├¬ncias', NULL),
fato central ├ù subtemas', NULL),
substantivos', NULL),
adjetivos', NULL),
s├¡laba t├┤nica e acento gr├ífico', NULL),
X e CH', NULL),
(178, 'Pontua├º├úo', NULL),
uso da cedilha', NULL),
(180, 'Termina├º├úo -gem', NULL),
(181, 'Palavras "mau" e "mal"', NULL),
(182, 'Acentua├º├úo em palavras ox├¡tonas, proparox├¡tonas e parox├¡tonas', NULL),
(183, 'O sentido de sufixos', NULL),
(184, 'Leitura de poema', NULL),
(185, 'Leitura de conto', NULL),
(186, 'Leitura de lenda', NULL),
(187, 'Leitura de trecho de romance infantojuvenil', NULL),
(188, 'Leitura de cr├┤nica liter├íria', NULL),
(189, 'Concord├óncia nominal', NULL),
verbos', NULL),
(191, 'Concord├óncia verbal (sujeito simples)', NULL),
(192, 'Sin├┤nimos e ant├┤nimos', NULL),
(193, 'O sentido de prefixos', NULL),
(194, 'Leitura de carta de reclama├º├úo', NULL),
subjuntivo. Tempos e modos verbais', NULL),
artigos definidos e indefinidos', NULL),
(197, 'Leitura e compreens├úo de poemas', NULL),
(198, 'Compara├º├úo de not├¡cias', NULL),
(199, 'Fato ├ù opini├úo em textos jornal├¡sticos', NULL),
(200, 'Leitura de an├║ncio publicit├írio', NULL);
