INSERT INTO curriculum_contents (id, descricao, unidade_tematica) VALUES
(201, 'Linguagem verbal e não verbal em anúncios publicitários', NULL),
(202, 'Leitura de anúncio publicitário em mídias digitais', NULL),
(203, 'Leitura de reportagem', NULL),
(204, 'Leitura de fotorreportagem', NULL),
(205, 'Características de fotorreportagens', NULL),
(206, 'Leitura de petição', NULL),
(207, 'Leitura de entrevista', NULL),
(208, 'Coesão', NULL),
(209, 'Ortografia: uso de Ç e SS', NULL),
(210, 'Leitura e interpretação de notícias', NULL),
(211, 'Pronome demonstrativo', NULL),
(212, 'Modalização discursiva', NULL),
(213, 'Acento diferencial', NULL),
(214, 'Leitura: diferentes escolhas editoriais sobre um mesmo fato', NULL),
(215, 'Fato e opinião', NULL),
(216, 'Leitura de textos multissemióticos', NULL),
(217, 'Leitura de anúncio publicitário. Palavras-valise', NULL),
(218, 'Recursos linguístico-discursivos em folhetos/flyers de anúncios publicitários', NULL),
(219, 'Leitura de artigo de divulgação científica. Elementos do artigo de divulgação científica', NULL),
(220, 'Paragrafação', NULL),
(221, 'Tese', NULL),
(222, 'Opinião', NULL),
(223, 'Estratégias argumentativas', NULL),
(224, 'Verbo de ação', NULL),
(225, 'Verbo de estado', NULL),
(226, 'Leitura de biografia e de autobiografia. Verbo: pretérito. Conjunção', NULL),
(227, 'Leitura de romance infantojuvenil. Leitura de conto popular', NULL),
(228, 'Leitura de conto de ficção científica. Estratégias de leitura. Fábula', NULL),
(229, 'Elemento da narrativa: narrador e personagens', NULL),
(230, 'Verbos de enunciação', NULL),
(231, 'Leitura de parábola', NULL),
(232, 'Diário ficcional. Progressão textual: causa e consequência', NULL),
(233, 'Leitura de poemas', NULL),
(234, 'Poemas de versos livres × forma fixa', NULL),
(235, 'Leitura de conto indígena', NULL),
(236, 'Estratégias de leitura', NULL),
(237, 'Mecanismos da narrativa', NULL),
(238, 'Elementos dos livros: quarta capa', NULL),
(239, 'Programa (de teatro, dança, exposições etc.)', NULL),
(240, 'Leitura de cartaz de campanha', NULL),
(241, 'Comparação entre peças publicitárias', NULL),
(242, 'Estratégias de persuasão com recursos linguístico-discursivos (jogos de palavras, metáforas, sentidos figurados etc.)', NULL),
(243, 'Intertextualidade em textos diversos', NULL),
(244, 'Valores culturais em textos literários', NULL),
(245, 'Contos populares', NULL),
(246, 'Estratégias de leitura de textos literários', NULL),
(247, 'Práticas de leitura de textos literários', NULL),
(248, 'Contos indígenas', NULL),
(249, 'Leitura de piadas e anedotas', NULL),
(250, 'Leitura de contos de humor', NULL),
(251, 'Leitura de paródia e sátira', NULL),
(252, 'Leitura de mito', NULL),
(253, 'Coesão e coerência em textos narrativos', NULL),
(254, 'Tessitura textual', NULL),
(255, 'Leitura de crônica', NULL),
(256, 'Relato de viagem', NULL),
(257, 'Adjuntos adverbiais', NULL),
(258, 'Leitura de notícia impressa e digital', NULL),
(259, 'Leitura e análise crítica de artigo de opinião', NULL),
(260, 'Leitura de trecho de romance', NULL),
(261, 'Características de texto de divulgação científica', NULL),
(262, 'Pontuação: parênteses e aspas', NULL),
(263, 'Leitura de memórias', NULL),
(264, 'Leitura de biografia', NULL),
(265, 'Leitura de autobiografia', NULL),
(266, 'Leitura de diário pessoal', NULL),
(267, 'Compreensão de efeitos de sentido', NULL),
(268, 'Verbos', NULL),
(269, 'Estudo de tempos verbais', NULL),
(270, 'Presente histórico', NULL),
(271, 'Pretérito imperfeito do indicativo', NULL),
(272, 'Pontuação: ponto-final', NULL),
(273, 'Oração: sujeito e predicado', NULL),
(274, 'Concordância verbal e nominal', NULL),
(275, 'Observar uso de hífen no texto e conhecer critérios de hifenização', NULL),
(276, 'Modos indicativo e subjuntivo', NULL),
(277, 'Ortografia: acentuação', NULL),
(278, 'Transitividade verbal', NULL),
(279, 'Tempos e modos verbais', NULL),
(280, 'Sentido real e figurado de palavras', NULL),
(281, 'Artigos definidos e indefinidos', NULL),
(282, 'Verbo "haver" como auxiliar', NULL),
(283, 'Pretérito perfeito e imperfeito do indicativo', NULL),
(284, 'Notícia: fato central', NULL),
(285, 'Reportagem: fato central', NULL),
(286, 'Entrevista: ideia central', NULL),
(287, 'Reportagem: relação entre parágrafos', NULL),
(288, 'Comparação entre editorial e artigo de opinião. Confiabilidade em textos jornalísticos', NULL),
(289, 'Argumentação', NULL),
(290, 'Acentuação: oxítonas, paroxítonas e proparoxítonas', NULL),
(291, 'Leitura de tirinha', NULL),
(292, 'Leitura de cartaz instrucional (primeiros socorros)', NULL),
(293, 'Cartaz sobre direitos e deveres do estudante', NULL),
(294, 'Leitura de cartaz de campanha de saúde', NULL),
(295, 'Estratégias de persuasão', NULL),
(296, 'Características de anúncios publicitários', NULL),
(297, 'Figura de linguagem: metáfora', NULL),
(298, 'Verbo: modo imperativo', NULL),
(299, 'Leitura de anúncio publicitário digital', NULL),
(300, 'Ortografia', NULL),
(301, 'Ficha catalográfica', NULL),
(302, 'Resumo', NULL),
(303, 'Leitura de esquema(s)', NULL),
(304, 'Leitura de relatório(s)', NULL),
(305, 'Leitura de petição online', NULL),
(306, 'Coesão sequencial', NULL),
(307, 'Modalizadores argumentativos', NULL),
(308, 'Leitura de carta aberta', NULL),
(309, 'Ler memes e gifs, analisando efeitos de sentido gerados pelo uso de linguagem verbal, não verbal e mista', NULL),
(310, 'Refletir e posicionar-se de forma crítica e ética sobre opiniões e visões de mundo expressas por esses gêneros da cultura digital', NULL),
(311, 'Posts e comentários', NULL),
(312, 'Adequação do registro escrito', NULL),
(313, 'A Idade Média em Portugal e a influência da cultura galego-portuguesa. Flexão verbal (tempos e modos verbais)', NULL),
(314, 'As origens do Trovadorismo no século XII. A primeira época medieval. Conjugações verbais regulares e irregulares', NULL),
(315, 'Cantigas: amor, amigo, escárnio e maldizer', NULL),
(316, 'A segunda época medieval: fragmento de O Auto da Barca do Inferno, de Gil Vicente', NULL),
(317, 'Contexto histórico do Classicismo. Fragmento da obra épica Os Lusíadas, de Camões. Vida e obra de Luís Vaz de Camões e sua influência', NULL),
(318, 'Leitura de poemas. Comparação entre características de obras clássicas e obras marginais. Conceito de literatura marginal. Contracultura', NULL),
(319, 'Leitura e compreensão de poema', NULL),
(320, 'Figuras de linguagem (comparação, metáfora, antítese e eufemismo)', NULL),
(321, 'Leitura e compreensão de biografia. Leitura e compreensão de poema', NULL),
(322, 'Leitura e compreensão de poemas. Figuras de linguagem (hipérbole, paradoxo e personificação). Sonoridade em textos poéticos (rima, aliteração, assonância e eufonia)', NULL),
(323, 'Verbos. Flexão verbal', NULL),
(324, 'Elementos mórficos na formação de palavras. Formação de palavras (radicais, prefixos, sufixos)', NULL),
(325, 'Tipos de sujeito (simples, composto, oculto, indeterminado)', NULL),
(326, 'Poema falado: slam. Linguagem informal e variedades linguísticas', NULL),
(327, 'A norma-padrão e a variação linguística. Ortografia e a contracultura na “geração mimeógrafo”. A poesia periférica e a construção ortográfica', NULL),
(328, 'Advérbios e locuções adverbiais', NULL),
(329, 'Regência verbal e nominal', NULL),
(330, 'Morfologia: estrutura das palavras (radical, desinência, vogal temática, tema e afixos)', NULL),
(331, 'Processos de formação de palavras: derivação', NULL),
(332, 'Concordância verbal com sujeito composto', NULL),
(333, 'Regência nominal e verbal', NULL),
(334, 'Período composto por coordenação e subordinação', NULL),
(335, 'Poema falado: slam', NULL),
(336, 'Versificação', NULL),
(337, 'Intertextualidade. Paráfrase e paródia', NULL),
(338, 'Denotação e conotação em textos literários. Efeitos de sentido', NULL),
(339, 'Linguagem verbal e não verbal: charges e cartuns', NULL),
(340, 'Neologismo. Estrangeirismo', NULL),
(341, 'Acentuação de palavras', NULL),
(342, 'Elementos coesivos', NULL),
(343, 'Compreensão de texto', NULL),
(344, 'Sensibilização para sentidos literais e não literais', NULL),
(345, 'Literatura periférica', NULL),
(346, 'Fatos e opiniões no texto jornalístico. Pronomes demonstrativos', NULL),
(347, 'Análise de manchetes de jornais. Presente histórico', NULL),
(348, 'Fotonotícias. Fotorreportagens. Fotodenúncias', NULL),
(349, 'Leitura e análise de infográficos', NULL),
(350, 'Leitura de artigo de opinião', NULL),
(351, 'Resenha crítica', NULL),
(352, 'Reflexão crítica sobre função social e intencionalidade de textos', NULL),
(353, 'Leitura de texto de opinião. Movimentos argumentativos (sustentação e negociação)', NULL),
(354, 'Leitura de textos publicitários. Análise de efeitos de sentido (verbais e não verbais). Função social e estrutura do gênero anúncio publicitário', NULL),
(355, 'Leitura de textos publicitários. Ortografia: palavras que geram dúvida', NULL),
(356, 'Gênero debate', NULL),
(357, 'Debate: Parte 1 – preparação para o evento', NULL),
(358, 'Debate: Parte 2 – apresentação do evento a partir da discussão de tópicos polêmicos', NULL),
(359, 'Debate: Parte 3 – avaliação dos grupos do debate (planejamento, produção, revisão dos textos e apresentação oral)', NULL),
(360, 'Período composto por coordenação', NULL),
(361, 'Texto literário e não literário (definição)', NULL),
(362, 'Contexto de produção e circulação de textos literários (Barroco, Arcadismo e Pré- Romantismo)', NULL),
(363, 'Intertextualidade e interdiscursividade', NULL),
(364, 'Construção de sentido a partir da relação entre textos', NULL),
(365, 'Introdução ao Romantismo', NULL),
(366, 'Romantismo em Portugal', NULL),
(367, 'Estrutura da oração (sujeito, predicado)', NULL),
(368, 'Estrutura da oração (sujeito, predicado, complementos verbais e nominais)', NULL),
(369, 'Emprego da conjunção adversativa “mas” e do advérbio de intensidade comparativa “mais”', NULL),
(370, 'Conectivos – conjunções e locuções conjuntivas', NULL),
(371, 'Uso de pronomes', NULL),
(372, 'Slogan. Pontuação', NULL),
(373, 'Morfossintaxe e estilo nos textos literários: ordem dos constituintes, coordenação, subordinação, concordância e regência. Efeitos de sentido gerados pelas escolhas linguísticas e estruturais. Contextualização das escolhas linguísticas conforme época, autor e situação comunicativa', NULL),
(374, 'Acentuação', NULL),
(375, 'Poema – marcas do gênero. Contexto de produção de texto literário', NULL),
(376, 'Gregório de Matos. Informações sobre o poeta e seu tempo. A poesia satírica. Análise de poema', NULL),
(377, 'Arcadismo: período e características, principais autores e obras', NULL),
(378, 'Barroco e Arcadismo: períodos e características, principais autores e obras', NULL),
(379, 'Barroco (retomada): período e características, principais autores e obras. Emprego do verbo "haver"', NULL),
(380, 'Neoclassicismo e Pré-Romantismo português', NULL),
(381, 'O abolicionismo na literatura romântica brasileira. Maria Firmina dos Reis e o Romantismo no Brasil. Construção frasal e recursos linguísticos', NULL),
(382, 'Mulheres na literatura romântica no Brasil. Narcisa Amália e o Romantismo no Brasil. O abolicionismo na literatura romântica brasileira', NULL),
(383, 'Textos multimodais diversos', NULL),
(384, 'Artigo de opinião', NULL),
(385, 'Leitura de cartaz', NULL),
(386, 'Leitura de texto de divulgação científica', NULL),
(387, 'Identificação e inferência de motivações e/ou finalidades do texto/autor', NULL),
(388, 'Textos de divulgação científica: estrutura e características', NULL),
(389, 'Progressão temática', NULL),
(390, 'Pesquisa científica', NULL),
(391, 'Curadoria de informações', NULL),
(392, 'Referências bibliográficas e normas de referência', NULL),
(393, 'Citação direta e indireta', NULL),
(394, 'Gênero resumo', NULL),
(395, 'Citação direta e paráfrase', NULL),
(396, 'Análise de resenha crítica de livro', NULL),
(397, 'Adjetivos e orações adjetivas', NULL),
(398, 'Escrita e compartilhamento de resenhas', NULL),
(399, 'O gênero sinopse', NULL),
(400, 'Leitura de verbete enciclopédico. Compreensão do tipo textual expositivo. Denotação e conotação', NULL);
