INSERT INTO curriculum_contents (id, descricao, unidade_tematica) VALUES
(401, 'Modalizadores discursivos. Tipos de modalizadores. AnÃ¡lise de modalizadores em diferentes textos', NULL),
(402, 'Leitura e anÃ¡lise de conto. Classes de palavras (revisÃ£o)', NULL),
(403, 'Leitura de e anÃ¡lise de artigo de opiniÃ£o. Conectores sequenciais e referenciais', NULL),
caracterÃ­sticas', NULL),
(405, 'Leitura e interpretaÃ§Ã£o', NULL),
(406, 'Linguagem verbal, nÃ£o verbal e mista', NULL),
(407, 'Leitura e anÃ¡lise de resultados de pesquisa', NULL),
(408, 'Curadoria de textos de cientÃ­ficos', NULL),
(409, 'Artigo cientÃ­fico como fonte de pesquisa', NULL),
(410, 'Textos cientÃ­ficos e sua funÃ§Ã£o social', NULL),
(411, 'GÃªnero anÃºncio publicitÃ¡rio', NULL),
(412, 'Elementos de persuasÃ£o', NULL),
(413, 'Modo imperativo do verbo', NULL),
(414, 'GÃªnero anÃºncio publicitÃ¡rio e slogan', NULL),
(415, 'Tipo textual injuntivo', NULL),
(416, 'FunÃ§Ã£o apelativa ou conativa da linguagem', NULL),
(417, 'Linguagem verbal e nÃ£o verbal', NULL),
(418, 'GÃªnero conto. Foco narrativo', NULL),
(419, 'GÃªnero literÃ¡rio conto. Elementos da narrativa', NULL),
(420, 'Leitura e anÃ¡lise de contos. ReconstruÃ§Ã£o das condiÃ§Ãµes de produÃ§Ã£o, circulaÃ§Ã£o e recepÃ§Ã£o de textos artÃ­stico-literÃ¡rios no Brasil. JosÃ© de Alencar e sua relevÃ¢ncia na literatura brasileira. Literatura indianista', NULL),
(421, 'Literatura comparada. AnÃ¡lise de texto indianista do sÃ©culo XIX e literatura indÃ­gena contemporÃ¢nea', NULL),
(422, 'Planejamento de texto de divulgaÃ§Ã£o cientÃ­fica', NULL),
(423, 'Banner de divulgaÃ§Ã£o cientÃ­fica', NULL),
exposiÃ§Ã£o e discussÃ£o', NULL),
(425, 'AutoavaliaÃ§Ã£o de apresentaÃ§Ã£o', NULL),
(426, 'Tese, argumentos, refutaÃ§Ã£o', NULL),
(427, 'PrÃ©-Modernismo. Euclides da Cunha. Lima Barreto. Augusto dos Anjos', NULL),
(428, 'A poÃ©tica de Oswald de Andrade. Revistas modernistas brasileiras. Ortografia', NULL),
(429, 'Leitura de poemas. ComparaÃ§Ã£o de literaturas (portuguesa, africana, brasileira, indÃ­gena, latino-americana etc.). Contexto de produÃ§Ã£o de texto literÃ¡rio', NULL),
(430, 'Leitura do conto "Pai contra mÃ£e", de Machado de Assis. CompreensÃ£o do conto. AnÃ¡lise do contexto de produÃ§Ã£o', NULL),
personificaÃ§Ã£o', NULL),
(432, 'Leitura de conto de GuimarÃ£es Rosa. CompreensÃ£o do conto. AnÃ¡lise de efeitos de sentido de trechos especÃ­ficos', NULL),
(433, 'Efeitos de sentido do conto. AnÃ¡lise de contexto de produÃ§Ã£o. VariaÃ§Ã£o linguÃ­stica', NULL),
(434, 'Leitura de conto. CompreensÃ£o do conto. AnÃ¡lise de efeitos de sentido de trechos especÃ­ficos', NULL),
(435, 'Leitura e compreensÃ£o do conto. AnÃ¡lise dos efeitos de sentido do conto. AnÃ¡lise de contexto de produÃ§Ã£o', NULL),
(436, 'Conceito de manifesto e antropofagia. Manifesto antropÃ³fago', NULL),
(437, 'Semana de Arte Moderna. PoÃ©tica de Manuel Bandeira', NULL),
(438, 'Primeira geraÃ§Ã£o modernista. PoÃ©tica de MÃ¡rio de Andrade', NULL),
(439, 'Primeira geraÃ§Ã£o modernista. PoÃ©tica de Oswald de Andrade', NULL),
(440, 'Segunda geraÃ§Ã£o modernista e poesia dos anos 1930. PoÃ©tica de Carlos Drummond de Andrade', NULL),
(441, 'Segunda geraÃ§Ã£o modernista e poesia dos anos 1930. PoÃ©tica de Murilo Mendes', NULL),
prosa regionalista. Prosa de Rachel de Queiroz', NULL),
prosa regionalista. Prosa de Graciliano Ramos', NULL),
prosa regionalista. Prosa de Jorge Amado', NULL),
(445, 'Leitura e anÃ¡lise de crÃ´nica', NULL),
caracterÃ­sticas', NULL),
(447, 'Leitura e compreensÃ£o de artigo de opiniÃ£o', NULL),
(448, 'ComparaÃ§Ã£o de dados e informaÃ§Ãµes em textos de divulgaÃ§Ã£o cientÃ­fica opinativos', NULL),
(449, 'IdentificaÃ§Ã£o de posicionamento crÃ­tico', NULL),
(450, 'AveriguaÃ§Ã£o de fidedignidade de informaÃ§Ãµes', NULL),
(451, 'Editorial. ReflexÃ£o crÃ­tica sobre funÃ§Ã£o social e intencionalidade de textos', NULL),
(452, 'Formas contemporÃ¢neas de publicidade. ReflexÃ£o crÃ­tica sobre funÃ§Ã£o social e intencionalidade de textos', NULL),
(453, 'Leitura de notÃ­cia. VisÃ£o de mundo no texto. IdentificaÃ§Ã£o e inferÃªncia de motivaÃ§Ãµes e/ou finalidades do texto/autor', NULL),
(454, 'Leitura de reportagem. Vozes no texto. IdentificaÃ§Ã£o e inferÃªncia de motivaÃ§Ãµes e/ou finalidades do texto/autor. RegÃªncia verbal e nominal', NULL),
(455, 'Leitura e anÃ¡lise de editorial', NULL),
(456, 'OraÃ§Ãµes subordinadas adjetivas; ModalizaÃ§Ã£o textual', NULL),
(457, 'ModalizaÃ§Ã£o textual; OraÃ§Ãµes subordinadas adverbiais', NULL),
(458, 'OraÃ§Ãµes coordenadas sindÃ©ticas aditivas, adversativas, alternativas, conclusivas, explicativas', NULL),
(459, 'Paralelismo sintÃ¡tico', NULL),
metonÃ­mia e sinestesia', NULL),
estrutura e caracterÃ­sticas. Sinais de pontuaÃ§Ã£o', NULL),
(462, 'Operadores lÃ³gico-discursivos', NULL),
(463, 'Ordem direta e inversÃµes', NULL),
(464, 'ConjunÃ§Ãµes e outros elementos coesivos', NULL),
Iracema e Senhora, ambas de JosÃ© de Alencar', NULL),
Dom Casmurro, de Machado de Assis', NULL),
(467, 'SistematizaÃ§Ã£o de diferenÃ§as marcantes entre romances romÃ¢nticos e realistas, com base em trechos de livros', NULL),
(468, 'DefiniÃ§Ãµes e caracterÃ­sticas das vanguardas europeias', NULL),
(469, 'Leitura e anÃ¡lise de crÃ´nica. Intertextualidade. Polissemia', NULL),
(470, 'Leitura e compreensÃ£o do Estatuto da Pessoa Idosa (texto normativo)', NULL),
(471, 'Entrevista oral', NULL),
(472, 'Marcas de oralidade', NULL),
(473, 'VariaÃ§Ã£o linguÃ­stica', NULL),
(474, 'Marcas de oralidade em textos transcritos', NULL),
(475, 'Tipos de transcriÃ§Ã£o', NULL),
(476, 'DefiniÃ§Ã£o de esporte de invasÃ£o. HistÃ³ria do handebol. Regras do handebol. Movimentos/fundamentos. PosiÃ§Ãµes e sistemas tÃ¡ticos', NULL),
Queimada', NULL),
Resgate', NULL),
empunhadura, recepÃ§Ã£o, passe, finta, drible e arremesso', NULL),
(480, 'ExercÃ­cios em duplas, trios e grupos, se utilizando dos fundamentos do handebol', NULL),
(481, 'Jogo de handebol com equipes femininas e equipes masculinas', NULL),
(482, 'Jogo de handebol com equipes mistas', NULL),
(483, 'Esporte de marca. Atletismo. Provas do atletismo. Esportes e Jogos ParalÃ­mpicos. Atletismo paralÃ­mpico', NULL),
(484, 'Corrida de velocidade. Corrida de revezamento', NULL),
(485, 'Corrida com barreiras. Corrida com obstÃ¡culos', NULL),
(486, 'Salto vertical. Salto horizontal', NULL),
(487, 'Arremesso de peso. LanÃ§amento de disco', NULL),
(488, 'Caminhada de olhos vendados', NULL),
(489, 'com guia', NULL),
(490, 'Corrida de olhos vendados', NULL),
origem; elementos constitutivos; diferentes estilos e evoluÃ§Ã£o em diferentes Ã©pocas', NULL),
o movimento, a mÃºsica e a danÃ§a Hip-hop', NULL),
(493, 'Diferentes sensaÃ§Ãµes atravÃ©s da danÃ§a', NULL),
RAP', NULL),
(495, 'Movimentos do Break', NULL),
(496, 'CriaÃ§Ã£o de coreografias de hip-hop em grupos', NULL),
(497, 'Ensaio das coreografias criadas', NULL),
(498, 'ApresentaÃ§Ã£o das coreografias criadas', NULL),
(499, 'DefiniÃ§Ã£o de GinÃ¡stica de Condicionamento FÃ­sico:', NULL),
(500, 'Conceito de Capacidades FÃ­sicas', NULL),
(501, 'Conceito de exercÃ­cios aerÃ³bios e exercÃ­cios anaerÃ³bios', NULL),
(502, 'BenefÃ­cios da GCF e prÃ¡tica de alongamento (flexibilidade)', NULL),
(503, 'Circuito de capacidades fÃ­sicas (flexibilidade, velocidade, agilidade, resistÃªncia e forÃ§a)', NULL),
(504, 'Estafetas de capacidades fÃ­sicas (velocidade e agilidade)', NULL),
(505, 'ExercÃ­cios aerÃ³bios (caminhar, correr e pedalar)', NULL),
(506, 'ExercÃ­cios anaerÃ³bios (membros superiores)', NULL),
(507, 'ExercÃ­cios anaerÃ³bios (membros inferiores)', NULL),
(508, 'Lutas do Brasil', NULL),
(509, 'Conceitos', NULL),
(510, 'Capoeira Regional Ã Capoeira Angola', NULL),
(511, 'Golpes da capoeira', NULL),
(512, 'A mÃºsica, os instrumentos e o ritmo da capoeira', NULL),
(513, 'A ginga como posiÃ§Ã£o base da capoeira', NULL),
Meia-lua de frente;Queixada; Armada', NULL),
Martelo, BÃªnÃ§Ã£o, AÃº, Cocorinha etc', NULL),
(516, 'Atividades lÃºdicas se utilizando de movimentos da capoeira, em roda', NULL),
(517, 'Roda de capoeira com os golpes aprendidos', NULL),
(518, 'DefiniÃ§Ã£o de Esporte de precisÃ£o', NULL),
(519, 'O boliche como esporte de precisÃ£o', NULL),
(520, 'A bocha como esporte de precisÃ£o', NULL),
(521, 'A bocha paralÃ­mpica', NULL),
(522, 'PrÃ¡ticas alternativas de precisÃ£o', NULL),
(523, 'ConfecÃ§Ã£o de materiais para jogar boliche e bocha nas aulas de EducaÃ§Ã£o FÃ­sica', NULL),
(524, 'Jogo de boliche com os materiais confeccionados', NULL),
(525, 'Jogo de bocha com os materiais confeccionados', NULL),
(526, 'Jogo de bocha no contexto paralÃ­mpico', NULL),
(527, 'OpÃ§Ã£o de brincadeiras e jogos prÃ©-desportivos com materiais reciclÃ¡veis/ adaptados/ alternativos', NULL),
Street Dance', NULL),
Breaking, Locking, Popping e Freestyle', NULL),
(530, 'Passos bÃ¡sicos do breaking', NULL),
(531, 'Passos bÃ¡sicos do locking', NULL),
(532, 'Passos bÃ¡sicos do popping', NULL),
(533, 'Passos bÃ¡sicos do freestyle', NULL),
(534, 'CriaÃ§Ã£o e ensaio de coreografias de street dance, em grupos', NULL),
(535, 'GinÃ¡stica de condicionamento fÃ­sico', NULL),
(536, 'Capacidades fÃ­sicas em aÃ§Ã£o', NULL),
(537, 'BenefÃ­cios do exercÃ­cio regular', NULL),
(538, 'CriaÃ§Ã£o de exercÃ­cios em grupos, se utilizando da ginÃ¡stica de condicionamento fÃ­sico', NULL),
(539, 'Desafios que se utilizam de diferentes capacidades fÃ­sicas', NULL),
(540, 'ExploraÃ§Ã£o das capacidades fÃ­sicas por meio de exercÃ­cios em formato de circuito', NULL),
melhora da forÃ§a, resistÃªncia, postura e saÃºde cardiovascular./BenefÃ­cios mentais: bem', NULL),
cooperaÃ§Ã£o, respeito Ã s regras, convivÃªncia e trabalho em equipe', NULL),
(543, 'CriaÃ§Ã£o, em grupos, de programas de exercÃ­cios fÃ­sicos', NULL),
(544, 'ApresentaÃ§Ã£o, em grupos, dos programas de exercÃ­cios fÃ­sicos criados', NULL),
(545, 'DefiniÃ§Ã£o de esporte de rede/ parede', NULL),
(546, 'HistÃ³ria e caracterÃ­sticas do voleibol', NULL),
(547, 'Fundamentos e regras do voleibol', NULL),
(548, 'Posicionamento e RodÃ­zio', NULL),
(549, 'Esporte ParalÃ­mpico; vÃ´lei sentado', NULL),
VolenÃ§ol', NULL),
Rede Humana', NULL),
CÃ¢mbio', NULL),
saque por baixo, toque, machete etc', NULL),
(554, 'ExercÃ­cios em duplas, trios e grupos, se utilizando dos fundamentos do voleibol', NULL),
(555, 'Jogo de voleibol com 4 equipes praticando ao mesmo tempo (meia quadra)', NULL),
(556, 'Jogo de voleibol com rodÃ­zio 6x0', NULL),
(557, 'PrÃ¡tica e jogo de voleibol com regras, fundamentos e rodÃ­zio 6x0', NULL),
VÃ´lei sentado', NULL),
(559, 'DefiniÃ§Ã£o de esporte de campo e taco', NULL),
(560, 'Jogo de taco', NULL),
(561, 'Jogo base 4', NULL),
(562, 'Beisebol', NULL),
Taco', NULL),
Base 4', NULL),
(565, 'Jogo de Beisebol adaptado para o ambiente escolar', NULL),
(566, 'Conceito de lutas do mundo', NULL),
(567, 'Origem do JudÃ´, Jiu-Jitsu e do CaratÃª', NULL),
(568, 'CaracterÃ­sticas especÃ­ficas do JudÃ´, Jiu-Jitsu e CaratÃª', NULL),
(569, 'SaudaÃ§Ãµes e Ukemis do JudÃ´', NULL),
(570, 'TÃ©cnicas de perna, braÃ§o e quadril no JudÃ´', NULL),
(571, 'VivÃªncias do JudÃ´', NULL),
(572, 'simulaÃ§Ã£o de luta', NULL),
(573, 'Jogos de oposiÃ§Ã£o no Jiu-Jitsu', NULL),
(574, 'TÃ©cnicas do Jiu-Jitsu', NULL),
(575, 'SaudaÃ§Ãµes e bases no caratÃª', NULL),
(576, 'Chutes no caratÃª', NULL),
(577, 'Socos e defesas no caratÃª', NULL),
(578, 'Katas no caratÃª', NULL),
(579, 'Materiais Digitais -Origem e evoluÃ§Ã£o do JudÃ´ para cegos', NULL),
(580, 'MudanÃ§as e adequaÃ§Ãµes Ã s regras base do judÃ´ para sua versÃ£o paralÃ­mpica', NULL),
(581, 'Ukemis e movimentaÃ§Ãµes', NULL),
(582, 'TÃ©cnicas de perna, braÃ§o e quadril no JudÃ´ para cegos', NULL),
(583, 'VivÃªncias do JudÃ´ para cegos', NULL),
(584, 'Retomada da definiÃ§Ã£o de esporte de invasÃ£o', NULL),
(585, 'HistÃ³ria do futsal', NULL),
(586, 'Regras e fundamentos do futsal', NULL),
Futebol de cegos', NULL),
(588, 'Fundamentos do futsal atravÃ©s de estafetas; domÃ­nio, conduÃ§Ã£o, drible, passe de chapa, chute ao gol etc', NULL),
(589, 'ExercÃ­cios em duplas, trios e grupos, se utilizando dos fundamentos do futsal', NULL),
Futsal de duplas', NULL),
(591, 'Jogo de Futsal com regras e fundamentos', NULL),
(592, 'equipes mistas', NULL),
(593, 'Jogo de futsal com regras e fundamentos', NULL),
(594, 'equipes femininas e equipes masculinas', NULL),
(595, 'HistÃ³ria do basquetebol', NULL),
(596, 'Regras e fundamentos do basquetebol', NULL),
basquete em cadeira de rodas', NULL),
(598, 'Fundamentos do basquete atravÃ©s de estafetas; drible, passe, arremesso, rebote, defesa, bloqueio etc', NULL),
(599, 'ExercÃ­cios em duplas, trios e grupos, se utilizando dos fundamentos do basquete', NULL),
Torrebol', NULL);
