INSERT INTO aprendizagens_essenciais (id, nivel_ensino, disciplina, ano_serie, bimestre, codigo, descricao, created_at) VALUES
(251, 'Ensino Médio', 'Química', '2ª Série', NULL, 'AE5', 'Analisar a estrutura, a síntese e as aplicações de polímeros naturais e sintéticos, identificando as principais reações de polimerização e casos de isomeria cis-trans.', NOW()),
(252, 'Ensino Médio', 'Sociologia', '2ª Série', NULL, 'AE1', 'Analisar a especificidade do conhecimento sociológico como campo científico, reconhecendo seus conceitos fundamentais e teorias clássicas da relação entre indivíduo e sociedade, aplicando-os na análise de processos sociais.', NOW()),
(253, 'Ensino Médio', 'Sociologia', '2ª Série', NULL, 'AE2', 'Analisar a relação entre o indivíduo e o contexto sociocultural em que vive, aplicando conceitos da antropologia e da sociologia, identificando os processos que tornam os humanos seres sociais e culturais.', NOW()),
(254, 'Ensino Médio', 'Sociologia', '2ª Série', NULL, 'AE3', 'Elaborar hipóteses e argumentos a partir da análise de evidências de processos sociais, culturais e políticos, de informações confiáveis e da coleta e sistematização de dados.', NOW()),
(255, 'Ensino Médio', 'Sociologia', '2ª Série', NULL, 'AE4', 'Analisar as relações entre sujeitos e grupos no mundo contemporâneo, aplicando os conceitos de diferenciação, produção social da diferença, estratificação e classe social, para explicar problemas de convivência, exclusão social, marginalização e desigualdades.', NOW()),
(256, 'Ensino Médio', 'Sociologia', '2ª Série', NULL, 'AE5', 'Analisar as diferentes formas de violência presentes no cotidiano, compreendendo suas causas sociais, culturais e institucionais e discutindo seus impactos na convivência social.', NOW()),
(257, 'Ensino Médio', 'Sociologia', '2ª Série', NULL, 'AE6', 'Analisar situações da vida cotidiana, estilos de vida, valores e condutas, aplicando conceitos sociológicos, para desnaturalizar formas de desigualdade, preconceito, intolerância, discriminação e violência presentes nas relações étnico-raciais, de gênero e em outros contextos sociais.', NOW()),
(258, 'Ensino Médio', 'Sociologia', '2ª Série', NULL, 'AE7', 'Analisar os princípios dos Direitos Humanos, como a dignidade humana, a igualdade e a não violência, para identificar práticas cotidianas de violação e avaliar ações que promovem a defesa desses direitos.', NOW());
