INSERT INTO aprendizagens_essenciais (id, nivel_ensino, disciplina, ano_serie, bimestre, codigo, descricao, created_at) VALUES
Anos Finais', 'Arte', '6Âº Ano', NULL, 'AE1', 'Diferenciar movimentos coreogrÃ¡ficos em danÃ§as folclÃ³ricas de diferentes Ã©pocas.', NOW()),
Anos Finais', 'Arte', '6Âº Ano', NULL, 'AE2', 'Experimentar composiÃ§Ãµes coreogrÃ¡ficas autorais com base em elementos das danÃ§as folclÃ³ricas brasileiras.', NOW()),
Anos Finais', 'Arte', '6Âº Ano', NULL, 'AE3', 'Analisar os gÃªneros da mÃºsica brasileira a partir de seus contextos de produÃ§Ã£o, circulaÃ§Ã£o e apreciaÃ§Ã£o.', NOW()),
Anos Finais', 'Arte', '6Âº Ano', NULL, 'AE4', 'Criar composiÃ§Ãµes musicais, por meio da voz, sons corporais e instrumentos nÃ£o convencionais, traduzindo-as em partituras criativas.', NOW()),
Anos Finais', 'Arte', '7Âº Ano', NULL, 'AE1', 'Relacionar elementos estruturais, origens e contextos das danÃ§as clÃ¡ssicas e modernas a partir da apreciaÃ§Ã£o de diferentes artistas e grupos.', NOW()),
Anos Finais', 'Arte', '7Âº Ano', NULL, 'AE2', 'Experimentar as variaÃ§Ãµes dos fatores do movimento (tempo, peso, fluÃªncia e espaÃ§o) na prÃ¡tica da danÃ§a.', NOW()),
Anos Finais', 'Arte', '7Âº Ano', NULL, 'AE3', 'Analisar as funÃ§Ãµes sociais e polÃ­ticas da mÃºsica clÃ¡ssica e do canto coral, considerando seus contextos histÃ³ricos.', NOW()),
Anos Finais', 'Arte', '7Âº Ano', NULL, 'AE4', 'Criar composiÃ§Ãµes musicais coletivamente, por meio de prÃ¡ticas de improvisaÃ§Ã£o.', NOW()),
Anos Finais', 'Arte', '7Âº Ano', NULL, 'AE5', 'Investigar instrumentos acÃºsticos, reconhecendo seus timbres.', NOW()),
Anos Finais', 'Arte', '8Âº Ano', NULL, 'AE1', 'Analisar composiÃ§Ãµes de danÃ§as coletivas de diferentes matrizes culturais brasileiras para apreciÃ¡-las.', NOW()),
Anos Finais', 'Arte', '8Âº Ano', NULL, 'AE2', 'Explorar as variaÃ§Ãµes dos fatores do movimento (tempo, fluÃªncia e espaÃ§o) explorando-os na prÃ¡tica da danÃ§a.', NOW()),
Anos Finais', 'Arte', '8Âº Ano', NULL, 'AE3', 'Compor sequÃªncias coreogrÃ¡ficas a partir de repertÃ³rio e vocabulÃ¡rio especÃ­fico da danÃ§a.', NOW()),
Anos Finais', 'Arte', '8Âº Ano', NULL, 'AE4', 'Explorar mÃºsicas de diferentes matrizes brasileiras e africanas, reconhecendo caracterÃ­sticas, usos, funÃ§Ãµes e timbres de instrumentos musicais diversos.', NOW()),
Anos Finais', 'Arte', '8Âº Ano', NULL, 'AE5', 'Analisar os elementos das mÃºsicas indÃ­genas como uma das matrizes culturais brasileiras, utilizando canÃ§Ãµes, jogos e apreciando as composiÃ§Ãµes.', NOW()),
Anos Finais', 'Arte', '8Âº Ano', NULL, 'AE6', 'Expressar ideias musicais de forma individual e coletiva, por meio da improvisaÃ§Ã£o e composiÃ§Ã£o com voz, sons corporais e instrumentos variados.', NOW()),
Anos Finais', 'Arte', '9Âº Ano', NULL, 'AE1', 'Analisar o uso de elementos cÃªnicos (figurino, cenÃ¡rio, iluminaÃ§Ã£o, espaÃ§os e tecnologias digitais) nos contextos de criaÃ§Ã£o coreogrÃ¡fica e apresentaÃ§Ãµes de danÃ§a.', NOW()),
Anos Finais', 'Arte', '9Âº Ano', NULL, 'AE2', 'Explorar brincadeiras e jogos no processo de criaÃ§Ã£o coreogrÃ¡fica em danÃ§a contemporÃ¢nea, integrando tecnologias digitais nas apresentaÃ§Ãµes.', NOW()),
Anos Finais', 'Arte', '9Âº Ano', NULL, 'AE3', 'Analisar funÃ§Ãµes e estÃ©ticas dos diferentes gÃªneros da mÃºsica popular brasileira e estrangeira, considerando seu contexto histÃ³rico e social.', NOW()),
Anos Finais', 'Arte', '9Âº Ano', NULL, 'AE4', 'Compor e decompor mÃºsicas, explorando variaÃ§Ãµes de timbre, altura, intensidade, melodia e ritmo com uso de diversas tecnologias, inclusive as digitais.', NOW()),
(20, 'Ensino MÃ©dio', 'Arte', '1Âª SÃ©rie', NULL, 'AE1', 'Analisar o funcionamento das linguagens artÃ­sticas em suas dimensÃµes visuais, verbais, sonoras e gestuais para a interpretaÃ§Ã£o e a produÃ§Ã£o de discursos presentes na mÃ­dia e em obras de diversos artistas.', NOW()),
(21, 'Ensino MÃ©dio', 'Arte', '1Âª SÃ©rie', NULL, 'AE2', 'Utilizar as linguagens artÃ­sticas, analisando sua aplicabilidade e sua funÃ§Ã£o como fenÃ´meno social, cultural, histÃ³rico, polÃ­tico e econÃ´mico.', NOW()),
(22, 'Ensino MÃ©dio', 'Arte', '1Âª SÃ©rie', NULL, 'AE3', 'Interpretar discursos midiÃ¡ticos, identificando visÃµes de mundo e interesses, para posicionar-se contra preconceitos e ideologias presentes na mÃ­dia.', NOW()),
(23, 'Ensino MÃ©dio', 'Arte', '1Âª SÃ©rie', NULL, 'AE4', 'Explorar as prÃ¡ticas de linguagem, discutindo os princÃ­pios e desafios contemporÃ¢neos, e atuando de forma crÃ­tica, criativa, solidÃ¡ria e Ã©tica.', NOW()),
(24, 'Ensino MÃ©dio', 'Arte', '1Âª SÃ©rie', NULL, 'AE5', 'Experimentar processos de criaÃ§Ã£o em diversas linguagens artÃ­sticas, considerando seus aspectos formais, seus funcionamentos e a produÃ§Ã£o de sentido, em diferentes contextos.', NOW()),
Anos Finais', 'MatemÃ¡tica', '6Âº Ano', NULL, 'AE1', 'Compor e decompor nÃºmeros naturais de diferentes ordens, reconhecendo as caracterÃ­sticas do sistema de numeraÃ§Ã£o decimal.', NOW()),
Anos Finais', 'MatemÃ¡tica', '6Âº Ano', NULL, 'AE2', 'Comparar e ordenar nÃºmeros naturais de diferentes ordens, utilizando, inclusive, a reta numÃ©rica como suporte.', NOW()),
Anos Finais', 'MatemÃ¡tica', '6Âº Ano', NULL, 'AE3', 'Resolver problemas envolvendo as quatro operaÃ§Ãµes fundamentais com nÃºmeros naturais, por meio de estratÃ©gias variadas.', NOW()),
Anos Finais', 'MatemÃ¡tica', '6Âº Ano', NULL, 'AE4', 'Resolver problemas envolvendo mÃºltiplos e divisores de nÃºmeros naturais, utilizando-os para ampliar as estratÃ©gias de cÃ¡lculo.', NOW()),
Anos Finais', 'MatemÃ¡tica', '6Âº Ano', NULL, 'AE5', 'Resolver problemas envolvendo cÃ¡lculo da fraÃ§Ã£o de uma quantidade, cujo resultado Ã© um nÃºmero natural.', NOW()),
Anos Finais', 'MatemÃ¡tica', '6Âº Ano', NULL, 'AE6', 'Comparar e ordenar fraÃ§Ãµes, utilizando equivalÃªncia, representaÃ§Ãµes visuais e a reta numÃ©rica como apoio.', NOW()),
Anos Finais', 'MatemÃ¡tica', '6Âº Ano', NULL, 'AE7', 'Resolver problemas que envolvam adiÃ§Ã£o ou subtraÃ§Ã£o de nÃºmeros racionais positivos na representaÃ§Ã£o fracionÃ¡ria, por meio de estratÃ©gias diversas.', NOW()),
Anos Finais', 'MatemÃ¡tica', '6Âº Ano', NULL, 'AE8', 'Classificar polÃ­gonos, considerando lados, vÃ©rtices e Ã¢ngulos, diferenciando os regulares dos nÃ£o regulares.', NOW()),
Anos Finais', 'MatemÃ¡tica', '6Âº Ano', NULL, 'AE9', 'Classificar triÃ¢ngulos em relaÃ§Ã£o Ã s medidas dos lados.', NOW()),
Anos Finais', 'MatemÃ¡tica', '6Âº Ano', NULL, 'AE10', 'Classificar quadrilÃ¡teros em relaÃ§Ã£o Ã s medidas dos lados e Ã¢ngulos, comparando suas classes.', NOW()),
Anos Finais', 'MatemÃ¡tica', '7Âº Ano', NULL, 'AE1', 'Resolver problemas que envolvam mÃºltiplos e divisores de nÃºmeros naturais, em contextos reais.', NOW()),
Anos Finais', 'MatemÃ¡tica', '7Âº Ano', NULL, 'AE2', 'Comparar e ordenar nÃºmeros inteiros, utilizando, inclusive, a reta numÃ©rica como recurso.', NOW()),
Anos Finais', 'MatemÃ¡tica', '7Âº Ano', NULL, 'AE3', 'Resolver problemas que envolvam operaÃ§Ãµes com nÃºmeros inteiros, por meio de estratÃ©gias diversas.', NOW()),
Anos Finais', 'MatemÃ¡tica', '7Âº Ano', NULL, 'AE4', 'Comparar e ordenar fraÃ§Ãµes associadas Ã s ideias de partes de inteiros, resultado da divisÃ£o, razÃ£o e operador, utilizando, inclusive, a reta numÃ©rica como apoio.', NOW()),
Anos Finais', 'MatemÃ¡tica', '7Âº Ano', NULL, 'AE5', 'Resolver problemas envolvendo as quatro operaÃ§Ãµes fundamentais com fraÃ§Ãµes, por meio de estratÃ©gias diversas de cÃ¡lculo e representaÃ§Ãµes visuais.', NOW()),
Anos Finais', 'MatemÃ¡tica', '7Âº Ano', NULL, 'AE6', 'Resolver problemas envolvendo as quatro operaÃ§Ãµes fundamentais com nÃºmeros racionais nas formas fracionÃ¡ria e decimal, estabelecendo relaÃ§Ãµes entre essas representaÃ§Ãµes.', NOW()),
Anos Finais', 'MatemÃ¡tica', '7Âº Ano', NULL, 'AE7', 'Reconhecer e representar figuras geomÃ©tricas planas no plano cartesiano, identificando suas caracterÃ­sticas.', NOW()),
Anos Finais', 'MatemÃ¡tica', '7Âº Ano', NULL, 'AE8', 'Resolver problemas de cÃ¡lculo de Ã¡reas de figuras planas, por meio da decomposiÃ§Ã£o em quadrados, retÃ¢ngulos e triÃ¢ngulos, utilizando a equivalÃªncia entre Ã¡reas e estabelecendo expressÃµes de cÃ¡lculos.', NOW()),
Anos Finais', 'MatemÃ¡tica', '8Âº Ano', NULL, 'AE1', 'Resolver problemas que envolvam cÃ¡lculos com nÃºmeros racionais, inclusive potÃªncias de expoentes inteiros, utilizando propriedades operatÃ³rias.', NOW()),
Anos Finais', 'MatemÃ¡tica', '8Âº Ano', NULL, 'AE2', 'Utilizar a relaÃ§Ã£o entre potenciaÃ§Ã£o e radiciaÃ§Ã£o para representar raÃ­zes como potÃªncias de expoente fracionÃ¡rio e resolver problemas.', NOW()),
Anos Finais', 'MatemÃ¡tica', '8Âº Ano', NULL, 'AE3', 'Calcular o valor numÃ©rico de expressÃµes algÃ©bricas, utilizando as propriedades das operaÃ§Ãµes.', NOW()),
Anos Finais', 'MatemÃ¡tica', '8Âº Ano', NULL, 'AE4', 'Resolver problemas que possam ser representados por equaÃ§Ãµes polinomiais do 1Âº grau, utilizando as propriedades da igualdade, e interpretÃ¡-los geometricamente.', NOW()),
Anos Finais', 'MatemÃ¡tica', '8Âº Ano', NULL, 'AE5', 'Resolver problemas com sistemas de equaÃ§Ãµes do 1Âº grau com duas incÃ³gnitas, utilizando a representaÃ§Ã£o grÃ¡fica no plano cartesiano.', NOW()),
Anos Finais', 'MatemÃ¡tica', '9Âº Ano', NULL, 'AE1', 'Resolver problemas envolvendo cÃ¡lculos de potenciaÃ§Ã£o e radiciaÃ§Ã£o com nÃºmeros racionais, utilizando as propriedades operatÃ³rias.', NOW()),
Anos Finais', 'MatemÃ¡tica', '9Âº Ano', NULL, 'AE2', 'Reconhecer as condiÃ§Ãµes necessÃ¡rias e suficientes para que dois triÃ¢ngulos sejam semelhantes, utilizando-as para resolver problemas.', NOW()),
Anos Finais', 'MatemÃ¡tica', '9Âº Ano', NULL, 'AE3', 'Reconhecer relaÃ§Ãµes mÃ©tricas do triÃ¢ngulo retÃ¢ngulo, entre elas o teorema de PitÃ¡goras, utilizando a semelhanÃ§a de triÃ¢ngulos.', NOW());
