INSERT INTO aprendizagens_essenciais (id, nivel_ensino, disciplina, ano_serie, bimestre, codigo, descricao, created_at) VALUES
Anos Finais', 'MatemÃ¡tica', '9Âº Ano', NULL, 'AE4', 'Resolver problemas com a aplicaÃ§Ã£o do teorema de PitÃ¡goras.', NOW()),
Anos Finais', 'MatemÃ¡tica', '9Âº Ano', NULL, 'AE5', 'Reconhecer que existem segmentos de reta cujo comprimento nÃ£o Ã© expresso por nÃºmero racional.', NOW()),
Anos Finais', 'MatemÃ¡tica', '9Âº Ano', NULL, 'AE6', 'Estimar a localizaÃ§Ã£o na reta numÃ©rica de nÃºmeros irracionais, reconhecendo que possuem representaÃ§Ã£o decimal infinita e nÃ£o periÃ³dica.', NOW()),
Anos Finais', 'MatemÃ¡tica', '9Âº Ano', NULL, 'AE7', 'Resolver problemas envolvendo os nÃºmeros reais, realizando operaÃ§Ãµes e representando esses nÃºmeros na reta numÃ©rica.', NOW()),
(55, 'Ensino MÃ©dio', 'MatemÃ¡tica', '1Âª SÃ©rie', NULL, 'AE1', 'Utilizar operaÃ§Ãµes com nÃºmeros reais, incluindo potenciaÃ§Ã£o e radiciaÃ§Ã£o, para resolver situaÃ§Ãµes-problemas envolvendo grandezas, medidas e suas conversÃµes.', NOW()),
(56, 'Ensino MÃ©dio', 'MatemÃ¡tica', '1Âª SÃ©rie', NULL, 'AE2', 'Resolver problemas geomÃ©tricos que envolvem o Teorema de PitÃ¡goras.', NOW()),
(57, 'Ensino MÃ©dio', 'MatemÃ¡tica', '1Âª SÃ©rie', NULL, 'AE3', 'Reconhecer as funÃ§Ãµes como relaÃ§Ãµes de dependÃªncia unÃ­voca entre duas variÃ¡veis, identificando as relaÃ§Ãµes entre duas grandezas, em situaÃ§Ãµes econÃ´micas, sociais e das CiÃªncias da Natureza.', NOW()),
(58, 'Ensino MÃ©dio', 'MatemÃ¡tica', '1Âª SÃ©rie', NULL, 'AE4', 'Resolver situaÃ§Ãµes-problema que possam ser modeladas por funÃ§Ãµes polinomiais de 1Âº grau, resolvendo equaÃ§Ãµes e usando representaÃ§Ãµes algÃ©bricas e geomÃ©tricas.', NOW()),
(59, 'Ensino MÃ©dio', 'MatemÃ¡tica', '2Âª SÃ©rie', NULL, 'AE1', 'Utilizar a notaÃ§Ã£o cientÃ­fica para representar medidas e resolver problemas que empregam unidades de medida de diferentes grandezas.', NOW()),
(60, 'Ensino MÃ©dio', 'MatemÃ¡tica', '2Âª SÃ©rie', NULL, 'AE2', 'Modelar problemas que possam ser representados por equaÃ§Ãµes polinomiais do 1Âº e 2Âº grau, em situaÃ§Ãµes econÃ´micas, sociais e das CiÃªncias da Natureza.', NOW()),
(61, 'Ensino MÃ©dio', 'MatemÃ¡tica', '2Âª SÃ©rie', NULL, 'AE3', 'Resolver situaÃ§Ãµes-problema que possam ser modeladas por funÃ§Ãµes exponenciais, resolvendo equaÃ§Ãµes e utilizando das representaÃ§Ãµes algÃ©bricas e geomÃ©tricas.', NOW()),
(62, 'Ensino MÃ©dio', 'MatemÃ¡tica', '2Âª SÃ©rie', NULL, 'AE4', 'Resolver situaÃ§Ãµes-problema que possam ser modeladas por funÃ§Ãµes logarÃ­tmicas, resolvendo equaÃ§Ãµes e fazendo uso das representaÃ§Ãµes algÃ©bricas e geomÃ©tricas.', NOW()),
(63, 'Ensino MÃ©dio', 'MatemÃ¡tica', '3Âª SÃ©rie', NULL, 'AE1', 'Utilizar equaÃ§Ãµes polinomiais de 1Âº e 2Âº grau para modelar situaÃ§Ãµes-problema envolvendo grandezas e medidas.', NOW()),
(64, 'Ensino MÃ©dio', 'MatemÃ¡tica', '3Âª SÃ©rie', NULL, 'AE2', 'Resolver problemas do cotidiano que envolvem equaÃ§Ãµes lineares simultÃ¢neas, utilizando tÃ©cnicas algÃ©bricas e grÃ¡ficas.', NOW()),
(65, 'Ensino MÃ©dio', 'MatemÃ¡tica', '3Âª SÃ©rie', NULL, 'AE3', 'Resolver problemas de contagem envolvendo agrupamentos ordenados ou nÃ£o de elementos, recorrendo a estratÃ©gias diversas.', NOW()),
(66, 'Ensino MÃ©dio', 'MatemÃ¡tica', '3Âª SÃ©rie', NULL, 'AE4', 'Resolver problemas de probabilidade envolvendo eventos aleatÃ³rios nÃ£o sucessivos, por meio da identificaÃ§Ã£o do espaÃ§o amostral e da contagem de possibilidades.', NOW()),
(67, 'Ensino MÃ©dio', 'MatemÃ¡tica', '3Âª SÃ©rie', NULL, 'AE5', 'Resolver problemas de probabilidade em experimentos sucessivos, envolvendo eventos dependentes e independentes.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '6Âº Ano', NULL, 'AE1', 'Analisar as caracterÃ­sticas de textos do campo jornalÃ­stico-midiÃ¡tico.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '6Âº Ano', NULL, 'AE2', 'Estabelecer relaÃ§Ãµes entre gÃªneros jornalÃ­sticos, comparando suas caracterÃ­sticas estruturais, linguÃ­sticas e temÃ¡ticas.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '6Âº Ano', NULL, 'AE3', 'Analisar a funÃ§Ã£o e o impacto do uso dos substantivos, verbos e adjetivos, identificando seus modificadores.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '6Âº Ano', NULL, 'AE4', 'Aplicar regras de ortografia e pontuaÃ§Ã£o ao escrever textos, de acordo com as convenÃ§Ãµes da lÃ­ngua escrita.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '6Âº Ano', NULL, 'AE5', 'Utilizar diferentes estratÃ©gias de leitura em textos literÃ¡rios diversos, inferindo informaÃ§Ãµes implÃ­citas e analisando efeitos de sentido.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '6Âº Ano', NULL, 'AE6', 'Aplicar regras de concordÃ¢ncia nominal e verbal em textos diversos, reconhecendo os efeitos de sentido gerados.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '6Âº Ano', NULL, 'AE7', 'Aplicar recursos lexicais (sinÃ´nimos, antÃ´nimos, homÃ´nimos, afixos, escolhas de vocabulÃ¡rio) e semÃ¢nticos (relaÃ§Ãµes de significado, efeitos de sentido, parÃ¡frases, discurso direto/indireto), reconhecendo os sentidos produzidos nos textos.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '6Âº Ano', NULL, 'AE8', 'Analisar textos e espaÃ§os de reclamaÃ§Ã£o e solicitaÃ§Ã£o, reconhecendo suas caracterÃ­sticas e funÃ§Ãµes sociais.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '6Âº Ano', NULL, 'AE9', 'Aplicar conhecimentos linguÃ­sticos e gramaticais na produÃ§Ã£o e anÃ¡lise de textos diversos.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '6Âº Ano', NULL, 'AE10', 'Analisar as caracterÃ­sticas prÃ³prias de textos narrativos ficcionais, identificando efeitos de sentido gerados pela escolha de expressÃµes diversas e recursos linguÃ­sticos e literÃ¡rios.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '6Âº Ano', NULL, 'AE11', 'Comparar informaÃ§Ãµes sobre um mesmo fato divulgadas por diferentes veÃ­culos e mÃ­dias, analisando elementos que conferem credibilidade ao texto.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '6Âº Ano', NULL, 'AE12', 'Inferir os efeitos de sentido produzidos por palavras, imagens, pontuaÃ§Ã£o e outros recursos em textos multimodais.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '6Âº Ano', NULL, 'AE13', 'Analisar textos normativos, jurÃ­dicos e reivindicatÃ³rios, reconhecendo suas marcas linguÃ­sticas e estruturais.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '7Âº Ano', NULL, 'AE1', 'Reconhecer diferentes propostas editoriais, analisando o tratamento dado ao fato noticiado.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '7Âº Ano', NULL, 'AE3', 'Identificar os efeitos de sentido causados por estratÃ©gias de modalizaÃ§Ã£o e argumentaÃ§Ã£o em textos diversos.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '7Âº Ano', NULL, 'AE4', 'Comparar informaÃ§Ãµes sobre um mesmo fato divulgadas por diferentes veÃ­culos e mÃ­dias, identificando elementos que contribuem para a credibilidade.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '7Âº Ano', NULL, 'AE5', 'Analisar as escolhas linguÃ­sticas que contribuem para a construÃ§Ã£o de sentidos em textos argumentativos.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '7Âº Ano', NULL, 'AE6', 'Analisar os elementos da narrativa em gÃªneros narrativos ficcionais diversos, reconhecendo suas caracterÃ­sticas prÃ³prias.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '7Âº Ano', NULL, 'AE7', 'Interpretar efeitos de sentido produzidos pelo uso de recursos sonoros, semÃ¢nticos e grÃ¡ficos em poemas.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '7Âº Ano', NULL, 'AE9', 'Inferir a presenÃ§a de valores sociais, culturais e humanos em diferentes visÃµes de mundo em textos literÃ¡rios para reconhecer a riqueza cultural e linguÃ­stica de diferentes nacionalidades.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '7Âº Ano', NULL, 'AE10', 'Identificar a funÃ§Ã£o de gÃªneros de carÃ¡ter avaliativo (prefÃ¡cio, orelha, sinopse, resenha crÃ­tica e vlog), expressando opiniÃµes e crÃ­ticas pessoais com embasamento.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '8Âº Ano', NULL, 'AE1', 'Identificar os efeitos de sentido que fortalecem a persuasÃ£o nos textos publicitÃ¡rios.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '8Âº Ano', NULL, 'AE3', 'Analisar os efeitos de sentido gerados pelo uso de diferentes mecanismos de intertextualidade em textos variados.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '8Âº Ano', NULL, 'AE4', 'Analisar a presenÃ§a de valores e de diferentes visÃµes de mundo em textos literÃ¡rios de gÃªneros diversos.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '8Âº Ano', NULL, 'AE5', 'Analisar os efeitos de sentido produzidos por recursos linguÃ­sticos e gramaticais, paralinguÃ­sticos e cinÃ©sicos, como a gestualidade, em textos diversos.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '8Âº Ano', NULL, 'AE6', 'Analisar os efeitos de sentido produzidos pelos modificadores do verbo em textos diversos.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '8Âº Ano', NULL, 'AE7', 'Analisar as caracterÃ­sticas prÃ³prias de gÃªneros textuais do campo jornalÃ­stico, identificando a posiÃ§Ã£o assumida pelo autor e/ou veÃ­culo.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '8Âº Ano', NULL, 'AE8', 'Analisar a estrutura e os efeitos de sentido criados por recursos linguÃ­sticos em textos narrativos de diversos gÃªneros, como romances e contos.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '8Âº Ano', NULL, 'AE9', 'Analisar as caracterÃ­sticas dos gÃªneros de divulgaÃ§Ã£o cientÃ­fica, para identificar textos desse gÃªnero.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '8Âº Ano', NULL, 'AE10', 'Reconhecer as formas de introduzir outras vozes em textos cientÃ­ficos.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '9Âº Ano', NULL, 'AE1', 'Participar de prÃ¡ticas compartilhadas de leitura e interpretaÃ§Ã£o de obras literÃ¡rias e manifestaÃ§Ãµes artÃ­sticas, demonstrando preferÃªncias pessoais.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '9Âº Ano', NULL, 'AE2', 'Aplicar regras de escrita da norma-padrÃ£o em textos com estruturas sintÃ¡ticas complexas.', NOW()),
Anos Finais', 'LÃ­ngua Portuguesa', '9Âº Ano', NULL, 'AE3', 'Analisar as caracterÃ­sticas e os efeitos de sentido gerados pela linguagem e organizaÃ§Ã£o de textos literÃ¡rios narrativos.', NOW());
