INSERT INTO aprendizagens_essenciais (id, nivel_ensino, disciplina, ano_serie, bimestre, codigo, descricao, created_at) VALUES
(251, 'Ensino MÃ©dio', 'QuÃ­mica', '2Âª SÃ©rie', NULL, 'AE5', 'Analisar a estrutura, a sÃ­ntese e as aplicaÃ§Ãµes de polÃ­meros naturais e sintÃ©ticos, identificando as principais reaÃ§Ãµes de polimerizaÃ§Ã£o e casos de isomeria cis-trans.', NOW()),
(252, 'Ensino MÃ©dio', 'Sociologia', '2Âª SÃ©rie', NULL, 'AE1', 'Analisar a especificidade do conhecimento sociolÃ³gico como campo cientÃ­fico, reconhecendo seus conceitos fundamentais e teorias clÃ¡ssicas da relaÃ§Ã£o entre indivÃ­duo e sociedade, aplicando-os na anÃ¡lise de processos sociais.', NOW()),
(253, 'Ensino MÃ©dio', 'Sociologia', '2Âª SÃ©rie', NULL, 'AE2', 'Analisar a relaÃ§Ã£o entre o indivÃ­duo e o contexto sociocultural em que vive, aplicando conceitos da antropologia e da sociologia, identificando os processos que tornam os humanos seres sociais e culturais.', NOW()),
(254, 'Ensino MÃ©dio', 'Sociologia', '2Âª SÃ©rie', NULL, 'AE3', 'Elaborar hipÃ³teses e argumentos a partir da anÃ¡lise de evidÃªncias de processos sociais, culturais e polÃ­ticos, de informaÃ§Ãµes confiÃ¡veis e da coleta e sistematizaÃ§Ã£o de dados.', NOW()),
(255, 'Ensino MÃ©dio', 'Sociologia', '2Âª SÃ©rie', NULL, 'AE4', 'Analisar as relaÃ§Ãµes entre sujeitos e grupos no mundo contemporÃ¢neo, aplicando os conceitos de diferenciaÃ§Ã£o, produÃ§Ã£o social da diferenÃ§a, estratificaÃ§Ã£o e classe social, para explicar problemas de convivÃªncia, exclusÃ£o social, marginalizaÃ§Ã£o e desigualdades.', NOW()),
(256, 'Ensino MÃ©dio', 'Sociologia', '2Âª SÃ©rie', NULL, 'AE5', 'Analisar as diferentes formas de violÃªncia presentes no cotidiano, compreendendo suas causas sociais, culturais e institucionais e discutindo seus impactos na convivÃªncia social.', NOW()),
(257, 'Ensino MÃ©dio', 'Sociologia', '2Âª SÃ©rie', NULL, 'AE6', 'Analisar situaÃ§Ãµes da vida cotidiana, estilos de vida, valores e condutas, aplicando conceitos sociolÃ³gicos, para desnaturalizar formas de desigualdade, preconceito, intolerÃ¢ncia, discriminaÃ§Ã£o e violÃªncia presentes nas relaÃ§Ãµes Ã©tnico-raciais, de gÃªnero e em outros contextos sociais.', NOW()),
(258, 'Ensino MÃ©dio', 'Sociologia', '2Âª SÃ©rie', NULL, 'AE7', 'Analisar os princÃ­pios dos Direitos Humanos, como a dignidade humana, a igualdade e a nÃ£o violÃªncia, para identificar prÃ¡ticas cotidianas de violaÃ§Ã£o e avaliar aÃ§Ãµes que promovem a defesa desses direitos.', NOW());
